### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by Coldfire2019** [picons/picons#10]
Sky Batman HD and Sky Spooky HD

**Comment by mrhotio** [comment]
So those are missing from a local turkish cable company or are they from a arial feed in Norway?

**Comment by Coldfire2019** [comment]
Sorry UK VM

**Comment by mrhotio** [comment]
Sorry, please read CONTRIBUTING.md, without correct servicrefs, nothing can be done.

**Comment by Coldfire2019** [comment]
Sorry 
1_0_19_964_18_F020_FFFF0000_0_0_0
1_0_19_D4A_22_F020_FFFF0000_0_0_0

**Comment by AbuBaniaz** [comment]
Are you using SNP or SRP?

**Comment by Coldfire2019** [comment]
SNP

**Comment by AbuBaniaz** [comment]
Please check latest release and close issue if satisfied. I have used the bog standard movies logos. Names will revert in a few days.
