### ISSUE TITLE
A complete Vodafone Network Review of Logos

### ISSUE THREAD

**Issue by scheilch** [picons/picons#1023]
# SNP/SRP entries

**snp.index**
```
comes later
```

**srp.index**
```
file is attached in the archive
```

# Logos
I have updated some logos and added some new ones. The Sky Sport + Sky Sport Bundesliga logos should all look the same now. For the Sky Sport logos I used a Sky font and updated the channel numbers accordingly.

The archive also includes a text file that contains more detailed information about each logo. I've searched for the current sky logos on [wikimedia](https://commons.wikimedia.org/w/index.php?search=sky+sport&title=Special:MediaSearch&go=Go&type=image) and took the one that matched the original sky logo at best.

I spent almost the entire day today looking at every single (visible) channel on the Vodafone network and matching the logos, even from foreign channels that I don't watch at all. Some logos in the srp file have been updated in the process.

There are still outdated logos and you'll find an updated (but mostly not usable) version in the archive.

Please do a review and get back to me if there are any questions. 

[outdated.zip](https://github.com/picons/picons/files/8052106/outdated.zip)
[astrotv](https://user-images.githubusercontent.com/19861673/153683002-de785c57-764b-499c-8f97-46053c33bc23.png)
[astrotv-vuspujapri default](https://user-images.githubusercontent.com/19861673/153714521-0c03ef2a-0b25-4a00-b895-89373c3a5c56.svg)
[ardalpha-vuspujapri default](https://user-images.githubusercontent.com/19861673/153715333-8360caa1-a6d7-4681-bdca-ebe147d2c1fa.svg)

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by Lexzie** [comment]
I was quite busy the last days. I will get back to you about this.
Before looking in to it mind that I have used the logos from [Logopedia](https://logos.fandom.com/wiki/Sky_Group) who are usually very up-to-date. Furthermore if a logo is not used anymore by Sky Deutschland that doesn't mean it is not used by Sky UK or Sky Italy. So make sure what they are using. Unfortunately they usually don't use the same type of logos.

Can you explain what you want us to do with the attached files?
Do they need to be added or do you want to remove them from the repo?
Also at first hand I see a lot is not confirm our guidelines.

Please make a zip-file named `logos_to_add.zip` f.e. and make sure the naming is correct:
`<logoname>.<default|light|dark|white>.<ext>`

Edit the logos according the contribution guidelines.
F.e., or in addition to the guidelines:
- No png image in an svg.
- Trim the logos, no empty space around the logos.
- No background.
- Submit at least a `default` logo and if that one is not visible on a light or dark background then also submit a `dark` or `light` one (You can be a little creative with this if the station had only one variant. You can invert the color or just make what's too dark white or black what is too light).
- If editing a png image, make sure no left-over pixels are in the background or around the edges. (I know, it's a lot work. Been there.)

**Comment by Lexzie** [comment]
First about the Astro TV logo. The png is of too low quality so I guess you made an svg from it?
Make two layers in Inkscape and make the logos of the same size and you will see that you need to improve the svg a lot to make it right. Sometimes you'd better wait until there is a better logo found.
Also why did you add the random 10 letters to the name of the svg's? Just use the name that is in use right now.
Only if the old logo is still in use elsewhere (so not in this case).

**Comment by scheilch** [comment]
The png is of too low quality - right. Therefore I searched for a better one. This svg was the result.

I just posted all my stuff here to avoid accepting a PR and then revert it again - especially because of the sky logos in the zip file.

Take out what fits best of the needs and leave the rest inside.

**Comment by dalmore72** [comment]
Astro TV logo svg

https://www.astrotv.de/build/AstrobaseBundle/logo-new.svg

**Comment by Lexzie** [comment]
Kazakh TV logo is present under the name `qazakhtv`.

**Comment by Lexzie** [comment]
What's wrong with the Servus TV logo? The missing `DEUTSCHLAND`? I don't feel like making that (lot of work), so unless you can find that logo somewhere?

I have been busy a long time trying to figure out the Sky Cinema logos.
Seems like Sky changes them whenever the wind changes and uses different ones on TV as they do on the website.
Hard to keep up. As long as I don't see them on the TV it's hard to check which one they use.
I'll try to do that but takes a lot of time...

**Comment by scheilch** [comment]
![4A31BFB9-CA7B-459D-BF3A-41E5AF6A5094](https://user-images.githubusercontent.com/19861673/156642645-00ae1c89-aa8f-44b0-a260-ea403ce243fd.jpeg)

Nothing is wrong with it but it looks like this at Vodafone Cable TV.

The image above is a screenshot from my mobile tvh client.

**Comment by Lexzie** [comment]
Can you find a SVG version?
Or find out what font they are using? (Try the font identifier on [Fontsquirrel](https://www.fontsquirrel.com/matcherator) )

**Comment by Lexzie** [comment]
I have already begun with the Sky Cinema logos.
I will finish that later.

**Comment by 4l3x2k** [comment]
- Sky Sport 8 HD (13E_3_85_FFFF0000)
- Sky Sport 9 HD (148_3_85_FFFF0000)
- Sky Sport Bundesliga 8 HD (147_3_85_FFFF0000)
- Sky Sport Bundesliga 9 HD (151_4_85_FFFF0000)

use old picons and are not aligned with the new ones. All Sky Sport * picons are the non-hd variants.

Sky Sport F1 HD (11_4_85_FFFF0000) uses the UK picon (skysportsf1) and should be the DE picon (skysportf1hd). The DE picon has no "s". So it is "sport" not "sports".

I hope it is ok posting it here because I also use Vodafone cable. I could also create a new issue.

**Comment by AbuBaniaz** [comment]
I am not making sense of what you are saying in terms of deciphering whether you are saying something is the wrong  or that is what it should be.

From a previous pull request, somebody had the links changed so that instead of pointing to logos with HD, they point to the ones without.  It is unclear to me whether you are saying that is wrong or that is correct.

We have these hits on the file
```
13E_3_85_FFFF0000=skysport8
148_3_85_FFFF0000=skysport9
147_3_85_FFFF0000=skysportbundesliga8
151_4_85_FFFF0000=skysportbundesliga9
11_4_85_FFFF0000=skysportsf1
```

If we already have the correct logos on the repository, just submit  a pull request with the changes.

**Comment by 4l3x2k** [comment]
I thought skysport8, skysport9 and skysportbundesliga8, skysportbundesliga9 was forgotten but these logos are simply only available with old style.

I mentioned HD because all these channels (skysport1-11 and skysportbundesliga1-11) are HD but I can see why the SD variants are used. The HD variants are only available with old style.

For skysportf1hd I'll create a PR.

**Comment by Lexzie** [comment]
Without checking I could download the standard logos. For HD logos I have to do a lot of work adding the 'HD' to the logos.
Feel free to do that. ;-)
German logos should not have 'sports' indeed.

**Comment by Lexzie** [comment]
The same for `Sky Sport 8` and `Sky Sport 9`. The source where I got the other logos has no new logos for 8 and 9 and I couldn't find them elsewhere.
If you find a good quality source or want to make them? Takes too much time for me.

**Comment by 4l3x2k** [comment]
I've also been looking for decent logos for 8 and 9. In vain.
Maybe I'll find time this weekend to take a closer look.

Thank you for merging the srp change Lexzie.

**Comment by Lexzie** [comment]
I lost track of what is still to be done in this issue.
If so, please tell what needs to be done or close the issue.
You can always open a new issue again.

**Comment by Lexzie** [comment]
Since there is no answer I'll close the issue.
