### ISSUE TITLE
SRP updates

### ISSUE THREAD

**Issue by nhathaway** [picons/picons#1040]
# SNP/SRP entries

1_0_C_3C48_3006_233A_EEEE0000_0_0_0     |  Arise News               |  3C48_3006_233A_EEEE0000=--------
1_0_1_11C0_1041_233A_EEEE0000_0_0_0     |  BBC FOUR                 |  11C0_1041_233A_EEEE0000=--------
1_0_1_10C0_1041_233A_EEEE0000_0_0_0     |  BBC THREE                |  10C0_1041_233A_EEEE0000=--------
1_0_19_4600_4082_233A_EEEE0000_0_0_0    |  BBC THREE HD             |  4600_4082_233A_EEEE0000=--------
1_0_1_8380_8002_233A_EEEE0000_0_0_0     |  GREAT! movies +1         |  8380_8002_233A_EEEE0000=--------
1_0_19_A068_A000_233A_EEEE0000_0_0_0    |  QVC Beauty HD            |  A068_A000_233A_EEEE0000=--------
1_0_C_3298_3006_233A_EEEE0000_0_0_0     |  YAAAS!                   |  3298_3006_233A_EEEE0000=--------
1_0_1_5D40_5040_233A_EEEE0000_0_0_0     |  Yesterday+1              |  5D40_5040_233A_EEEE0000=--------

Arise news: https://www.arise.tv/
BBC FOUR use bbcfour
BBC THREE & BBC THREE HD - not sure where to get picon of same generation as BBC1 etc (bbcthree ?)
GREAT! movies +1 use greatmovies
QVC Beauty HD use qvcbeauty
YAAAS! : https://yaaas.tv/
Yesterday+1 use yesterday

**snp.index**
```
samplechannelname=samplelogoname
samplechannelname1=samplelogoname1
samplechannelname2=samplelogoname2
```

**srp.index**
```
422B_3DB8_13E_820000=samplelogoname
425A_3DB8_13E_820000=samplelogoname1
4257_3DB8_13E_820000=samplelogoname2
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by nhathaway** [comment]
Confirmed: you already have "bbcthree"
For Arise News, you already have arisenews
For YAAAS, the logo is here: https://simplestream-portal.s3.eu-west-1.amazonaws.com/164/0a0f8e77-YAAAS%21.png
But the colour needs filling in, and it needs resizing.

**Comment by Lexzie** [comment]
What's with the title of this issue? ("A description of what you are updating by this request")

Besides that, the rest is a mess too...

What about the YAAAS logo? Am I supposed to guess the colours?

Please submit an issue so that we don't have to do all the work.
Provide the links so that we can copy-paste them.
Read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)

**Comment by nhathaway** [comment]
see #1042
