### ISSUE TITLE
Update of various items from Mendip transmiiter, UK

### ISSUE THREAD

**Issue by nhathaway** [picons/picons#1042]
# SNP/SRP entries

**srp.index**
```
3C48_3006_233A_EEEE0000=arisenews
11C0_1041_233A_EEEE0000=bbcfour
10C0_1041_233A_EEEE0000=bbcthree
4600_4082_233A_EEEE0000=bbcthree
8380_8002_233A_EEEE0000=greatmovies
A068_A000_233A_EEEE0000=qvcbeauty
3298_3006_233A_EEEE0000=yaaas
5D40_5040_233A_EEEE0000=yesterday
```
# Logos

```
logos.zip
```

[logos.zip](https://github.com/picons/picons/files/8168594/logos.zip)

I hope I did better this time.

**Comment by Lexzie** [comment]
This is right how we like it, I can easily copy-paste the links.

What I can't see here but what I know from your previous issue #1040 is that you want the normal logos for the `+1` stations, not the `+1` logo?
On satellite I still see the `+1` logo on Great! Movies. (No QVC Beaty +1 on satellite).
Does Great! Movies +1 on Freeview has no `+1` logo?
Unfortunately the Yaaas! logo is too small and if you want to submit it right please remove the empty space around the logo, so it would be like this (still to small/low resolution though):
[yaaas.zip](https://github.com/picons/picons/files/8170100/yaaas.zip)

I'll try to find a better logo or colour the other one. Give me some time.

**Comment by nhathaway** [comment]
Yes, the +1 logos would be wanted wherever they exist. I must have missed their existence and assumed they didn't exist. I looked for +1's on BBC3 and BBC4 but didn't find them.

**Comment by Lexzie** [comment]
> Yes, the +1 logos would be wanted wherever they exist. I must have missed their existence and assumed they didn't exist. I looked for +1's on BBC3 and BBC4 but didn't find them.

I meant for `Great! Movies +1` and `Yesterday +1` (and maybe for `QVC Beauty +1`?)
On Freesat I can clearly see a +1:
![afbeelding](https://user-images.githubusercontent.com/14023349/156387711-12b124df-fb9b-4dee-8c12-6faa59d505f3.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/156387733-2b77b40f-276d-4ebc-8fe3-b513b2754a54.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/156392658-fdd08c56-7f93-4806-8580-9ed50a04aa33.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/156392684-9d4a4567-2afd-4630-a20e-19311a053b3f.png)

**Comment by nhathaway** [comment]
5D40_5040_233A_EEEE0000=yesterdayplus1
8380_8002_233A_EEEE0000=greatmoviesplus1

**Comment by nhathaway** [comment]
[yaaas.zip](https://github.com/picons/picons/files/8176578/yaaas.zip)

I traced around it and created an SVG

**Comment by Lexzie** [comment]
> [yaaas.zip](https://github.com/picons/picons/files/8176578/yaaas.zip)
> 
> I traced around it and created an SVG

That's not always going okay.
I'll check later.
I already coloured the png's from their website.

**Comment by Lexzie** [comment]
I stand correct, this SVG looks very good. With what did you trace the bitmap to SVG?

One thing you also need to do with a SVG (in Inkscape) is:
-Select all (Ctrl+A) > Object to Path (Shift+Ctrl+C)
-Resize Page to Selection (Shift+Ctr+R)  < This was already okay.
-Transform > Scale > Scale proportionaly > Width 800 (or Height depending on which is the largest) > Apply
-Then Resize Page to Selection (Shift+Ctr+R)  again.
-Save as Optimized SVG (see [Cleaning up SVG metadata](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata)).

I've done that already and will submit the logo and the links right now.

Oh yeah, I also filled in the white like in the png logo.
