### ISSUE TITLE
[FEEDBACK] Input wanted on what to do with comedycentral_viva

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#109]
Can anyone check what currently is on air on this index entries?

the entries in the snp.index can be deleted without any issue i think. or not?
but the srp.index has to be checked

# SNP/SRP entries

**snp.index**
```
comedycentralviva=comedycentral_viva
comedycentralvivaat=comedycentral_viva
comedycentralvivaaustria=comedycentral_viva
vivacomedycentral=comedycentral_viva
```

**srp.index**
```
7004_436_1_C00000=comedycentral_viva
D8_14B4_9C_FFFF0000=comedycentral_viva
```

thx

**Comment by mrhotio** [comment]
just delete it all, we'll see what happens after.....

**Comment by SmoothMC** [comment]
ok...i will

**Comment by mrhotio** [comment]
Could you also stop using the template for general questions, just click on the link 'blank issue' or what it's called.

**Comment by mrhotio** [comment]
I've also renamed the titles for some of your issues, so you can see what is expected....
