### ISSUE TITLE
Help creating svg

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#111]
I found this svg: https://tv3play.skaties.lv/static/assets/3-play-logo-red-black.svg
I just need the '3' but when I open this svg in Inkscape the shadow is gone.
It is in the svg, the color is #BA2026, but I don't know how to edit the file in f.e. Notepad++.
The result should be this:
![afbeelding](https://user-images.githubusercontent.com/14023349/73028502-f4d4d880-3e35-11ea-88f5-a2a311d0f4c5.png)

I also need the `3 film` and `3 sport` logo, as shown here:
![afbeelding](https://user-images.githubusercontent.com/14023349/73029492-eab3d980-3e37-11ea-9a01-cbd258f23072.png)

**Comment by dalmore72** [comment]
I can help you with the logos :)

[Tv3 Baltic.zip](https://github.com/picons/picons/files/4106203/Tv3.Baltic.zip)

**Comment by dalmore72** [comment]
Here are also some svg files for Ukraine

[Ukraine logos.zip](https://github.com/picons/picons/files/4106187/Ukraine.logos.zip)

**Comment by Lexzie** [comment]
> Jeg kan hjelpe deg med logoene

@dalmore72 Norwegian?

**Comment by dalmore72** [comment]
Yes I was a little tired last night so I didn't think about the language before I wrote the message :)

**Comment by Lexzie** [comment]
I need some time to submit these, don't know if I can do that the next days, but I will do it ASAP.

**Comment by dalmore72** [comment]
Tv3 Life and Tv3 Mini replace LNT and Kanalas2 01.03.2020

https://www.neplpadome.lv/lv/sakums/komercialie-mediji/komercialas-televizijas/

**Comment by Lexzie** [comment]
The TV3, TV3 Sport, TV3 Film and TV3 Sport 3 logos are added (stangly enough I have no TV3 Sport 2 channel on 4.8E).
We'll have to wait until 1-3-2020 for TV3 Life and TV3 Mini.

**Comment by chocholousek** [comment]
> I found this svg: https://tv3play.skaties.lv/static/assets/3-play-logo-red-black.svg
> I just need the '3' but when I open this svg in Inkscape the shadow is gone.
> It is in the svg, the color is #BA2026, but I don't know how to edit the file in f.e. Notepad++.
> 
> I also need the `3 film` and `3 sport` logo, as shown here:
> ![afbeelding](https://user-images.githubusercontent.com/14023349/73029492-eab3d980-3e37-11ea-9a01-cbd258f23072.png)

https://drive.google.com/open?id=15lueNvFMnwDOkv_rSSAwfUA9E6KCUp9_

**Comment by Lexzie** [comment]
What about this Google-link?

![afbeelding](https://user-images.githubusercontent.com/14023349/73846067-22e9ed80-4824-11ea-846d-dc38242b042b.png)

**Comment by chocholousek** [comment]
I will not help, automatically creating a link to github erase the last letter, type the address manually.
OK => `https://drive.google.com/open?id=15lueNvFMnwDOkv_rSSAwfUA9E6KCUp9_`

**Comment by Lexzie** [comment]
If it's a logo you want to share just paste it (or in a zip file) in the message here.

**Comment by Lexzie** [comment]
I see it's the TV3 logo. Thanks for helping, but I have added that logo already in commit e9c3925fac61b7ea6cd3ea0739890b348c295941.

**Comment by Lexzie** [comment]
I see the logo for TV3 I added still not the desired shadow, I will add this one.
