### ISSUE TITLE
Blank servicelist-tvheadend-servermode-srp.txt

### ISSUE THREAD

**Issue by skunge2000** [picons/picons#112]
Hi there. I've used the picons build scripts with TV Headend in the past with no problems with TV Headend running in LibreElec or CoreElec (and running the picons build script stuff on a separate machine on my LAN - an Ubuntu server VM inside VirtualBox on my Mac)

I'm now running TV Headend on a Pi 4B Raspbian install - TV Headend version "HTS Tvheadend 4.2.8-34~g24a2f59e9"

I have configured the tvheadend.serverconf file :

```
# hostname or ip address of tvheadend server (default: "localhost")
TVH_HOST="10.0.0.207"

# port of tvheadend API (default: 9981)
TVH_PORT="9981"

# tvheadend user name
TVH_USER="admin"

# tvheadend password of above user
TVH_PASS="admin"
```

and running the bash script 1 with -x I get this :

https://pastebin.com/AcCDpzbe

(I've snipped out the list of all the channels in the Picons database to reduce the size of the pastebin)

The script seems to be reading the services from TV Headend OK - all 133 of them - so it looks as if the script is properly talking to TV Headend on my LAN (though it may not be getting all the information it requires I guess)

Any ideas why the service list file isn't being created? (I ran the script as root this time just in case it was an odd permissions thing) 

Do I need to be running a newer/older version of TV Headend?

I get a blank snp file if I run a name-based script rather than reference-based.

Any help gratefully received.

**Comment by mrhotio** [comment]
Is the picon setting enabled?

**Comment by skunge2000** [comment]
In TV Headend?  Is that required for the script to create the srp or snp service list?  I haven't created any picons yet using script 2 because I don't have a valid service list to create them from - the servicelist-tvheadend-servermode-srp.txt  and servicelist-tvheadend-servermode-snp.txt files created using reference or names (i.e. using option 1 or option 2 in script 1) are both blank?

Do I need to enable a setting in TV Headend for script 1 to read the service list correctly from TV Headend?  The only Picon options I can see in TV Headend look to be based around defining what type of picons (service, name etc.) and where the files are?

**Comment by mrhotio** [comment]
SNP is not supported, so that can be ignored. Yes, you need to enable something in tvheadend...a picon:// url should show up somewhere.

**Comment by skunge2000** [comment]
OK - I've previously followed this guide https://jamiej.co.uk/blog/working-picons-tvheadend-kodi/ in the past and it 'just worked'.  No reference to enabling anything in TV Headend to generate the service reference file - just to point to the picons file once it has been created and copied to a location TV Headend can access?  As I don't have any picons yet - those aren't relevant?

I can't see where in TV Headend I'd enable what the Service Reference script needs TV Headend to do?  

The script is getting data like this from my TV Headend : 

```
++ curl -s --anyauth 'http://admin:admin@10.0.0.207:9981/api/channel/grid?start=0&limit=1'
+ rx_buf='{"entries":[{"uuid":"96692a8036841d8972e609d2ff8ad345","enabled":true,"autoname":true,"name":"BBC TWO HD","number":102,"epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":-1,"services":["69450844fcc2b156c0d4bd26963ccab0"],"tags":["901b48e891369bb3910d9b4a09510d92","9002b0c32b8bbc15d22cd91b5b464535","6de9afd9a1fc34acf756a181ed8415a9"],"bouquet":""}],"total":133}'

```
but the srp text file remains empty?

**Comment by mrhotio** [comment]
I have nothing to do with that bad guide. At the end you do see a screenshot with what I meant.

**Comment by mrhotio** [comment]
Copied this from our readme

Note: In order to make the generator work with TvHeadend, you'll need to enable picons first by defining a path to the future picon folder under Configuration -> General -> Base.

**Comment by skunge2000** [comment]
Thanks very much. I missed that in the read me, and I guess the LibreElec installs have a default icon path mapping already.  Adding a picon path in TV Headend has got me a service list.
