### ISSUE TITLE
Sky Comedy HD Virgin channel 121 - showing wrong logo

### ISSUE THREAD

**Issue by chenks** [picons/picons#114]
the new Sky Comedy HD entertainment channel that just launched is showing the logo for Sky Comedy HD movie channel.

Channel names on Virgin - Sky Comedy HD / Sky Comedy
SRP for HD version 1_0_19_519_D_F020_FFFF0000_0_0_0

to be honest, i'm not sure show SNP is going to deal with this considering Virgin now has two different channels with the same name.

correct logo for entertainment channel is here - https://media.info/i/lf/600/1580094867/1136.png
![1136](https://user-images.githubusercontent.com/11945919/73595174-6505ed00-450d-11ea-9be8-9fb792022d48.png)

**Comment by mrhotio** [comment]
Follow the template please

**Comment by chenks** [comment]
forget it then.
sorry for taking time out from my boring life to let you know about an issue.
so it appears you'll choose to ignore a problem because it doesn't follow a "template". i give you the channel name, then SRP, the platform and the PNG of the correct logo.

**Comment by mrhotio** [comment]
Sorry, just trying to save everybody their time...if people follow the template, it's a 30 second job. People are just doing this in their free time, the least you could do is show some respect for them and follow a basic template.

**Comment by mrhotio** [comment]
If anyone actually wants to add the logo, I found this good version after a 5sec google search instead of the crappy one provided by @chenks 
[skycomedy.default.zip](https://github.com/picons/picons/files/4143097/skycomedy.default.zip)

**Comment by AbuBaniaz** [comment]
I was going to add the ones that Jasmeet has. including the HD one

**Comment by mrhotio** [comment]
fine by me
