### ISSUE TITLE
Cine34 logo

### ISSUE THREAD

**Issue by liegepr** [picons/picons#115]
Hi,
May I suggest to include this one:
https://commons.wikimedia.org/wiki/File:Cine34_logo.svg
Hot Bird13E, 11432.00V 
Thanks

**Comment by Lexzie** [comment]
Can you please provide all the information we need to add this?
Please follow the guidelines so our job will be much easier.
https://github.com/picons/picons/blob/master/CONTRIBUTING.md

**Comment by Lexzie** [comment]
I meant to close this issue, but I got errors when doing that.
