### ISSUE TITLE
tf1seriesfilms picon

### ISSUE THREAD

**Issue by nicolasnantua** [picons/picons#116]
The tf1seriesfilms picon is not the same as the tf1seriesfilms.default.svg logo. The right side of the logo is missing.
[tf1seriesfilms.zip](https://github.com/picons/picons/files/4278604/tf1seriesfilms.zip)

**Comment by Lexzie** [comment]
I had noticed that too but was unable to fix it.
You will see if you open the logo in the repository it **will** have the part on the right side.
Maybe someone else can fix this?

**Comment by nicolasnantua** [comment]
I fixed this issue. I replaced the logo in the repository with this one:
https://upload.wikimedia.org/wikipedia/fr/5/5f/TF1_S%C3%A9ries_Films_logo_2018.svg
Now with this logo the picon is correct.

**Comment by mrhotio** [comment]
Nope, that hasn't fixed it

**Comment by AbuBaniaz** [comment]
@nicolasnantua 
What are you using? SNP or SRP? Please provide the service reference and also service name.
Our  project has following forumula: 
`Link on repo` + `logo on repo` = `picon created`


SNPicons use 
`tf1seriesfilms=tf1seriesfilms`

SRPicons use
```
140_3E1C_13F_820000=tf1seriesfilms
232B_442_1_C00000=tf1seriesfilms
5DF_F_1_FFFF0000=tf1seriesfilms
A01_A_20FA_EEEE0000=tf1seriesfilms
BB8_4E84_55F_DDE0000=tf1seriesfilms
```

**Comment by Jasmeet181** [comment]
Remove `mask="url(#d-0)"` in line 15 of the svg to fix the missing text or take [my copy](https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/TF1%20Series%20Films.svg).
