### ISSUE TITLE
Canal Digitaal NL fixes in SRP

### ISSUE THREAD

**Issue by bpwats** [picons/picons#118]
# SRP entries

**srp.index**
```
36F8_C8C_3_EB0000=comedycentral
52B0_C99_3_EB0000=discoveryshowcasehd
36F9_C8C_3_EB0000=spike
1BFD_C88_3_EB0000=nauticalchannel
6FF7_436_1_C00000=nickjr
17AF_C82_3_EB0000=travelxp
52EA_C96_3_EB0000=animalplanet
36F4_C8C_3_EB0000=ducktv
FE2_451_35_C00000=rtllounge
36F6_C8C_3_EB0000=mtv
7D_9_85_C00000=cnbchd
17ED_C82_3_EB0000=retromusictv
7004_436_1_C00000=comedycentral
170D_419_1_C00000=frankenfernsehen
16AB_3FF_1_C00000=ulmallgau
1469_C98_3_EB0000=canaleitalia83
1469_C98_3_EB0000=chambertvhd
145A_C98_3_EB0000=tvlux
64D_2454_13E_820000=automototv
```
several Canal Digitaal NL fixes (HotBird 13 not included)
17AF_C82_3_EB0000=travelxp is actually
17AF_C82_3_EB0000=travelxphd

1469_C98_3_EB0000=canaleitalia83 is actually
1469_C98_3_EB0000=chambertvhd

**Comment by AbuBaniaz** [comment]
I don't understand what the bottom section of your report is trying to convey. The process we use will only use the first hit.

Can you please rephrase with

Please delete these lines
xxxx

Please add these lines
yyyyy

**Comment by mrhotio** [comment]
I think he means this:

```
17AF_C82_3_EB0000=travelxphd
1469_C98_3_EB0000=chambertvhd
36F8_C8C_3_EB0000=comedycentral
52B0_C99_3_EB0000=discoveryshowcasehd
36F9_C8C_3_EB0000=spike
1BFD_C88_3_EB0000=nauticalchannel
6FF7_436_1_C00000=nickjr
17AF_C82_3_EB0000=travelxp
52EA_C96_3_EB0000=animalplanet
36F4_C8C_3_EB0000=ducktv
FE2_451_35_C00000=rtllounge
36F6_C8C_3_EB0000=mtv
7D_9_85_C00000=cnbchd
17ED_C82_3_EB0000=retromusictv
7004_436_1_C00000=comedycentral
170D_419_1_C00000=frankenfernsehen
16AB_3FF_1_C00000=ulmallgau
1469_C98_3_EB0000=canaleitalia83
1469_C98_3_EB0000=chambertvhd
145A_C98_3_EB0000=tvlux
64D_2454_13E_820000=automototv
```

**Comment by AbuBaniaz** [comment]
To me he is suggesting that something is wrong. That something needs to be changed from A to B
i.e
Delete A
Add B

But those references are not present. It is pointless adding two links as only one will be used.  We do not have `travelxphd` or `chambertvhd` logos either.

I have committed some changes, please double check it is what is required.

Our project has following formula:
`Link on repo` + `logo on repo` = `picon created`

**Comment by bpwats** [comment]
17AF_C82_3_EB0000=travelxp broadcast in HD format. There is no Travel XP HD logo.

**Comment by bpwats** [comment]
delete 1469_C98_3_EB0000=canaleitalia83
add 1469_C98_3_EB0000=chambertvhd

**Comment by AbuBaniaz** [comment]
We cannot add links if the logos do not exist. Do you have them? Otherwise you will have to wait until someone sources/makes them

**Comment by Jasmeet181** [comment]
I have [Travelxp HD](https://raw.githubusercontent.com/Jasmeet181/mediaportal-cz-logos/master/TV/Source/Travelxp%20HD.svg). Thanks for the invitation Hotio but I'm not currently using anything that supports picons.

**Comment by mrhotio** [comment]
You don't have to accept it if you don't feel like it....you are good with "logos", so that's why....

**Comment by AbuBaniaz** [comment]
With regards to Chamber TV HD, can you post  a picture of what the logo looks like please? I can't seem to find anything differrnt to what we have already

https://github.com/picons/picons/blob/master/build-source/logos/chambertv.default.svg

**Comment by bpwats** [comment]
Here is a screen shot:
![chamber_tv_hd-vlcsnap-2020-03-09-18h53m55s530](https://user-images.githubusercontent.com/4590024/76242924-c2d9d300-6237-11ea-83c9-a511896e2713.png)
So it does not differ, Fastscan lists the channel as "Chamber TV HD" and resolution is in Full HD indeed, the official logo does not reflect it.

**Comment by AbuBaniaz** [comment]
That is the logo we have used.

**Comment by AbuBaniaz** [comment]
I'll close this now. Please report back if there is a problem/more work to be done
