### ISSUE TITLE
[ADD] CBNN

### ISSUE THREAD

**Issue by bpwats** [picons/picons#119]
Would somebody be so kind as to create a proper CBNN logo? I cannot do this myself.
[https://cbnn.io/](url)
CBNN is a "A New Kind of News" Crypto-Blockchain and Tech News with Entertainment.

# SRP entries

**srp.index**
```
107D_3EE_1_C00000=cbnn
```

# Logos
Website logo and screen shot added.
[cbnn.zip](https://github.com/picons/picons/files/4308278/cbnn.zip)
[cbnn-screen_schot.zip](https://github.com/picons/picons/files/4308279/cbnn-screen_schot.zip)

**Comment by Jasmeet181** [comment]
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/CBNN.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/CBNN%20-%20Dark.svg

**Comment by AbuBaniaz** [comment]
Done
