### ISSUE TITLE
Picons at 0byte

### ISSUE THREAD

**Issue by cmarchi** [picons/picons#1217]
Hi, I've downloaded your picons (snp-full.400x240-400x240.light.on.transparent_2022-10-29--19-56-00.hardlink.tar.xz) but almost half of the logos are 0 byte in size and can't read them. Tried to download different size but same problem. One example is "canale5hd" that I can see in your repo but is 0 byte in the downloaded file. Thanks for any clarification

**Comment by TheLegoBatman** [comment]
Is that before or after extracting?

**Comment by cmarchi** [comment]
Both, before and after. I'm on ubuntu 22.04

Il Mar 1 Nov 2022, 14:15 TheLegoBatman ***@***.***> ha
scritto:

**Comment by TheLegoBatman** [comment]
Since I can't find the package and test it, it's probably best to wait for the next build.

**Comment by cmarchi** [comment]
Got the file from here: https://openpicons.com/picons/

So they are packaging your picons but you are not related to them? I've
read on that website that issue could be reported here

Il Mer 2 Nov 2022, 17:55 TheLegoBatman ***@***.***> ha
scritto:

**Comment by TheLegoBatman** [comment]
I just downloaded the package and all is fine with the picons including `canale5hd`.

A ls of them gives the following sizes:
` 9.3K Oct 31 20:45 snp-full.400x240-400x240.light.on.transparent_2022-10-31--20-45-03/canale5hd.png`
` 7.2K Oct 31 20:45 snp-full.400x240-400x240.light.on.transparent_2022-10-31--20-45-03/canale5.png`
