### ISSUE TITLE
ITV (UK) has refreshed its channel idents

### ISSUE THREAD

**Issue by wedebe** [picons/picons#1227]
https://www.itv.com/presscentre/press-releases/itv-launches-unified-brand-across-family-channels-ahead-launch-itvx

Not sure where to get the official logos but thought I'd log it here for reference!

**Comment by AbuBaniaz** [comment]
https://www.itv.com/presscentre/sites/default/files/styles/card/public/itv1_logo_primary_web1.jpg?itok=otW1y0V5

**Comment by Jasmeet181** [comment]
CillBill posted the whole set on Logopedia
https://logos.fandom.com/wiki/Special:ListFiles/CillBill

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons/commit/872f19d35564416ef49bc34e9e1c728aee9daf7f

**Comment by wedebe** [comment]
Confirmed all appearing, many thanks!
