### ISSUE TITLE
[ADD] 28.2East (Astra 2) UK Radio SRP reference fixes

### ISSUE THREAD

**Issue by bpwats** [picons/picons#123]
# SRP entries

**srp.index**
```
CBE6_831_2_11A0000=absoluteradio90s
CBE8_831_2_11A0000=absoluteradioclassicrock
D761_82F_2_11A0000=jazzfm
```
All are radio stations.

**Comment by mrhotio** [comment]
@bpwats first, thank you for creating proper issues like suggested by the template....second, if you want, there's no need to split them up in multiple issues, you can just lump them all togheter into one issue...unless this is more conveniant for you, in that case feel free to continue as you were doing.
