### ISSUE TITLE
Where do I report missing picons?

### ISSUE THREAD

**Issue by ghost** [picons/picons#1237]
Hi

I downloaded snp-full.220x132-190x102.light.on.transparent (2022-09-01--15-47-57) in the openATV 7.1 Plugin Manager, unfortunately there are still a few picons missing that I could deliver...
But they still need some editing.

Where do I report missing picons?

I added the setting later... there are not many picons missing for the setting. (See attached file)
Above all, missing Swiss picons can all be found here [Sunrise TV Channels - Channels overview](https://www.sunrise.ch/en/internet-tv/channel-list) they would simply have to be adjusted....
Downloaded the most important ones (see attached file Sunrise Picon)

If every transmitter really had a cleanly adapted picon, that would be awesome.
[Picon Sunrise.zip](https://github.com/picons/picons/files/10098553/Picon.Sunrise.zip)
[setting-icam-mixed-sat-cable-upc-innerschweiz.zip](https://github.com/picons/picons/files/10098554/setting-icam-mixed-sat-cable-upc-innerschweiz.zip)

**Comment by AbuBaniaz** [comment]
This repository builds the picons packs every sunday morning. They are available here:
https://github.com/picons/picons/releases

The ones on the PLI images are built every night if there is a change here as far as I know. At least for the developer images.

The ones on the OE-A team images are built and by them. Their last picon build was on 01/09/2022. The frequncy they build the picons based on their criteria. Nothing to do with what is here. I shall ask when the next build will be.

You can also build your own packs.

**Comment by AbuBaniaz** [comment]
For items on this repository, read here:
https://github.com/picons/picons/blob/master/CONTRIBUTING.md

https://github.com/picons/picons#readme

**Comment by AbuBaniaz** [comment]
The picons on the OE-A plugin feeds have been updated.

**Comment by AbuBaniaz** [comment]
Here is a list of missing picons for you.  The formula is: `Link + logo = picon`  
The links are in the `snp.index` or `srp.index` on thsi repository  as well as the logos.
So, if logo is present but picon is not being created, the link is missing, add that.
If we don't have the logo, we would not have the link too, so add both.

Your cable services are coming up as N/A for me so I cant really check properly.
[missing-picons-all_services.csv](https://github.com/picons/picons/files/10128900/missing-picons-all_services.csv)

**Comment by ghost** [comment]
Thanks ;-)

**Comment by AbuBaniaz** [comment]
How are you getting along with submitting the required changes?

**Comment by ghost** [comment]
Unfortunately, I had a sports accident and cannot test it..

**Comment by AbuBaniaz** [comment]
Sorry to hear, get well soon.

**Comment by 4l3x2k** [comment]
[This](https://github.com/picons/picons/pull/1253) is the first part of adding missing Sunrise picons.

The second part with new picons is coming [here](https://github.com/4l3x2k/picons/commit/78544f208f142f5c32c03f0cadde95bf5bffae83) after the first part is accepted.

**Comment by Lexzie** [comment]
Please correct all the remarks added [here](https://github.com/picons/picons/pull/1253#pullrequestreview-1222076359) and [here](https://github.com/4l3x2k/picons/commit/78544f208f142f5c32c03f0cadde95bf5bffae83#commitcomment-93483510).

**Comment by 4l3x2k** [comment]
@William-Richards 
1st change has been accepted https://github.com/picons/picons/pull/1253
2nd change has been accepted https://github.com/picons/picons/pull/1255

Are you happy with changes (and additions) now?

**Comment by ghost** [comment]
These picons are still missing.

Pro7 Sat.1 UHD - Sat 19.2 = Picon missing

Servus TV Motorsport HD - IPTV = Picon missing
FC Bayern TV HD - IPTV = Picon missing

7+ HD - UPC Sunrise Kabel = Picon missing
Blue Sport Event 1 HD - UPC Sunrise Kabel = Picon missing
Blue Sport Event 2 HD - UPC Sunrise Kabel = Picon missing
Sky Sport App - UPC Sunrise Kabel = Picon missing
Wetter TV HD - UPC Sunrise Kabel = Picon missing
Helvetia One TV - UPC Sunrise Kabel = Picon missing
RMC Sport Access 1 - UPC Sunrise Kabel = Picon missing
RTP - UPC Sunrise Kabel = Picon missing
Welcome to Sunrise - UPC Sunrise Kabel = (Sunrise) Picon missing
Store D - UPC Sunrise Kabel = (Sunrise) Picon missing
Store F - UPC Sunrise Kabel =(Sunrise) Picon missing
Store I - UPC Sunrise Kabel = (Sunrise) Picon missing
MySports UN - UPC Sunrise Kabel = (MySports 1) Picon missing
MySports EINS - UPC Sunrise Kabel = (MySports 1) Picon missing
MySports 1 - UPC Sunrise Kabel = (MySports 1) Picon missing

**Comment by Lexzie** [comment]
Without your proposed changes to snp.index and/or srp.index we cannot do anything.

And please use: https://github.com/picons/picons/issues/new/choose

**Comment by AbuBaniaz** [comment]
Please add your latest lamedb file. 
Edit:
Are you using SNP orSNP picon pack? And when we're they built?

**Comment by ghost** [comment]
src/gz openvision-picon-feed https://github.com/OpenVisionE2/picons-feed/raw/master/feed

**Comment by ghost** [comment]
[setting-cable-upc-innerschweiz.zip](https://github.com/picons/picons/files/10430082/setting-cable-upc-innerschweiz.zip)

**Comment by ghost** [comment]
Pro7 Sat.1 UHD - Sat 19.2 = Picon missing
#SERVICE 1:0:1F:183D:40B:1:C00000:0:0:0::Pro7 Sat.1 UHD
#DESCRIPTION Pro7 Sat.1 UHD

Servus TV Motorsport HD - IPTV = Picon missing
#SERVICE 4097:0:1:29E:3B53:0:0:0:0:0:http%3a//iptv——.com%3a8080/live/user/passwort/277327.ts:Servus TV Motorsport HD
#DESCRIPTION Servus TV Motorsport HD

FC Bayern TV HD - IPTV = Picon missing
#SERVICE 4097:0:1:6808:35F2:EC:0:0:0:0:http%3a//iptv——.com%3a8080/live/user/passwort/277322.ts:FC Bayern TV HD
#DESCRIPTION FC Bayern TV HD

**Comment by AbuBaniaz** [comment]
link + logo = picon

Are all logos on our repository correct?
prosieben.default.svg
servustv.default.svg

**Comment by AbuBaniaz** [comment]
I have added some more links here:
https://github.com/picons/picons/commit/5d7fad6872b611dd5de120bf2e6846167a9415b3

To recap:
If we do not have the logo on our repository, logos need to be supplied. (To an acceptable standard)
If logos exist on our repository but picons are not created, the links to create the picons must be added.

**Comment by Lexzie** [comment]
Good luck finding an acceptable logo for Pro7 Sat.1 UHD.
Had no luck so far.

**Comment by ghost** [comment]
[PROSIEBENSAT.1_UHD_Logo_2021.svg.zip](https://github.com/picons/picons/files/10440907/PROSIEBENSAT.1_UHD_Logo_2021.svg.zip)

**Comment by Lexzie** [comment]
I said an **acceptable** logo.

This is not acceptable:
![afbeelding](https://user-images.githubusercontent.com/14023349/213057370-d0aeb274-f18f-4dab-bde8-69ec9bb070a9.png)

**Comment by Lexzie** [comment]
I found a clean one. Just need to make a light version too.

**Comment by Jasmeet181** [comment]
I made these
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ProSiebenSat.1%20UHD%20-%20Dark.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ProSiebenSat.1%20UHD.svg

@lapicidae made these
https://github.com/lapicidae/svg-channellogos/blob/master/dark/pro7sat.1%20uhd.svg
https://github.com/lapicidae/svg-channellogos/blob/master/light/pro7sat.1%20uhd.svg

**Comment by Lexzie** [comment]
Nice. I see @AbuBaniaz already added them.

**Comment by ghost** [comment]
Servus TV Motorsport HD - IPTV = Picon missing
#SERVICE 4097:0:1:29E:3B53:0:0:0:0:0:http%3a//iptv——.com%3a8080/live/user/passwort/277327.ts:Servus TV Motorsport HD
#DESCRIPTION Servus TV Motorsport HD

[Servus TV Motorsport.svg.zip](https://github.com/picons/picons/files/10468680/Servus.TV.Motorsport.svg.zip)

**Comment by Lexzie** [comment]
This logo also looks like a bad import from a bitmap image.
Look f.e. example close at the `TV` letters:
![afbeelding](https://user-images.githubusercontent.com/14023349/213769121-63799933-7814-4459-9c29-ec17362cb8ee.png)

But maybe we can find one elsewhere and it's easy to make it with the standard Servus TV logo.

**Comment by Lexzie** [comment]
Finding the right font for the `MOTORSPORT` letters is harder than I thought.
Anyone an idea which font I could use?

**Comment by AbuBaniaz** [comment]
Re: `Bayern Munchen`
Could someone make an svg file out of this one and add it to the repository please?
```https://vignette3.wikia.nocookie.net/logopedia/images/4/47/FC_Bayern_Munich.png/revision/latest?cb=20160531131327```
I'm not having much luck with inkscape and tracing it

**Comment by ghost** [comment]
Ok ?

[FC_Bayern_Munich.svg.zip](https://github.com/picons/picons/files/10472463/FC_Bayern_Munich.svg.zip)

**Comment by Jasmeet181** [comment]
> Finding the right font for the `MOTORSPORT` letters is harder than I thought. Anyone an idea which font I could use?

Digital Fernsehen's picture used a different font to MagentaTV and a screenshot on Twitter.
https://www.digitalfernsehen.de/wp-content/uploads/2022/06/einstieg_spartensender_normal_servustvmotorsport.jpg
http://ngiss.t-online.de/sweetprogrammanager/media/0dc70ce1d79eb0698093130d9b85712f34127484.png
https://twitter.com/m4rcbr4ndt/status/1400941023732420610

Nimbus Sans Black (D) was the first match on WhatTheFont.
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ServusTV%20Motorsport%20-%20Dark.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ServusTV%20Motorsport.svg

> Re: `Bayern Munchen` Could someone make an svg file out of this one and add it to the repository please? `https://vignette3.wikia.nocookie.net/logopedia/images/4/47/FC_Bayern_Munich.png/revision/latest?cb=20160531131327` I'm not having much luck with inkscape and tracing it

This is the logo for the channel, there's an SVG on WIkimedia Commons but it's just auto traced.
https://www.magentasport.de/images/editorial/Logos/Bewerb-Logos/FCBTVLive-Logo-3C-1.png
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/FC%20Bayern.TV%20Live.png
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/FC%20Bayern.TV%20Live%20-%20Dark.png

**Comment by ghost** [comment]
maybe Helvetica font

**Comment by Lexzie** [comment]
> WhatTheFont

Great tip, I only used [Fontsquirrel](https://www.fontsquirrel.com/).

If the exact font is not found or public available, we can use a font that looks almost the same and maybe pimp it a little.

I can dig into this later, if anyone else is going to do it please say it here, so I won't waste my time building a logo for a channel that I will probably never receive.

**Comment by Lexzie** [comment]
> Ok ?
> 
> [FC_Bayern_Munich.svg.zip](https://github.com/picons/picons/files/10472463/FC_Bayern_Munich.svg.zip)

No:
![afbeelding](https://user-images.githubusercontent.com/14023349/213933977-ae9c3e9d-53af-42a1-97d5-8e5604e4b2f9.png)

But I think it can be fixed, working on it...

**Comment by Lexzie** [comment]
I didn't even had to fix. There is a perfectly good svg on the website of FC Bayern Munchen.
What srp. and snp.links can I add with the logo?

**Comment by Lexzie** [comment]
> Bayern

Already found the name and service reference

**Comment by ghost** [comment]
Only a small rest of Sunrise is missing

7+ HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:2371:19:1:FFFF0000:0:0:0:
 Blue Sport Event 1 HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BD0:DE:1:FFFF0000:0:0:0::Blue Sport Event 1 HD
#DESCRIPTION Blue Sport Event 1 HD
 Blue Sport Event 2 HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BD3:E1:1:FFFF0000:0:0:0::Blue Sport Event 2 HD
#DESCRIPTION Blue Sport Event 2 HD
 Wetter TV HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:24A8:1B:1:FFFF0000:0:0:0::Wetter TV
#DESCRIPTION Wetter TV
 RMC Sport Access 1 - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BDA:E0:1:FFFF0000:0:0:0:
 RTP - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:1:277:13:1:FFFF0000:0:0:0::RTP
#DESCRIPTION RTP 

**the next 4 channels have the same pre-existing picon as UHD Test - UPC Sunrise Kabel 
#SERVICE 1:0:1F:23E7:C4:1:FFFF0000:0:0:0:**

Welcome to Sunrise - UPC Sunrise Kabel = (Sunrise) Picon missing
#SERVICE 1:0:1:1:65:1:FFFF0000:0:0:0:
 Store D - UPC Sunrise Kabel = (Sunrise) Picon missing
#SERVICE 1:0:19:21B7:C4:1:FFFF0000:0:0:0:
 Store F - UPC Sunrise Kabel =(Sunrise) Picon missing
#SERVICE 1:0:19:21B8:C4:1:FFFF0000:0:0:0:
 Store I - UPC Sunrise Kabel = (Sunrise) Picon missing
#SERVICE 1:0:19:21B9:C4:1:FFFF0000:0:0:0:

 
**these 3 channels must have the same picon:**

MySports UN - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:20DC:6F:1:FFFF0000:0:0:0:
 MySports EINS - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:20DB:6F:1:FFFF0000:0:0:0:
 MySports 1 - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:200A:D4:1:FFFF0000:0:0:0:

**Comment by Lexzie** [comment]
To make our work easier, can you please provide this in the correct format, like this:

**Add to snp.index**
```
servicename=logoname
```

**Add to srp.index**
```
servicereference=logoname
```

And provide us with the logos if they are missing.

And in the correct format, see: https://github.com/picons/picons/blob/master/CONTRIBUTING.md

**Comment by 4l3x2k** [comment]
Yes.  That would really be helpful. 

```
welcometosunrise=sunrise
sunrisestored=sunrise
sunrisestoref=sunrise
sunrisestorei=sunrise
```
is already in snp.index. So these need to be renamed to simply stored, storef and storei. He expects SNP picons to work and provides wrong names of the channel.

```
1_65_1_FFFF0000=sunrise
21B7_C4_1_FFFF0000=sunrise
21B8_C4_1_FFFF0000=sunrise
21B9_C4_1_FFFF0000=sunrise
```
is already in srp.index.

**Comment by ghost** [comment]
ok Thanks

**Comment by AbuBaniaz** [comment]
Which logo on our repository do we use for the channels called 

`7+hd`.  We add the link `7plushd=logoname`
`Auto Motor + Sport HD` We add the link `automotorplussporthd=logoname`

Please also provide the logo names (on our repository)  for the following channels

bluesportevent1 
bluesportevent1hd
bluesportevent2
bluesportevent2hd
diagnostics
swiss1
wbtvcomedyhd
wbtvcomedyhdblue
wbtvfilmhd
wbtvfilmhdblue
wbtvseriehd
wbtvseriehdblue

**Comment by Jasmeet181** [comment]
automotorplussporthd=automotorsporthd
diagnostics=sunrise
swiss1=swiss1 (my repo has an svg version)
wbtvcomedyhd=warnertvcomedyhd
wbtvcomedyhdblue=warnertvcomedyhd
wbtvfilmhd=warnertvfilmhd
wbtvfilmhdblue=warnertvfilmhd
wbtvseriehd=warnertvseriehd
wbtvseriehdblue=warnertvseriehd

7plushd

- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/7%20Plus%20Nick%20Schweiz%20-%20Dark.svg
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/7%20Plus%20Nick%20Schweiz.svg
or
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/7%20Plus%20HD.svg

bluesportevent1/bluesportevent1hd

- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Blue%20Sport%20Event%201%20-%20Dark.svg
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Blue%20Sport%20Event%201.svg

bluesportevent2/bluesportevent2hd

- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Blue%20Sport%20Event%202%20-%20Dark.svg
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Blue%20Sport%20Event%202.svg

The light versions of Blue Sport Event 1+2 need changing from #fff to #0030e0 to match your others.

> I can dig into this later, if anyone else is going to do it please say it here, so I won't waste my time building a logo for a channel that I will probably never receive.

The ServusTV Motorsport logo is already linked in my last post along with the logo for FC Bayern.TV Live.

- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ServusTV%20Motorsport%20-%20Dark.svg
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/ServusTV%20Motorsport.svg

- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/FC%20Bayern.TV%20Live.png
- https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/FC%20Bayern.TV%20Live%20-%20Dark.png

**Comment by Lexzie** [comment]
> Which logo on our repository do we use for the channels called
> 
> `7+hd`. 
> bluesportevent1 bluesportevent1hd bluesportevent2 bluesportevent2hd diagnostics swiss1 wbtvcomedyhd wbtvcomedyhdblue wbtvfilmhd wbtvfilmhdblue wbtvseriehd wbtvseriehdblue

My best guess is that wb stands for Warner Brothers?

@William-Richards already said that these logos are missing in our repo.
I told him to supply the logos.

But firstly we can use the logos from Jasmeet181's repo.
They are already cropped and in Optimized SVG format, so we only need to rename them according our filenaming system.
Servus TV Motorsport and Bayern München TV are already present in the repo.

@Jasmeet181 we have a svg for Bayern Münchem FC: https://github.com/picons/picons/blob/master/build-source/logos/bayernmunichfc.default.svg

I could do some work, but not earlier than this evening.

**Comment by AbuBaniaz** [comment]
@jasmeet181, thanks for your help once again. I have added these:
https://github.com/picons/picons/commit/afdf127e2c810ccc36daabb2ad2a7539bed019dd

**Comment by AbuBaniaz** [comment]
Apart from wetter and test channels, all SNPicons show after last commit. 

@Lexzie
Please add the wetter logo you want.

@William-Richards
Are you able to add the SRP links?

**Comment by ghost** [comment]
Only a small rest of Cable Provider Sunrise is missing

7+ HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:2371:19:1:FFFF0000:0:0:0:
 Blue Sport Event 1 HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BD0:DE:1:FFFF0000:0:0:0::Blue Sport Event 1 HD
#DESCRIPTION Blue Sport Event 1 HD
 Blue Sport Event 2 HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BD3:E1:1:FFFF0000:0:0:0::Blue Sport Event 2 HD
#DESCRIPTION Blue Sport Event 2 HD
 Wetter TV HD - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:24A8:1B:1:FFFF0000:0:0:0::Wetter TV
#DESCRIPTION Wetter TV
 RMC Sport Access 1 - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:19:1BDA:E0:1:FFFF0000:0:0:0:
 RTP - UPC Sunrise Kabel = Picon missing
#SERVICE 1:0:1:277:13:1:FFFF0000:0:0:0::RTP
#DESCRIPTION RTP 
 
these 3 channels must have the same picon:

MySports UN - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:20DC:6F:1:FFFF0000:0:0:0:
 MySports EINS - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:20DB:6F:1:FFFF0000:0:0:0:
 MySports 1 - UPC Sunrise Kabel = (MySports 1) Picon missing
#SERVICE 1:0:19:200A:D4:1:FFFF0000:0:0:0:

**Comment by AbuBaniaz** [comment]
Sorry, you are mistaken. I have added the links and logos. You will have to wait until next build unless you build them yourself.

![1](https://user-images.githubusercontent.com/6644489/214180681-471f2b9a-e068-4643-8bc6-ec629a170d57.jpg)
![2](https://user-images.githubusercontent.com/6644489/214180703-247eacb7-646c-44f7-aee0-4d9e580e5cdc.jpg)
![3](https://user-images.githubusercontent.com/6644489/214180715-e99ce75d-5d67-4b84-8c7a-d8c2092145c3.jpg)
![4](https://user-images.githubusercontent.com/6644489/214180743-dfdcfd8a-5522-49d3-8fda-7ce2dbdae8a9.jpg)
![5](https://user-images.githubusercontent.com/6644489/214180846-1de35b18-a88f-444a-a4e3-a8babd716a4e.jpg)


Once again, please use the terms on this repository.  Have a look at the snp.index and srp.index files.  That is what we use and using those will get to the result you want quicker instead of wasting your time.

**Comment by ghost** [comment]
Ok Thanks ;-)

**Comment by Lexzie** [comment]
> @Lexzie Please add the wetter logo you want.

I see the logos are already added? In that case thanks, I didn't had the time yet.

**Comment by AbuBaniaz** [comment]
@William-Richards
Will you be helping by adding the SRP links?

A. Yes
B. No
C. I don't fully understand how to

**Comment by ghost** [comment]
B. No

Thanks
