### ISSUE TITLE
Channel 5 (UK) service reference changes

### ISSUE THREAD

**Issue by wedebe** [picons/picons#1246]
Channel 5's suite of channels has recently changed.

Updated refs:

channel5hd.png 
1_0_19_1E46_809_2_11A0000_0_0_0

channel5.png
1_0_1_1E15_809_2_11A0000_0_0_0

5usa.png
1_0_1_1E1E_809_2_11A0000_0_0_0

5usaplus1.png
1_0_1_1E1F_809_2_11A0000_0_0_0

5star.png
1_0_1_1E23_809_2_11A0000_0_0_0

5select.png
1_0_1_1E24_809_2_11A0000_0_0_0

5starplus1.png
1_0_1_1E25_809_2_11A0000_0_0_0

channel5plus1.png 
1_0_1_1E28_809_2_11A0000_0_0_0

5action.png 
1_0_1_1E50_809_2_11A0000_0_0_0

**Comment by AbuBaniaz** [comment]
Those were the old references and were present on repo.  I have added the new ones here:
https://github.com/AbuBaniaz/picons/commit/be22cb7c18917b746f1b3c8c2c1ee8a37b4b2d85
