### ISSUE TITLE
New Sky Germany Channel Names and Logos

### ISSUE THREAD

**Issue by FirstS0ul** [picons/picons#125]
Hi,

there. Since March 13th there are new channels:

![Anmerkung 2020-03-14 222504](https://user-images.githubusercontent.com/38192724/76690675-b6dc7f80-6642-11ea-8b69-70fbe6024dee.png)

Translation:
wird zu = changed to
beendet = closed
bleibt = no change

**Comment by Lexzie** [comment]
I would love to add the logos, but it's a lot of work so please use the template.
Just click on the green button after you click on New Issue, you can do it!
![afbeelding](https://user-images.githubusercontent.com/14023349/76907708-35d1f200-68a7-11ea-951a-3ef6e065beaa.png)
