### ISSUE TITLE
Add NBC Sports Network and Newsy Channel Logos (HD and SD images provided)

### ISSUE THREAD

**Issue by LargeTalons** [picons/picons#126]
# SNP/SRP entries

**snp.index**
```

According to Schedules Direct XML Data:
These are US based TV networks.

nbcsnhd=nbcsnhd
nbcsn=nbcsn
newsy=newsy
newsysd=newsysd


```

# Logos

Theres no HD logo for the newsy channel
[newsy.zip](https://github.com/picons/picons/files/4364766/newsy.zip)
[nbcsn logos.zip](https://github.com/picons/picons/files/4364764/nbcsn.logos.zip)

**Comment by Lexzie** [comment]
No srp links?

**Comment by LargeTalons** [comment]
Im sorry, I dont know if SRP applies to American TV networks. I even looked through the picons that already exist and its seems that most of the channels with SRP links are foreign. 

If I'm wrong, I will see if I can try to find out the information

**Comment by AbuBaniaz** [comment]
Are you using Enigma2 or something else?

**Comment by LargeTalons** [comment]
Im using a CableCard from Verizon and a HDHomeRun Prime.

**Comment by AbuBaniaz** [comment]
I have added them, please check above commit to check if everything is Okay.

Just for reference, we do not need both png and svg files. I have also used logo names that are similar to existing washington logos.

**Comment by LargeTalons** [comment]
Looks great! Thanks yall!
