### ISSUE TITLE
Updating the picons

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#1318]
I never had to update the picons on my receiver manually because Pli updated it every night.
Right now the last stable release (OpenPLi 8.3) is 20230129 and the release before that 20230122.
So weekly build?

I want to see if all picons are good on my receiver so can anyone help me how to manually update?

You might say, you can build it yourself but also never done that and I don't have a Linux PC.

Maybe someone can make an ipk for me, I use `snp-full.400x240-370x210.light.on.transparant`
I have a Xtrend ET10000 (mipsel I believe) and a Dreambox DM920UHD (arm).

**Comment by AbuBaniaz** [comment]
You don't need a linux pc, you can do them on a windows pc by installing the ubuntu for windows too.

Anyway, I will run a build for you. Not sure I can do the large size, but let's see.

**Comment by AbuBaniaz** [comment]
[enigma2-plugin-picons-snp-full.100x60-86x46.dark.on.reflection_2023-02-03--22-29-16_all.ipk.zip](https://github.com/picons/picons/files/10583568/enigma2-plugin-picons-snp-full.100x60-86x46.dark.on.reflection_2023-02-03--22-29-16_all.ipk.zip)

Maximum filesize is 68MB so can't upload the 400x 240, hope these are ok. I can't upload ipks, so `.zip` added to filename. Please rename it bore installing it. You may need to uninstall your existing one first.

**Comment by Lexzie** [comment]
Thank you very much!

You could send it with WeTransfer via my email.
You should have my email address, if you lost it I can sent you an email first.

Could you please build the `light on transparant` version?

**Comment by AbuBaniaz** [comment]
Uploaded here. 

```
https://www.mediafire.com/file/bet5zq5ysm2cxxf/enigma2-plugin-picons-snp-full.400x240-370x210.light.on.transparent_2023-02-03--22-29-16_all.ipk/file
```

**Comment by Lexzie** [comment]
That works too.
Thanks!

**Comment by AbuBaniaz** [comment]
Please add this link on next commit, otherwise I will do it on my next one

`ultrahd=ultrahd`
