### ISSUE TITLE
ITV HD channel logos still in use

### ISSUE THREAD

**Issue by orryverducci** [picons/picons#1349]
The HD variants of the logos for the ITV channels were removed in #1313.

Although not used on air any more, these logos are still used by ITV on the EPG's of all the UK TV platforms to differentiate between the HD and SD variants of the channels. This can be seen on the online versions of the platform EPG's linked below:

Freeview (channel 103): https://www.freeview.co.uk/tv-guide
Sky (channels 803, 816, 817 & 818): https://www.sky.com/tv-guide
Freesat (channels 103, 113, 115 & 117): https://www.freesat.co.uk/tv-guide
Virgin Media: https://virgintvgo.virginmedia.com/en/tv/tv-guide.html

Given that these logos are still used I would suggest reverting this commit to match.

**Comment by AbuBaniaz** [comment]
Are we matching the TV or website?

**Comment by Lexzie** [comment]
My opinion is we use the logos as seen on TV.

Furthermore: Most TV Guides use old logos for a long time.
I don't think we should use third party website as a reference.

**Comment by orryverducci** [comment]
The logos on the platform EPG's were updated when ITV rebranded in November, so the logos are the current. The UK platforms usually update the logos pretty quickly, often on the day of rebrand (as happened with ITV), as we as broadcasters request the updates.

So it's a question of if you want to use the logos ITV (and others) supply for the EPG, or if you want to use the ones used on air on the channel bugs.

If you wish to use the ones used on air that fine, but in that case it might be worth reviewing all the UK channel logos. Most UK broadcasters have stopped using on screen HD logos, but most the logos in the repo still feature the HD branding seen on the platform EPG's. Channel 4 is the only broadcater that comes to mind that still uses HD logos on their channels.

**Comment by Lexzie** [comment]
We use the logos as seen on TV.

The trend is that more stations replace their HD logos for standard logos, slowly we will adjust that if we come across it.
By the way, if you use snp-picons and a station removes 'HD' in the name the logo is probably changed automatically.

Feel free to make a new issue what should be changed. I don't have a lot of time right now to check every channel.
Make sure you make an issue in the format as stated here: https://github.com/picons/picons/issues/new/choose

**Comment by AbuBaniaz** [comment]
I'm in the middle and prefer picons that look best on the medium for which they will be used, receivers. The `HD` takes space and makes the text smaller overall. Just like the two tier sky movie logos look better than having all the name on one line.

Channel 4 HD has the HD. Channel 5 does not, so I'll change that unless you want to submit a pull request.

**Comment by Lexzie** [comment]
I totally agree @AbuBaniaz

**Comment by orryverducci** [comment]
I'm also in agreement. Just wanted to clarify as only ITV had its HD logos removed while the others are still there.

The BBC, Channel 5, UKTV and Sky all stopped using their HD logos on screen a while ago. The only broadcaster I'm aware of that's still using on screen HD logos is Channel 4 on their channels.

Not sure if you were asking me or Lexzie about the pull request. I'm happy to submit one, but I think it'll take some time to go through all the broadcasters and remove the unused HD logos, so it might be worthwhile you doing one for Channel 5 now and I can follow it up with more removals.

> The trend is that more stations replace their HD logos for standard logos, slowly we will adjust that if we come across it. By the way, if you use snp-picons and a station removes 'HD' in the name the logo is probably changed automatically.

I do use snp-picons but unfortunately Sky still require all HD channels on their platform to have HD on the end of the service name, so all the HD logos are still being used. We're only just starting to slowly switch off SD on satellite, so it will likely remain that way for a while.
