### ISSUE TITLE
Sunrise cable - Request for two more logos and picons

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons#1396]
Hello, I would like to report several channels to Sunrise Cable Switzerland that do not have a picon. Can I do that here too?
That would be 2 channels. But I don't have any transmitter data, only exact names

SHF HD
![SHF HD](https://user-images.githubusercontent.com/35585833/232366287-60878175-3663-4c42-8c1d-17024b053add.png)

TV Oberwallis HD
![TV Oberwallis HD](https://user-images.githubusercontent.com/35585833/232366348-d75871e2-c803-441f-ac74-e8b8e35a724c.png)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1022#issuecomment-1510613216_

**Comment by AbuBaniaz** [comment]
SHF logo in Gif format here
```
https://seeklogo.com/vector-logo/125781/shf-schaffhauser-fernsehen
```
TV oberwallis logos are available on Jasmeet 181 Germany channel repository

**Comment by ghost** [comment]
Will the two channel logos be available in the next update?

**Comment by AbuBaniaz** [comment]
![schaffhauserfernsehen default](https://user-images.githubusercontent.com/6644489/233780759-513e6052-d070-4bb6-9280-4d799b163c8e.svg)
@lexzie @TheLegoBatman 
Is this acceptable? I converted from attached eps file
[SHf_Schaffhauser_Fernsehen-vector-logo-seeklogo.com.zip](https://github.com/picons/picons/files/11301151/SHf_Schaffhauser_Fernsehen-vector-logo-seeklogo.com.zip)

**Comment by Lexzie** [comment]
I would have to take a look later today.
Are these channels also on satellite?

How do you convert the eps ti svg?
I used to do that in a commandline with Inkscape, but that doesn't seem to work anymore.
Last time I used an online converter.

**Comment by TheLegoBatman** [comment]
Instead of converting you can just open the eps with inkscape then copy and paste to a new empty drawing. Works better than trying to convert.

If you open that svg with a text editor you can see that it says `image/svg+xml` which is not ideal.

I'll try to get on these today and the ippica ones on issue #1340 later on today. What should they be linked to? A screenshot of the actual channel would be better.

**Comment by AbuBaniaz** [comment]
Inkscape would not even open it.

**Comment by TheLegoBatman** [comment]
If you are on windows maybe this will work `https://inkscape.org/learn/faq/#how-open-eps-files-windows`.

**Comment by Lexzie** [comment]
> I'll try to get on these today and the ippica ones on issue #1340 later on today. What should they be linked to? A screenshot of the actual channel would be better.

Screenshots are in the issue #1340 
I did not provide the links because if I had the logos I thought I'd make a PR myself, but feel free to add this:

**snp.index**

```
101ippica1=ippica1
102ippica2=ippica2
```

**srp.index**

```
65_65_FFFF_A031B4=ippica1
66_65_FFFF_A031B4=ippica2
```

**Comment by TheLegoBatman** [comment]
@Lexzie I meant the ones in this issue.

**Comment by ghost** [comment]
I downloaded the update prime everything works fine. but SHF and TV Oberwallis still no logo to see

**Comment by AbuBaniaz** [comment]
Logos exits on this repository on Github
 
https://github.com/picons/picons/blob/6cf36caeb9bd67514785fe7e3d05e4e6c5226f78/build-source/logos/tvoberwallis.default.png

https://raw.githubusercontent.com/picons/picons/07c04a1742aaf549ba6ab3aa8e14bfca548a5c24/build-source/logos/schaffhauserfernsehenhd.default.svg

To create picons the following links are in use.  The left hand side of the `=` sign are the names of the channels. Are they correct?
```
schaffhauserfernsehenhd=schaffhauserfernsehenhd
tvoberwallis=tvoberwallis
tvoberwallishd=tvoberwallis
```

Logos are present on this repository. Please do not refer to the logos.

**Comment by ghost** [comment]
#SERVICE 4097:0:1:29F:90B8:0:0:0:0:0:http%3a//website%3a8080/live/user/passwd/364723.ts:SHF HD
#DESCRIPTION SHF HD
#SERVICE 4097:0:2:57E:13:1:FFFF0000:0:0:0:http%3a//website%3a8080/live/user/passwd/364724.ts:TV Oberwallis HD
#DESCRIPTION TV Oberwallis HD

**Comment by AbuBaniaz** [comment]
The `shfhd` link is not present. I will add it.
`tvoberwallishd` is present. You will need to speak to your skin/image team about it.

**Comment by ghost** [comment]
I don't have a skin/image team, I'm just a regular user who wants to report bugs or missing logos and help.

**Comment by AbuBaniaz** [comment]
What we need to have is there as far as I can see. So unless we know what image you are using, what skin you are using it is going to be difficult. Some skins use their own renderers  and may not be showing them for that reason. 

Can you upload the lamedb file again? I know you did so a few months ago.

**Comment by ghost** [comment]
Here ist the lamedb
Thanks

**Comment by AbuBaniaz** [comment]
No attachment there.

**Comment by AbuBaniaz** [comment]
What device (set top box) are you using?

**Comment by TheLegoBatman** [comment]
@William-Richards which version of the picons did you install?

**Comment by ghost** [comment]
OpenATV 7.2 update to day
Dreambox DM920
Picons update to day

Tuners:
Cable (Swiss Sunrise Cable)
Satellite 13.0, 19.2, 23.5, 28.2
IPTV

**Comment by ghost** [comment]
[lamedb.zip](https://github.com/picons/picons/files/11362249/lamedb.zip)

**Comment by TheLegoBatman** [comment]
Those won't be on your lamedb. You need to install the snp package and the TV Oberwallis HD at least, should be there. 

I've tested your setup and it works on openpli at least. If it doesn't show up for you, you will need to ask in the openatv forum.

**Comment by ghost** [comment]
I also have the direct installer link with which it does not work either..
[openvision-picon-feed.conf.zip](https://github.com/picons/picons/files/11362332/openvision-picon-feed.conf.zip)

When I look in the picons folder, I can't find tv oberwallis.

**Comment by TheLegoBatman** [comment]
Firstly can you let us know which exact picon package did you install!

**Comment by ghost** [comment]
snp.full.220x132-190x102.light.on transparent (2023-04-28-23-32-51)

**Comment by AbuBaniaz** [comment]
OpenATV uses the picons that @TheLegoBatman builds, you can remove the openvision feeds. 
I am using ATV 7.3 with metrixhd skin. There isn't a a channel called `SHF HD`  or `TV oberwallis HD` in your lamedb file

Please post a screenshot of what you are seeing/not seeing

![1_0_1_10BF_1044_233A_EEEE0000_0_0_0_20230430224305](https://user-images.githubusercontent.com/6644489/235377543-564312c8-cc34-42d6-833a-62d3a77acaa3.jpg)

**Comment by TheLegoBatman** [comment]
The openvison feed isn't up to date. I can confirm that the picon is present in the latest build named enigma2-plugin-picons-snp-full.220x132-190x102.light.on.transparent_2023-04-29--23-28-03_all.ipk. Maybe just wait until Tuesday and then if the picons still aren't there, come back to let us know.

**Comment by ghost** [comment]
I have just recognized the problem you already have a newer update that cannot be downloaded automatically from the box. I just downloaded it manually, now tv oberwallis is there... in that case, only the SHF name needs to be optimized.

**Comment by ghost** [comment]
otherwise the updates will come faster with openvision-picon-feed.conf.zip  no idea why not today?

**Comment by AbuBaniaz** [comment]
> I have just recognized the problem you already have a newer update that cannot be downloaded automatically from the box. I just downloaded it manually, now tv oberwallis is there... in that case, only the SHF name needs to be optimized.

Can you please post a screenshot.  Maybe we can see what the error is.
[missing picons.csv](https://github.com/picons/picons/files/11362481/missing.picons.csv)

**Comment by ghost** [comment]
please wait a moment, I will restore box box from backup and try again with update and see if I have to do it again manually..

**Comment by ghost** [comment]
yes it is actually like that, automatically it only takes the update from the day before yesterday. so I downloaded the last update directly from the homepage and installed it manually. The only thing missing is SHF, which is not displayed because of the name.

**Comment by AbuBaniaz** [comment]
And if you post a screenshot of what the name should be, we will fix it.  

Please co-operate.

**Comment by ghost** [comment]
why a screenshot? the name is SHF
What do I have to take a screenshot of?

**Comment by AbuBaniaz** [comment]
You now say the name is `SHF` and you previously said it was `SHF HD` which we we have already added that, why do you say the name needs to be optimized? How do we optimise what is 100% correct?

Screenshot of the channel name and missing picon. Not blood!  There is a mixup somewhere and instead of wasting time, let us fix it, if needed.

**Comment by ghost** [comment]
Ok sorry it's SHF HD but you just said it's also TV Oberwallis HD but the logo doesn't show HD (see screenshot)
![IMG_4982](https://user-images.githubusercontent.com/35585833/235380712-04964a67-cb47-4ba2-8c1f-e61761ee5968.jpg)
![IMG_4983](https://user-images.githubusercontent.com/35585833/235380720-dce30d63-3951-4e8c-9426-8f4fcb49cdef.jpg)
![IMG_4984](https://user-images.githubusercontent.com/35585833/235380721-276ec864-dbf8-4485-a240-b46294bb46e4.jpg)
![IMG_4985](https://user-images.githubusercontent.com/35585833/235380723-051a4cb5-1854-48f9-a3a0-2ef4310c7391.jpg)

**Comment by Lexzie** [comment]
I made the `tvoberwallishd` logos.
I hope these are okay?

![tvoberwallishd default](https://user-images.githubusercontent.com/14023349/235383844-3880c233-95fc-445e-8171-67c9c069e4a6.png)
![tvoberwallishd light](https://user-images.githubusercontent.com/14023349/235383845-391cdfde-c27f-4bde-a8ee-6872a7cd863d.png)

**Comment by ghost** [comment]
Perfect !!! ;-)

when is the next update coming?

**Comment by ghost** [comment]
no update to day?

**Comment by AbuBaniaz** [comment]
On this repository, they are run on Saturday night going into Sunday morning.

On openpicons.com, they are built every day there is a change. Your images' picon feeds picks up those build changes automatically at 00:00. A software update will update them, or uninstall and then re-install for newest one.

**Comment by ghost** [comment]
ok then i'll wait a few more hours until i update my box and make a backup...

**Comment by AbuBaniaz** [comment]
The picons on your image's picon feeds are not dependent on the releases here. So you did not need to wait.  Yes, you can update the box,, which will also update the picons.

The picons are independent from the image. As I mentioned, they fetch them from openpicons.com nightly. Just for future reference, if you want, you can do the following:

```
opkg update
opkg upgrade enigma2-plugin-picons-snp-full.220x132-190x102.light.on.transparent
```
