### ISSUE TITLE
New channel Logo ES1

### ISSUE THREAD

**Issue by daviok** [picons/picons#14]
Hello
Here is the logo for the es1 channel ( esport french channel)

srp.index
`256D_AC_1_FFFF0000=es1`

snp.index
`es1=es1`
[logo.zip](https://github.com/picons/picons/files/3012506/logo.zip)

thanks

**Comment by mrhotio** [comment]
The logo inside the zip file is incorrectly named and it's a picon taken from somewhere else, having useless whitespace around the logo.

**Comment by mrhotio** [comment]
Sorry, no picon from somewhere else...it's this logo:
https://www.google.com/search?q=es1+tv&tbs=ift:png&tbm=isch&source=lnt&sa=X&ved=0ahUKEwjjpcSfqaThAhXFKlAKHb5wAwUQpwUIIA&biw=1400&bih=878&dpr=1#imgrc=mPbYvq5VwIgvlM:

**Comment by mrhotio** [comment]
Perhaps this can be turned into an svg:
https://www.google.com/search?q=es1+tv&tbs=ift:png&tbm=isch&source=lnt&sa=X&ved=0ahUKEwjjpcSfqaThAhXFKlAKHb5wAwUQpwUIIA&biw=1400&bih=878&dpr=1#imgdii=Sm5BNSACcv5YpM:&imgrc=mPbYvq5VwIgvlM:

**Comment by daviok** [comment]
yes its the logo from the offical logo website and it is correctly named (i think)
I got only the png from here : https://fr.wikipedia.org/wiki/Fichier:ES1_Logo.png

**Comment by mrhotio** [comment]
You don't have to think about it, I'm telling it's named incorrect. The logo file should be named `es1.default.png`. I'm mentioning it so that if someone picks up this issue, they won't forget renaming it...

**Comment by TheLegoBatman** [comment]
Probably better to add this one as svg indeed. That logo is very low quality and probably very difficult to make as svg. If you find a better version as a png we can add it. 

![es1 default svg](https://user-images.githubusercontent.com/22258726/55173666-05fc7c80-5174-11e9-9c29-659f2af332b4.png)

If this is acceptable I'll add it.
