### ISSUE TITLE
SRP release for ziggo

### ISSUE THREAD

**Issue by mvdlaan** [picons/picons#1429]
I wanted to update the picons on my device running VTI. A year ago I installed a ziggo SRP package, but in the latest releases it is not available anymore. Could you add it again? 
I'm looking for the SRP version of [enigma2-plugin-picons-snp-ziggo.220x132-190x102.light.on.transparent_](https://github.com/picons/picons/releases/download/2023-05-05--21-46-57/enigma2-plugin-picons-snp-ziggo.220x132-190x102.light.on.transparent_2023-05-05--21-46-57_all.ipk)

**Comment by Lexzie** [comment]
Do you really need srp-picons?
I would prefer snp-picons.

And why can't you use https://github.com/picons/picons/releases/download/2023-05-05--21-46-57/enigma2-plugin-picons-srp-full.220x132-190x102.light.on.transparent_2023-05-05--21-46-57_all.ipk?

**Comment by mvdlaan** [comment]
snp picons do only work on VTI when the name is exactly the same as the channel name (including spaces, special characters and lowercase/uppercase).

I installed the full package, but it gives me only picons on the satellite channels and not the Ziggo cable channels in the epg.

**Comment by Lexzie** [comment]
Okay, but you are referring to a snp package and I am referring to the same but srp package.
Are you sure you installed the right one?
Could you share your lamedb? (Settings file in /etc/enigma2/ or read it with Dreamset or dreamboxEDIT f.e.

**Comment by mvdlaan** [comment]
Yes, I have installed now:

enigma2-plugin-picons-snp-ziggo.220x132-190x102.light.on.transparent - 2023-05-05--21-46-57
enigma2-plugin-picons-srp-full.220x132-190x102.light.on.transparent - 2023-05-05--21-46-57

Here is my lamedb:

[lamedb.zip](https://github.com/picons/picons/files/11441991/lamedb.zip)

**Comment by AbuBaniaz** [comment]
Only a few packages are shown at first. You have to click on a button at bottom saying `show all resources` or something along those words. 

If the SNP package shows all of them them, the logos exist on this repository. We will need to add the links in the srp.index file so the picons are created.

Install this plugin and run it. Click on raw to download it. It will create a list in /tmp with most of the details we need.
```
https://github.com/oe-alliance/3rdparty-plugins-python3/blob/main/enigma2-plugin-extensions-missingpicons_2022_09_18_all.ipk
```
 
Please upload your lamedb file, but I think it is better if you can provide the missing links if you can.

**Comment by mvdlaan** [comment]
The installation of the given plugin fails:
root@vuultimo4k:/hdd/downloads# opkg install enigma2-plugin-extensions-missingpicons_2022_09_18_all.ipk
Collected errors:
 * deb_extract: enigma2-plugin-extensions-missingpicons_2022_09_18_all.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from enigma2-plugin-extensions-missingpicons_2022_09_18_all.ipk.

My lamedb is in the previous message in this thread.

**Comment by AbuBaniaz** [comment]
Here is the missing list, fltered for cable services. I have removed the radio services. Will you be able to list the links we need to add? Two entries as an example. More details in the contributing file.

```
13BA_69_8C9_FFFF0000=100procentnltv
1BB2_6B_8C9_FFFF0000=192tv
```

[ziggo.zip](https://github.com/picons/picons/files/11442258/ziggo.zip)

**Comment by Lexzie** [comment]
I'm pretty sure all the Ziggo links are okay.
I will check them with your lamedb, but can't right now.

**Comment by mvdlaan** [comment]
> Here is the missing list, fltered for cable services. I have removed the radio services. Will you be able to list the links we need to add? Two entries as an example. More details in the contributing file.
> 
> ```
> 13BA_69_8C9_FFFF0000=100procentnltv
> 1BB2_6B_8C9_FFFF0000=192tv
> ```
> 
> [ziggo.zip](https://github.com/picons/picons/files/11442258/ziggo.zip)

The provided zip file is empty.

**Comment by AbuBaniaz** [comment]
Oops, sorry about that.
[ziggo.zip](https://github.com/picons/picons/files/11442381/ziggo.zip)

I had a brief look on 5 random entries, none of those are in the index file.

**Comment by mvdlaan** [comment]
I checked for example npo1. In my bouquet:

#SERVICE 1:0:19:4BC9:832:600:FFFF0000:0:0:0:M

In the srp.index in the repository:
4BC9_832_600_FFFF0000=npo1

So it's strange that it does not work with the 'full' srp package. Or is that one missing the ziggo cable service references?

**Comment by AbuBaniaz** [comment]
based on your lamedb, it should be `3F2_65_8C9_FFFF0000=npo1`

**Comment by Lexzie** [comment]
Should be okay.
Can you check the filename in /etc/picon/ or wherever you have them installed?
What happens if you rename 1_0_1_4BC8_etc... to 1_0_19_ ?

Edit: I did not had the chance to check the lamedb. I'm waiting at the dentist right now.

**Comment by AbuBaniaz** [comment]
Look in the service list, and select cable services and not just bouquets. Some of them are there, some are not. 

![picon](https://github.com/picons/picons/assets/6644489/f8d488e7-4d1b-4bf0-8312-f5f915fe755f)

**Comment by AbuBaniaz** [comment]
@mvdlaan 
It seems you have many old entries in your lamedb file. can you please do the following: Remove all cable services
Up ( next to OK), Green for satellites, Select Cable services , menu, remove cable services, confirm restarts, then rescan just the  cable services and then re-upload lamedb.

Thanks in advance

**Comment by AbuBaniaz** [comment]
this is as far as I have got.

```
13BA_69_8C9_FFFF0000=100procentnltv
1BB2_6B_8C9_FFFF0000=192tv
A032_8D_8C9_FFFF0000=24kitchen
271B_A_10EF_FFFF0000=24kitchen
6982_7F_8C9_FFFF0000=24kitchen
36E2_72_8C9_FFFF0000=2mmonde
2742_6E_8C9_FFFF0000=3sat
1798_6A_8C9_FFFF0000=538tv
192_4_10EF_FFFF0000=adultchannel
2EE7_C_10EF_FFFF0000=algerie5
698C_7F_8C9_FFFF0000=aljazeera
986C_8B_8C9_FFFF0000=animalplanethd-clivebesle
2B3E_6F_8C9_FFFF0000=antena3
2760_6E_8C9_FFFF0000=arte
38D_9_10EF_FFFF0000=arte
9C7C_8C_8C9_FFFF0000=artehd
2346_6D_8C9_FFFF0000=at5
3013_CB_600_FFFF0000=atosrtv
2B2A_6F_8C9_FFFF0000=atv
46E6_76_8C9_FFFF0000=babytv
2B34_6F_8C9_FFFF0000=bbcentertainment
9498_8A_8C9_FFFF0000=bbcfirst
A438_8E_8C9_FFFF0000=bbcfirst
177A_6A_8C9_FFFF0000=bbcone
A80C_8F_8C9_FFFF0000=bbcone
61A9_19_10EF_FFFF0000=bbcone
1784_6A_8C9_FFFF0000=bbctwo
5DFC_7C_8C9_FFFF0000=bbctwo
61AA_19_10EF_FFFF0000=bbctwo
139C_69_8C9_FFFF0000=bbcworldnews
B3D8_92_8C9_FFFF0000=bbcworldnews
4A6A_77_8C9_FFFF0000=boomerang
3E81_10_10EF_FFFF0000=brazzerstv
36CE_72_8C9_FFFF0000=brazzerstv
7F8_66_8C9_FFFF0000=canvas
88CC_87_8C9_FFFF0000=canvas
6D92_80_8C9_FFFF0000=cartoonnetwork
4AC9_80C_600_FFFF0000=cartoonnetwork
3EA8_74_8C9_FFFF0000=cbbc
3EB2_74_8C9_FFFF0000=cbeebies_bbcfour
3336_71_8C9_FFFF0000=cbsreality
4B5B_813_600_FFFF0000=cbsreality
4B5B_813_600_FFFF0000=cbsreality
55F0_7A_8C9_FFFF0000=cctv9
466E_76_8C9_FFFF0000=cnbceurope
13B0_69_8C9_FFFF0000=cnn
32D2_71_8C9_FFFF0000=cnnturk
BE0_67_8C9_FFFF0000=comedycentral
55F2_16_10EF_FFFF0000=comedycentral
4B34_810_600_FFFF0000=comedycentralextra
2C4_7_10EF_FFFF0000=comedycentralextra
13E2_69_8C9_FFFF0000=comedycentralextra
4B34_810_600_FFFF0000=comedycentralextra
4A42_77_8C9_FFFF0000=comedycentralhd
69B4_7F_8C9_FFFF0000=crimeandinvestigation
4AF8_840_600_FFFF0000=daserste
1F86_6C_8C9_FFFF0000=daserste
2C8_7_10EF_FFFF0000=delta
26AD_7_10EF_FFFF0000=delta
3AB6_73_8C9_FFFF0000=denhaagtv
1B6C_6B_8C9_FFFF0000=discoverychannel
6D7E_80_8C9_FFFF0000=discoverychannelhd
4A7E_77_8C9_FFFF0000=discoveryscience-clivebesle
C22_1F_10EF_FFFF0000=discoveryscience-clivebesle
AFF0_91_8C9_FFFF0000=discoverysciencehd-clivebesle
46A_65_8C9_FFFF0000=disneychannel
6D64_1C_10EF_FFFF0000=disneyjunior
5618_7A_8C9_FFFF0000=dorceltv
3AA1_F_10EF_FFFF0000=dusk
5DE8_7C_8C9_FFFF0000=dusk
7EE_66_8C9_FFFF0000=een
88C2_87_8C9_FFFF0000=een
6D6A_80_8C9_FFFF0000=epopofculture
3EBC_74_8C9_FFFF0000=espn
3EC6_74_8C9_FFFF0000=espn2
88D6_87_8C9_FFFF0000=espn2
2B16_6F_8C9_FFFF0000=espn3
7544_82_8C9_FFFF0000=espn3
61B2_7D_8C9_FFFF0000=espn4
BB94_94_8C9_FFFF0000=espn4
718E_81_8C9_FFFF0000=espnhd
32E6_71_8C9_FFFF0000=eurod
13A6_69_8C9_FFFF0000=euronews
8CC8_88_8C9_FFFF0000=eurosport1
7D3C_84_8C9_FFFF0000=eurosport1hd
2332_6D_8C9_FFFF0000=eurosport2
909C_89_8C9_FFFF0000=eurosport2hd
5226_79_8C9_FFFF0000=eurostar
3340_71_8C9_FFFF0000=extremesports
4B5C_813_600_FFFF0000=extremesports
4B5C_813_600_FFFF0000=extremesports
301B_CB_600_FFFF0000=exxact
36B8_1C_10EF_FFFF0000=family7
1F5E_6C_8C9_FFFF0000=family7
330E_71_8C9_FFFF0000=fashiontv
7D32_84_8C9_FFFF0000=fashiontv
429A_75_8C9_FFFF0000=film1action
4272_75_8C9_FFFF0000=film1drama
36B5_E_10EF_FFFF0000=film1drama
4286_75_8C9_FFFF0000=film1family
36B3_E_10EF_FFFF0000=film1family
427C_75_8C9_FFFF0000=film1premiere
61BC_7D_8C9_FFFF0000=film1premiere
4664_76_8C9_FFFF0000=filmbox
5DC4_18_10EF_FFFF0000=foodnetwork
7954_83_8C9_FFFF0000=fox
9880_8B_8C9_FFFF0000=foxhd
560E_7A_8C9_FFFF0000=foxnews
138_3_10EF_FFFF0000=foxsports1
4A4D_806_600_FFFF0000=foxsports1
12E_3_10EF_FFFF0000=foxsports2
12F_3_10EF_FFFF0000=foxsports3
130_3_10EF_FFFF0000=foxsports4
2EEA_C_10EF_FFFF0000=foxsports5
3E89_10_10EF_FFFF0000=foxsports6
65D6_7E_8C9_FFFF0000=france2
6D9C_80_8C9_FFFF0000=france24
B3CE_92_8C9_FFFF0000=france24
5672_7A_8C9_FFFF0000=france3
2B02_6F_8C9_FFFF0000=haberturk
C23_1F_10EF_FFFF0000=havoc
524E_79_8C9_FFFF0000=history
756C_82_8C9_FFFF0000=historyhd
7D0A_84_8C9_FFFF0000=horseandcountry
370A_72_8C9_FFFF0000=hustlertv
9C68_8C_8C9_FFFF0000=iconcerts
A03C_8D_8C9_FFFF0000=iconcerts
90C4_89_8C9_FFFF0000=inplus
A046_8D_8C9_FFFF0000=insighttv
BB9E_94_8C9_FFFF0000=investigationdiscoveryhd-jusowanusw
4A88_77_8C9_FFFF0000=investigationdiscovery-jusowanusw
4AE0_80D_600_FFFF0000=investigationdiscovery-jusowanusw
947A_8A_8C9_FFFF0000=ketnet
A42E_8E_8C9_FFFF0000=kika
7170_81_8C9_FFFF0000=l1mburg
59E2_7B_8C9_FFFF0000=laune
300D_CB_600_FFFF0000=linq
9876_8B_8C9_FFFF0000=mediasetitalia
9862_8B_8C9_FFFF0000=meidenvanholland
3017_CB_600_FFFF0000=merwertv
17A2_6A_8C9_FFFF0000=mezzo
D2_2_10EF_FFFF0000=mtv
1F72_6C_8C9_FFFF0000=mtv
90D8_89_8C9_FFFF0000=mtv00s
17C0_6A_8C9_FFFF0000=mtv80s
A424_8E_8C9_FFFF0000=mtvhits
A050_8D_8C9_FFFF0000=mtvlivehd
426C_11_10EF_FFFF0000=mtvmusic24
8CD2_88_8C9_FFFF0000=nationalgeographic
6978_7F_8C9_FFFF0000=nationalgeographic
659A_7E_8C9_FFFF0000=nationalgeographicwild
6D88_80_8C9_FFFF0000=nationalgeographicwild
135_3_10EF_FFFF0000=nauticalchannel
5A00_7B_8C9_FFFF0000=ndr
BD6_67_8C9_FFFF0000=net5
6D61_1C_10EF_FFFF0000=net5
FD2_68_8C9_FFFF0000=net5
1B9E_6B_8C9_FFFF0000=nh
7936_83_8C9_FFFF0000=nhkworldjapan
816_66_8C9_FFFF0000=nickelodeon
4E34_78_8C9_FFFF0000=nickelodeonhd
4E66_78_8C9_FFFF0000=nickjr
4A60_77_8C9_FFFF0000=nickmusic
2AFD_B_10EF_FFFF0000=nickmusic
61DA_7D_8C9_FFFF0000=nicktoons
3F2_65_8C9_FFFF0000=npo1
811A_85_8C9_FFFF0000=npo1extra
2B05_B_10EF_FFFF0000=npo1extra
36BA_72_8C9_FFFF0000=npo1hd
3FC_65_8C9_FFFF0000=npo2
233C_6D_8C9_FFFF0000=npo2extra
80FC_85_8C9_FFFF0000=npo2hd
406_65_8C9_FFFF0000=npo3
8106_85_8C9_FFFF0000=npo3hd
2712_A_10EF_FFFF0000=nponieuws
17AC_6A_8C9_FFFF0000=nponieuws
65C2_7E_8C9_FFFF0000=npopolitiek
65A4_7E_8C9_FFFF0000=npozappelinextra
6D63_1C_10EF_FFFF0000=ntv
A38_1A_10EF_FFFF0000=omroepbrabant
866_66_8C9_FFFF0000=omroepbrabant
46D2_76_8C9_FFFF0000=omroepflevoland
55FA_7A_8C9_FFFF0000=omroepgelderland
3012_CB_600_FFFF0000=omroephoekschewaard
3AAC_73_8C9_FFFF0000=omroeponswestbrabant
A2E_1A_10EF_FFFF0000=omroeptholen
44C_65_8C9_FFFF0000=omroepwest
7184_81_8C9_FFFF0000=omroepzeeland
7166_81_8C9_FFFF0000=omropfryslan
2724_6E_8C9_FFFF0000=ons
300E_CB_600_FFFF0000=openrotterdam
5622_7A_8C9_FFFF0000=outtv
25C_6_10EF_FFFF0000=passiexxx
4A40_F_10EF_FFFF0000=pcne
4650_76_8C9_FFFF0000=pcne
4E63_804_600_FFFF0000=pebbletv
1392_69_8C9_FFFF0000=pebbletv
4E63_804_600_FFFF0000=pebbletv
17CA_6A_8C9_FFFF0000=penthousegold
59EC_7B_8C9_FFFF0000=prosieben
451B_81B_600_FFFF0000=psvtv
451B_81B_600_FFFF0000=psvtv
5636_7A_8C9_FFFF0000=rai1
4273_11_10EF_FFFF0000=rai1
3B9C_73_8C9_FFFF0000=regio90
300F_CB_600_FFFF0000=rotterdampodium
7922_83_8C9_FFFF0000=rtl
FAA_68_8C9_FFFF0000=rtl4
84E4_86_8C9_FFFF0000=rtl4
FB4_68_8C9_FFFF0000=rtl5
84EE_86_8C9_FFFF0000=rtl5
FF0_68_8C9_FFFF0000=rtl7
697D_1B_10EF_FFFF0000=rtl7
8CAA_88_8C9_FFFF0000=rtl7
BF4_67_8C9_FFFF0000=rtl8
697E_1B_10EF_FFFF0000=rtl8
8CB4_88_8C9_FFFF0000=rtl8
5258_79_8C9_FFFF0000=rtlcrime
5A0A_7B_8C9_FFFF0000=rtllounge
4E2A_78_8C9_FFFF0000=rtltelekids
A834_8F_8C9_FFFF0000=rtlz
AC26_90_8C9_FFFF0000=rtlz
271E_A_10EF_FFFF0000=rtlz
3010_CB_600_FFFF0000=rtvdordrecht
717A_81_8C9_FFFF0000=rtvdrenthe
3019_CB_600_FFFF0000=rtvkrimpenerwaard
3015_CB_600_FFFF0000=rtvlansingerland
90B0_89_8C9_FFFF0000=rtvnoord
90BA_89_8C9_FFFF0000=rtvoost
301A_CB_600_FFFF0000=rtvpapendrecht
3018_CB_600_FFFF0000=rtvridderkerk
802_66_8C9_FFFF0000=rtvrijnmond
A39_1A_10EF_FFFF0000=rtvrijnmond
30DD_CD_600_FFFF0000=rtvrijnstreek
3014_CB_600_FFFF0000=rtvslogo
1B8A_6B_8C9_FFFF0000=rtvutrecht
59F6_7B_8C9_FFFF0000=sat1
BCC_67_8C9_FFFF0000=sbs6
948E_8A_8C9_FFFF0000=sbs6
AC12_90_8C9_FFFF0000=sbs9
AC1C_90_8C9_FFFF0000=sbs9
3AE8_73_8C9_FFFF0000=schietv
7D46_84_8C9_FFFF0000=schlagertv
5A1E_7B_8C9_FFFF0000=secretcircle
90CE_89_8C9_FFFF0000=shortstv
754E_82_8C9_FFFF0000=shortstv
D6_2_10EF_FFFF0000=shortstv
65AE_7E_8C9_FFFF0000=showturk
5230_79_8C9_FFFF0000=slamtv
988A_8B_8C9_FFFF0000=spike
4BDD_833_600_FFFF0000=spike
36F6_72_8C9_FFFF0000=spike
3011_CB_600_FFFF0000=srctv
7E4_66_8C9_FFFF0000=stingrayclassica
753A_82_8C9_FFFF0000=stingraydjazz
7D14_84_8C9_FFFF0000=stingraydjazz
325_8_10EF_FFFF0000=swr
1B62_6B_8C9_FFFF0000=tlc
4E52_78_8C9_FFFF0000=tlchd
2EE6_C_10EF_FFFF0000=travelchannel
5DDE_7C_8C9_FFFF0000=trt1
523A_79_8C9_FFFF0000=trtcocuk
69A0_7F_8C9_FFFF0000=trtmuzik
4B4C_812_600_FFFF0000=trtturk
5262_79_8C9_FFFF0000=trtturk
4B4C_812_600_FFFF0000=trtturk
1BA8_6B_8C9_FFFF0000=tv5mondeeurope
271A_6E_8C9_FFFF0000=tv8
7148_81_8C9_FFFF0000=tveinternacional
3AA0_F_10EF_FFFF0000=tveinternacional
4D6E_BBC_600_FFFF0000=tvlimburg
3076_CC_600_FFFF0000=tvlimburg
65EA_7E_8C9_FFFF0000=tvoranje
4E49_803_600_FFFF0000=ukraina24
BEA_67_8C9_FFFF0000=veronica_disneyxd
9484_8A_8C9_FFFF0000=veronicahd_disneyxdhd
2B48_6F_8C9_FFFF0000=wdr
3016_CB_600_FFFF0000=wos
13D8_69_8C9_FFFF0000=xite
BBB2_94_8C9_FFFF0000=xite
3700_72_8C9_FFFF0000=xmo
1F7C_6C_8C9_FFFF0000=zdf
9C86_8C_8C9_FFFF0000=zdfhd
452F_81B_600_FFFF0000=ziggo
6981_1B_10EF_FFFF0000=ziggo
4CD6_81A_600_FFFF0000=ziggo
4A64_807_600_FFFF0000=ziggosport
2F12_70_8C9_FFFF0000=ziggosportdocu
2EFE_70_8C9_FFFF0000=ziggosportgolf
B3C4_92_8C9_FFFF0000=ziggosportgolf
2F08_70_8C9_FFFF0000=ziggosportracing
AFDC_91_8C9_FFFF0000=ziggosportracing
2EF4_70_8C9_FFFF0000=ziggosportselect
61C6_7D_8C9_FFFF0000=ziggosportselect
2EEA_70_8C9_FFFF0000=ziggosporttennis
2F1C_70_8C9_FFFF0000=ziggosportvoetbal
AFE6_91_8C9_FFFF0000=ziggosportvoetbal
```

**Comment by mvdlaan** [comment]
> Look in the service list, and select cable services and not just bouquets. Some of them are there, some are not.
> 
> ![picon](https://user-images.githubusercontent.com/6644489/237417663-f8d488e7-4d1b-4bf0-8312-f5f915fe755f.jpg)

Ok. I will take a look. Maybe re adding those channels to my bouquet will solve the issue.

**Comment by Lexzie** [comment]
Why is it so hard to do a new scan?
Get rid of the channels that don't exist anymore. It will only be in your way.
Do you need a tutorial on how to do that?

**Comment by mvdlaan** [comment]
[lamedb.zip](https://github.com/picons/picons/files/11456069/lamedb.zip)
Here a new lamedb after I did a cleanup and new cable scan.

**Comment by AbuBaniaz** [comment]
Looks like all your services have picons when I used the SRP all from 09/05/2023.  345 cable picons. The only ones missing are those listed below

```
Code Download
Code Download HZN
Codedownload D4A
CUTV
Film1 Applicatie
iTV CDT New
iTV cod 32
iTV cod 35
iTV cod 37
iTV cod 38
iTV CoD Canvas
iTV CoD een
iTV CoD Ketnet
iTV General Messaging 4
iTV Nachtlounge COD
iTV Self Care Application
iTV TV Tips
ondemand
Place Holder Application
Radio Actual
Standby Application
Switch Image
Test 13341
TV Guide
TV Search
VOD2 Dual Barker 1
VOD2 Dual Barker 2
VOD2 test
Welcome Application
Ziggo Live Events
```

**Comment by Lexzie** [comment]
Those are datachannels

**Comment by AbuBaniaz** [comment]
@mvdlaan 
Please close issue if everything is fine now.

**Comment by mvdlaan** [comment]
I could only get the picons working for the ziggo cable channels (and the satellite channels) by :

opkg install enigma2-plugin-picons-srp-ziggo.220x132-190x102.light.on.transparent_2023-04-29--23-28-03_all.ipk

opkg install enigma2-plugin-picons-srp-full.220x132-190x102.light.on.transparent_2023-05-05--21-46-57_all.ipk --force-overwrite

So there must be a difference between the srp full package and the ziggo package. And why is the separate ziggo package not included in the latest release of 5-5-2023??

**Comment by AbuBaniaz** [comment]
You usually get conflicts when you change picon package types, for example from 100x60 to 220x132, from snp to srp. Not sure if the control file can list every single type. Best to uninstall one, then install the new one. Most people update the same one, so not affected.

I don't know why the Ziggo one was not built, maybe the bots/tools failed. However, I tested the full srp version with your latest lamedb file and only the handful of channels listed earlier were missing.

BTW, your 28.2 services need a cleanup too.

**Comment by AbuBaniaz** [comment]
I think this is complete. Ok to close?

**Comment by mvdlaan** [comment]
Yes, I think so. I will try the latest release. That includes a separate Ziggo SRP package again.
