### ISSUE TITLE
Adding Kanal D2 (HD)

### ISSUE THREAD

**Issue by Znuff** [picons/picons#1470]
# SNP/SRP entries

**snp.index**
```
kanald2hd=kanald2
```

**srp.index**
```
A5AB_1A8_2C_FFFF0000=kanald2
```

# Logos

[logos.zip](https://github.com/picons/picons/files/11593633/logos.zip)

Presumably it's the same for `Kanal D2`, but my cable company is only broadcasting the HD channel. TV station doesn't seem to have different logos.

**Comment by Lexzie** [comment]
Added
