### ISSUE TITLE
Tele Zentralschweiz

### ISSUE THREAD

**Issue by ghost** [picons/picons#1482]
# SNP/SRP entries

**snp.index**
```
samplechannelname= Tele Zentralschweiz
samplechannelname1= Tele Zentralschweiz HD

```

**srp.index**
```
#SERVICE 1:0:19:24A1:16:1:FFFF0000:0:0:0:=samplelogoname

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
![Tele_Zentralschweiz_logo](https://github.com/picons/picons/assets/35585833/cd892add-a2fe-4dae-88dc-4add807206e2)

**Comment by Lexzie** [comment]
I don't think this channel is named 'samplechannelname', is it?
Logo name is without spaces and all lowercase.

**Comment by ghost** [comment]
I only have this data

#SERVICE 1:0:19:24A1:16:1:FFFF0000:0:0:0:Tele Zentralschweiz

https://de.wikipedia.org/wiki/Tele_Zentralschweiz

Maybe you can help me?

**Comment by AbuBaniaz** [comment]
We have been through this before, so if you do not understand, please say so. Let us deal with one logo at a time. 

Part 1.
I am talking about logo on this repository , not picon you want to create. 
Does the logo you want to use exist on this repository. If yes, what is the name of the logo?
If it doesn't, do you have the logos? Name them correctly and attach them

Part 2a
What is/are the channel names you want to create a picon for? 

Part 2b
What are the service reference for the channels you want to create a picon for.

**Comment by Lexzie** [comment]
Part 1
The logo does not exist on our repository, they are on Jasmeet's repo:
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Tele%20Zentralschweiz.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Tele%20Zentralschweiz%20-%20Dark.svg

Part 2b
The srp-link would be:
```
24A1_16_1_FFFF0000=telezentralschweiz
```
