### ISSUE TITLE
Laola1 TV

### ISSUE THREAD

**Issue by ghost** [picons/picons#1483]
# SNP/SRP entries

**snp.index**
```
samplechannelname=Laola1 TV HD
samplechannelname1=Laola1.TV HD
samplechannelname2=Laola1.TV
```

**srp.index**
```
#SERVICE 4097:0:1:29F:E72:0:0:0:0:0:http%3a//website%3a8080/live/user/passwd/331373.ts:Laola1 TV HD
#DESCRIPTION Laola1 TV HD=samplelogoname
425A_3DB8_13E_820000=samplelogoname1
4257_3DB8_13E_820000=samplelogoname2
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```
![neues-LAOLA1-Symbol-1024x576](https://github.com/picons/picons/assets/35585833/dc073c1a-784c-4caa-a154-d19d825a5430)

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by Lexzie** [comment]
Please make correct issues.
The guidelines and wizard are very clear.

In snp.index you place the exact channelname on place of `samplechannelname` without spaces, lowercase only, no special characters etc. and behind the `=` place the name of the logo, also lowercase without spaces etc,

You provide aoe logo and say you want to add links for the standard logo and the HD logo.
What do you expect form us, that we design a HD-logo?

The logos you provide are unusable.

Please do it right or we will close this.

And what about the title??

**Comment by ghost** [comment]
I don't know what the exact dates are? I only know that the logo that looks.

https://www.laola1.at/de/sportdaten/live/

<channel id="Laola1.at">4097:0:1:29F:E72:0:0:0:0:0:http%3a//example.com</channel> 

#SERVICE 4097:0:1:29F:E72:0:0:0:0:0:http%3a//website%3a8080/live/user/passwd/331373.ts:Laola1 TV HD
#DESCRIPTION Laola1 TV HD

Maybe you can help me?

I still have the logo vectorized.
![244577968-dc073c1a-784c-4caa-a154-d19d825a5430 jpg](https://github.com/picons/picons/assets/35585833/5802a343-fc6f-4437-81f6-6b3b79e3fb55)

**Comment by Lexzie** [comment]
What I am trying to say i sthat you need to deliver an issue conform our guidelines.
Now we have to do that and take me more time.

You should have done it like this:

# SNP/SRP entries

SNP/SRP entries

**snp.index**
```
laola1tvhd=laola1tv
```

**srp.index**
```
29F_E72_???_??????=laola1tv
```
# Logos

```
[logos.zip](https://github.com/picons/picons/files/11710349/logos.zip)

```

These logos are okay, I can only add the snp-link.

I cannot add the srp-link for the stream because it has no ONID and no namesapce.
If you use snp-picons you don't need a srp-link, otherwise add a ONID and namespace. If you have to make one up. use namesapce DDDD.

**Comment by Lexzie** [comment]
Added the logos and snp-links.
