### ISSUE TITLE
Update german channels

### ISSUE THREAD

**Issue by 0per8or** [picons/picons#150]
# SRP entries

Add/update logos for german channels

**srp.index**
```
A_4_85_C00000=skycinemapremieren
2B_3_85_C00000=skycinemapremierenplus24
87_8_85_C00000=skycinemapremierenplus24hd
83_6_85_C00000=skycinemapremierenhd
17_4_85_C00000=skykrimihd
6F_D_85_C00000=skycinemahd
2B7A_3F3_1_C00000=zdfneohd
5274_41D_1_C00000=welthd
5273_41D_1_C00000=comedycentralhd
EF14_421_1_C00000=ntvhd
11A_3_85_C00000=skysportbundesliga3
```

# Logos

[logos.zip](https://github.com/picons/picons/files/4432311/logos.zip)

**Comment by mrhotio** [comment]
there seems to be an error with the logo names inside logos.zip (EDIT: just one logo too many with a wrong name I think)
the color inconsistency "grey/white" for hd and non hd logos, is that how it's intended by the tv station?

**Comment by 0per8or** [comment]
Oh yes, you're right. There is one logo too much. Please ignore the one with the timestamp.

Can you explain what do you mean by color inconsistency?

**Comment by mrhotio** [comment]
Some have a greyish background, others white

**Comment by 0per8or** [comment]
There should be no background color. I had a look with different tools now, but for me it is transparent.

**Comment by mrhotio** [comment]
Sigh, it's part of the logo, you can't miss it

**Comment by 0per8or** [comment]
I didn't modify anything on the logos themselves.

To create them I used templates like this:
[https://de.wikipedia.org/wiki/Datei:Sky_Cinema_Classics_-_Logo_2016.svg](https://de.wikipedia.org/wiki/Datei:Sky_Cinema_Classics_-_Logo_2016.svg)

There are already more logos like that in the repo, like "skycinemaaction-wispelutri.default.png". But they are all PNG.
