### ISSUE TITLE
New Logos

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1555]
# SNP/SRP entries

**snp.index**
```
go3films=go3films.default
go3sport1=go3sport1.default
go3sport2=go3sport2.default
go3sport3=go3sport3.default
go3sportopen=go3sportopen.default
hits=hits.default
mtvaitio=mtvaitio.dark
mtvviihde=mtvviihde.default
nickelodeon=nickelodeon.default
nickelodeonhd=nickelodeonhd.default
nickelodeonglobal=nickelodeonglobal.default
sfkanalen=sfkanalen.default
stars=stars.default
tv4fakta=tv4fakta.default
tv4film=tv4film.default
tv4fotboll=tv4fotboll.default
tv4guld=tv4guld.default
tv4hits=tv4hits.default
tv4hockey=tv4hockey.default
tv4motor=tv4motor.default
tv4sportkanalen=tv4sportkanalen.default
tv4sportlive1=tv4sportlive1.default
tv4sportlive2=tv4sportlive2.default
tv4sportlive3=tv4sportlive3.default
tv4sportlive4=tv4sportlive4.default
tv4stars=tv4stars.default
tv4tennis=tv4tennis.default
tv4sweden=tv4sweden.default








[new 2023.zip](https://github.com/picons/picons/files/12352361/new.2023.zip)

**Comment by yannydodo12** [comment]
C more in Sweden Closed and TV4 Play took over..
TV3Sport changed to Go3Sport..

**Comment by Lexzie** [comment]
These links are already present in our repo:
```nickelodeon=nickelodeon
nickelodeonhd=nickelodeonhd
sfkanalen=sfkanalen
tv4fakta=tv4fakta
tv4film=tv4film
tv4guld=tv4guld
```

If I change the Nickelodeon logo, I first want to be sure all countries using the logo have changed or will change to the new logo.
So I first have to examinate that further before throwing away the old logo.

Save the logos as optimized svg's, see [here](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata) how that is done.


Please next time leave out the .default etc. in the list for new to add links in snp.index and also supply the srp-links.

**Comment by yannydodo12** [comment]
> These links are already present in our repo:
> 
> ```
> nickelodeonhd=nickelodeonhd
> sfkanalen=sfkanalen
> tv4fakta=tv4fakta
> tv4film=tv4film
> tv4guld=tv4guld
> ```
> 
> If I change the Nickelodeon logo, I first want to be sure all countries using the logo have changed or will change to the new logo. So I first have to examinate that further before throwing away the old logo.
> 
> Save the logos as optimized svg's, see [here](https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata) how that is done.
> 
> Please next time leave out the .default etc. in the list for new to add links in snp.index and also supply the srp-links.

Yeah sorry first time doing it lol
As for Nickelodeon. As far as I can see most have changed the logo to the splash logo.  I couldn't find a good Nickelodeon+1 logo for the UK.

**Comment by Lexzie** [comment]
> Yeah sorry first time doing it lol As for Nickelodeon. As far as I can see most have changed the logo to the splash logo. I couldn't find a good Nickelodeon+1 logo for the UK.

First time? Well then you did a (almost) flawless job.
You earned a label for that.
The comments are to learn from. The more you can supply us in correct order the more time we have for other logos.

I will get back at Nickelodeon, but now time to sleep.

**Comment by Lexzie** [comment]
Closed? How about the Nickelodeon logos?

**Comment by yannydodo12** [comment]
> Closed? How about the Nickelodeon logos?

Forgot about that lol.
I'd say it's safe to add them mate.
Need to find the Nickelodeon+1 logo that's it then..

**Comment by Lexzie** [comment]
Can you place a screenshot of the +1 logo as seen on your TV?
Maybe I can make it.

**Comment by yannydodo12** [comment]
> Can you place a screenshot of the +1 logo as seen on your TV? Maybe I can make it.

That's the problem with +1 they seems to be different on the different satellites l.
Heres on 19.2e  
https://ibb.co/dW1k6w6
Heres 13.0e
https://ibb.co/RjPMKCW
Here's 29.2e
https://ibb.co/31fDWHk

>

**Comment by yannydodo12** [comment]
Found this one but not too sure if it's correct
https://www.tvchannellists.com/wiki/images/d/d0/Nickelodeon_%2B1.svg

**Comment by Lexzie** [comment]
> > Can you place a screenshot of the +1 logo as seen on your TV? Maybe I can make it.
> 
> That's the problem with +1 they seems to be different on the different satellites l. Heres on 19.2e https://ibb.co/dW1k6w6 Heres 13.0e https://ibb.co/RjPMKCW Here's 29.2e https://ibb.co/31fDWHk
> 
> >

So we have to make three different +1 logos.

**Comment by yannydodo12** [comment]
yeah mate.. so will have to name them different.
13.0e   
38C4_1AF4_FBFF_820000=nickelodeonplus1	
28.2e	
C78D_815_2_11A0000=nickelodeonplus1
19.2e	
2010_430_1_C00000=nickelodeonplus1

**Comment by AbuBaniaz** [comment]
The logo on the sky website does not have a Plus 1. It does not matter if we use the logo with the +1 on our project, it is an icon. It is on LCN 616
```
https://www.sky.com/tv-guide/20230824/4101-1
```

The png without `plus 1` can be downloaded from here
```
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb1845.png
```

**Comment by Lexzie** [comment]
> Found this one but not too sure if it's correct https://www.tvchannellists.com/wiki/images/d/d0/Nickelodeon_%2B1.svg

Although the extension is svg, this is still a png image.
The nickelodeon and nicjkelodeon hd logos contain a base64-image, so not usable as svg's.


> yeah mate.. so will have to name them different. 13.0e 38C4_1AF4_FBFF_820000=nickelodeonplus1 28.2e C78D_815_2_11A0000=nickelodeonplus1 19.2e 2010_430_1_C00000=nickelodeonplus1

If we do, that's not the way to name them.

> The logo on the sky website does not have a Plus 1. It does not matter if we use the logo with the +1 on our project, it is an icon. It is on LCN 616
> 
> https://www.sky.com/tv-guide/20230824/4101-1
> 

Imho I think the logo on screen is leading.
 
> The png without `plus 1` can be downloaded from here
> 
> https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb1845.png

There was allready a svg provided by @yannydodo12

**Comment by yannydodo12** [comment]
I know was just showing you which was which.. 😆
Try here 
https://www.tvchannellists.com/w/File:Nickelodeon_%2B1.svg

**Comment by Lexzie** [comment]
> I know was just showing you which was which.. 😆 Try here https://www.tvchannellists.com/w/File:Nickelodeon_%2B1.svg

Is also a png.

The "splat"-logo is present there as an png: https://logos.fandom.com/wiki/Nickelodeon_(Latin_America)?file=Nickelodeon_Splat_2023.png
I think we'll have to settle with a png instead of a svg.

I have made a list of all the Nickelodeon channels I know so far to check their logos.
Unfortunately I cannot decode as many channels as I would like to to check the logo.
I cannot see: [Nickelodeon UK](https://www.lyngsat.com/tvchannels/us/Nickelodeon-UK.html), [Nickelodeon Ireland](https://www.lyngsat.com/tvchannels/us/Nickelodeon-Ireland.html), [Nickelodeon France](https://www.lyngsat.com/tvchannels/us/Nickelodeon-France.html), [Nickelodeon Greece](https://www.lyngsat.com/tvchannels/us/Nickelodeon-Greece.html), [Nickelodeon Italia](https://www.lyngsat.com/tvchannels/us/Nickelodeon-Italia.html), [Nickelodeon CIS](https://www.lyngsat.com/tvchannels/us/Nickelodeon-CIS.html), [Nickelodeon Türkiye](https://www.lyngsat.com/tvchannels/us/Nickelodeon-Turkiye.html), [Nickelodeon Africa](https://www.lyngsat.com/tvchannels/us/Nickelodeon-Africa.html). 
(I wonder how you managed to get all the +1 screenshots @yannydodo12).
For now I assume the normal logo if I don't have any other information.
Unless someone can make a screenshot.

Another problem is the white nickelodeon letters on a light background.

**Comment by yannydodo12** [comment]
It's definitely a svg lol not sure why you're seeing it as a PNG.
I'll upload the svg now for you..
And I have IPTV and satellite sub to see them..

**Comment by Lexzie** [comment]
> It's definitely a svg lol not sure why you're seeing it as a PNG.

This is why:
![afbeelding](https://github.com/picons/picons/assets/14023349/eed82a00-e97a-46e8-aa30-b325f6c691a6)


If it is a svg, I get this when I right-click on it:
Save page as... and not save image as...
![afbeelding](https://github.com/picons/picons/assets/14023349/907bde8f-7f95-40e9-b59d-157f86c77649)

I downloaded the file and opening it with Notepad++ reveiles why it is (partially) a png:
![afbeelding](https://github.com/picons/picons/assets/14023349/7d8621b7-f886-40d4-b5d5-0bbdcdc58ac5)

No problem though, we'll just have to use it as png.

**Comment by yannydodo12** [comment]
yeah your right.
here it is in svg format you might be able to do something with it..
[Nickelodeon_+1.zip](https://github.com/picons/picons/files/12446584/Nickelodeon_%2B1.zip)

**Comment by yannydodo12** [comment]
I would like to to check the logo.
I cannot see: Nickelodeon UK, Nickelodeon Ireland, Nickelodeon France, Nickelodeon Greece, Nickelodeon Italia, Nickelodeon CIS, Nickelodeon Türkiye, Nickelodeon Africa.

Nickelodeon UK = YES
Nickelodeon Ireland = YES
Nickelodeon France = YES
Nickelodeon Greece ,= NO using old logo
Nickelodeon Italia, = YES
Nickelodeon Türkiye = is using the Nickelodeon global logo
Nickelodeon CIS = don't know what this is.?
Nickelodeon Africa = YES

Hope this help..

**Comment by Lexzie** [comment]
> Hope this help..

Thank you

> Nickelodeon CIS = don't know what this is.?
> 

If you clicked on it you would see where it is on satellite.
I beleive CIS is this: https://en.wikipedia.org/wiki/Commonwealth_of_Independent_States.

**Comment by yannydodo12** [comment]
> If you clicked on it you would see where it is on satellite. I beleive CIS is this: https://en.wikipedia.org/wiki/Commonwealth_of_Independent_States.

Yeah lol
Can't pick any of them up here..

**Comment by Lexzie** [comment]
> I would like to to check the logo. I cannot see: Nickelodeon UK, Nickelodeon Ireland, Nickelodeon France, Nickelodeon Greece, Nickelodeon Italia, Nickelodeon CIS, Nickelodeon Türkiye, Nickelodeon Africa.
> 
> Nickelodeon UK = YES Nickelodeon Ireland = YES Nickelodeon France = YES Nickelodeon Greece ,= NO using old logo Nickelodeon Italia, = YES Nickelodeon Türkiye = is using the Nickelodeon global logo Nickelodeon CIS = don't know what this is.? Nickelodeon Africa = YES
> 
> Hope this help..

I have seen no channels showing the nickelodeonhd logo, did you?

**Comment by yannydodo12** [comment]
I have seen no channels showing the nickelodeonhd logo, did you?

No mate..
Most channels seems to be moving away from the HD logos.

**Comment by Lexzie** [comment]
Great, that saves a lot of trouble with different logos.
Only just the +1 logos.
Have to make them yet,

But the list is now complete enough, I think.

Strangly a few who are known on Lyngsat for being 'Nickelodeon Europe' have the global logo and others not. Guess those are not the 'Europe' version...

**Comment by Lexzie** [comment]
I am almost ready to upload all the changes.

In the meantime, could you check on the French Nickelodeon Junior and Nickelodeon Teen if the logos have changed?
In [Nickipedia](https://nickelodeon.fandom.com/wiki/Nickelodeon_Wiki) I see that (US) NickToons and TeenNick also have the splat-logo. Have not seen any changes overhere so far.

**Comment by yannydodo12** [comment]
> I am almost ready to upload all the changes.
> 
> In the meantime, could you check on the French Nickelodeon Junior and Nickelodeon Teen if the logos have changed? In [Nickipedia](https://nickelodeon.fandom.com/wiki/Nickelodeon_Wiki) I see that (US) NickToons and TeenNick also have the splat-logo. Have not seen any changes overhere so far.

No change mate I've already checked them. 
Like you said so far only the American have changed..

**Comment by Lexzie** [comment]
Looks like all is done.
![afbeelding](https://github.com/picons/picons/assets/14023349/cfd9a7cb-26f7-47a7-8b15-1f3428a8275f)
