### ISSUE TITLE
updated logos

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1567]
Just updated logos, no change of snp or srp
[new logos.zip](https://github.com/picons/picons/files/12428182/new.logos.zip)

**Comment by yannydodo12** [comment]
daznlaliga 3 & 4 again no change to snp or srp
[daznlaliga3&4.zip](https://github.com/picons/picons/files/12429156/daznlaliga3.4.zip)

**Comment by Lexzie** [comment]
By the way, unbeleivable how many LaLiga channels you can have in one country???

The default `laligatv` logo is usable for both dark and light backgrounds, zo no need for a light variant.
