### ISSUE TITLE
laligatvbar 

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1568]
# SNP/SRP entries

**snp.index**
```
laligatvbarhd=laligatvbarhd
laligatvbar2=laligatvbar2
laligatvbar3=laligatvbar3
laligatvbar4=laligatvbar4
laligatvbar5=laligatvbar5
```

**srp.index**
```
7859_41A_1_C00000=laligatvbarhd
76C5_40E_1_C00000=laligatvbar2
769A_41E_1_C00000=laligatvbar3
7610_408_1_C00000=laligatvbar4
760E_408_1_C00000=laligatvbar5

laligatvbar no change to snp.index or srp.index

can be removed in srp.index
76C5_40E_1_C00000=laligatvbarm2
769A_41E_1_C00000=laligatvbarm3
7610_408_1_C00000=laligatvbarm4
760E_408_1_C00000=laligatvbarm5
[LaligaTVBar.zip](https://github.com/picons/picons/files/12428624/LaligaTVBar.zip)

**Comment by Lexzie** [comment]
What's the source of those logos?
We also need svg logos for La Liga TV Hypermotion 2-5.

Can you also supply LaLiga TV Bar 6-9?

`laligatvbar` and `laligatvbarhd` are the same. No need for duplicate logos. We'll fix that in the .index files, like this:
```
laligatvbar=laligatvbar
laligatvbarhd=laligatvbar
```
We link the two different names (or service references) to the same logo.

**Comment by yannydodo12** [comment]
What's the source of those logos? 
Logopedia mostly

We also need svg logos for La Liga TV Hypermotion 2-5.
Sorry haven't found good enough ones for them yet.

Can you also supply LaLiga TV Bar 6-9
Will have to make them.

laligatvbar=laligatvbar
> laligatvbarhd=laligatvbar
K mate.. 

can see the logos used here but are too small to use.
https://comunidad.orange.es/t5/Todo-el-f%C3%BAtbol-series-y-estrenos-en-OrangeTV/Calendario-f%C3%BAtbol-Orange-TV-2023-2024/td-p/580905

**Comment by Lexzie** [comment]
> What's the source of those logos? Logopedia mostly
> 
Not all those logos are in SVG there.

> We also need svg logos for La Liga TV Hypermotion 2-5. Sorry haven't found good enough ones for them yet.
> 
> can see the logos used here but are too small to use. https://comunidad.orange.es/t5/Todo-el-f%C3%BAtbol-series-y-estrenos-en-OrangeTV/Calendario-f%C3%BAtbol-Orange-TV-2023-2024/td-p/580905

Indeed, I will make them with help from the DAZN-logos.

**Comment by yannydodo12** [comment]
Yeah can't find most of them in svg.
So I made some with the help of 
https://svgtrace.com/

**Comment by yannydodo12** [comment]
What happened to this lad, he was the best at looking after all the channel changes
Jasmeet181

**Comment by Lexzie** [comment]
> Yeah can't find most of them in svg. So I made some with the help of https://svgtrace.com/

In that case did that website a pretty good job, or did you clean them afterwards?
Because mostly converting a bitmapped imgae to a vectorimage produces all kinds of ugly errors.
Look for exmple in the left corner below the 3 in `daznlaliga3`. The corner isn't straight.
(You have to zoom in to see it.)
Which ones did you convert? I have to check them for those tiny flaws

> What happened to this lad, he was the best at looking after all the channel changes Jasmeet181

He has his own [repositories](https://github.com/Jasmeet181), you may use it as a source.
But indeed he was always quick with changes and last changes are 7 months ago.

**Comment by yannydodo12** [comment]
> In that case did that website a pretty good job, or did you clean them afterwards? Because mostly converting a bitmapped imgae to a vectorimage produces all kinds of ugly errors. Look for exmple in the left corner below the 3 in `daznlaliga3`. The corner isn't straight. (You have to zoom in to see it.) Which ones did you convert? I have to check them for those tiny flaws


What I done with 3&4 is use your uploaded daznlaliga 3&4 and output them as a PNG. Then I output the daznlaliga as a PNG and just cut out the 3&4 and added them to the daznlaliga PNG. Must of copied a bit of the corner 😂
Then used that website to convert to svg.

**Comment by Lexzie** [comment]
I cleaned daznlaliga2, 3 and 4.
