### ISSUE TITLE
Blue Sport Live HD and UHD Channels

### ISSUE THREAD

**Issue by ghost** [picons/picons#1578]
# SNP/SRP entries

**snp.index**
```
BlueSport1Live=Blue Sport 1 Live
BlueSport1LiveHD=Blue Sport 1 Live HD

BlueSport2Live=Blue Sport 2 Live
BlueSport2LiveHD=Blue Sport 2 Live HD

BlueSport3Live=Blue Sport 3 Live
BlueSport3LiveHD=Blue Sport 3 Live HD

BlueSport4Live=Blue Sport 4 Live
BlueSport4LiveHD=Blue Sport 4 Live HD

BlueSport5Live=Blue Sport 5 Live
BlueSport5LiveHD=Blue Sport 5 Live HD

BlueSport6Live=Blue Sport 6 Live
BlueSport6LiveHD=Blue Sport 6 Live HD

BlueSport7Live=Blue Sport 7 Live
BlueSport7LiveHD=Blue Sport 7 Live HD

BlueSport8Live=Blue Sport 8 Live
BlueSport8LiveHD=Blue Sport 8 Live HD

BlueSport9Live=Blue Sport 9 Live
BlueSport9LiveHD=Blue Sport 9 Live HD

BlueSport10Live=Blue Sport 10 Live
BlueSport10LiveHD=Blue Sport 10 Live HD

BlueSport11Live=Blue Sport 11 Live
BlueSport11LiveHD=Blue Sport 11 Live HD

BlueSport12Live=Blue Sport 12 Live
BlueSport12LiveHD=Blue Sport 12 Live HD

BlueSport13Live=Blue Sport 13 Live
BlueSport13LiveHD=Blue Sport 13 Live HD

BlueSport14Live=Blue Sport 14 Live
BlueSport14LiveHD=Blue Sport 14 Live HD

BlueSport15Live=Blue Sport 15 Live
BlueSport15LiveHD=Blue Sport 15 Live HD

BlueSport16Live=Blue Sport 16 Live
BlueSport16LiveHD=Blue Sport 16 Live HD

BlueSport17Live=Blue Sport 17 Live
BlueSport17LiveHD=Blue Sport 17 Live HD

```

**srp.index**
```
4097:0:1:29F:B976:0:0:0:0:0=Blue Sport 1 Live HD
4097:0:1:029f:b976:0:0:0:0:0=Blue Sport 1 HD

4097:0:1:29F:B977:0:0:0:0:0=Blue Sport 2 Live HD
4097:0:1:029f:b977:0:0:0:0:0=Blue Sport 2 HD

4097:0:1:29F:B978:0:0:0:0:0=Blue Sport 3 Live HD
4097:0:1:029f:b978:0:0:0:0:0=Blue Sport 3 HD

4097:0:1:29F:B979:0:0:0:0:0=Blue Sport 4 Live HD
4097:0:1:029f:b979:0:0:0:0:0=Blue Sport 4 HD

4097:0:1:29F:B97B:0:0:0:0:0=Blue Sport 5 Live HD
4097:0:1:029f:b97b:0:0:0:0:0=Blue Sport 5 HD

4097:0:1:29F:B97C:0:0:0:0:0=Blue Sport 6 Live HD
4097:0:1:029f:b97c:0:0:0:0:0=Blue Sport 6 HD

4097:0:1:29F:B97D:0:0:0:0:0=Blue Sport 7 Live HD
4097:0:1:029f:b97d:0:0:0:0:0=Blue Sport 7 HD

4097:0:1:29F:B97E:0:0:0:0:0=Blue Sport 8 Live HD
4097:0:1:029f:b97e:0:0:0:0:0=Blue Sport 8 HD

4097:0:1:29F:B97F:0:0:0:0:0=Blue Sport 9 Live HD
4097:0:1:029f:b97f:0:0:0:0:0.=Blue Sport 9 HD

4097:0:1:29F:B980:0:0:0:0:0=Blue Sport 10 Live HD
4097:0:1:029f:b980:0:0:0:0:0=Blue Sport 10 HD

4097:0:1:29F:B981:0:0:0:0:0=Blue Sport 11 Live HD
4097:0:1:029f:b981:0:0:0:0:0=Blue Sport 11 HD

4097:0:1:29F:B982:0:0:0:0:0=Blue Sport 12 Live HD
4097:0:1:029f:b982:0:0:0:0:0=Blue Sport 12 HD

4097:0:1:29F:B983:0:0:0:0:0=Blue Sport 13 Live HD
4097:0:1:029f:b983:0:0:0:0:0=Blue Sport 13 HD

4097:0:1:29F:B984:0:0:0:0:0=Blue Sport 14 Live HD
4097:0:1:029f:b984:0:0:0:0:0=Blue Sport 14 HD

4097:0:1:29F:B985:0:0:0:0:0=Blue Sport 15 Live HD
4097:0:1:029f:b985:0:0:0:0:0=Blue Sport 15 HD

4097:0:1:29F:B986:0:0:0:0:0=Blue Sport 16 Live HD
4097:0:1:029f:b986:0:0:0:0:0=Blue Sport 16 HD

4097:0:1:29F:B987:0:0:0:0:0=Blue Sport 17 Live HD
4097:0:1:029f:b987:0:0:0:0:0=Blue Sport 17 HD

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```
[Blue Sport Logos.zip](https://github.com/picons/picons/files/12459034/Blue.Sport.Logos.zip)

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
[Blue Sport Logos.zip](https://github.com/picons/picons/files/12459036/Blue.Sport.Logos.zip)

**Comment by ghost** [comment]
Hello 

There are new Blue Sport channel names. I can't find any decent logos of acceptable quality anywhere. (See attachment)

Kind regards
William

**Comment by Lexzie** [comment]
The logos in the zipfile are totally unusable.
Please find good quality logos.

**Comment by ghost** [comment]
I can't find any decent logos of acceptable quality anywhere.

**Comment by Lexzie** [comment]
Then we can't use it.

**Comment by William-Richards** [comment]
![bluesport1livehd](https://github.com/picons/picons/assets/35585833/4b721e3b-87d9-407b-b7d3-bac0fdb527aa)
![bluesport2livehd](https://github.com/picons/picons/assets/35585833/0666d501-7ab2-48b7-bfe6-224a659ec90b)
![bluesport3livehd](https://github.com/picons/picons/assets/35585833/274c34a7-d9ea-408f-ad03-c7e4baf7eaf9)
![bluesport4livehd](https://github.com/picons/picons/assets/35585833/c480c79f-6f93-4943-8a81-3fd1ae77a622)
![bluesport5livehd](https://github.com/picons/picons/assets/35585833/39aa6acc-1263-4357-b030-ce5dfd10bff5)
![bluesport6livehd](https://github.com/picons/picons/assets/35585833/2d2115aa-1b8b-4b8f-bc1e-218d46de5a6a)
![bluesport7livehd](https://github.com/picons/picons/assets/35585833/3c40a123-44ad-4eb9-a3dd-24c3480a62ec)
![bluesport8livehd](https://github.com/picons/picons/assets/35585833/df4574fd-30ce-4d75-be53-e58e92814871)
![bluesport9livehd](https://github.com/picons/picons/assets/35585833/40d58c8b-b889-4941-9314-30946be22de7)
![bluesport10livehd](https://github.com/picons/picons/assets/35585833/84fb975c-99e1-4cf3-9874-f34691bc6fa9)
![bluesport11livehd](https://github.com/picons/picons/assets/35585833/cd85e91f-c538-4a8d-aac5-61c08eb05931)
![bluesport12livehd](https://github.com/picons/picons/assets/35585833/4449c53d-f3fa-4e37-948f-187ebdabd346)
![bluesport13livehd](https://github.com/picons/picons/assets/35585833/0d85ea58-b53d-45b9-98fe-4dece22b478a)
![bluesport14livehd](https://github.com/picons/picons/assets/35585833/73fec056-b813-495c-b4d5-255aad5816fd)
![bluesport15livehd](https://github.com/picons/picons/assets/35585833/55b3c36b-f3e5-44a4-a9e0-22be7b7b56d6)
![bluesport16livehd](https://github.com/picons/picons/assets/35585833/b42910f4-2b30-408d-ac63-8bcd4a49d45e)
![bluesport17livehd](https://github.com/picons/picons/assets/35585833/d043be24-0ed7-473e-bf13-b87f380ae79a)

**Comment by ghost** [comment]
Blue Sport 1-17 Picon without number and Live Logo

They always change the name anyway, sometimes it's called Blue Sport Live or Blue Sport Event or Blue Sport Direct.
With neutral Blue Sport Picon it will always be good for Blue Sport 1- 17...

**Comment by Lexzie** [comment]
If you want it that way, we can do that.

You could also try to find out what font is used, f.e. with [fontsquirrel](https://www.fontsquirrel.com/).
Quick look looks like Arial Rounded MT Bold could be a good one.

If logos are the same make just one.
In this case `bluesport`.
Although these logos are not good enough too.
Just use one of the logos already in our repo and edit it with Inkscape.


Please provide a correct list of srp- and snp-links, like this:

**snp.index**
```
bluesportlive1uhd=bluesport
bluesportlive2uhd=bluesport
```

**srp.index**
```
29F_B976_0_0=bluesport
29F_B977_0_0=bluesport
```
etc. 
Make some effort yourself.
