### ISSUE TITLE
Telekom Sport Logos

### ISSUE THREAD

**Issue by Znuff** [picons/picons#159]
# SNP/SRP entries

I don't have a proper SRP/SNP, so I'll give this a try:

**snp.index**
```
telekomsport1=telekomsport1
telekomsport1hd=telekomsport1hd
telekomsport2=telekomsport2
telekomsport2hd=
telekomsport3=telekomsport3
telekomsport3hd=
telekomsport4=telekomsport4
telekomsport4hd=

moozhd=
moozro=moozro
```

**srp.index**
```
A2E5_1A1_2C_FFFF0000=telekomsport1
9D09_192_2C_FFFF0000=telekomsport1hd
A2E6_1A1_2C_FFFF0000=telekomsport2
A7FD_1AE_2C_FFFF0000=
A350_1A2_2C_FFFF0000=telekomsport3
A861_1AF_2C_FFFF0000=
9C44_1A9_2C_FFFF0000=telekomsport4
A862_1AF_2C_FFFF0000=

9D6F_193_2C_FFFF0000=
A47F_1A5_2C_FFFF0000=moozro
```

# Logos

[telekom_logos.zip](https://github.com/picons/picons/files/4448493/telekom_logos.zip)

This is the rawdata from `servicelist-tvheadend-servermode-snp.txt`:

```
1_0_1_A2E5_1A1_2C_FFFF0000_0_0_0     |  Telekom Sport 1          |  A2E5_1A1_2C_FFFF0000=--------    |  telekomsport1=--------
1_0_19_9D09_192_2C_FFFF0000_0_0_0    |  Telekom Sport 1 HD       |  9D09_192_2C_FFFF0000=--------    |  telekomsport1hd=--------
1_0_1_A2E6_1A1_2C_FFFF0000_0_0_0     |  Telekom Sport 2          |  A2E6_1A1_2C_FFFF0000=--------    |  telekomsport2=--------
1_0_19_A7FD_1AE_2C_FFFF0000_0_0_0    |  Telekom Sport 2 HD       |  A7FD_1AE_2C_FFFF0000=--------    |  telekomsport2hd=--------
1_0_1_A350_1A2_2C_FFFF0000_0_0_0     |  Telekom Sport 3          |  A350_1A2_2C_FFFF0000=--------    |  telekomsport3=--------
1_0_19_A861_1AF_2C_FFFF0000_0_0_0    |  Telekom Sport 3 HD       |  A861_1AF_2C_FFFF0000=--------    |  telekomsport3hd=--------
1_0_1_9C44_1A9_2C_FFFF0000_0_0_0     |  Telekom Sport 4          |  9C44_1A9_2C_FFFF0000=--------    |  telekomsport4=--------
1_0_19_A862_1AF_2C_FFFF0000_0_0_0    |  Telekom Sport 4 HD       |  A862_1AF_2C_FFFF0000=--------    |  telekomsport4hd=--------

1_0_19_9D6F_193_2C_FFFF0000_0_0_0    |  Mooz HD                  |  9D6F_193_2C_FFFF0000=--------    |  moozhd=--------
1_0_1_A47F_1A5_2C_FFFF0000_0_0_0     |  Mooz RO                  |  A47F_1A5_2C_FFFF0000=--------    |  moozro=--------
```

**Comment by Lexzie** [comment]
You have some mising logo names in your links, Probably because you don't have HD logos for them, I think I can make them like the `telekomsport1hd` logo.
Your supplied logos also do not meet the desired filename resolution.
```
<logoname>.default.<png|svg>
```
No worries, I will fix that.

I can have a look at this later. But first a few questions:

Can you give me the sources where you found the logos?

Also I can provide the links for the channels on satellite, I guess these are the channels?
https://www.lyngsat.com/tvchannels/ro/Telekom-Sport-1.html
https://www.lyngsat.com/tvchannels/ro/Telekom-Sport-2.html
https://www.lyngsat.com/tvchannels/ro/Telekom-Sport-3.html
https://www.lyngsat.com/tvchannels/ro/Telekom-Sport-4.html
https://www.lyngsat.com/tvchannels/ro/Mooz-Ro.html

Are Mooz HD and Mooz Ro the same channel? (HD / SD)

Do I need to do anything with the linkpress logo? It's not in the Telekom package on Hellas Sat.
https://www.lyngsat.com/packages/Telekom-TV.html

**Comment by Znuff** [comment]
Thank you. Sorry for the naming, didn't pay enough attention.

All the logos were found here: https://logos.fandom.com/wiki/Category:Television_channels_in_Romania

Indeed, I have not provided the logos with HD because I wasn't able to find them.

I was hoping someone could actually make them (they don't seem complicated, but I lack the skills to draw them vectorially).

Further more, on a second look, it doesn't actually seem the channels themselves use a different logo with "HD" appended, they use the normal logo, so I think it's safe to actually just use the normal one? 

- Screenshot from Telekom Sport 1 HD: https://i.imgur.com/kB1l1UL.png
- Screenshot from Telekom Sport 4 HD: https://i.imgur.com/ePokK7c.png

In regards to Mooz HD and Mooz RO, they are not the same channel, they have different transmissions, for example at this hour:

- Mooz HD: https://i.imgur.com/SRFVfIk.png
- Mooz RO: https://i.imgur.com/3qGxY0k.png

LinkPress seems to be only broadcast trough DVB-C for the moment, and it's kind of new. In my initial scan & build with TvHeadEnd I didn't find it, but it appeared in the last ~2 weeks, so sadly I do not have it in a format that I can give out a properly formatted SNP entry, BUT, I do have this:

```
PAT TSID:405
- PNR:40510 PID:2220
PMT PNR:40510
- PCR PID:2320
- VIDEO PID:2320 TYPE:0x02 ISO/IEC 13818-2 Video
- AUDIO PID:2420 TYPE:0x03 ISO/IEC 11172 Audio
- Language: ron
SDT TSID:405
- PNR:40510
- Provider: Next Gen INE 3
- Service: LinkPress
```

Based on my (simple) understanding of the SNP format, I think they're simply HEX(PMT PNR)_HEX(PAT TSID) conversions of the PIDs, so I believe LinkPress should be:

```
9E3E_195_2C_FFFF0000=linkpress
```

Again, this is DVB-C.

**Comment by Lexzie** [comment]
> I was hoping someone could actually make them (they don't seem complicated, but I lack the skills to draw them vectorially).

I could do that.

> Further more, on a second look, it doesn't actually seem the channels themselves use a different logo with "HD" appended, they use the normal logo, so I think it's safe to actually just use the normal one?

Yes, in that case I don't like special HD logos, mostly the actual logo in the picon gets smaller and less recognisable.
Besides that, without a special HD logo it should be enough to have just one snp-link if HD is appended to the same name.
So in this case these links are sufficient for both the SD and the HD names:
```
telekomsport1=telekomsport1
telekomsport2=telekomsport2
telekomsport3=telekomsport3
telekomsport4=telekomsport4
```
At least that's what is normal on Enigma2 set-top-boxes.
Could you please check if I'm right for TV Headend too after the picons are updated on your server?

> In regards to Mooz HD and Mooz RO, they are not the same channel, they have different transmissions, for example at this hour:
> 
>     Mooz HD: https://i.imgur.com/SRFVfIk.png
>     Mooz RO: https://i.imgur.com/3qGxY0k.png

In that case they **do** need each an own logo.
Maybe you can find the Mooz HD logo?

> LinkPress seems to be only broadcast trough DVB-C for the moment, and it's kind of new. In my initial scan & build with TvHeadEnd I didn't find it, but it appeared in the last ~2 weeks, so sadly I do not have it in a format that I can give out a properly formatted SNP entry, BUT, I do have this:
> 
> PAT TSID:405
> - PNR:40510 PID:2220
> PMT PNR:40510
> - PCR PID:2320
> - VIDEO PID:2320 TYPE:0x02 ISO/IEC 13818-2 Video
> - AUDIO PID:2420 TYPE:0x03 ISO/IEC 11172 Audio
> - Language: ron
> SDT TSID:405
> - PNR:40510
> - Provider: Next Gen INE 3
> - Service: LinkPress
> 
> Based on my (simple) understanding of the SNP format, I think they're simply HEX(PMT PNR)_HEX(PAT TSID) conversions of the PIDs, so I believe LinkPress should be:
> 
> `9E3E_195_2C_FFFF0000=linkpress`
> 

No, it's not, this is the format:
HEX(SID)_HEX(TID)_HEX(ONID)_HEX(namespace)
Where I mean with SID the Service PID, TID is Transponder ID, ONID is Network ID.
Namespace for DVB-C is always FFFF0000 (as far as I have seen).
By the way, this is a SRP entry (SRP=Service Reference Picon).

SNP is Service Name Picon.

I can only add a srp-link if you can provide the correct service reference.
For now I can add it with just a snp-link.

**Comment by mrhotio** [comment]
Maybe we should start considering to stop wasting time on HD logos.....it's 2020 afterall and HD isn't all that special anymore.

**Comment by Znuff** [comment]
> Maybe we should start considering to stop wasting time on HD logos.....it's 2020 afterall and HD isn't all that special anymore.

That may very well be the case, but there are still some providers that have different logos for HD/SD channels. Your guess is as good as mine as to why that would still be the case in 2020.




> So in this case these links are sufficient for both the SD and the HD names:
> 
> ```
> telekomsport1=telekomsport1
> telekomsport2=telekomsport2
> telekomsport3=telekomsport3
> telekomsport4=telekomsport4
> ```
> 
> At least that's what is normal on Enigma2 set-top-boxes.
> Could you please check if I'm right for TV Headend too after the picons are updated on your server?

I could do that in a few days.

> > In regards to Mooz HD and Mooz RO, they are not the same channel, they have different transmissions, for example at this hour:
> > ```
> > Mooz HD: https://i.imgur.com/SRFVfIk.png
> > Mooz RO: https://i.imgur.com/3qGxY0k.png
> > ```
> 
> In that case they **do** need each an own logo.
> Maybe you can find the Mooz HD logo?

This is all I could find on their official website, but size is not that great (it's the same size as the one I have attached for Mooz RO):

From: https://mooz.tv/mooz-hd/ -- https://mooz.tv/site/img/mooz-hd.jpg

> > LinkPress seems to be only broadcast trough DVB-C for the moment, and it's kind of new. In my initial scan & build with TvHeadEnd I didn't find it, but it appeared in the last ~2 weeks, so sadly I do not have it in a format that I can give out a properly formatted SNP entry, BUT, I do have this:
> > PAT TSID:405
> > 
> > * PNR:40510 PID:2220
> >   PMT PNR:40510
> > * PCR PID:2320
> > * VIDEO PID:2320 TYPE:0x02 ISO/IEC 13818-2 Video
> > * AUDIO PID:2420 TYPE:0x03 ISO/IEC 11172 Audio
> > * Language: ron
> >   SDT TSID:405
> > * PNR:40510
> > * Provider: Next Gen INE 3
> > * Service: LinkPress
> > 
> > Based on my (simple) understanding of the SNP format, I think they're simply HEX(PMT PNR)_HEX(PAT TSID) conversions of the PIDs, so I believe LinkPress should be:
> > `9E3E_195_2C_FFFF0000=linkpress`
> 
> No, it's not, this is the format:
> HEX(SID)_HEX(TID)_HEX(ONID)_HEX(namespace)
> Where I mean with SID the Service PID, TID is Transponder ID, ONID is Network ID.
> Namespace for DVB-C is always FFFF0000 (as far as I have seen).
> By the way, this is a SRP entry (SRP=Service Reference Picon).
> 
> SNP is Service Name Picon.
> 
> I can only add a srp-link if you can provide the correct service reference.
> For now I can add it with just a snp-link.

Actually I'm pretty convinced I'm right in this case for `LinkPress`. 

I'm comparing Mooz RO values, which are:

```
PAT TSID:421
- PNR:42111 PID:297
PMT PNR:42111
- PCR PID:803
- VIDEO PID:803 TYPE:0x02 ISO/IEC 13818-2 Video
- AUDIO PID:903 TYPE:0x04 ISO/IEC 13818-3 Audio
- Language: rum
SDT TSID:421
- PNR:42111
- Provider: Next gen INE 3
- Service: Mooz RO
```

And we have: `1A5` and `A47F` which match the srp values I offered in the first message of:

```
A47F_1A5_2C_FFFF0000=moozro
```

-- and all channels on this provider use `2C_FFFF0000`, so I'm fairly positive

Either way, I'm OK with SNP, I don't end up using SRP anyway personally.

Thank you very much.

**Comment by Lexzie** [comment]
And I'm pretty sure it's the SID, ONID and TID.
![afbeelding](https://user-images.githubusercontent.com/14023349/78937747-4b56c800-7ab1-11ea-82e0-9fc574af6b77.png)
Just look at this (DVB-C) station above. You'll see the service reference
`1:0:19:4BC9:832:600:FFFF0000:0:0:0:`
(By the way we use `_` instead of `:` and the prefix (in this case `1:0:19:`) and the suffix `:0:0:0:` are cut off).
You'll also see that 4BC9 is the Service ID, 832 is the TSID (=TID) and 600 is the ONID.
But maybe you're cable provider uses another format.

> 
> This is all I could find on their official website, but size is not that great (it's the same size as the one I have attached for Mooz RO):
> 
> From: https://mooz.tv/mooz-hd/ -- https://mooz.tv/site/img/mooz-hd.jpg

I managed to make a `moozhd` logo using the existing logo for `moozdance` without the white background.
[moozhd.zip](https://github.com/picons/picons/files/4458529/moozhd.zip)

I'm now ready to scan Hellas Sat 3 (39.0°E), so I can add the satellite srp-links too.
After that I will commit all this.

**Comment by Lexzie** [comment]
Please report if the HD channels of Telekom Sport have a picon on TV Headend.
And if everything else is okay.

**Comment by Lexzie** [comment]
@Znuff Could you please report if you have all the picons you want and especially on the Telekom Sport HD channels?
So we can close this issue.

**Comment by Znuff** [comment]
Hey, sorry, I tested yesterday, all was good. 

I will make a new issue/enhancement for some other logos in the near future, for the same provider.

Thank you.

**Comment by Lexzie** [comment]
@Znuff 

> I will make a new issue/enhancement for some other logos in the near future, for the same provider.

As you can see (https://github.com/picons/picons/pull/163) I added a lot more logos than requested, so a lot will be in our database already, just supply the correct links. (In a new issue).
If you have enhancements (logo changed, higher resolution png of a svg instead of a png), you can supply them too.
