### ISSUE TITLE
ESPNews

### ISSUE THREAD

**Issue by ghost** [picons/picons#1598]
# SNP/SRP entries

**snp.index**
```
ESPNews=ESPNews
ESPN News=ESPN News

```

**srp.index**
```

4097:0:1:29F:817F:0:0:0:0:0=ESPNews
4097:0:1:29F:817F:0:0:0:0:0=ESPN News

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
![ESPNews svg](https://github.com/picons/picons/assets/35585833/04844f2e-d89d-4b40-8489-7540ded4b496)

**Comment by AbuBaniaz** [comment]
Why is it you are not understanding things properly? Please expain the confsing aspects so we can reword things for you.

 There is no attachment.

 Thing of it like this when you post links you want added:

For snp
snpnameofchannel=nameoflogo (logo you are attaching or what is already existing on this project) 

For SRP
service reference (in format and only sections that we use)= nameoflogo (what you are attaching or what is already existing on this project)

Please stop pasting/typing `samplechannelname` 

as an example
espnnews=espnnews

**Comment by ghost** [comment]
Why don't you just correct it and I'll see how it should be correct. With what they are telling me and what they are currently writing, I know exactly the same amount as before. But when you correct it, I automatically see how it should be correct.

**Comment by AbuBaniaz** [comment]
How can I attach something that is not attached? Give the logos valid names and attach them and I will correct your comment/request.

**Comment by Lexzie** [comment]
@William-Richards last time I showed you the correct way for the links:
https://github.com/picons/picons/issues/1578#issuecomment-1704320047

So if f.e. the channel on your receiver is named _ESPN News_, the service reference is _4097:0:1:29F:817F:0:0:0:0:0_ and the logo has as name `espnews.default.svg` you should have done this:

**snp.index**
```
espnnews=espnews
```

**srp.index**
```
29F_817F_0_0=espnews
```

Although those two zero's at the end (_0_0) is not common.

We have no way of knowing which name is right, since we have no access to this channel like you.

And we'll use this logo instead of yours:
![espnews default](https://github.com/picons/picons/assets/14023349/4cbfa1cc-2ad8-4feb-8061-250dcddc3e48)

**Comment by AbuBaniaz** [comment]
You missed these two lines: 
`Make sure you replace the above sample data with the actual data you want added.`
`Attach a zip file containing the logos, properly named according to the channelname used in snp.index or srp.index.`

We have re-explained this several times for you. We are either not explaining properly for you  to understand , or something is not clear.  I appreciate by your posting you are just an iptv user, but even then, the iptv providers will use a reference so the epg-cross referencing occurs


Let us think of it this way:

A. What is the name of the channel?
B. What is the SNP name of the channel
C. What is the service reference of the channel
D: What is the service reference of the channel used by this project  (We drop the first three fields and the last three three 0's )
E: What is the name of the logo on this repository?
F: If the logo does not exist on this repository, what is the name of the logo you are adding in the zip file?

For SNP additions you would then say
B=E or D

For SRP additions, you would then say
D=E or D

For this issue

A: ESPN News
B: espnnews
C: This is not a valid service reference.
D: We cant answer this as D is not valid
E: It does not exist in this repository
F: You did not add a logo file in the zip. I would have called it espnnews.default

The index changes would then be (as posted above)
 `espnnews=espnnews`

**Comment by Lexzie** [comment]
Totally right. The svg=logo I added is named espnews.default.svg

We don't know if the channel is named ESPN News or ESPNews.

**Comment by AbuBaniaz** [comment]
I added it as `espnnews.default.svg`

**Comment by Lexzie** [comment]
I noticed, But the logo clearly is `espnews` with just one `n`.

**Comment by ghost** [comment]
![image](https://github.com/picons/picons/assets/35585833/1c27808a-5a41-45f9-aaed-1e04f7edab5d)

**Comment by ghost** [comment]
ESPNEWS is The Right Name
