### ISSUE TITLE
ESPN +

### ISSUE THREAD

**Issue by ghost** [picons/picons#1599]
# SNP/SRP entries

**snp.index**
```
ESPN+=ESPN+
ESPN + =ESPN +
ESPNPlus=ESPN Plus
```

**srp.index**
```
4097:0:1:029f:8181:0:0:0:0:0= ESPN+
4097:0:1:029f:8181:0:0:0:0:0= ESPN +
4097:0:1:029f:8181:0:0:0:0:0= ESPN Plus

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
![ESPN_Plus svg](https://github.com/picons/picons/assets/35585833/d5af0139-97a0-4e80-a852-7d9a15761a81)

**Comment by Lexzie** [comment]
Found a svg-logo and made these:

![espnplus default](https://github.com/picons/picons/assets/14023349/20aeed33-50db-4c66-a810-fa6546a865a2)

![espnplus light](https://github.com/picons/picons/assets/14023349/56eb1c4e-c30e-44f1-b737-ec4d3eb2e7ff)

We still need correct links, f.e. if the channel name on your receiver is "ESPN+", the link shoudl be:
```
espnplus=espnplus
```

**Comment by AbuBaniaz** [comment]
I have added this, but please see comments in the other issue to help you understand what you should be posting better. Please bear in mind for future issues.
