### ISSUE TITLE
Add Indonesian logos

### ISSUE THREAD

**Issue by leap0x7b** [picons/picons#1606]

**Comment by AbuBaniaz** [comment]
Do you have the logos you want added? Do you have the SNP names? Do you have the service references?

**Comment by AbuBaniaz** [comment]
I'll close this for now. Please read the contribution guide.

**Comment by leap0x7b** [comment]
Sorry if I'm late. I don't have the SNP names and the service references but here's the logos that can be added:
- TVRI
- TVRI World
- TVRI Sports
- RCTI
- MNCTV
- GTV
- iNews
- SCTV
- Indosiar
- Moji
- Mentari TV
- ANTV
- tvOne
- VTV
- MetroTV
- Magma Channel
- BN Channel
- Trans TV
- Trans 7
- CNN Indonesia
- CNBC Indonesia
- NET.
- RTV
- Garuda TV
- BTV
- JTV
More can be seen here: https://www.lyngsat.com/Telkom-4.html

**Comment by AbuBaniaz** [comment]
Can you please upload the logos in a zip file.

**Comment by Lexzie** [comment]
@leap0x7b if you are watching these channels via Telkom 4 and want the logos on your receiver, you might be watching them on a Enigma2 receiver.
If so, download a settings editor like [Dreamset](https://www.dreamset-editor.com/index.php), read out your receiver.
There are functions in there to copy the references and to export the list in a text file.


Read our [contribution guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md) on how you must supply us with the changes or additions.

Logos can be found on f.e. Wikipedia, Logopedia or the websites of the stations themselves.

I'm happy to help you, but we don't have the time to do everything for you with a satellite I could never receive.
