### ISSUE TITLE
Play Sports

### ISSUE THREAD

**Issue by ghost** [picons/picons#1617]
# SNP/SRP entries

**snp.index**
```
playsports1=playsports1
playsports2=playsports2
playsports3=playsports3
playsports4=playsports4
playsports5=playsports5

```

**srp.index**
```
IPTV

4097:0:1:AA94:FDE2:EC:0:0:0:0:http%3a//website%3a8080/live/user/passwd/378156.ts:Play Sports 1 HD
4097:0:1:AA94:FDE1:EC:0:0:0:0:http%3a//website%3a8080/live/user/passwd/378157.ts:Play Sports 2 HD
4097:0:1:AA94:FDD4:EC:0:0:0:0:http%3a//website%3a8080/live/user/passwd/378158.ts:Play Sports 3 HD
4097:0:1:AA94:FDD3:EC:0:0:0:0:http%3a//website%3a8080/live/user/passwd/378159.ts:Play Sports 4 HD

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
[Play Sports.zip](https://github.com/picons/picons/files/12667462/Play.Sports.zip)

**Comment by Lexzie** [comment]
The snp.index part is correct. Well done!

The srp.index part should be like this:

```
AA94_FDE2_EC_0=playsports1
etc...
```

Name the files in the zip:
playsport1.default.svg
etc.

**Comment by AbuBaniaz** [comment]
He is an PTV only user, so he won't have valid service references by the looks of it. Best to just post valid SNP.index entries only instead of also posting invalid SRP.index entries. There is no requirement to have both SRP and SNP.

It has been more than two weeks since we last helped him again in the right direction.

**Comment by Lexzie** [comment]
> He is an IPTV only user, so he won't have valid service references by the looks of it. Best to just post valid SNP.index entries only instead of also posting invalid SRP.index entries. There is no requirement to have both SRP and SNP.
> 
> It has been more than two weeks since we last helped him again in the right direction.

Even IPTV can have a service reference, f.e. to add EPG, like William is posting:
`4097:0:1:AA94:FDE2:EC:0:0:0:0:`
Only this one has namespace 0.

What is missing is the conversion to the format we use, so deleting the leading `4097:0:1:` and all from the last `:0:0:0:` until the end, and replacing the `:` with `_` (underscore):
![afbeelding](https://github.com/picons/picons/assets/14023349/ed1ca920-3deb-453d-9d73-2b409c8baf11)

And then linking it to the right logo:
`AA94_FDE2_EC_0=playsports1`

But:
We already have logos for Play Sports and I don't see why they need to be replaced by these ones.

The supplied logos do not have the right file-naming _(f.e. playsports1.default.svg)_. This can be done by anyone.

And furthermore (remember, this is to help you help us, if you're not familiair with editing svg's try to learn it and just say so):
The supplied logos are not cropped and have a white background.

I'll add the snp-links, maybe our Belgian users will need them too.
