### ISSUE TITLE
German channel icons missing

### ISSUE THREAD

**Issue by major-mayer** [picons/picons#164]
Hi 
I just wanted to inform you that for these mostly german channels the icons are missing in the latest package:
```
MDR Thüringen HD
RBB Berlin HD
SR Fernsehen HD
Radio Bremen TV HD
HSE24 Extra HD
ZDFINFO HD
ARD Alpha HD
Tagesschau 24 HD
SR Fernsehen
Radio Bremen TV
GigaTv
Videothek
Health TV
Hope Channel
BBC World NEws
Nederland 2
Netflix
```

I'm using Tvheadend 4.3 and my TV provider is "Unitymedia".
If you need additional information feel free to ask me :)

**Comment by mrhotio** [comment]
Use the template in which we ask for all the info we need :-)
