### ISSUE TITLE
Saorview 2rn missing

### ISSUE THREAD

**Issue by wedebe** [picons/picons#1656]
# SNP/SRP entries

**snp.index**
```
2rn=2rn
```

**srp.index**
```
4A5_3E9_2174_EEEE0000=2rn
852_3EA_2174_EEEE0000=2rn
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
[2rn.svg.zip](https://github.com/picons/picons/files/13189747/2rn.svg.zip)
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by AbuBaniaz** [comment]
All the three issues you raised should really have been one issue. The whole idea is to make it as easy as possible for the person doing the work.
