### ISSUE TITLE
upcoming UK changes 22nd November..

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1668]
# SNP/SRP entries

**snp.index**
```
truecrime=truecrime
truecrimextra=truecrimextra
legendxtra=legendxtra

```

**srp.index**
```
none yet
```
CBS Reality will be become to True Crime..
CBS Reality+1 will be become to True Crime+1..
Reality Xtra will become True Crime Xtra..
Horror Xtra channel will become Legend Xtra..
Horror Xtra+1 channel will become Legend Xtra+1..
Existing Legend channel gets New Logo..
Haven't seen the +1 logos yet..
[upcomng changes uk.zip](https://github.com/picons/picons/files/13287690/upcomng.changes.uk.zip)

**Comment by Lexzie** [comment]
Why no srp.index?

**Comment by yannydodo12** [comment]
> Why no srp.index?

Because not sure if they will change or keep the existing channels srp..

**Comment by Lexzie** [comment]
> > Why no srp.index?
> 
> Because not sure if they will change or keep the existing channels srp..

Aha, so we'll change that later.

**Comment by Lexzie** [comment]
The logo of Legend is not changed yet.

**Comment by yannydodo12** [comment]
# SNP/SRP entries

**snp.index**
```
truecrimex=truecrimextra
legendxtraplus1=legendxtraplus1
truecrimeplus1=truecrimeplus1
```
**srp.index**
delete
```
D7AE_840_2_11A0000=cbsreality
D7B0_840_2_11A0000=cbsreality
D7B1_840_2_11A0000=cbsrealityplus1
D7A2_840_2_11A0000=horrorxtra
D7B2_840_2_11A0000=horrorxtraplus1
C6D7_840_2_11A0000=realityxtra
D7A8_840_2_11A0000=realityxtra


```
New
```
D7AE_840_2_11A0000=truecrime
D7B0_840_2_11A0000=truecrime
D7B1_840_2_11A0000=truecrimeplus1
D7A2_840_2_11A0000=legendxtra
D7B2_840_2_11A0000=legendxtraplus1
C6D7_840_2_11A0000=truecrimextra
D7A8_840_2_11A0000=truecrimextra


```
[plus1.zip](https://github.com/picons/picons/files/13437388/plus1.zip)

**Comment by Lexzie** [comment]
I will attend to this today.
Elections for parliament today here.

**Comment by AbuBaniaz** [comment]
@Lexzie 
See here: https://github.com/picons/picons/pull/1704
Please merge/modify as required

**Comment by yannydodo12** [comment]
> @Lexzie See here: #1704 Please merge/modify as required

Hi mate it's looks like it's only the UK CBS Realty that have changed their logos from what I can see..

**Comment by AbuBaniaz** [comment]
Thanks, reverted the non-UK changes
