### ISSUE TITLE
Sky Crime Italy 

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1670]
# SNP/SRP entries

**snp.index**
```

```

**srp.index**
```
old
37A9_14B4_FBFF_820000=crimeandinvestigationhd
```
```
new
37A9_14B4_FBFF_820000=skycrimehd
1020_14B4_FBFF_820000=skycrimehd
```

**Comment by AbuBaniaz** [comment]
By saying `old`, do you mean `delete`

**Comment by yannydodo12** [comment]
> By saying `old`, do you mean `delete`

Yeah mate.
crimeandinvestigation is now skycrime
