### ISSUE TITLE
19.2e logo updates

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1676]
**snp.index**
```
justfishing=justfishing
justfishinghd=justfishing
others logos no change just updated logos..
```

**srp.index**
```
290C_45E_1_C0000=justfishing
29CC_45C_1_C0000=justfishing
others logos no change just updated logos..
```
The hd logos for hrfernsehen. , srfernsehen. , will need to be made as can't find them..
I've included a screenshot of them in the zip file..
[19.2e updated logos.zip](https://github.com/picons/picons/files/13301628/19.2e.updated.logos.zip)

**Comment by Lexzie** [comment]
I was looking all over for a deacent logo of Just Fishing.
Does your source also have good logos for Red Adventure and Serien+?

**Comment by yannydodo12** [comment]
> I was looking all over for a deacent logo of Just Fishing. Does your source also have good logos for Red Adventure and Serien+?

Was looking for them myself and no look so far mate.
I found the just fishing here.
https://goldbach.com/de/en/portfolio/tv/channels
But can't see them 2 unless I'm blind 😂

**Comment by Lexzie** [comment]
Too bad, I'll try making them.
Already busy with making the HD logos for HR and SR, I think I can commit everything tomorrow.

**Comment by yannydodo12** [comment]
> Too bad, I'll try making them. Already busy with making the HD logos for HR and SR, I think I can commit everything tomorrow.

https://www.fernsehserien.de/serien-nach-sendern
Looks like you can resize the logos here.

**Comment by yannydodo12** [comment]
Not sure it's good enough to use..
[](url) https://bilder.fernsehserien.de/logos/hr/1080-36d14f2e9ff393d94b379dee2706b2ed.png

**Comment by yannydodo12** [comment]
**snp.index**
```
serienplus=serienplus
serienplus=serienplushd
```

**srp.index**
```
2910_45E_1_C00000=serienplus
29D1_45C_1_C00000=serienplus
```
[serien plus.zip](https://github.com/picons/picons/files/13307054/serien.plus.zip)

**Comment by Lexzie** [comment]
It was not good enough, but you cleaned the black letters better than I did so I combined it with the colored part of the one I had cleaned.

**Comment by Lexzie** [comment]
I guess it's all done and dusted?

**Comment by yannydodo12** [comment]
> I guess it's all done and dusted?

Yeah mate thanks..

**Comment by bkuhls** [comment]
Is there a zero missing for justfishing?
```
290C_45E_1_C0000=justfishing
29CC_45C_1_C0000=justfishing
```
should be
```
290C_45E_1_C00000=justfishing
29CC_45C_1_C00000=justfishing
```

**Comment by AbuBaniaz** [comment]
I have changed it.

**Comment by Lexzie** [comment]
> Is there a zero missing for justfishing?
> 
> ```
> 290C_45E_1_C0000=justfishing
> 29CC_45C_1_C0000=justfishing
> ```
> 
> should be
> 
> ```
> 290C_45E_1_C00000=justfishing
> 29CC_45C_1_C00000=justfishing
> ```

In my defence I just copy-pasted it.

Anyhow, thanks for noticing.

**Comment by yannydodo12** [comment]
My fault mate.. 😂
