### ISSUE TITLE
Saorview (Ireland) & Astra 28.2 missing picons

### ISSUE THREAD

**Issue by wedebe** [picons/picons#1682]
# SNP/SRP entries

**snp.index** - Saorview (Ireland) - logos exist in repo
```
rte2xm=rte2xm
rtegold=rtegold
rteradio1extra=rteradio1extra
```

**snp.index** - Saorview (Ireland) - logos don't (yet) exist in repo
```
rtechill=rtechill
rtepulse=rtepulse
ssu=ssu
```

**srp.index** - Astra 28.2 - logos exist in repo
```
2906_90B_3B_11A0000=freesat
```

**srp.index** - Astra 28.2 - logos don't (yet) exist in repo
```
2954_90B_3B_11A0000=bbcndra
2959_90B_3B_11A0000=d1dab
41D_7D4_2_11A0000=etbg
41E_7DC_2_11A0000=etfg
13B2_7D3_2_11A0000=primevideo1hd
17A0_7D3_2_11A0000=primevideo2hd
295E_90B_3B_11A0000=sdlnatl
290F_90B_3B_11A0000=slatea
2910_90B_3B_11A0000=slateb
2911_90B_3B_11A0000=slatec
2963_90B_3B_11A0000=talksportdist
D3CE_839_2_11A0000=tvx40plus
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos
(N/A)
```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by Lexzie** [comment]
> logos don't (yet) exist in repo
> 

So, please add the logos in your request.

**Comment by Lexzie** [comment]
> ssu=ssu
>
> 2954_90B_3B_11A0000=bbcndra
> 2959_90B_3B_11A0000=d1dab
> 41D_7D4_2_11A0000=etbg
> 41E_7DC_2_11A0000=etfg
> 295E_90B_3B_11A0000=sdlnatl
> 290F_90B_3B_11A0000=slatea
> 2910_90B_3B_11A0000=slateb
> 2911_90B_3B_11A0000=slatec
> 2963_90B_3B_11A0000=talksportdist

These are data-channels. I would not know which logos they should have.

**Comment by Lexzie** [comment]
> 2906_90B_3B_11A0000=freesat

> D3CE_839_2_11A0000=tvx40plus

links exist in repo.

Logos were easily found on Logopedia, next time please download them yourself and supply them with the issue.
