### ISSUE TITLE
How to sort out this mess..

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1687]
Not sure what way to sort out the new motorvision logos. From looking at the channels it all very confusing..
This is what I'm seeing 😂

1CC2_19_46_E080000=motorvisiontvhd 0.8w 
Can't check the logo as can't receive it here. But the channel is called motorvisionhd
LyngSat has the channel named motorvisionplus
kingofsat has the channel named motorvision

70_E_3_130000=motorvisionplus 1.9e
Checked the logo it's using and it's the motorvisionplus logo. But the channel is called motorvision...

25E_146C_A7_1860000=motorvisiontv 39.0e
Can't check the logo as don't have anything that clears it..
LyngSat has the channel named motorvisionplus
kingofsat has the channel named motorvision

51A_2F_36_CE40000=motorvisionplus 30.0w
Checked the logo t's using and it's the motorvisionplus logo
But the channel is called motorvision..

401_4_AA_5A0000=motorvisionplus 9.0e
can't check the logo as don't have anything that clears it..But the channel is called motorvisionplus..
LyngSat has the channel named motorvisionplus
kingofsat has the channel named motorvision

A8_B_85_C00000=motorvisionplus 19.2e
Checked the logo it's using and it's the motorvisionplus logo. But the channel is called motorvision tv

**Comment by Lexzie** [comment]
Lyngsat and/or Kingofsat could be wrong.
Naming in the ident is often wrong or they are (very) late in changing them.
Logopedia and the [Motorvision Group website](https://motorvision-group.com/) describes two/three channels: Motorvision, Motorvision Classic and Motorvision+.
Motorvision+ is the one intended for Pay TV (cable, satellite etc.), the others for online.
So and according to Lyngsat they should all be Motorvision+.
The ones you could check do have the Motorvision+ logo.

To identify a station:
-Make screenshots of the logos and post them here.
-Check leaders etc. what stationname they use.
-If possible check if stations are showing unique programming or if and which are the same.
All as far as you can receive them.
I'll have a go on 0.8W and 39E later, probably tomorrow.

**Comment by yannydodo12** [comment]
K mate will give her a go.
It does seem like they're all using the + logo.
It's the snp that's getting me up mixed up lol..

**Comment by Lexzie** [comment]
Imho they should all be Motorvision+.
Satellite operators are lazy or not accurate.
If the wrong names will not be corrected we might have to change some snp.links.

**Comment by yannydodo12** [comment]
This is what I think it would be like..
1CC2_19_46_E080000=motorvisionplus 0.8w 
Can't scan it in..

70_E_3_130000=motorvisionplus 1.9e
the channel is named Motorvision after a scan...

25E_146C_A7_1860000=motorvisionplus 39.0e
the channel is named Motorvision HD after a scan...

51A_2F_36_CE40000=motorvisionplus 30.0w
the channel is named Motorvision after a scan..

401_4_AA_5A0000=motorvisionplus 9.0e
the channel is named Motorvision+ after a scan..

A8_B_85_C00000=motorvisionplus 19.2e
the channel is named Motorvision+ after a scan..

snp
motorvisionplus=motorvisionplus
motorvision=motorvisionplus
motorvisionhd=motorvisionplus

**Comment by Lexzie** [comment]
I saw the logo on 0.8°W and that's also Motorvision+

**Comment by yannydodo12** [comment]
> I saw the logo on 0.8°W and that's also Motorvision+

How is it named ?
So it's safe to say they all use the + logo..
Will we go with the onscreen logo or the one with motorvision writing.

Onscreen logo
https://www.tvchannellists.com/wiki/images/8/81/Motorvision%2B.svg

Normal logo
https://motorvision.tv/wp-content/uploads/2023/09/MV_Logo_positiv_light_background-2048x465.png

**Comment by Lexzie** [comment]
It's still named MOTORVISION TV HD, even after scanning the transponder, so we have to add that to snp too:
```
motorvisiontvhd=motorvisionplus
```

Maybe it's more logic to use the logo onscreen.

**Comment by yannydodo12** [comment]
Hope this is right lol
```
new srp
1CC2_19_46_E080000=motorvisionplus
70_E_3_130000=motorvisionplus
25E_146C_A7_1860000=motorvisionplus
51A_2F_36_CE40000=motorvisionplus
401_4_AA_5A0000=motorvisionplus
A8_B_85_C00000=motorvisionplus
```
```
delete srp
1CC2_19_46_E080000=motorvisiontvhd
70_E_3_130000=motorvisiontv
25E_146C_A7_1860000=motorvisiontvhd
51A_2F_36_CE40000=motorvisiontv
401_4_AA_5A0000=motorvisiontv
A8_B_85_C00000=motorvisiontv
```
```
new snp
motorvisionplus=motorvisionplus
motorvision=motorvisionplus
motorvisionhd=motorvisionplus
motorvisiontvhd=motorvisionplus

```
```
delete snp
motorvision=motorvisiontv
motorvisionhd=motorvisiontvhd
```
Thought I had 😂
[motorvision plus.zip](https://github.com/picons/picons/files/13357927/motorvision.plus.zip)

**Comment by yannydodo12** [comment]
not sure with these ones
``
snp
motorvisionchannel=motorvisiontv
motorvisionchannelhd=motorvisiontv
motorvisiontv=motorvisiontv
motorvisiontvconnect=motorvisiontv

srp
70B_44_36_FFFF0000=motorvisiontvhd
428C_4072_2114_EEEE0000=motorvisiontv
117_15_3_130000=motorvisiontv
24AE_55_1_FFFF0000=motorvisiontvhd
AC4B_1B9_270F_FFFF0000=motorvisiontvhd
AC4B_1B9_270F_FFFF0000=motorvisiontv
372D_8D_270F_FFFF0000=motorvisiontv
A8_E_85_C00000=motorvisiontv
A8_1_85_FFFF0000=motorvisiontv
A8_4_85_FFFF0000=motorvisiontv
``

**Comment by Lexzie** [comment]
Next time (or edit your post) place the links between **three** backticks ( ` )

**Comment by Lexzie** [comment]
I guess this is done now?

**Comment by yannydodo12** [comment]
> I guess this is done now?

Yeah mate..
Can close it.
