### ISSUE TITLE
Remove background

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#169]
Does anybody know how I make the background transparent, including the black shadows.
http://www.romittv.ro/logo.jpg

**Comment by mcfly822** [comment]
Hello @Lexzie ,
this work not ready, I just removed the white part of the image. It is good with white background. With black, not prefect... maybe you can do some more with this,
![romittv](https://user-images.githubusercontent.com/22531870/79077793-30c85d00-7d04-11ea-963e-38002a23d0c2.png)

**Comment by Jasmeet181** [comment]
Working from http://www.romittv.eu/images/408550_145844272224385_2000077819_n_copy_(1).png

![romittv default](https://user-images.githubusercontent.com/14339434/79079152-4f7b2380-7d05-11ea-8d49-6244d41fb01e.png)

**Comment by Pumuckel65** [comment]
Try this one ... maybe ist o.k. for you
![logo](https://user-images.githubusercontent.com/29928422/79079805-966f1600-7d11-11ea-8192-f469da11b0d7.png)

**Comment by Lexzie** [comment]
I think one from @Jasmeet181 is suitable, because it has no shadows it can easily be converted to a dark variant.
![romittv dark](https://user-images.githubusercontent.com/14023349/79363442-2dbdae80-7f48-11ea-90c6-a393ecc0420c.png)

Everyone Thanks for helping.
