### ISSUE TITLE
Rockland TV

### ISSUE THREAD

**Issue by ghost** [picons/picons#1696]
# SNP/SRP entries

**snp.index**
```
rocklandtv=rocklandtv
rocklandradiotv=rocklandtv
```

# Logos

```
logos.zip

[Rockland TV.svg.zip](https://github.com/picons/picons/files/13402074/Rockland.TV.svg.zip)




```

**Comment by ghost** [comment]
![Rockland TV](https://github.com/picons/picons/assets/35585833/1ee1ed9d-a421-4c5e-8cd0-6ecf7ce7adb1)

**Comment by AbuBaniaz** [comment]
My friend, you are making the same mistake over and over again.  We keep telling you the same thing again and again.

Zip the svg file then attach it ( just drag the zip file from your PC onto this website)
Correct the title.  "Rockland TV" is better than "A description of what you are updating by this request"
The SRP is fake, delete it
The SNP reference has to be lower case

**Comment by AbuBaniaz** [comment]
Delete this text
```
Attach a zip file containing the logos, properly named according to the channelname used in snp.index or srp.index.

PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)
```

And delete this link
`
https://www.rockland.de/programm.html
`

**Comment by ghost** [comment]
Is it good now?

**Comment by AbuBaniaz** [comment]
Better, thank you. 

Can you please attach the zip file containing the logo. Zip the svg  file on you PC/mac. Then drag and drop it here when you respond /edit.

**Comment by ghost** [comment]
I've been trying that since the beginning but it doesn't work, I'll try a different browser
[Rockland TV.svg.zip](https://github.com/picons/picons/files/13397084/Rockland.TV.svg.zip)

**Comment by AbuBaniaz** [comment]
Can you change the title of your issue.
Do not use `A description of what you are updating by this request`
As this issue is to do with adding rockland tv, rename it to `Add rockland tv` or similar. 

Do the same for other issue you raised. I won't be committing anything until you do it. Otherwise you won't start doing things correctly.
 
The svg file is attached. Thank you. I will rename it correctly for you.

**Comment by AbuBaniaz** [comment]
The logo you provided had an embedded png, so is not acceptable. I have replaced the logo we had with a different one, I hope it is OK. Please close issue if satisfied.

https://github.com/picons/picons/commit/0d993c6d06a3d0fac1bf962cc35d3fc27be0b418
