### ISSUE TITLE
Red Adventure

### ISSUE THREAD

**Issue by ghost** [picons/picons#1697]
# SNP/SRP entries

**snp.index**
```
red adventure=redadventure
red adventure hd=redadventurehd
```

# Logos

```
logos.zip

[red adventure hd.svg.zip](https://github.com/picons/picons/files/13397393/red.adventure.hd.svg.zip)

[red-adventure.svg.zip](https://github.com/picons/picons/files/13397395/red-adventure.svg.zip)

```

**Comment by ghost** [comment]
[red adventure hd.svg.zip](https://github.com/picons/picons/files/13397399/red.adventure.hd.svg.zip)

[red-adventure.svg.zip](https://github.com/picons/picons/files/13397401/red-adventure.svg.zip)

**Comment by Lexzie** [comment]
The normal logo contained a base64 image, but luckily the HD logo didn't.
