### ISSUE TITLE
svg files for some pngs

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1701]
# SNP/SRP entries

**snp.index**
```
no change
```

**srp.index**
```
no change
```

[svg of some pngs.zip](https://github.com/picons/picons/files/13425983/svg.of.some.pngs.zip)

**Comment by AbuBaniaz** [comment]
Thanks. Are there replacements for following? 
federalna.dark
sportklub.default
123tvhd.default
123tvhd.white
cgtnarabic.default

**Comment by yannydodo12** [comment]
No HD logo for 123tvhd.default
only one i can find i don't think is the right one..   https://de.wikipedia.org/wiki/Datei:1-2-3.tv_HD_Logo_2020.svg
can't find svg for cgtnarabic.default
federalna.dark  i'm not sure on.. But could just make the light one dark just plain black. 
sportklub.default was a different logo so not sure if this one is correct...
[sportklub & federalna.zip](https://github.com/picons/picons/files/13426440/sportklub.federalna.zip)

**Comment by AbuBaniaz** [comment]
This svg contains text or a png image: sportklubesports.default.svg

**Comment by yannydodo12** [comment]
> This svg contains text or a png image: sportklubesports.default.svg

sorry didn't know.. may leave the png so..
