### ISSUE TITLE
Few more PNG's converted to svg..

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1705]
I've converted few more PNG's
Just double check them to make sure they're good enough.. They look ok to me .
[new svg's.zip](https://github.com/picons/picons/files/13450550/new.svg.s.zip)

**Comment by Lexzie** [comment]
Looks like you Bitmap traced the png's to make svg's.
Although we appreciate the effort please don't if we have good png logos.
And if you use that function you have to correct a lot to get a good image.
F.e. the circle in `1tv-trenaslupi` is not perfectly round.
It's quite possible to correct that, but takes too much time while the png is 800x501 which is fine.

`4fungold` looks pretty good but zoom in and you'll still see the circle is not round.

Zoom in on `7telekanal` and you'll see this:
![afbeelding](https://github.com/picons/picons/assets/14023349/71a78bd3-cef4-489a-8b09-94d6000f14d5)

The bottom left of the 1 in `21bis` in the png:
![afbeelding](https://github.com/picons/picons/assets/14023349/10bfe7cd-3a5f-4023-b165-fedda7c249a7)

And now in your svg:
![afbeelding](https://github.com/picons/picons/assets/14023349/57968a83-2837-43ec-9aa8-fe05daa4f160)

`34kanal`
![afbeelding](https://github.com/picons/picons/assets/14023349/f35c0502-0c4f-4229-b9ab-d802fa6f5dd9)


etc.

I am not going to clean that if we have perfect bitmap images already.
I simply don't have the time for that.

**Comment by yannydodo12** [comment]
K mate. No more PNG's converting from me...

**Comment by Lexzie** [comment]
Only if you can't find a logo in good quality, but after tracing zoom in and correct the flaws.
