### ISSUE TITLE
Energy Zürich

### ISSUE THREAD

**Issue by ghost** [picons/picons#1710]
# SNP/SRP entries

**snp.index**
```
energyzurich=energyzurich
radioenergyzurich=energyzurich
```
logos.zip
[energyzurich.default.svg.zip](https://github.com/picons/picons/files/13464643/energyzurich.default.svg.zip)

```

**Comment by Lexzie** [comment]
I found this png, looks better
![Energy_Zürich_Logo](https://github.com/picons/picons/assets/14023349/989127e9-a0cc-4f0f-b85f-28d9bce2e48e)

**Comment by ghost** [comment]
I know this png is not arranged the same as the others. That's why I deliberately didn't take it

**Comment by AbuBaniaz** [comment]
We have a few of these already. Really need converting to a text box so we can edit properly/easily.

**Comment by AbuBaniaz** [comment]
And also, the links and attached file names  are all wrong. The whole idea is to make it easy for person committing/adding these changes. We should be able to drag and drop the files, Copy and paste text.

All the first part of the links are wrong. SNP names are all lower case with no spaces. We are having to edit them.

All the logos should be names `example.default.svg` Instead, we have to rename the files and add the `.default`

**Comment by ghost** [comment]
I don't fully understand, can you give me an example of this Energy Zurich #1710 so that I can do it correctly...

I've changed something now, is that ok?

**Comment by AbuBaniaz** [comment]
Wrong logo name:
`energyluzern.svg`

Correct logo name:
`energyluzern.default.svg`

Wrong link:
`Radio Central=radiocentral`

Correct link:
`radiocentral=radiocentral`

I see you have edited them. A lot better, thanks. 

enigma2 images will not use the umlauts in picon names.

Wrong link:
`radioenergyzürich=energyzürich`

Correct link:
`radioenergyzurich=energyzurich`

Anyway, lets see if the logos can be made with an editable text box, it will be easier to amend them.

**Comment by AbuBaniaz** [comment]
The energy luzern svg is 11kb, The other ones I have looked at so far are 23kb. The luzern svg is the better one.

**Comment by AbuBaniaz** [comment]
Can you please make the three remaining radio energy logos by editing the existing clean logos. For example:
https://github.com/picons/picons/blob/master/build-source/logos/energyberlin.default.svg

Add all three logos in one zip file.

We will add these links
```
energybasel=energybasel
radioenergybasel=energybasel
energybern=energybern
radioenergybern=energybern
energyzurich=energyzurich
radioenergyzurich=energyzurich
```

**Comment by Lexzie** [comment]
@AbuBaniaz I'm affraid @William-Richards has not the skills to edit a SVG.

Furthermore:
The fonts in f.e. `energyberlin.default.svg` are not the same as in the logo  of Energy Zürich.
The word 'BERLIN' looks like the same font as the word `ENERGY` in the Enegry Zürich logo, but BERLIN is Italic.
`ZÜRICH` is a whole different font.
They are converted to path, so how to find out which fonts they were?

If I use the png, I can convert it to:

![energyzurich default](https://github.com/picons/picons/assets/14023349/a1dd9b7e-ab53-4de6-87e4-26944b2ca3b0)


Is that good enough?

**Comment by ghost** [comment]
Hello
Yes, you are right, I have never worked with an editing program. But I think that at least all Swiss energy radios should be identical.... if you look at Germany and France it's different again…

**Comment by Lexzie** [comment]
I found the right font, working on all the Energy logos now...

**Comment by ghost** [comment]
thanks :-)
