### ISSUE TITLE
Radio 4 TNG

### ISSUE THREAD

**Issue by ghost** [picons/picons#1715]
# SNP/SRP entries

**snp.index**
```
radio4tng=radio4tng
4tng=radio4tng
```

logos.zip

[radio4tng.default.svg.zip](https://github.com/picons/picons/files/13520143/radio4tng.default.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radio4tng.default.svg.zip](https://github.com/picons/picons/files/13520131/radio4tng.default.svg.zip)

![radio4tng default](https://github.com/picons/picons/assets/35585833/a5e2635a-d70f-4cd9-bdfb-4f4ed875ee62)

**Comment by ghost** [comment]
Radio 4 TNG
radio4tng=radio4tng
4tng=radio4tng

Logo correction
[radio4tng.default.svg.zip](https://github.com/picons/picons/files/13709203/radio4tng.default.svg.zip)
