### ISSUE TITLE
Radio Central

### ISSUE THREAD

**Issue by ghost** [picons/picons#1723]
# SNP/SRP entries

**snp.index**
```
radiocentral=radiocentral
```
logos.zip

[Radio Central Logos.zip](https://github.com/picons/picons/files/13708999/Radio.Central.Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radiocentral.default.svg.zip](https://github.com/picons/picons/files/13519439/radiocentral.default.svg.zip)
![radiocentral default](https://github.com/picons/picons/assets/35585833/b3ea39e9-77b5-4f0e-b579-0f7bb6e5b856)

**Comment by ghost** [comment]
Radio Central
radiocentral=radiocentral

Logo correction
[Radio Central Logos.zip](https://github.com/picons/picons/files/13708995/Radio.Central.Logos.zip)
