### ISSUE TITLE
Radio Chablais

### ISSUE THREAD

**Issue by ghost** [picons/picons#1724]
# SNP/SRP entries

**snp.index**
```
radiochablais=radiochablais
```
logos.zip

[radiochablais.default.svg.zip](https://github.com/picons/picons/files/13464727/radiochablais.default.svg.zip)

```

**Comment by Lexzie** [comment]
@William-Richards the logo you provided is unfortunately very bad. Probably a conversion from a png.
The red "globe" looks like this:
![287102060-2d6c9cd9-161d-4f04-a2ad-d940ce36ebf0](https://github.com/picons/picons/assets/14023349/dad5be20-a60f-4feb-abe7-13cd7dac054a)

Also logos should not have a background, unless it's an essential part of the logo.

I have tried to find a better logo, but all I could find was this:
![287101756-8aa55c85-ff18-492b-ad1e-eef84bab4ed5](https://github.com/picons/picons/assets/14023349/7d918b3b-6dca-4bf7-8042-58498c42e0a1)

So I am going to use that.
