### ISSUE TITLE
Radio Fribourg / Freiburg

### ISSUE THREAD

**Issue by ghost** [picons/picons#1728]
# SNP/SRP entries

**snp.index**
```
radiofribourg=radiofribourg
radiofreiburg=radiofribourg
```

**srp.index**
```
6E1:D:1:FFFF0000=radiofribourg
6E0:10:1:FFFF0000=radiofribourg
```

logos.zip

[radiofribourg.default.svg.zip](https://github.com/picons/picons/files/13693702/radiofribourg.default.svg.zip)

[radiofribourg.light.svg.zip](https://github.com/picons/picons/files/13693704/radiofribourg.light.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

radiofribourg=radiofribourg
radiofreiburg=radiofribourg

[radiofribourg.default.svg.zip](https://github.com/picons/picons/files/13519547/radiofribourg.default.svg.zip)

![radiofribourg default](https://github.com/picons/picons/assets/35585833/ee0b2561-81fe-4637-8473-0839994377c7)

**Comment by William-Richards** [comment]
**srp.index**
```
6E1:D:1:FFFF0000=radiofribourg

**Comment by ghost** [comment]
> # SNP/SRP entries
> **snp.index**
> 
> ```
> radiofribourg=radiofribourg
> radiofreiburg=radiofribourg
> ```
> 
> **srp.index**
> 
> ```
> 6E1:D:1:FFFF0000=radiofribourg
> 6E0:10:1:FFFF0000=radiofribourg
> ```
> 
> logos.zip
> 
> [radiofribourg.default.svg.zip](https://github.com/picons/picons/files/13693702/radiofribourg.default.svg.zip)
> 
> [radiofribourg.light.svg.zip](https://github.com/picons/picons/files/13693704/radiofribourg.light.svg.zip)

![radiofribourg default](https://github.com/picons/picons/assets/35585833/92c375db-4ca3-41d3-9a6d-cc7d7f58ac04)

![radiofribourg light](https://github.com/picons/picons/assets/35585833/13d44b92-bfc5-4615-923f-ef6ef359d9b6)
