### ISSUE TITLE
Radio Jazz International

### ISSUE THREAD

**Issue by ghost** [picons/picons#1732]
# SNP/SRP entries

**snp.index**
```
radiojazzinternational=radiojazzinternational
```
logos.zip

[Radio Jazz International Logos.zip](https://github.com/picons/picons/files/13709034/Radio.Jazz.International.Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radiojazzinternational.default.svg.zip](https://github.com/picons/picons/files/13533169/radiojazzinternational.default.svg.zip)

![radiojazzinternational default](https://github.com/picons/picons/assets/35585833/b860ca92-4412-4200-b35a-7dfe3a409668)

**Comment by ghost** [comment]
Radio Jazz International
radiojazzinternational=radiojazzinternational

Logo correction
[Radio Jazz International Logos.zip](https://github.com/picons/picons/files/13709037/Radio.Jazz.International.Logos.zip)
