### ISSUE TITLE
Radio Kaiseregg

### ISSUE THREAD

**Issue by ghost** [picons/picons#1733]
# SNP/SRP entries

**snp.index**
```
radiokaiseregg=radiokaiseregg
```
logos.zip

[Radio Kaiseregg Logos.zip](https://github.com/picons/picons/files/13709053/Radio.Kaiseregg.Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radiokaiseregg.default.svg.zip](https://github.com/picons/picons/files/13533154/radiokaiseregg.default.svg.zip)

![radiokaiseregg default](https://github.com/picons/picons/assets/35585833/77383d18-d1d4-47e2-80bd-978950639460)

**Comment by ghost** [comment]
Radio Kaiseregg
radiokaiseregg=radiokaiseregg

Logo correction
[Radio Kaiseregg Logos.zip](https://github.com/picons/picons/files/13709056/Radio.Kaiseregg.Logos.zip)
