### ISSUE TITLE
Radio Montecarlo I

### ISSUE THREAD

**Issue by ghost** [picons/picons#1738]
# SNP/SRP entries

**snp.index**
```
radiomontecarlol=radiomontecarlol
```
logos.zip

[radiomontecarlol.default.svg.zip](https://github.com/picons/picons/files/13709134/radiomontecarlol.default.svg.zip)

```

**Comment by William-Richards** [comment]
![radiomontecarlol default](https://github.com/picons/picons/assets/35585833/e0461258-4dfc-4941-9064-b9bbd1cea2f0)

**Comment by ghost** [comment]
Radio Montecarlo I
radiomontecarlol=radiomontecarlol

Logo correction
[radiomontecarlol.default.svg.zip](https://github.com/picons/picons/files/13709138/radiomontecarlol.default.svg.zip)
