### ISSUE TITLE
Radio Orbital

### ISSUE THREAD

**Issue by ghost** [picons/picons#1740]
# SNP/SRP entries

**snp.index**
```
radioorbital=radioorbital
```
logos.zip

[radioorbital.default.svg.zip](https://github.com/picons/picons/files/13465563/radioorbital.default.svg.zip)

```

**Comment by Lexzie** [comment]
Is this the same radio station?
https://www.orbitalfm.ch/

Your logo is from a Portugese station:
https://www.orbital.pt/
(Logo can be seen on Tunein (if you open 'More Information' you'll see the details of that station).

**Comment by ghost** [comment]
Radio ORBITAL Hit Musicorbitalfm.chThis is the Correct Von meinem iPhone gesendetAm 13.12.2023 um 19:49 schrieb Alex ***@***.***>:﻿
Is this the same radio station?
https://www.orbitalfm.ch/
Your logo is from a Portugese station:
https://www.orbital.pt/
(Logo can be seen on Tunein (if you open 'More Information' you'll see the details of that station).

**Comment by Lexzie** [comment]
So, this one:
![afbeelding](https://github.com/picons/picons/assets/14023349/1f31c212-7a5b-448a-b91f-6abb0e1a6efd)

**Comment by ghost** [comment]
Ok yes
