### ISSUE TITLE
Radio Südostschweiz

### ISSUE THREAD

**Issue by ghost** [picons/picons#1746]
# SNP/SRP entries

**snp.index**
```
radiosudostschweiz=radiosudostschweiz
```
logos.zip

[radiosudostschweiz.default.svg.zip](https://github.com/picons/picons/files/13565176/radiosudostschweiz.default.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radiosudostschweiz.default.svg.zip](https://github.com/picons/picons/files/13565167/radiosudostschweiz.default.svg.zip)

![radiosudostschweiz default](https://github.com/picons/picons/assets/35585833/0a7c6aa6-70e6-461e-8ccc-31336670b16e)

**Comment by ghost** [comment]
Radio Südostschweiz
radiosudostschweiz=radiosudostschweiz

Logo correction
[radiosudostschweiz.default.svg.zip](https://github.com/picons/picons/files/13709176/radiosudostschweiz.default.svg.zip)
