### ISSUE TITLE
Radio Swiss Classica

### ISSUE THREAD

**Issue by ghost** [picons/picons#1748]
# SNP/SRP entries

**snp.index**
```
radioswissclassica=radioswissclassica
radiosuisseclassique=radiosuisseclassique
```
logos.zip

[radioswissclassica.default.svg.zip](https://github.com/picons/picons/files/13465619/radioswissclassica.default.svg.zip)

```

**Comment by Lexzie** [comment]
Logo is already present:
https://github.com/picons/picons/blob/master/build-source/logos/radioswissclassic.default.svg

Link updated.
