### ISSUE TITLE
Radio Tell

### ISSUE THREAD

**Issue by ghost** [picons/picons#1749]
# SNP/SRP entries

**snp.index**
```
radiotell=radiotell
```
logos.zip

[radiotell.default.svg.zip](https://github.com/picons/picons/files/13719095/radiotell.default.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radiotell.default.svg.zip](https://github.com/picons/picons/files/13565259/radiotell.default.svg.zip)

![radiotell default](https://github.com/picons/picons/assets/35585833/962c2439-c8dd-4fd4-adbc-c112c712289f)

**Comment by AbuBaniaz** [comment]
Updated logo added here: https://github.com/picons/picons/commit/1d10b5178c417f98249be5a3f5616ed0d96a2c29

**Comment by William-Richards** [comment]
![radiotell default](https://github.com/picons/picons/assets/35585833/bff25af9-b8f2-43e6-a3b5-f76bc44c4059)

**Comment by William-Richards** [comment]
![radiotell default](https://github.com/picons/picons/assets/35585833/162207fa-7228-4b33-899d-ae1e0b8818f2)

**Comment by William-Richards** [comment]
![radiotell default](https://github.com/picons/picons/assets/35585833/7fe1a29b-1cdb-4714-acbb-278d58cb15c3)

**Comment by ghost** [comment]
Radio Tell 
radiotell=radiotell
596_D_1_FFFF0000=radiotell

Logo corrected
[radiotell.default.svg.zip](https://github.com/picons/picons/files/13719118/radiotell.default.svg.zip)
