### ISSUE TITLE
Radio Ticino

### ISSUE THREAD

**Issue by ghost** [picons/picons#1750]
# SNP/SRP entries

**snp.index**
```
radioticino=radioticino
```
logos.zip

[radioticino.default.svg.zip](https://github.com/picons/picons/files/13688302/radioticino.default.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radioticino.default.svg.zip](https://github.com/picons/picons/files/13520063/radioticino.default.svg.zip)

![radioticino default](https://github.com/picons/picons/assets/35585833/9104d440-b3f9-4ea8-be08-4572fd3cacc1)

**Comment by ghost** [comment]
Radio Ticino
radioticino=radioticino

Logo correction
[radioticino.default.svg.zip](https://github.com/picons/picons/files/13709192/radioticino.default.svg.zip)
