### ISSUE TITLE
Radio X Switzerland

### ISSUE THREAD

**Issue by ghost** [picons/picons#1753]
# SNP/SRP entries

**snp.index**
```
radiox=radioxswitzerland
```
logos.zip

[radioxswitzerland.default.svg.zip](https://github.com/picons/picons/files/13467323/radioxswitzerland.default.svg.zip)

```

**Comment by ghost** [comment]
This is Radio X in Switzerland not Radio X Uk

Please at to Radio X UK: radioxuk=radiox

**Comment by AbuBaniaz** [comment]
You cannot have two lines like this
```
radiox=radio-uk
radiox=radio-switzerland
```
Only the first hit will be used. The only way is to add a `real` service reference for one of them.

**Comment by ghost** [comment]
No, I mean the Radio X UK logo is already there. But shows wrong on Radio X (Switzerland). It's basically swapped
![IMG_6424](https://github.com/picons/picons/assets/35585833/c6a01848-45f1-4a3e-a9e6-64887328ca86)
![IMG_6425](https://github.com/picons/picons/assets/35585833/1d4287b4-4a16-4403-ae4c-940b77d43998)
![Radio X UK Kopie](https://github.com/picons/picons/assets/35585833/aebd6f37-5564-47de-a1c1-398cb70f2267)

**Comment by AbuBaniaz** [comment]
In our indexes, there are two items on the links. 

The section on the left  of `=` is the SNP name/service reference of the channel. 

The section on the right of `=` is the logo on this repository.

You cannot have two identical left sections pointing to two different logos on this repository. Only the first one will be used to create a picon.

**Comment by AbuBaniaz** [comment]
We already have this link in the snp index. 

`radiox=radiox`

**Comment by ghost** [comment]
Yes that is Radio X UK

https://en.wikipedia.org/wiki/Radio_X_(United_Kingdom)

**Comment by AbuBaniaz** [comment]
Are you not understanding what I am saying?

**Comment by ghost** [comment]
You said, We already have this link in the SNP index. I say that this should be corrected as I described...

**Comment by AbuBaniaz** [comment]
So if we change the Switzerland one, what do we then use for the UK one? Their SNP names are the same.

**Comment by ghost** [comment]
is not the same see picture...

![image](https://github.com/picons/picons/assets/35585833/3705f4fa-cb99-4f91-9d5e-6d3c4a683242)

**Comment by AbuBaniaz** [comment]
Picture below is one on 28.2.
Channel name:  `Radio X`
SNP name for the channel:  `radiox`
We have to add `radioxuk` too.


![radio x 28 2](https://github.com/picons/picons/assets/6644489/351958f8-5110-4fd9-8ccd-f4e070c41092)

**Comment by ghost** [comment]
Thanke :-)

I hope you're more satisfied now and I'm doing my job better now? ;-)

Kind Regards from Switzerland

**Comment by AbuBaniaz** [comment]
It is better. Thank you.

It would be appreciated if in future you could do the following in inkscape:
clean up document.
resize page to selection
save as optimised svg

**Comment by ghost** [comment]
OK, I've never worked with Inkscape before, I have to get to know it first

**Comment by AbuBaniaz** [comment]
The logo has been added.  Please provide the real service reference for it.

I am sorry, I cant find any other way to express how we operate. This project provides for people from different countries/receiving different satellites. Some channels will have the same name/snp name but are different. We have to use service references for some of them. Sometimes it is first come first, other times it is efficiency. No point having 6 srp vs 1 snp.

**Comment by ghost** [comment]
#NAME radio
#SERVICE 1:0:2:56C:D:1:FFFF0000:0:0:0: Radio X
#SERVICE 1:0:2:61C:E:1:FFFF0000:0:0:0: Radio X UK

I think I understand the problem. Thanks

**Comment by AbuBaniaz** [comment]
Links added here: https://github.com/picons/picons/commit/cbf7b0147cd0adf5123cbc392da883aaf6869b18

`56C_D_1_FFFF0000=radioxswitzerland`
