### ISSUE TITLE
Radio Zürisee

### ISSUE THREAD

**Issue by ghost** [picons/picons#1754]
# SNP/SRP entries

**snp.index**
```
radiozurisee=radiozurisee
```
logos.zip

[radiozurisee.default.svg.zip](https://github.com/picons/picons/files/13465647/radiozurisee.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
Link was already present. Updated logo added here: https://github.com/picons/picons/commit/1d10b5178c417f98249be5a3f5616ed0d96a2c29
