### ISSUE TITLE
Rockit Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1755]
# SNP/SRP entries

**snp.index**
```
rockitradio=rockitradio
```
logos.zip

[rockitradio.default.svg.zip](https://github.com/picons/picons/files/13465735/rockitradio.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
This is present on repository

https://github.com/picons/picons/blob/master/build-source/snp.index#L12200
https://github.com/picons/picons/blob/master/build-source/logos/rockitradio.default.svg
