### ISSUE TITLE
RTN Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1762]
# SNP/SRP entries

**snp.index**
```
rtn=rtnradio
rtnradio=rtnradio
```
logos.zip

[rtnradio.default.svg.zip](https://github.com/picons/picons/files/13688822/rtnradio.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
The attachment won't download. Please try again.

**Comment by ghost** [comment]
Thanks, new upload

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/68b8cff0d6e8abbf7ab8f0506cd81486ce34e542
