### ISSUE TITLE
RTS La 1 Ere

### ISSUE THREAD

**Issue by ghost** [picons/picons#1764]
# SNP/SRP entries

**snp.index**
```
rtsla1ere=rtsla1ere
```
logos.zip

[rtsla1ere.default.svg.zip](https://github.com/picons/picons/files/13465769/rtsla1ere.default.svg.zip)

```

**Comment by Lexzie** [comment]
Whot!...
Please do as many changes in one Issue please!!

**Comment by Lexzie** [comment]
Logo is already present and, again, this is a very bad conversion of a png to svg.
Please do take some time to find a good svg. Most of them you can find on Logopedia of Wikipedia.

**Comment by Lexzie** [comment]
Link is also already present.
Please check our current `snp.index` before isssueing new links.
