### ISSUE TITLE
Spital Radio LuZ

### ISSUE THREAD

**Issue by ghost** [picons/picons#1766]
# SNP/SRP entries

**snp.index**
```
spitalradioluz=spitalradioluz
```
logos.zip

[Logos.zip](https://github.com/picons/picons/files/13699222/Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[spitalradioluz.default.svg.zip](https://github.com/picons/picons/files/13519660/spitalradioluz.default.svg.zip)

![spitalradioluz default](https://github.com/picons/picons/assets/35585833/670bafba-db2f-484c-9b3e-0c7c4fd3e5e9)

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[spitalradioluz.default.svg.zip](https://github.com/picons/picons/files/13519754/spitalradioluz.default.svg.zip)

![spitalradioluz default](https://github.com/picons/picons/assets/35585833/86d7fc6e-22b4-4049-a62e-26ef75705cfa)

**Comment by ghost** [comment]
Spital Radio LuZ
Logo correction

[Logos.zip](https://github.com/picons/picons/files/13699227/Logos.zip)
