### ISSUE TITLE
Spoon Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1767]
# SNP/SRP entries

**snp.index**
```
spoonradio=spoonradio
```
logos.zip

[spoonradio.default.svg.zip](https://github.com/picons/picons/files/13506584/spoonradio.default.svg.zip)

```

**Comment by ghost** [comment]
please reopen. 
I edited the logo and it looks better, please check. This is my first logo that I edited myself...

[spoonradio.default.svg.zip](https://github.com/picons/picons/files/13492944/spoonradio.default.svg.zip)

**Comment by ghost** [comment]
Thanks ;-) 
Please check

**Comment by Lexzie** [comment]
One at a time...

**Comment by Lexzie** [comment]
Is this the Spoon Radio you are referring to?
https://www.spoonradio.com/

**Comment by ghost** [comment]
Yes mmmhhh Sorry
Have a new logo

**Comment by Lexzie** [comment]
Yes, so far I only found a default and light logo, but 300x300 pixels and that's too small.
![logo](https://github.com/picons/picons/assets/14023349/03460f58-ceb1-4c9c-b0b4-641cb3836b5e)
![afbeelding](https://github.com/picons/picons/assets/14023349/405dc89f-b66c-468b-964e-b30f716b9159)

Maybe I have to make a svg. But I am done for now...

**Comment by ghost** [comment]
should I do the 2? do you trust me to do that?

**Comment by Lexzie** [comment]
If I say I make them, I mean really edit them.
First try to find which font is used (with the help of the Font Identifier on Fontsquirrel), then I make the logo in Inkscape.
The background and the two half circles should be no problem to draw.

I guess you'll convert the png with bitmap trace? Probably more work if you really clean the flaws out of it (zoom in).

**Comment by Lexzie** [comment]
Looks like the font is Metropolis Semi Bold. The font is free available.

**Comment by ghost** [comment]
Ok, so wouldn't this be good?

![spoonradio default Black](https://github.com/picons/picons/assets/35585833/a95397cb-ad5b-4446-9a55-2247f4d60f6e)


![spoonradio default](https://github.com/picons/picons/assets/35585833/07872453-21ca-4f73-8e6b-2010f00f2d10)

**Comment by Lexzie** [comment]
Indeed, these look good.
Only the official logo has round edges and the logos are not totally converted to path, and not saved as optimized svg's.
No problem for me to do that, only not now anymore.

**Comment by ghost** [comment]
![spoonradio default Black](https://github.com/picons/picons/assets/35585833/3cdfdfdc-8bbb-42b8-a10d-5a99dd31feb3)

![spoonradio default](https://github.com/picons/picons/assets/35585833/38a2e5a3-2202-44b5-9866-5a1517e929aa)
