### ISSUE TITLE
Radio SRF 1

### ISSUE THREAD

**Issue by ghost** [picons/picons#1768]
# SNP/SRP entries

**snp.index**
```
radiosrf1=radiosrf1
radiosrf1ag=radiosrf1
radiosrf1be=radiosrf1
radiosrf1bs=radiosrf1
radiosrf1gr=radiosrf1
radiosrf1lu=radiosrf1
radiosrf1sg=radiosrf1
radiosrf1zh=radiosrf1
```
logos.zip

[radiosrf1.default.svg.zip](https://github.com/picons/picons/files/13465839/radiosrf1.default.svg.zip)

```

**Comment by yannydodo12** [comment]
wow mate can you not do them all in one instead of a few at a time..
