### ISSUE TITLE
Country Radio Switzerland

### ISSUE THREAD

**Issue by ghost** [picons/picons#1783]
# SNP/SRP entries

**snp.index**
```
countryradioswitzerland=countryradioswitzerland
```
logos.zip

[countryradioswitzerland.default.svg.zip](https://github.com/picons/picons/files/13688996/countryradioswitzerland.default.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[countryradioswitzerland.default.svg.zip](https://github.com/picons/picons/files/13520258/countryradioswitzerland.default.svg.zip)

![countryradioswitzerland default](https://github.com/picons/picons/assets/35585833/fa25bb8b-fb39-4bdd-a861-50ab364b9e59)

**Comment by ghost** [comment]
Country Radio Switzerland
Logo correction

[countryradioswitzerland.default.svg.zip](https://github.com/picons/picons/files/13699162/countryradioswitzerland.default.svg.zip)
