### ISSUE TITLE
diis Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1784]
# SNP/SRP entries

**snp.index**
```
diisradio=diisradio
```
logos.zip

[diisradio.default.svg.zip](https://github.com/picons/picons/files/13688773/diisradio.default.svg.zip)

[diisradio.light.svg.zip](https://github.com/picons/picons/files/13688774/diisradio.light.svg.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[diisradio.default.svg.zip](https://github.com/picons/picons/files/13520308/diisradio.default.svg.zip)

![diisradio default](https://github.com/picons/picons/assets/35585833/0e12c483-594e-476e-9a61-56d4b9a168a4)

**Comment by ghost** [comment]
diis Radio
Logo correction

[diis Radio Logo.zip](https://github.com/picons/picons/files/13699177/diis.Radio.Logo.zip)
