### ISSUE TITLE
GVFM

### ISSUE THREAD

**Issue by ghost** [picons/picons#1789]
# SNP/SRP entries

**snp.index**
```
gvfm=gvfm
gvfmromandie=gvfm
```
logos.zip

[gvfm.default.svg.zip](https://github.com/picons/picons/files/13481402/gvfm.default.svg.zip)

```

**Comment by ghost** [comment]
ad snp.index

gvfmromandie=gvfm

**Comment by AbuBaniaz** [comment]
Please stop responding in closed issues.
