### ISSUE TITLE
Jam on Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1790]
# SNP/SRP entries

**snp.index**
```
jamonradio=jamonradio
```
logos.zip

[Jam on Radio Logos.zip](https://github.com/picons/picons/files/13708807/Jam.on.Radio.Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[jamonradio.default.svg.zip](https://github.com/picons/picons/files/13533023/jamonradio.default.svg.zip)

![jamonradio default](https://github.com/picons/picons/assets/35585833/e2fdc632-ed68-4af0-9513-5ad14087b44b)

**Comment by ghost** [comment]
Jam on Radio
jamonradio=jamonradio

[Jam on Radio Logos.zip](https://github.com/picons/picons/files/13708810/Jam.on.Radio.Logos.zip)
