### ISSUE TITLE
Radio NRJ Alsace

### ISSUE THREAD

**Issue by ghost** [picons/picons#1804]
# SNP/SRP entries

**snp.index**
```
radionrjalsace=radionrjalsace
radionrjf=radionrjalsace
radionrjleman=radionrjalsace
```
logos.zip

[Radio NRJ Alsace Logos.zip](https://github.com/picons/picons/files/13709087/Radio.NRJ.Alsace.Logos.zip)

```

**Comment by William-Richards** [comment]
Please reopen. I think the logo is better with a black and white background.

[radionrjalsace.default.svg.zip](https://github.com/picons/picons/files/13519599/radionrjalsace.default.svg.zip)

![radionrjalsace default](https://github.com/picons/picons/assets/35585833/38e1e2db-9670-49c0-a28f-9c3bb8179011)

**Comment by ghost** [comment]
Radio NRJ Alsace 
radionrjalsace=radionrjalsace
radionrjf=radionrjalsace
radionrjleman=radionrjalsace

Logo correction
[Radio NRJ Alsace Logos.zip](https://github.com/picons/picons/files/13709093/Radio.NRJ.Alsace.Logos.zip)
