### ISSUE TITLE
Radio Monut to Radio BeO

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#1814]
# SNP/SRP entries

**snp.index**
```
radiobeo=radiobeo
beO=radiobeo
radiobern1=radiobern1
bern1=radiobern1
radioblindpower=radioblindpower
blindpower=radioblindpower
radiocentral=radiocentral
radiochablais=radiochablais
radiocité=radiocité
radioeviva=radioeviva
eviva=radioeviva
radiofribourg=radiofribourg
radiogloria=radiogloria
radioinside=radioinside
radioitaliaanni60=radioitaliaanni60
radiojazzinternational=radiojazzinternational
radiokaiseregg=radiokaiseregg
radiol=radioliechtenstein
radioliechtenstein=radioliechtenstein
radiolora=radiolora
radiomariaschweiz=radiomariaschweiz
radiomelody=radiomelody
radiomontecarlol=radiomontecarlol
radiomonut=radiomonut
radioorbital=radioorbital
radiopilatus=radiopilatus
radiorabe=radiorabe
radiorasa=radiorasaschaffhausen
radiorasaschaffhausen=radiorasaschaffhausen
radiorottuoberwallis=radiorottuoberwallis
radiostadtfilter=radiostadtfilter

```
all resized and optimized..
[Radio Monut to Radio BeO.zip](https://github.com/picons/picons/files/13491166/Radio.Monut.to.Radio.BeO.zip)
[Radio Orbital to Radio Stadtfilter.zip](https://github.com/picons/picons/files/13491346/Radio.Orbital.to.Radio.Stadtfilter.zip)

**Comment by Lexzie** [comment]
@AbuBaniaz what do you think of the logo 'radiochablais.default.svg`. As a rule we don't use a background right?
But looking at their website, I would rather expect something like this:
![Logo_anime](https://github.com/picons/picons/assets/14023349/da67c65c-2c3f-4f51-963a-040d8588dde0)

What we could also do is this:
https://yt3.googleusercontent.com/ytc/APkrFKYYEtyCdIZnxs-qoRmXPuvW-oPIDmV8AFQLY3TEmQ=s1200-c-k-c0x00ffffff

**Comment by yannydodo12** [comment]
Could just remove the background for it..
And I think some more or them had some sort of background. I just thought that was the way the logo was lol..

**Comment by Lexzie** [comment]
If that is an essential part of the logo, like Radio Bern, Radio Beo, then leave it.
But make it shaped like the gif I showed.

**Comment by Lexzie** [comment]
And are you able to edit a svg logo?
The logo for Radio Cité should be like this:
![BvVgGW74SE](https://github.com/picons/picons/assets/14023349/2f829f22-502f-4381-9f57-d5d531c5610d)

Also there are some ugly things because of the conversion from png to svg, like the orange dot in the C is not round.

**Comment by Lexzie** [comment]
@yannydodo12 isn't this the right logo for `radioinside`? #1730

**Comment by yannydodo12** [comment]
If I remember correctly the svg had a path to the background. most that I resized had a path which was the second last path.
As for editing svg file, no I've no clue on how to fix them properly sorry..

**Comment by Lexzie** [comment]
> If I remember correctly the svg had a path to the background. most that I resized had a path which was the second last path. As for editing svg file, no I've no clue on how to fix them properly sorry..

Never mind. I guess you mean the Radio Cité logo? I will give it a try.

**Comment by yannydodo12** [comment]
radiochablais.default.svg` 
That one you should be able to remove the background in the svg

**Comment by Lexzie** [comment]
> radiochablais.default.svg` That one you should be able to remove the background in the svg

I have a problem with this logo.
No problem for me to remove the background, but the 'globe' symbol on the left looks horrible from converting the png to a svg.
Just see and compare it with the logo below:

![afbeelding](https://github.com/picons/picons/assets/14023349/2d6c9cd9-161d-4f04-a2ad-d940ce36ebf0)

No way I can fix that.
I hope you accept that we will use this logo instead (I can't find a decent one without the text):

![radiochablais default](https://github.com/picons/picons/assets/14023349/8aa55c85-ff18-492b-ad1e-eef84bab4ed5)

**Comment by yannydodo12** [comment]
I've no issues with it mate..
I didn't do them 😂
William did I just resized them and made it easier to add instead of doing the 50 odd he added one at a time 😂

**Comment by AbuBaniaz** [comment]
> @AbuBaniaz what do you think of the logo 'radiochablais.default.svg`. As a rule we don't use a background right? But looking at their website, I would rather expect something like this: 

We should use what looks best on the receivers. What is on the website is not the most important thing.
