### ISSUE TITLE
Voice of America

### ISSUE THREAD

**Issue by ghost** [picons/picons#1817]
# SNP/SRP entries

**snp.index**
```
voiceofamerica=voiceofamerica
```
logos.zip

[voiceofamerica.default.svg.zip](https://github.com/picons/picons/files/13494571/voiceofamerica.default.svg.zip)

```

**Comment by Lexzie** [comment]
I would not know why we should replace the logo with (almost) the same one.
Only difference is the colour. Looking at [their website](https://www.voanews.com/) we already have the right colour.

**Comment by ghost** [comment]
Question, Radio SRF 2 should already be there but I can't find it. Radio SRF 2 Kultur should be added there.

radiosrf2kultur=radiosrf2

**Comment by Lexzie** [comment]
[srf2kultur.default.svg](https://github.com/picons/picons/blob/master/build-source/logos/srf2kultur.default.svg)

So the link should be:
```
radiosrf2kultur=srf2kultur
```
