### ISSUE TITLE
Sunradio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1822]
# SNP/SRP entries

**snp.index**
```
sunradio=sunradio
```
logos.zip

[sunradio.default.svg.zip](https://github.com/picons/picons/files/13688218/sunradio.default.svg.zip)

```

**Comment by William-Richards** [comment]
![sunradio default](https://github.com/picons/picons/assets/35585833/2d2acd29-9f02-4dc4-8d7b-495f1a61bb80)

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/3e51a88dcee8906e1fa3dc5ba4954d18a4cd000f
