### ISSUE TITLE
Radio 24 ORE

### ISSUE THREAD

**Issue by ghost** [picons/picons#1834]
# SNP/SRP entries

**snp.index**
```
radio24ore=radio24ore
```
logos.zip

[Logo Radio24 Ore.zip](https://github.com/picons/picons/files/13699265/Logo.Radio24.Ore.zip)

```

**Comment by ghost** [comment]
They are 2 different channels and have been mixed up.

Radio 24 ORE
radio24ore=radio24ore
[Logo Radio24 Ore.zip](https://github.com/picons/picons/files/13699273/Logo.Radio24.Ore.zip)

Radio 24
radio24=radio241028
radio24fm102.8=radio241028
[Radio241028.svg.png.zip](https://github.com/picons/picons/files/13699276/Radio241028.svg.png.zip)

**Comment by ghost** [comment]
Radio 24 Ore

radio24ore=radio24

**Comment by AbuBaniaz** [comment]
Please do not do double posts. 

I am going to to re-open this issue and close the other one.

**Comment by AbuBaniaz** [comment]
I have added the link here: https://github.com/picons/picons/commit/3c0eefcd3a86e8fe20b937951cc2e8a159bc766c

If there are any other issues after the next build,  Do not double post.  Start a new issue and answer thr following questions.

What is the name of the channel?
What is the snp name of the channel?
Is the snp name already in use? Check snp.index file on this repository.

What is the service reference of the channel?
What is the trimmed reference as used by this project? See contributing to .md or the srp.index

What is the name of the logo on this repository that you want to use to make the picon?
