### ISSUE TITLE
RNE Radio Nacional

### ISSUE THREAD

**Issue by ghost** [picons/picons#1836]
# SNP/SRP entries

**snp.index**
```
rneradionacional=rneradionacional
```
logos.zip

[rneradionacional.default.svg.zip](https://github.com/picons/picons/files/13519953/rneradionacional.default.svg.zip)

```

**Comment by Lexzie** [comment]
This logo is already present.
Logopedia says there is a new logo.
I checked the website of rne and still the logo we have in our repository.
Added the missing link.

**Comment by ghost** [comment]
Ok OK Thanks, can you tell me where I can find it? I didn't find it when searching and how should I deal with it if there is already a logo if I have something to complain about or want to add name?

Thank you

**Comment by Lexzie** [comment]
Told you before you can see the logos in our repository here:
https://github.com/picons/picons/tree/master/build-source/logos
If you check there you will also see the name used for the logo you want to link to.

The list of links can be found here (snp.index and srp.index):
https://github.com/picons/picons/tree/master/build-source
