### ISSUE TITLE
Radio Studio Star

### ISSUE THREAD

**Issue by ghost** [picons/picons#1839]
# SNP/SRP entries

**snp.index**
```
radiostudiostar=radiostudiostar
```
logos.zip

[Radio Studio Star Logos.zip](https://github.com/picons/picons/files/13709159/Radio.Studio.Star.Logos.zip)

```

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/05a753dffa914feb09c78233c3987748c444e65d
