### ISSUE TITLE
Radio Suisse Classique

### ISSUE THREAD

**Issue by ghost** [picons/picons#1840]
# SNP/SRP entries

**snp.index**
```
radiosuisseclassique=radiosuisseclassique
```
logos.zip

[radiosuisseclassique.svg.zip](https://github.com/picons/picons/files/13532964/radiosuisseclassique.svg.zip)

```

**Comment by Lexzie** [comment]
Could you please add a link to the website of the stations?

I can only find this:
https://www.radioswissclassic.ch/fr

**Comment by ghost** [comment]
no, is not the same !

**Comment by Lexzie** [comment]
That's obvious, so could you give a link to the right website?

**Comment by ghost** [comment]
Ok, I've listened to both, maybe it's the same station but a little different in time... so maybe it's the same logo

https://www.radioswissclassic.ch/fr
https://liveonlineradio.net/de/radio-suisse-classique

**Comment by Lexzie** [comment]
It's the same station and you provided the old logo.
https://logos.fandom.com/wiki/Radio_Swiss_Classic
Please check it on f.e. Logopedia (they are very actual) and the official website of the station, not a website with streams of all stations.

**Comment by Lexzie** [comment]
Link added.
