### ISSUE TITLE
Okto

### ISSUE THREAD

**Issue by ghost** [picons/picons#1842]
# SNP/SRP entries

**snp.index**
```
okto=oktowien
oktohd=oktowien
oktotv=oktowien
oktotvhd=oktowien
```

```

**Comment by Lexzie** [comment]
Why are you reopening this?

**Comment by ghost** [comment]
No Logo last update

**Comment by Lexzie** [comment]
What update?

The links are all in snp.index

**Comment by ghost** [comment]
Ok, maybe next update...?

**Comment by Lexzie** [comment]
You're probably referring to the update on your receiver.
We have logos and a list what names to link to which logo, we have nothing to do what your imagebuilder is providing.
Ask them for an update.

**Comment by ghost** [comment]
No, I actually always do the updates directly from Github, the last one was today at around 4 a.m....

**Comment by Lexzie** [comment]
The only packages we provide are here: https://github.com/picons/picons/releases
Last one was from two days ago. We build them only weekly, not daily.

So what is the Github you are referring to?

As a side-note: I am not involved in building that. I just supply logos and links.

**Comment by ghost** [comment]
Ok, I just did the last few and will now wait until after Christmas and then I'll see what's missing or not good.

**Comment by Lexzie** [comment]
Well maybe it is taking a bit longer.
And you submitted a lot. I am happy @AbuBaniaz is doing a lot. My time is limited too and I have my own updates too.

**Comment by AbuBaniaz** [comment]
I wish I could communicate directly with him. The constant e-mails from him and wrong approach is annoying. And just posting links to links with no mention of what he wants to achieve/solve.

@Lexzie 
Please accept the Skype invite

**Comment by Lexzie** [comment]
I haven't used Skype for ages.
You can find me on OpenPLi forum. And you had my email address before.

**Comment by ghost** [comment]
I have to tell you, I don't speak English, I have to translate everything first in order to understand something. This text is also translated…

Unfortunately that's the case... but I won't stress you anymore because we'll soon be at our destination and Switzerland will soon have logos for pretty much all TV and radio stations... thank you for your patience and openness. I wish you all a merry christmas

**Comment by Lexzie** [comment]
Well that explains it a bit. I am also able to communicate in Dutch or German, but we use English in this repository.
If we come on strong don't let that discourage you, but we like to keep thinks clean and of high quality.

Merry Christmas to you too.

**Comment by AbuBaniaz** [comment]
Openpicons (legobatman) builds almost everyday. You can install his "feeds" for more frequent updates. OpenATV take from his repository.https://openpicons.com/picons/
