### ISSUE TITLE
Kronehit TV

### ISSUE THREAD

**Issue by ghost** [picons/picons#1843]
# SNP/SRP entries

**snp.index**
```
kronehittv=kronehittv
kronehittvhd=kronehittv
```
logos.zip

[kronehittv.default.svg.zip](https://github.com/picons/picons/files/13537516/kronehittv.default.svg.zip)

```

**Comment by Lexzie** [comment]
There is no background used in the logo:
![afbeelding](https://github.com/picons/picons/assets/14023349/b49f68b0-1d06-49c6-b4fc-a0e3b6405893)

So, I removed the background and also made a dark variant (the default (light) variant is white so you won't see it here).
![kronehittv dark](https://github.com/picons/picons/assets/14023349/b75b4d12-3193-489e-8b3a-7a2b4e303ba6)
