### ISSUE TITLE
Radio Regenbogen

### ISSUE THREAD

**Issue by ghost** [picons/picons#1849]
# SNP/SRP entries

**snp.index**
```
radioregenbogen=radioregenbogen
```
logos.zip

[radioregenbogen.default.svg.zip](https://github.com/picons/picons/files/13565089/radioregenbogen.default.svg.zip)

[radioregenbogen.light.svg.zip](https://github.com/picons/picons/files/13625122/radioregenbogen.light.svg.zip)

```

**Comment by Lexzie** [comment]
Logo is also already in our repo.

**Comment by ghost** [comment]
Yes I know, I changed it so that it looks better even with a black background

Please reopen. I think the logo is better with a black and white background.

1723 Radio Central
1728 Radio Fribourg / Freiburg 
1804 Radio NRJ France etc..
1766 Spital Radio LuZ
1750 Radio Ticino 
1715 Radio 4 TNG
1781 95.8 Capital FM
1783 Country Radio Switzerland
1784 diis Radio
1786 FM 1
1790 Jam on Radio
1792 Kanal K
1719 Radio Basilisk
1722 Radio Blind Power
1733 Radio Kaiseregg
1732 Radio Jazz International
1749 Radio Tell
1849 Radio Regenbogen

**Comment by Lexzie** [comment]
> Yes I know, I changed it so that it looks better even with a black background
> 
> Please reopen. I think the logo is better with a black and white background.
>

If a logo is not looking good on (in this case) a dark background you leave the default logo the same and you create a `light` logo.
If a logo is not looking good on a light background you leave the default logo the same and you create a `dark` logo.
There must always be at least a `default` logo and you can never have a `light` **and** a `dark` logo (besides the default).
If the default logo is a png, the variant must also be a png.
If the default logo is a svg, the variant must also be a svg.

Mention in the issue that you would like to add a variant.
 
> 1723 Radio Central 1728 Radio Fribourg / Freiburg 1804 Radio NRJ France etc.. 1766 Spital Radio LuZ 1750 Radio Ticino 1715 Radio 4 TNG 1781 95.8 Capital FM 1783 Country Radio Switzerland 1784 diis Radio 1786 FM 1 1790 Jam on Radio 1792 Kanal K 1719 Radio Basilisk 1722 Radio Blind Power 1733 Radio Kaiseregg 1732 Radio Jazz International 1749 Radio Tell 1849 Radio Regenbogen

What fo you want me to do with this list?

**Comment by ghost** [comment]
how can I reopen this to change

**Comment by Lexzie** [comment]
It's already reopened.

**Comment by Lexzie** [comment]
Logo look okay to me on a dark (black) background.
![afbeelding](https://github.com/picons/picons/assets/14023349/79e323b0-bfc3-4e2b-833f-fe02d4e7f851)

Maybe not on f.e. a dark blue background (some people like to use that).
So I will add you light variant.

**Comment by Lexzie** [comment]
> # SNP/SRP entries
> 
> **snp.index**
> 
> ```
> radioregenbogen=radioregenbogen
> ```
> 

Please only add a link if it's not already in snp.index.
**https://github.com/picons/picons/blob/master/build-source/snp.index**

**Comment by ghost** [comment]
Thank you
I've tried a few things with the channels listed
