### ISSUE TITLE
Sunshine Live

### ISSUE THREAD

**Issue by ghost** [picons/picons#1850]
# SNP/SRP entries

**snp.index**
```
sunshinelive=sunshinelive
```
logos.zip

[sunshinelive.default.svg.zip](https://github.com/picons/picons/files/13572289/sunshinelive.default.svg.zip)

[sunshinelive.dark.svg.zip](https://github.com/picons/picons/files/13688059/sunshinelive.dark.svg.zip)

```

**Comment by ghost** [comment]
New Logo

![sunshinelive default](https://github.com/picons/picons/assets/35585833/e3543141-8194-40dd-8913-75d6bdefcd2a)

**Comment by AbuBaniaz** [comment]
We have this logo on our repository:
https://github.com/picons/picons/blob/master/build-source/logos/radiosunshine.default.svg

We have this assignment already
`sunshinelive=radiosunshinelive`

The snp name `sunshinelive` is already taken up. We can not use the link you are asking for. You need to supply the service reference for it to be added to point to the logo you have supplied.

**Comment by ghost** [comment]
Sunshine Live is not Radio Sunshine. Big different.Von meinem iPhone gesendetAm 10.12.2023 um 20:54 schrieb AbuBaniaz ***@***.***>:﻿
We have this logo on our repository:
https://github.com/picons/picons/blob/master/build-source/logos/radiosunshine.default.svg
We have this assignment already
sunshinelive=radiosunshinelive
The snp name sunshinelive is already taken up. We can not use the link you are asking for. You need to supply the service reference for it to be added.

**Comment by AbuBaniaz** [comment]
Once again, I am repeating what was said to you before.

Sometimes different channels have the same name, even though they are different. When  we have different channels with the same snp name , one of them will have to use a service reference. We create picons for several providers and have to cater for everyone.

Please provide the service reference and we will add it so the picon is created for you to use with the logo you want.

**Comment by ghost** [comment]
Yes, but the Radio Sunshine logo is not to be confused with Sunradio or Sunshine Live

54C:D:1:FFFF0000=radiosunshine
567:B:1:FFFF0000=sunradio
5CA:B:1:FFFF0000=sunshinelive

Thanks

Kind regards
William

**Comment by AbuBaniaz** [comment]
Can you please attach your lamedb file.  This is very frustrating.

All I wanted was the references for the channel and logo you wanted to be added.

**Comment by AbuBaniaz** [comment]
By mentioning something different to what want added, you have caused confusion.

All we want in our snp.index file is 
`snp_name_of_channel=name_of_logo_on_repository_to use`

If you cannot have the snpname, we must have
`trimmed_service_reference_of_channel=name_of_logo_on_repository_to use`

We uses underscores on the service references, if you can use that in future issues, it will make it easier to add what you want. None of us get paid for this.  Have a look at previous commits, we just want to copy and paste. Make it as easy as possible please.

**Comment by AbuBaniaz** [comment]
Logo added here: https://github.com/picons/picons/commit/1d10b5178c417f98249be5a3f5616ed0d96a2c29
A picon using that logo will not be generated until you provide a service reference

We now have the following logos on this repository:
https://github.com/picons/picons/blob/master/build-source/logos/radiosunshinelive.default.png
https://github.com/picons/picons/blob/master/build-source/logos/radiosunshinelive-thukalafri.default.svg

For those struggling to understand how we operate, ask yourself these questions:

What is the name of the channel?
What is the `snp name`  of the channel?
Is the snp name already in use? Check snp.index file on this repository.
What is the service reference of the channel?
What is the trimmed reference as used by this project? See contributing to .md
What is the name of the logo you want to use to make the picon?

**Comment by AbuBaniaz** [comment]
I will close this issue tomorrow unless you provide just the service reference to create a picon using this logo:
https://github.com/picons/picons/blob/master/build-source/logos/radiosunshinelive-thukalafri.default.svg

`radiosunshinelive-thukalafri`

Or upload your lamedb file.

**Comment by ghost** [comment]
[setting-cable-upc-innerschweiz.zip](https://github.com/picons/picons/files/13688802/setting-cable-upc-innerschweiz.zip)

[lamedb.zip](https://github.com/picons/picons/files/13688813/lamedb.zip)

**Comment by AbuBaniaz** [comment]
>What is the name of the channel?

Sunshine Live

>What is the snp name of the channel?

sunshinelive

>Is the snp name already in use? Check snp.index file on this repository.

Yes it is. We have `sunshinelive=radiosunshinelive`. So we have to add the service reference in the snp.index file

>What is the service reference of the channel?

1_0_2_5CA_B_1_FFFF0000_0_0_0

>What is the trimmed reference as used by this project? See contributing to .md

5CA_B_1_FFFF0000

>What is the name of the logo you want to use to make the picon?

radiosunshinelive-thukalafri.default.svg

Based on the above, I will add to the snp.index file
`5CA_B_1_FFFF0000=radiosunshinelive-thukalafri`

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/0af116a998f3f939507a46f04199848f41039233
