### ISSUE TITLE
Deutschlandfunk

### ISSUE THREAD

**Issue by ghost** [picons/picons#1851]
# SNP/SRP entries

**snp.index**
```
deutschlandfunk=deutschlandfunk
dlf=deutschlandfunk
```
logos.zip

[deutschlandfunk.default.svg.zip](https://github.com/picons/picons/files/13572374/deutschlandfunk.default.svg.zip)

```

**Comment by ghost** [comment]
New Logo


![deutschlandfunk default](https://github.com/picons/picons/assets/35585833/1b686ed6-ea70-40d8-8cbd-1577421d16a6)

**Comment by Lexzie** [comment]
> New Logo
> 
> ![deutschlandfunk default](https://private-user-images.githubusercontent.com/35585833/288190356-1b686ed6-ea70-40d8-8cbd-1577421d16a6.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MTI1NjgsIm5iZiI6MTcwMTgxMjI2OCwicGF0aCI6Ii8zNTU4NTgzMy8yODgxOTAzNTYtMWI2ODZlZDYtZWE3MC00MGQ4LThjYmQtMTU3NzQyMWQxNmE2LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDIxMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MjQyZGM0OWRkNzI4Yzg5MDk2MzdiOTk3MzljNDQyN2E1Y2RkODYxODRmMjgzYTA4ZGEwMWJjNDczNjFiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kuWXA0GsWmkY9sF1_2Hm3Ln7y9yNZegDPllBKBR-C1Q)

It was new in 2017...

https://logos.fandom.com/wiki/Deutschlandfunk

https://github.com/picons/picons/blob/master/build-source/logos/deutschlandfunk.default.svg

**Comment by Lexzie** [comment]
Links are also all present.

**Comment by ghost** [comment]
New logo should be larger and easier to read.
