### ISSUE TITLE
Deutschlandfunk Kultur

### ISSUE THREAD

**Issue by ghost** [picons/picons#1852]
# SNP/SRP entries

**snp.index**
```
deutschlandfunkkultur=deutschlandfunkkultur
dlfkultur=deutschlandfunkkultur
```
logos.zip

[deutschlandfunkkultur.default.svg.zip](https://github.com/picons/picons/files/13572416/deutschlandfunkkultur.default.svg.zip)

```

**Comment by ghost** [comment]
New Logo

![deutschlandfunkkultur default](https://github.com/picons/picons/assets/35585833/86b8cb9c-ffe4-4adb-a484-4b68eb048c59)

**Comment by Lexzie** [comment]
New logo?

https://github.com/picons/picons/blob/master/build-source/logos/deutschlandfunkkultur.default.svg

**Comment by Lexzie** [comment]
Links are also already present.

**Comment by ghost** [comment]
New logo should be larger and easier to read.
