### ISSUE TITLE
Best Christmas Music

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#1854]
I can't find anything better than these logos:

![bestchristmasmusic dark](https://github.com/picons/picons/assets/14023349/ca074c83-35e7-4da3-bb47-0b7fcc48ab5d)

![skychb1305](https://github.com/picons/picons/assets/14023349/0d9dc4ab-92a9-4fa2-8ba7-9621198af6ea)

The last one is like is shown on TV.

Can anyone do better?

**Comment by yannydodo12** [comment]
> I can't find anything better than these logos:
> 
> ![bestchristmasmusic dark](https://private-user-images.githubusercontent.com/14023349/288200973-ca074c83-35e7-4da3-bb47-0b7fcc48ab5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU1NzIsIm5iZiI6MTcwMTkwNTI3MiwicGF0aCI6Ii8xNDAyMzM0OS8yODgyMDA5NzMtY2EwNzRjODMtMzVlNy00ZGEzLWJiNDctMGI3ZmNjNDhhYjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDQ3NjdiMDc4Yjg3NTg5ODlkYjNiNmQyMTBlM2NkNjI5ZGUzYmY3ZThiNDczOWFhNjZkM2IwZmM0ZGZjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cZbZpXTPLB15BwgRR6h-iXdEmn8jPLxEB5C7YgCTrHg)
> 
> ![skychb1305](https://private-user-images.githubusercontent.com/14023349/288200602-0d9dc4ab-92a9-4fa2-8ba7-9621198af6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDU1NzIsIm5iZiI6MTcwMTkwNTI3MiwicGF0aCI6Ii8xNDAyMzM0OS8yODgyMDA2MDItMGQ5ZGM0YWItOTJhOS00ZmEyLThiYTctOTYyMTE5OGFmNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODY5MWZmYTVlYTc4NWRjNWQ3Y2QwMjIyOGQzOWY3MDcwOWJiYzFmZjhkNDEyOTFlZWI2NzMxYjRiNTk4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vy0c4jBYRHR1ePTH-TodjBLVTYGm4avaNMtzNRXk0LE)
> 
> The last one is like is shown on TV.
> 
> Can anyone do better?

The best one available seems to be the sky one mate .

**Comment by Lexzie** [comment]
But it's 56x40 pixels, that's way below the recommended 800 px

**Comment by yannydodo12** [comment]
> But it's 56x40 pixels, that's way below the recommended 800 px

https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb1305.png

**Comment by AbuBaniaz** [comment]
What about this?
```
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb1305.png
```

**Comment by Lexzie** [comment]
LOL
@yannydodo12 was quicker, @AbuBaniaz :)

Looks okay, I will check it later today or tomorrow and submit it.

**Comment by AbuBaniaz** [comment]
Merge this if okay: https://github.com/picons/picons/pull/1862
