### ISSUE TITLE
N24 Doku HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#1874]
# SNP/SRP entries

**snp.index**
```
n24dokuhd=n24dokuhd
```
logos.zip

[n24dokuhd.default.svg.zip](https://github.com/picons/picons/files/13679895/n24dokuhd.default.svg.zip)

[n24dokuhd.light.svg.zip](https://github.com/picons/picons/files/13679896/n24dokuhd.light.svg.zip)

```

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/4b6613642289ddf3331e81c054327b2406fb0e38

**Comment by Lexzie** [comment]
What's the reason of using the color f2f2f2 for the light logo while the existing logos use ffffff?

**Comment by AbuBaniaz** [comment]
Were there existing logos? If so, what are their names? I'll delete the ones I added and point links to the older ones.

**Comment by ghost** [comment]
Ok

**Comment by Lexzie** [comment]
I meant the N24 Docu logo without HD and also other N24-logos.
```
n24.light.svg
n24hd.light.svg
n24doku.light.svg
n24dokuaustria.light.svg
```

**Comment by AbuBaniaz** [comment]
Can you improve the ones I added when you get a chance please?

**Comment by Lexzie** [comment]
No problem, I can do that this evening.
You're not able to edit a svg?
I reopen this to find it easier.

**Comment by ghost** [comment]
I think I not understand exactly what you mean?

N24 Doku HD
n24dokuhd=n24dokuhd

[N24 Doku HD Logos.zip](https://github.com/picons/picons/files/13705549/N24.Doku.HD.Logos.zip)

**Comment by Lexzie** [comment]
> I think I not understand exactly what you mean?
> 
> N24 Doku HD
> n24dokuhd=n24dokuhd
> 
> [N24 Doku HD Logos.zip](https://github.com/picons/picons/files/13705549/N24.Doku.HD.Logos.zip)
> 
> 

There were already logos for N24, N24 Docu etc.
The light logos of these stations use white letters, not grey like in your light logo.
We would like to keep it the same for the same (sister) stations.

**Comment by ghost** [comment]
Ok I understand, unfortunately I can't match that with the total yet. That would have to be done by someone with more experience.

**Comment by Lexzie** [comment]
Consider it done.
