### ISSUE TITLE
srp.index

### ISSUE THREAD

**Issue by ghost** [picons/picons#1895]
srp.index

58D:C:1:FFFF0000=radio1fm936

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1712#issuecomment-1848668750_

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/e1b9bf7cfe97001d038a1b22ab94e0d8b1005212

Please note, we use the underscore. There are two sections of service references in openwebif. One has colons, other has underscores.  Easier/better to copy then paste the one we use.
