### ISSUE TITLE
diisradio=diisradio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1907]
diisradio=diisradio

[diisradio.default.svg.zip](https://github.com/picons/picons/files/13693185/diisradio.default.svg.zip)

[diisradio.light.svg.zip](https://github.com/picons/picons/files/13693186/diisradio.light.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1886#issuecomment-1858862717_

**Comment by William-Richards** [comment]
[diis Radio Logo.zip](https://github.com/picons/picons/files/13697447/diis.Radio.Logo.zip)
