### ISSUE TITLE
kanalk=kanalk

### ISSUE THREAD

**Issue by ghost** [picons/picons#1911]
kanalk=kanalk

[kanalk.default.svg.zip](https://github.com/picons/picons/files/13693200/kanalk.default.svg.zip)

[kanalk.light.svg.zip](https://github.com/picons/picons/files/13693201/kanalk.light.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1883#issuecomment-1858864774_

**Comment by AbuBaniaz** [comment]
Please attach all your logos in one zip file and open one issue for all those logo change/update request.

**Comment by ghost** [comment]
[Kanal K Logos.zip](https://github.com/picons/picons/files/13694619/Kanal.K.Logos.zip)
