### ISSUE TITLE
radiobasilisk=radiobasilisk

### ISSUE THREAD

**Issue by ghost** [picons/picons#1912]
radiobasilisk=radiobasilisk
basilisk=radiobasilisk

[logos.zip](https://github.com/picons/picons/files/13694022/logos.zip)

![radiobasilisk default](https://github.com/picons/picons/assets/35585833/c7092ffb-c00e-4684-8169-f208205f4ca8)

![radiobasilisk light](https://github.com/picons/picons/assets/35585833/762ac568-7f3f-47cb-aa87-057bf8a6a9a5)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1719#issuecomment-1836993100_

**Comment by AbuBaniaz** [comment]
Why have you uploaded two zip files? Zip the folder with both images, attach the one zip file. Do not attach the images, just the zip file.

**Comment by ghost** [comment]
one zip file now

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/f413d05f7da8ac435b3b954b6f6b3711d5862413
