### ISSUE TITLE
Country Radio Switzerland

### ISSUE THREAD

**Issue by ghost** [picons/picons#1919]
Country Radio Switzerland
Logo correction

[countryradioswitzerland.default.svg.zip](https://github.com/picons/picons/files/13699162/countryradioswitzerland.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1783#issuecomment-1859492815_

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/c619bc76c7eeefad1389cbce17aab86e705576ea
