### ISSUE TITLE
diis Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1920]
diis Radio
Logo correction

[diis Radio Logo.zip](https://github.com/picons/picons/files/13699177/diis.Radio.Logo.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1784#issuecomment-1859494668_

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/c619bc76c7eeefad1389cbce17aab86e705576ea
