### ISSUE TITLE
They are 2 different channels and have been mixed up.

### ISSUE THREAD

**Issue by ghost** [picons/picons#1922]
They are 2 different channels and have been mixed up.

Radio 24 ORE 
https://www.radio24.ilsole24ore.com
radio24ore=radio24ore
[Logo Radio24 Ore.zip](https://github.com/picons/picons/files/13699273/Logo.Radio24.Ore.zip)

Radio 24
https://www.radio24.ch
radio24=radio241028
radio24fm1028=radio241028
[radio241028.default.png.zip](https://github.com/picons/picons/files/13699346/radio241028.default.png.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1834#issuecomment-1859511933_

**Comment by AbuBaniaz** [comment]
We have these two links. Only the first one will be made.  As mentioned before, you cannot have two identical snp names.  
`
radio24=radio24
`
`
radio24=radio241028
`


The 2 logos on this repository are:
https://github.com/picons/picons/blob/master/build-source/logos/radio24.default.png
https://github.com/picons/picons/blob/master/build-source/logos/radio241028.default.svg

 I want to fix this for you. What is the service reference for the channel we WANT  to build with the logo:
https://github.com/picons/picons/blob/master/build-source/logos/radio241028.default.svg

**Comment by AbuBaniaz** [comment]
Fixed here: https://github.com/picons/picons/commit/c619bc76c7eeefad1389cbce17aab86e705576ea
I used your lamedb file you uploaded.

**Comment by ghost** [comment]
Ok Thanks

Radio 24
546_D_1_FFFF0000=radio241028

Radio 24 Ore
64D_F_1_FFFF0000=radio24

**Comment by AbuBaniaz** [comment]
Irrelevant posts. discussion closed.
