### ISSUE TITLE
Kanal K

### ISSUE THREAD

**Issue by ghost** [picons/picons#1928]
Kanal K
kanalk=kanalk

[Kanal K Logos.zip](https://github.com/picons/picons/files/13708776/Kanal.K.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1792#issuecomment-1861708895_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/cf3adf667e36a96cd861f04131238e0deb9a2689
