### ISSUE TITLE
Jam on Radio

### ISSUE THREAD

**Issue by ghost** [picons/picons#1929]
Jam on Radio
jamonradio=jamonradio

Logo correction
[Jam on Radio Logos.zip](https://github.com/picons/picons/files/13708810/Jam.on.Radio.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1790#issuecomment-1861721139_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/12d5187411a40da44fefea9a56421bdf67851b8e
