### ISSUE TITLE
Open Broadcast

### ISSUE THREAD

**Issue by ghost** [picons/picons#1930]
Open Broadcast
openbroadcast=openbroadcast

Logo correction
[Openbroadcast Logos.zip](https://github.com/picons/picons/files/13708923/Openbroadcast.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1798#issuecomment-1861757648_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/3f61e23a927bccca83d6ac97cf1a65dc106798d9
