### ISSUE TITLE
Radio Blind Power

### ISSUE THREAD

**Issue by ghost** [picons/picons#1931]
Radio Blind Power
radioblindpower=radioblindpower
blindpower=radioblindpower

Logo correction
[radioblindpower.default.svg.zip](https://github.com/picons/picons/files/13533117/radioblindpower.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1722#issuecomment-1836995475_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/fc602a932fb93a5cfe37288690821b1ad72cbab0
