### ISSUE TITLE
Radio Central

### ISSUE THREAD

**Issue by ghost** [picons/picons#1932]
Radio Central
radiocentral=radiocentral

Logo correction
[Radio Central Logos.zip](https://github.com/picons/picons/files/13708995/Radio.Central.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1723#issuecomment-1861767682_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/954adfc2bd7599441bf7247816f5ccc9b22c452c
