### ISSUE TITLE
Radio Jazz International

### ISSUE THREAD

**Issue by ghost** [picons/picons#1933]
Radio Jazz International
radiojazzinternational=radiojazzinternational

Logo correction
[Radio Jazz International Logos.zip](https://github.com/picons/picons/files/13709037/Radio.Jazz.International.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1732#issuecomment-1861776905_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/5e6e7557a087aeb84ab65c962c8726beeb54dd86
