### ISSUE TITLE
Radio Kaiseregg

### ISSUE THREAD

**Issue by ghost** [picons/picons#1934]
Radio Kaiseregg
radiokaiseregg=radiokaiseregg

Logo correction
[Radio Kaiseregg Logos.zip](https://github.com/picons/picons/files/13709056/Radio.Kaiseregg.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1733#issuecomment-1861780558_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/8bb5d3eb243dc54e426c343c92cb0d1f2a84a7be
