### ISSUE TITLE
Radio NRJ Alsace

### ISSUE THREAD

**Issue by ghost** [picons/picons#1935]
Radio NRJ Alsace 
radionrjalsace=radionrjalsace
radionrjf=radionrjalsace
radionrjleman=radionrjalsace

Logo correction
[Radio NRJ Alsace Logos.zip](https://github.com/picons/picons/files/13709093/Radio.NRJ.Alsace.Logos.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1804#issuecomment-1861786966_

**Comment by AbuBaniaz** [comment]
I take it you wanted to add a light version of the logo. However, the attached logos have the background grid included. Please try again.

Links are already present. No need to mention what we do not need to do/add. It just adds confusion.

**Comment by Lexzie** [comment]
Why not just use the `nrj` logo?

**Comment by AbuBaniaz** [comment]
My error or previous commit. The following two are more or less identical
https://github.com/picons/picons/blob/master/build-source/logos/nrj.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/radionrjalsace.default.svg

I take it he wanted to add a light version of the logo. I will change link the older logo

**Comment by AbuBaniaz** [comment]
@Lexzie, another one for your todo list. Can you create a light version of `nrj` when you get a chance please?

**Comment by Lexzie** [comment]
Yes, I can do that.
Later.

**Comment by Lexzie** [comment]
It will become f.e. one of these, which one will we choose?
![nrj light1](https://github.com/picons/picons/assets/14023349/c6955cd7-7d43-4a22-96c0-313f673a5bae)
![nrj light2](https://github.com/picons/picons/assets/14023349/b7c44c90-3f2b-47ab-9541-ba50fc6f0de5)
![nrj light3](https://github.com/picons/picons/assets/14023349/3f625cc6-db30-4f30-aab6-8d61a37579ee)
![nrj light4](https://github.com/picons/picons/assets/14023349/4ba5c4cd-4c1c-48ef-ac31-82bf134560a6)

**Comment by ghost** [comment]
Beim test auf meine Box wirkt nrj.light4.svg (view on web) <https://github.com/picons/picons/assets/14023349/4ba5c4cd-4c1c-48ef-ac31-82bf134560a6> bei schwarzer Hintergrund am besten.
Das ist aber nur meine Meinung.. ;-)

**Comment by Lexzie** [comment]
> Beim test auf meine Box wirkt nrj.light4.svg (view on web) <https://github.com/picons/picons/assets/14023349/4ba5c4cd-4c1c-48ef-ac31-82bf134560a6> bei schwarzer Hintergrund am besten. Das ist aber nur meine Meinung.. ;-)

Translation:
> Testing on my box is nrj.light4.svg with black background the best. But that is my opinion.. ;-)


What is your opinion @AbuBaniaz ?

**Comment by AbuBaniaz** [comment]
Number 4 for me.

**Comment by AbuBaniaz** [comment]
@Lexzie Pull request here: https://github.com/picons/picons/pull/1962

**Comment by AbuBaniaz** [comment]
I have added it here: https://github.com/picons/picons/commit/7d841a6f0540941a116c65b87f52f9702a5b2efe

**Comment by Lexzie** [comment]
@AbuBaniaz 
Sorry, had no time yesterday.
But it's all okay. 👍🏻
