### ISSUE TITLE
Radio Montecarlo I

### ISSUE THREAD

**Issue by ghost** [picons/picons#1937]
Radio Montecarlo I
radiomontecarlol=radiomontecarlol

Logo correction
[radiomontecarlol.default.svg.zip](https://github.com/picons/picons/files/13709138/radiomontecarlol.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1738#issuecomment-1861799277_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/b6b42eb3debdab7cec2f14d4b891ff48d4ed600d
