### ISSUE TITLE
Radio Südostschweiz

### ISSUE THREAD

**Issue by ghost** [picons/picons#1938]
Radio Südostschweiz
radiosudostschweiz=radiosudostschweiz

Logo correction
[radiosudostschweiz.default.svg.zip](https://github.com/picons/picons/files/13709176/radiosudostschweiz.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1746#issuecomment-1861809247_

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/picons/picons/commit/24b46d395e2fb16bc51311d5aa3325a8fbe275b3
