### ISSUE TITLE
Radio Ticino

### ISSUE THREAD

**Issue by ghost** [picons/picons#1939]
Radio Ticino
radioticino=radioticino

Logo correction
[radioticino.default.svg.zip](https://github.com/picons/picons/files/13709192/radioticino.default.svg.zip)

**Comment by AbuBaniaz** [comment]
The black text looks better than the grey one to me.

The links are already present. Please do not mention what we do not need to do/change.

**Comment by Lexzie** [comment]
A black-and-white logo will just be inverted, so this will be the light logo:
_Ein Schwarz-Weiß-Logo wird einfach invertiert, sodass dies das 'light'-Logo ist:_
![radioticino light](https://github.com/picons/picons/assets/14023349/76318c45-a3f7-40ae-acfd-2e56b8815aa4)
@AbuBaniaz could you make a PR and squash and merge it?

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/698126e3fdc8e56ed4df5a73abc7250f08bccc40
