### ISSUE TITLE
Radio 4 TNG

### ISSUE THREAD

**Issue by ghost** [picons/picons#1940]
Radio 4 TNG
radio4tng=radio4tng
4tng=radio4tng

Logo correction
[radio4tng.default.svg.zip](https://github.com/picons/picons/files/13709203/radio4tng.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1715#issuecomment-1861817096_

**Comment by AbuBaniaz** [comment]
The links are already present. Please do not mention/say what we do not need to change/add.

The black text looks better than the grey to me.  Please feel free to add a light version if you want.

**Comment by ghost** [comment]
Light version would be good because it looks terrible on me with a black background. 
Thanks

**Comment by AbuBaniaz** [comment]
Light variant of logo added here: https://github.com/picons/picons/commit/c038866b0e1cb5e1cd95dfd721613128b2c5210e

We now have:
https://github.com/picons/picons/blob/master/build-source/logos/radio4tng.light.svg

and

https://github.com/picons/picons/blob/master/build-source/logos/radio4tng.default.svg

See here:
https://github.com/picons/picons/blob/master/CONTRIBUTING.md
