### ISSUE TITLE
Radio Beograd

### ISSUE THREAD

**Issue by ghost** [picons/picons#1942]
# SNP/SRP entries

**snp.index**
```
radiobeograd=radiobeograd
```

**srp.index**
```
708_C_1_FFFF0000=radiobeograd
```
logos.zip

[radiobeograd.default.svg.zip](https://github.com/picons/picons/files/13709413/radiobeograd.default.svg.zip)

```

 Better Logo

**Comment by Lexzie** [comment]
The current logo is small, but this logo isn't better.

**Comment by Lexzie** [comment]
Furthermore, this is an old logo. The station is rebranded to Radio Beograd 1.
www.radiobeograd.rs/
Do some research instead of just converting the existing logos.

**Comment by AbuBaniaz** [comment]
We have this logo already. Shall we change links to point to it
https://github.com/picons/picons/blob/master/build-source/logos/rtsradiobeograd1.default.png

**Comment by Lexzie** [comment]
There were just two (unused?) links left:
```
radiobeograd=radiobeograd
```
```
49B_36_DE_FFFF0000=radiobeograd
```

Look at [logopedia](https://logos.fandom.com/wiki/Radio_Belgrade_1) for the change from Radio Beograd to Radio Beograd 1 and changes of logo.

**Comment by AbuBaniaz** [comment]
If OK, please merge https://github.com/picons/picons/pull/1958
