### ISSUE TITLE
Radio Tell

### ISSUE THREAD

**Issue by ghost** [picons/picons#1959]
Radio Tell 
radiotell=radiotell
596_D_1_FFFF0000=radiotell

Logo corrected
[radiotell.default.svg.zip](https://github.com/picons/picons/files/13719118/radiotell.default.svg.zip)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1749#issuecomment-1863277886_

**Comment by AbuBaniaz** [comment]
We have received 2 emails from you. Which one do you want us to process? What do you want us to add/change.

You have included  the sevicr references, they are already present, what do you want us to do with them? 

Respond in your native language.

**Comment by ghost** [comment]
Das aktuellste was ich heute noch hinzugefügt habe ist relevant.

Das war auch vorläufig das letzte. Dann lasse ich mal zeit vergehen…
Ich danke euch.

**Comment by AbuBaniaz** [comment]
![william richards](https://github.com/picons/picons/assets/6644489/7a918079-c053-4551-b7a7-8af738fc068e)
You sent two issues. Issues 1959 and 1749. I am going to ignore issue 1749.

Sie haben zwei Ausgaben gesendet. Ausgaben 1959 und 1749. Ich werde Ausgabe 1749 ignorieren.

![william richards 2](https://github.com/picons/picons/assets/6644489/fcd37d55-ade5-4636-9ebe-6178b69d39b7)
The link is already there. There is no other snpname of `radiotell`
Der Link ist bereits vorhanden. Es gibt keinen anderen Snp-Namen für "radiotell"

So what do you want do you do with the link you posted? Do you want us to delete/change the existing one?
Was willst du also mit dem Link machen, den du gepostet hast? Möchten Sie, dass wir das bestehende löschen/ändern?

If we don't have to do anything with the reference, that part of your post is irrelevant.
Wenn wir nichts mit der Referenz zu tun haben, ist dieser Teil Ihres Beitrags irrelevant.

Most people will just say:
I have found a better logo. Can you please replace the existing ones with the one I have attached. 
Ich habe ein besseres Logo gefunden. Können Sie bitte die vorhandenen durch die ersetzen, die ich beigefügt habe.

There is no need to mention anything that we do not need to do or change.
Es ist nicht nötig, irgendetwas zu erwähnen, was wir nicht tun oder ändern müssen.

**Comment by AbuBaniaz** [comment]
![william richards 3](https://github.com/picons/picons/assets/6644489/f520c7b7-7a11-4503-b17c-3e20f1607162)
This is the other comment you made.
Dies ist die andere Bemerkung, die Sie gemacht haben.

**Comment by ghost** [comment]
Ja, schau das logo an. Ich denke das ist wirklich das beste egal auf welcher Hintergrund.

**Comment by AbuBaniaz** [comment]
I have replaced the logo here:
Ich habe das Logo hier ersetzt:
https://github.com/picons/picons/commit/506df3f3bae514e33fb885efe134f5dcc31be124

You will have to wait for the picon on the plugin server of your image to be updated to see it.
Sie müssen warten, bis das Picon auf dem Plugin-Server Ihres Bildes aktualisiert wurde, um es zu sehen.
