### ISSUE TITLE
Fixes to Movistar+ ENERGY and M+LCAMPEON2

### ISSUE THREAD

**Issue by miberian** [picons/picons#1987]
These channels are showing the wrong picon. Changes required:

# SNP/SRP entries

**snp.index**
```
7889_414_1_C00000=energy
749E_41C_1_C00000=movistarligadecampeones2
```

**srp.index**
```
7889_414_1_C00000=energy
749E_41C_1_C00000=movistarligadecampeones2
```

I have temporarily fixed the issue by deleting the following files in my receiver, so I believe snp entries should be removed instead:

1_0_1_749E_41C_1_C00000_0_0_0.png
1_0_1_7889_414_1_C00000_0_0_0.png

**Comment by AbuBaniaz** [comment]
In the snp.index file ,we have these entries

```
7889_414_1_C00000=nationalgeographicwild
749E_41C_1_C00000=boing-tramufrasw
```

If we delete them, will that be fine? we only put in service references when there are clashes/differences or multiple channels with the the same name.

**Comment by AbuBaniaz** [comment]
To answer my question, deleting the service reference entries in snp file will fix the issue.
Done here: https://github.com/picons/picons/commit/5154bd7bd32948460adf23f0e26c34c3bd5778fc
