### ISSUE TITLE
New logo for SR 1

### ISSUE THREAD

**Issue by Dimi247TV** [picons/picons#1989]
Hello there, 
SR1 has since few days a new logo.
![416532158_1096073305067760_2368749879026464531_n(1)](https://github.com/picons/picons/assets/122408352/e6b76f77-baf7-45dc-8e21-53102fa11e0c)

**Comment by AbuBaniaz** [comment]
Can you please attach the logos in a zip file and we will replace them. SVG format or good quality png. Thanks.
