### ISSUE TITLE
TV LUX Slovakia refreshed logo

### ISSUE THREAD

**Issue by mac84mac** [picons/picons#1992]
# SNP/SRP entries

**snp.index**
```
tvluxhd=tvluxhd

```

**srp.index**
```

766E_2BF_600_E080000=tvluxhd

4B2_76C1_16E_A00000=tvluxhd

1F4E_CA1_3_EB0000=tvluxhd

177F_AF6_BB_E080000=tvluxhd

7A54_2CB_600_E080000=tvluxhd

```

# Logos

```
[TV LUX 2024.zip](https://github.com/picons/picons/files/13844717/TV.LUX.2024.zip)
```

**Comment by Lexzie** [comment]
Why link in snp.index to `tvlux` and in srp.index to `tvluxhd`?
Use underscores instead of semicolons in sro.index.

I Have not looked at the logo on TV yet, and can not open your zip file on my cell phone, so I don't know yet if the logo you supply is correct.

**Comment by mac84mac** [comment]
Hi Lexzie, I corrected the mistakes.
This channel now uses a new logo with only the L on screen and full LUX plus Televizia underneath depending where is used (screen, website, magazines).
Personally I would use L or eventually LUX, for sure without televizia. They have an inverted version where the L is on solid background instead within a frame.
But I leave the link with vectorial and pdf content so you and others more expert can judge, maybe some are more suitable with transparent and other with black picons version.
Personally I would use the full background for the L as used on TV like "LUX_ČIERNE priehladne_inverzne.png"
https://www.tvlux.sk/pre-media

Thank You and a Happy New Picon Year!

**Comment by Lexzie** [comment]
Next time please no blanc line between the links.

**Comment by AbuBaniaz** [comment]
If this is resolved, can we close please?

**Comment by mac84mac** [comment]
Sorry, I'm new to this I have to learn. Thank You!
