### ISSUE TITLE
RTV Maastricht HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2010]
# SNP/SRP entries

**snp.index**
```
rtvmaastricht=rtvmaastricht
rtvmaastrichthd=rtvmaastricht
```

**srp.index**
```
4097_0_1_DED9_5B52_EC_0_0_0_0=rtvmaastricht
```

[rtvmaastricht.default.svg.zip](https://github.com/picons/picons/files/13966146/rtvmaastricht.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
This has been done. 

Please resize "page to selection" in inkscape before you submit the logos for future issues.
