### ISSUE TITLE
New logo for some Nordic channels at Warner Bros. Discovery

### ISSUE THREAD

**Issue by roberi** [picons/picons#2020]
# Logos

[logos.zip](https://github.com/picons/picons/files/13999230/logos.zip)

These channels have new logos as of January 15, 2024:

- Denmark: Kanal 5, 6’eren, Kanal 4, and Canal 9
![image](https://github.com/picons/picons/assets/10847866/fb9b41ef-a4ef-4418-9afe-324e7ffd8de7)
- Finland: TV5, Kutonen, and Frii
![image](https://github.com/picons/picons/assets/10847866/392c564f-e389-4676-af4f-6d805da06cee)
- Sweden: Kanal 5, Kanal 9, and Kanal 11
![image](https://github.com/picons/picons/assets/10847866/66fcc295-f694-4867-bb74-dab3a5912eb8)
- Norway: TVNorge, MAX, FEM, and VOX
![image](https://github.com/picons/picons/assets/10847866/48495bdc-5d87-4c7c-8ac3-119992de48ee)

Since the new logos look good with both dark and light backgrounds, I think these old variants should be deleted:

- kanal9.light.svg
- tvnorgehd.default.svg
- tvnorgehd.light.svg

(EDIT: I have updated the zip file with "cleaned" SVG files as per instructions in the wiki.)

**Comment by AbuBaniaz** [comment]
Is there an updated `kanal10-cricroclot.default.png`

**Comment by Lexzie** [comment]
> Is there an updated `kanal10-cricroclot.default.png`

No, TV10 hasn't changed.
