### ISSUE TITLE
DAZN FAST HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2022]
# SNP/SRP entries

**snp.index**
```
daznfast=daznfast
daznfasthd=daznfast
```

**srp.index**
```
29F_D1F4_0_0_0_0_0=daznfast
```
[daznfast.default.svg.zip](https://github.com/picons/picons/files/13999460/daznfast.default.svg.zip)

```

I could only find this logo, maybe it needs to be edited?

**Comment by Lexzie** [comment]
> # SNP/SRP entries
> 
> **snp.index**
> 
> ```
> daznfast=daznfast
> daznfasthd=daznfast
> ```
> 
> **srp.index**
> 
> ```
> 4097_0_1_29F_D1F4_0_0_0_0_0=daznfast
> ```
> 
> [daznfast.default.svg.zip](https://github.com/picons/picons/files/13999460/daznfast.default.svg.zip)
> 
> ```
> 
> I could only find this logo, maybe it needs to be edited?
> ```

You've come from far but aren't there yet.
You should have left out the first and last three digitits (and the underscores) of the service reference.
So, it should have been:
```
29F_D1F4_0_0=daznfast
```

I'll clean the logo for you.

The letter `DAZN` are grey, is that correct? (In other DAZN logos they are white).

**Comment by ghost** [comment]
Ok danke :-)

**Comment by Lexzie** [comment]
How about answering this question? _Wie wäre es mit der Beantwortung dieser Frage?_
> 
> The letters `DAZN` are grey, is that correct? (In other DAZN logos they are white).
> _Die Buchstaben „DAZN“ sind grau, ist das richtig? (In anderen DAZN-Logos sind sie weiß)._

**Comment by ghost** [comment]
Nein, alle Logos die ich von Daten gesehen habe sind immer schwarz / weis Von meinem iPhone gesendetAm 21.01.2024 um 01:52 schrieb Alex ***@***.***>:﻿
How about answering this question? Wie wäre es mit der Beantwortung dieser Frage?

The letters DAZN are grey, is that correct? (In other DAZN logos they are white).
Die Buchstaben „DAZN“ sind grau, ist das richtig? (In anderen DAZN-Logos sind sie weiß).

**Comment by Lexzie** [comment]
I changed to logo and removed the invalid srp-links.
If you use snp picons you don't need them.
