### ISSUE TITLE
DAZN RISE HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2023]
# SNP/SRP entries

**snp.index**
```
daznrise=daznrise
daznrisehd=daznrise
```

**srp.index**
```
29F_D1F5_0_0_0_0_0=daznrise
```
[daznrise.default.svg.zip](https://github.com/picons/picons/files/13999470/daznrise.default.svg.zip)

```
I could only find this logo, maybe it needs to be edited?

**Comment by Lexzie** [comment]
In this logo everything is grey not white. Is that really the right color?

**Comment by ghost** [comment]
Nein das sollte weiss sein.
