### ISSUE TITLE
New Nickjr & NickjrToo logos UK

### ISSUE THREAD

**Issue by yannydodo12** [picons/picons#2052]
# SNP/SRP entries

**snp.index**
```
No change
```

**srp.index**
```
No change 
```

**Comment by yannydodo12** [comment]
[Nick channels UK.zip](https://github.com/picons/picons/files/14273881/Nick.channels.UK.zip)

**Comment by Lexzie** [comment]
On Logopedia the 'HD' and the '+1' are yellow, are they white on the screen?
And if white, make a 'dark' variant with black 'HD' and '+1'.
(Choosing yellow would be easy, only a default logo is enough).

![afbeelding](https://github.com/picons/picons/assets/14023349/93297021-b82c-4f2a-bd51-8f0041ed6c3f)

![afbeelding](https://github.com/picons/picons/assets/14023349/819c3f0a-8710-42f0-91b3-19ef473fe426)

**Comment by yannydodo12** [comment]
White onscreen..
No hd logo onscreen
I got them from the sky tv guide site..
The plus 1 looks different onscreen lol
Guess I should've checked first..

**Comment by yannydodo12** [comment]
https://static.wikia.nocookie.net/logopedia/images/6/68/Nick_Jr._%2B1_Splat_2.png/revision/latest/scale-to-width-down/250?cb=20240212193544

**Comment by Lexzie** [comment]
There is a variant for the '+1' logo, doesn't need a dark-variant either.
![afbeelding](https://github.com/picons/picons/assets/14023349/851d3537-619c-4b52-a065-0581aab2e7cc)

**Comment by yannydodo12** [comment]
Now I'm wondering did they change on other sats as well..
Will check in the morning..

**Comment by Lexzie** [comment]
In the meantime I checked 0.8W, 13E, 19.2E and 23.5E. I have seen Nick Jr. Hungary, Czech, Romania, Polska, Benelux, Deutschland, España. All have changed.

**Comment by yannydodo12** [comment]
> In the meantime I checked 0.8W, 13E, 19.2E and 23.5E. I have seen Nick Jr. Hungary, Czech, Romania, Polska, Benelux, Deutschland, España. All have changed.

Probably end up like Nickelodeon, some might be different lol

**Comment by yannydodo12** [comment]
Can add 16E, 39E, 45E to the list as well..

**Comment by Lexzie** [comment]
I think it's save to say all Nick Jr. channels use the "splash"-logo.

**Comment by Lexzie** [comment]
Are Nick Jr. Peppa Pig, Nick Jr. Paw Patrol and Nick Spongebob still used?
If you're able to, can you check the logo?

**Comment by yannydodo12** [comment]
> Are Nick Jr. Peppa Pig, Nick Jr. Paw Patrol and Nick Spongebob still used? If you're able to, can you check the logo?

No their not being used as far as I can see, but sky UK does change to them now and again..

**Comment by Lexzie** [comment]
If they appear we'll will make the changes if those logos have changed too.
No need to do more work than necessary.

I guess this issue can be closed.
