### ISSUE TITLE
Getting a svg logo out of this

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#207]
I keep getting black on the foreground (with Inkscape).
I even tried editing with Notepad++ but that doesn't matter.
This is the file after editing with Notepad++: 
[radiorock.default.svg.zip](https://github.com/picons/picons/files/4662618/radiorock.default.svg.zip)

This is the source: https://listenapi.s3.amazonaws.com/img/ConfigWebHeaderLogoSVGImageUrl/166.svg?ver=1493037971

Result have to be like this:
![afbeelding](https://user-images.githubusercontent.com/14023349/82562835-4c7e1900-9b76-11ea-8c71-f73a85180a20.png)

**Probably the same goes for these logos:**
https://listenapi.s3.amazonaws.com/img/ConfigWebHeaderLogoSVGImageUrl/169.svg?ver=1490107670
https://listenapi.s3.amazonaws.com/img/ConfigWebHeaderLogoSVGImageUrl/170.svg?ver=1504696854

**Comment by TheLegoBatman** [comment]
Try this one.
[radiorock.default.zip](https://github.com/picons/picons/files/4663259/radiorock.default.zip)

The other two seem fine.

**Comment by Lexzie** [comment]
Thank you. Will be added later.
