### ISSUE TITLE
A couple of 'index' changes for UK channels

### ISSUE THREAD

**Issue by tbgreen** [picons/picons#2087]
# SRP entries

**srp.index**
```
8540_800A_233A_EEEE0000=legendxtra
8200_800A_233A_EEEE0000=pop
8240_800A_233A_EEEE0000=popmax
3FEC_3006_233A_EEEE0000=togethertv
```

I hope I have done this correctly. No new entries required in snp.index file and no new logo files, just a change to the srp.index file.

**Comment by AbuBaniaz** [comment]
>I hope I have done this correctly. 

Perfectly done. Thank you.
