### ISSUE TITLE
QAM Dolby Test

### ISSUE THREAD

**Issue by ghost** [picons/picons#2116]
# SNP/SRP entries

**snp.index**
```
qamdolbytest=qamdolbytest
```

**srp.index**
```
1_0_19_25E2_13_1_FFFF0000_0_0_0=qamdolbytest
```

[logos.zip](https://github.com/picons/picons/files/14827739/logos.zip)

```

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/056ae5d0dbac252bedc7b4816f7b43220ea0b7f8

Made no sense using that logo name, so I changed it to "dolby digital".
