### ISSUE TITLE
Sky Cinema Highlights & Warner TV Comedy missing

### ISSUE THREAD

**Issue by nicoh88** [picons/picons#2158]
Thanks <3

**Comment by Lexzie** [comment]
Well, that's a fine contribution.
No logos to add, or a link to one.
No links to add or change.

**Comment by nicoh88** [comment]
> Well, that's a fine contribution. No logos to add, or a link to one. No links to add or change.

Sorry, my mistake!

**Sky Cinema Highlights**
Logo: https://de.wikipedia.org/wiki/Datei:Sky_Cinema_Highlights_Logo_2024.svg

```
Index	PID	Type	Language	Details
 	0x00ff /   255	PCR	 	 
 	0x0060 /    96	PMT	 	 
1	0x00ff /   255	H264	 	 
2	0x0103 /   259	AC3	ger	 
3	0x0104 /   260	AC3	eng	 
4	0x1ad3 /  6867	CA	 	CAIDS: 098c:000000
5	0x1bd3 /  7123	CA	 	CAIDS: 09c4:000000
6	0x1fd3 /  8147	CA	 	CAIDS: 09f0:000000
7	0x1cd3 /  7379	CA	 	CAIDS: 098d:000000
```

**Warner TV Comedy**
Logo: https://de.wikipedia.org/wiki/Warner_TV_Comedy#/media/Datei:WarnerTV_Comedy_Logo_2021.svg

```
Index	PID	Type	Language	Details
 	0x0eff /  3839	PCR	 	 
 	0x006e /   110	PMT	 	 
1	0x0eff /  3839	H264	 	 
2	0x0f03 /  3843	AC3	ger	 
3	0x0f04 /  3844	AC3	eng	 
4	0x1b77 /  7031	CA	 	CAIDS: 09c4:000000
5	0x1a77 /  6775	CA	 	CAIDS: 098c:000000
6	0x1c77 /  7287	CA	 	CAIDS: 098d:000000
7	0x1f77 /  8055	CA	 	CAIDS: 09f0:000000
```

**Comment by Lexzie** [comment]
That are not service references.
Please use the links as explianed in the guidelines.
https://github.com/picons/picons/blob/master/CONTRIBUTING.md

There are even examples as you make an issue.

**Comment by nicoh88** [comment]
**srp.index**
6F_D_85_C00000=skycinemahighlights
88_B_85_C00000=warnertvcomedy

**snp.index**
skycinemahighlights=skycinemahighlights
warnertvcomedy=warnertvcomedy

**Logos**
[Logos.zip](https://github.com/picons/picons/files/15181118/Logos.zip)

**Comment by Lexzie** [comment]
I think this is done.

**Comment by nicoh88** [comment]
> I think this is done.

I tested it this morning and it works! Thanks

**Comment by Lexzie** [comment]
Right now I am checking all of Astra 1.
