### ISSUE TITLE
Sportdigital Fussball HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2167]
# SNP/SRP entries

**snp.index**
```
sportdigitalfussball=sportdigitalfussball
sportdigitalfussballhd=sportdigitalfussball
```

# Logos

```
[sportdigitalfussball_default.png.zip](https://github.com/picons/picons/files/15228774/sportdigitalfussball_default.png.zip)

```

**Comment by AbuBaniaz** [comment]
There is no attachment.

Did you want us to change the existing snp links?

**Comment by Lexzie** [comment]
And strip the prefixes (1_0_19_ and 4097_0_19_) and suffixes (_0_0_0)!

Filenaming is wrong, should have been sportdigitalfussball.default.png (not a _ !)
But the logo is 400x100. Let's wait until a better logo is available, which probably will soon.
