### ISSUE TITLE
Sportdigital Fussball 2 HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2168]
# SNP/SRP entries

**snp.index**
```
sportdigitalfussball2=sportdigitalfussball2
sportdigitalfussball2hd=sportdigitalfussball2


# Logos

```
[sportdigitalfussball2.default.svg.zip](https://github.com/picons/picons/files/15410361/sportdigitalfussball2.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
No attachment

**Comment by ghost** [comment]
Beim letzten update ist nur Sportdigital Fussball  HD und Sportdigital Fussball Scooore  HD dabei.
Sportdigital Fussball 2 HD fehlt...

**Comment by AbuBaniaz** [comment]
Nobody has done anything about this issue.

1. Your attachment was missing.
2. You edited the post to add attachment, you did not say anything, so nobody knew that you had corrected it.
3. The png files is 400x118, so we are not going to use it.

**Comment by ghost** [comment]
Ich habe jetzt das logo verändert

**Comment by AbuBaniaz** [comment]
Thank you. Added here:
https://github.com/picons/picons/commit/96f9dac293bb21c4fcd51dc8f41f2a014ac1fee6
