### ISSUE TITLE
Wiki enhancement for svg cleanup

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#2258]
Hey there,

at first... thx for this great project.
briefly about me. I'm a webdesigner/developer and I use this tool https://svgomg.net to cleaning up svg for my and other project like yours. the advantage...you don't need to install an extra software locally.

The usage is easy. You can paste the svg markup directly or upload the svg file.
Here are the setting I use for your project.
![svgomg-global-settings](https://github.com/picons/picons/assets/6202293/264d10f0-a293-4e6b-a63f-31dda1f8512b)
![svgomg-feature-settings](https://github.com/picons/picons/assets/6202293/824b6ea6-caf4-407d-bed0-8cdb33c05153)

It would be nice if you could add it to your wiki.
Feel free to ask me if you need more infos

thx

**Comment by Lexzie** [comment]
Added
https://github.com/picons/picons/wiki
