### ISSUE TITLE
28.2 E srp.index update & new Logos 

### ISSUE THREAD

**Issue by leec32** [picons/picons#226]
**srp.index**

```
FA6_7EE_2_11A0000=whd
F82_7EE_2_11A0000=tlchd
FC5_7E3_2_11A2F26=vice
EE7_7EE_2_11A0000=skycinemagreatshd
F3C_7EE_2_11A0000=skycinemadisneyhd
EE8_7EE_2_11A0000=skycinemadramahd
13BA_7E3_2_11A2F26=movies24
E2A_7EE_2_11A0000=animalplanethd
E29_7EE_2_11A0000=boomeranghd

```

If someone would have time and wouldn't mind making logos for the 2 new sky channels and the 2 updated history channels please, i have no idea how to do it myself or i would.

142D_7F1_2_11A0000=skynaturehd
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb1165.png

1410_7D3_2_11A0000=skydocumentarieshd
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb1136.png

F2E_7EC_2_11A0000=skyhistoryhd
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb4086.png

144B_7F1_2_11A0000=skyhistory2hd
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb1195.png

I did check first and couldn't find them.

Thanks

**Comment by AbuBaniaz** [comment]
Jasmeet keeps the logos on his repo upto date. The ones he calls `dark` are our `default`, and the others are `light`

https://github.com/Jasmeet181/mediaportal-uk-logos

**Comment by leec32** [comment]
[logos.zip](https://github.com/picons/picons/files/4741454/logos.zip)


OK, Thanks, I didn't know that.

Can you check i have done this correct, Thanks 

These are just dark added in the zip, do i need to add light also, if i am wanting to use light, and do i need to end them with default.png and light.png

**Comment by AbuBaniaz** [comment]
That is not quite right, you are missing the `default` in the names.  He has light versions as well, so you should have added those too.

As the logos have been added, I will close the issue now.  Just need to add the snp links

**Comment by leec32** [comment]
Ok, will remember for next time, thanks
