### ISSUE TITLE
16e update required

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons#2306]
We have  the following missing SNP entries for 16e. I can't receive 16e so can't check

```
bih007
digitalb20vjet
esportslegend
gokitzstv
htv4hd
klasik
mcn24
mcntv
mymusic
premiumhd
pro1
realitykingshd
senemedia
sk1hrhd
sk1slohd
tvslo1hd
tvsonce
tvcg3
tvrmoldova
tvrsporthd
x1
zjarrtv
```

Anybody able to have a look please?

Lamedb here
[16e files.zip](https://github.com/user-attachments/files/16354853/16e.files.zip)

Output from `missing picons` here
[missing-picons_2024-07-23_22-13-19.zip](https://github.com/user-attachments/files/16354856/missing-picons_2024-07-23_22-13-19.zip)

**Comment by Lexzie** [comment]
I can give it a go.

**Comment by Lexzie** [comment]
As I see a lot of the logos we already have. I just have to assign it to the name and service reference.
I also scanned all frequencies (a few were missing in the lamedb) and will do all of 16E in one PR.
Some logos I maybe can create since they are not to be found on the internet in a acceptable format and quality.
I just created X1, be patience, it takes time.
But if anyone could find logos like `ESports Legend`, `ESport 24`, `myMusic` and perhaps some more, it would help.
If I can't find or make them (or too much work): Too bad, no logo.

I am not going to assign `11512hsid0x14` etc. to a logo.
It's an error in scanning, don't know what causes it and how to scan the transponders correctly.
They'll just have to be renamed to:
```
11512H SID 0x14  >  RTL Living.
11512H SID 0x15  >  RTL Kockica.
11512H SID 0x1e  >  National Geographic Channel.
11512H SID 0x1f  >  Nat Geo Wild.
11512H SID 0x2c  >  BBC Earth.
11512H SID 0x2f  >  Cinestar Fantasy.
11512H SID 0x30  >  Nickelodeon HR.
11512H SID 0x32  >  Disney.
11512H SID 0x33  >  Cartoonito.
11512H SID 0x34  >  Baby TV.
11512H SID 0x35  >  Cartoon Network.
11512H SID 0x3c  >  Epic Drama.
11512H SID 0x3d  >  STAR Life.
11512H SID 0x3e  >  STAR Crime.
11512H SID 0x42  >  11512H SID 0x42
11512H SID 0x46  >  Disney Junior.
11512H SID 0x49  >  NickJr CRO.
11512H SID 0x6c  >  Arena Sport 3 HD.
11512H SID 0x96  >  Jugoton TV.
11512H SID 0x9a  >  Aurora TV.
11512H SID 0xd9  >  MAXSport 1.

11595H SID 0x21  >  History Channel.
11595H SID 0x29  >  M1 Gold.
11595H SID 0x43  >  BrazzersTV.
11595H SID 0x50  >  MAXSport 2.
11595H SID 0x51  >  Arena Sport 7 HD.
11595H SID 0x5d  >  Extreme Sports.
11595H SID 0x64  >  HRT2 HD.
11595H SID 0x67  >  Z1
11595H SID 0x78  >  CMC - Croatian Music Channel.
11595H SID 0x7e  >  MTV 80s.
11595H SID 0x81  >  Da Vinci Learning.
11595H SID 0x8c  >  CNN.
11595H SID 0x98  >  STAR Movies.
11595H SID 0x9b  >  TVCG MNE.
11595H SID 0x9c  >  Radio CG.
11595H SID 0xa6  >  RTL Passion.
11595H SID 0xc0  >  RTL Crime.
11595H SID 0xc1  >  Vivid Touch.
11595H SID 0xc3  >  PrivateTV.
11595H SID 0xc5  >  STAR Channel.
11595H SID 0xc9  >  Otvoreni.
11595H SID 0xca  >  bravo!.
11595H SID 0xcb  >  Antena Zagreb.
11595H SID 0xd3  >  R.Marija.
11595H SID 0xd4  >  Happy FM.
11595H SID 0xda  >  R. Mediaservis
11595H SID 0xdb  >  Enter ZG.
11595H SID 0xdf  >  Radio Rovinj.
```
In the lists are also included data-services, we are not linking logos to data-services.

**Comment by Lexzie** [comment]
Logos I can't find so far:

ESport 24
ESports Legend
my Music
my Music Radio
Zjarr TV
(DigitAlb) Gold

And what is `DigitAlb   20 Vjet`. According to Lyngsat (DigitAlb) Family should be on that SID.
If the channel is changed I suppose this is the logo?
![1704049696694](https://github.com/user-attachments/assets/0f65c19f-b506-4245-a199-34852726c939)

**Comment by AbuBaniaz** [comment]
I don't have access to that satellite. The lamedb was from someone else who performed a blind scan for me. So the errors/issues may be from the blind scan binary.

Can we just focus on the 22 channels I listed above please?

**Comment by Lexzie** [comment]
The most work is finding the missing logos or making them.
And little spare time doesn't help either.

**Comment by Lexzie** [comment]
I could not find `BIH 007` and `Go-Kitz STV` in my scan, they are also not listed on Lyngsat or Flysat, probably feeds.

Still to do (if I can find or make the logo):
```
digitalb20vjet
esportslegend
mcn24
mcntv
mymusic
premiumhd
senemedia
zjarrtv
```
