### ISSUE TITLE
Miscreant files at top level of repo

### ISSUE THREAD

**Issue by wedebe** [picons/picons#2309]
Most likely just an accidental commit

-- | -- | --
uanddavejavu.default.png | Uktv 2 (picons#2294) | 2 weeks ago
uanddramaplus1.default.png | Uktv 2 (picons#2294) | 2 weeks ago
uandwplus1.default.png | Uktv 2 (picons#2294) | 2 weeks ago
uandyesterdayplus1.default.png | Uktv 2 (picons#2294) | 2 weeks ago

**Comment by AbuBaniaz** [comment]
Thanks
