### ISSUE TITLE
Search for logos Movistar+ COM ROM and Movistar+ Vacanciones

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#2318]
Examples, but we need much beter than these:
![MROMAN](https://github.com/user-attachments/assets/e95f0a4d-b4f1-41ca-94b5-247e5edc99be)

![afbeelding](https://github.com/user-attachments/assets/f13485ee-0ccf-4213-99ce-e1ac18f1ed3f)

**Comment by TheLegoBatman** [comment]
Here is the vacaciones.

[movistarvacaciones.zip](https://github.com/user-attachments/files/16550495/movistarvacaciones.zip)

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons/pull/2328

**Comment by Lexzie** [comment]
> #2328

Thanks, I was also "on vacanciones".
