### ISSUE TITLE
Fox & Fox Life new logos

### ISSUE THREAD

**Issue by Jglez3** [picons/picons#232]
# SNP/SRP entries

**srp.index**

Delete/modify:
```
7504_420_1_C00000=foxhd
78B5_3EC_1_C00000=foxlifehd
```

Add/replace:
```
7504_420_1_C00000=fox
78B5_3EC_1_C00000=foxlife
```

# Logos
Fox and Fox Life have new logos, here are the SVG files to replace the actual ones.

[fox.default.svg.zip](https://github.com/picons/picons/files/4752888/fox.default.svg.zip)
[foxlife.default.svg.zip](https://github.com/picons/picons/files/4752889/foxlife.default.svg.zip)

**Comment by TheLegoBatman** [comment]
The fox logo doesn't seem to have changed everywhere. I will add it and link it to that reference only for now.

Edit: Actually might be better to wait for other people to confirm this. There was probably a preference for the present coloured logos.

**Comment by Lexzie** [comment]
7504_420_1_C00000 is the (Spanish) Fox HD (746F_3F0_1_C00000 is the SD version).

But they don't use the HD logo on screen (anymore?):
![afbeelding](https://user-images.githubusercontent.com/14023349/85232984-b69f0d80-b403-11ea-9ae6-2638bedfeedd.png)

More Fox HD channel don't use the HD logo as far as I checked (checked Portugese, German, Dutch, Bulgaria).
So the question is would we get rid of separate logos for the HD and SD versions?
The Polish and the Serbian Fox (and Fox Life) channels still uses an HD-logo.
For now I think we leave it this way unless the logo is completely changed.

About the colour: The channel still uses an orange logo in leaders and f.e. on the Facebook or web pages: [Italy](https://www.facebook.com/foxtvnl/?brand_redir=133204090065163), [Dutch](https://www.facebook.com/foxtvnl/?brand_redir=172008316163648), [Sweden](https://www.foxtv.se/), [Norway](https://www.foxtv.no/), [Russian](https://www.foxtv.ru/).
  

The **Fox life** logo seems to be changed. I can't see the purple "textbaloon" anywhere anymore.
Not on channels, not on their websites.
![afbeelding](https://user-images.githubusercontent.com/14023349/85235423-fd493380-b414-11ea-9757-0ecde2edfaea.png)

But you have to consider that changing the logo means it will change for all countries unless we make two separate logos.

The [Portugal](https://www.facebook.com/37173152981/photos/10157410349267982/) Facebook page of FOXlife shows a coloured logo, so I would suggest we use that colour.
But we'd have to check the channel more to see if the colour is used in f.e. leaders.
