### ISSUE TITLE
TV Nova Czechia new logo

### ISSUE THREAD

**Issue by mac84mac** [picons/picons#2339]
# SNP/SRP entries
No need to change anything index files

# Logos

[Nova CZ 2024](https://github.com/user-attachments/files/16794866/Nova_CZ_2024.zip)

**Comment by mac84mac** [comment]
I didn't find a vectorial file for the HD version but is the same font as old logo, only the "o" has changed in the entire logo

**Comment by AbuBaniaz** [comment]
There is no attachment here.

**Comment by mac84mac** [comment]
[https://github.com/user-attachments/files/16794866/Nova_CZ_2024.zip](url)

**Comment by mac84mac** [comment]
[Nova CZ 2024](https://github.com/user-attachments/files/16794866/Nova_CZ_2024.zip)

**Comment by AbuBaniaz** [comment]
I don't fully understand what you want to achieve.

We have the following logos on this repository.

```
nova.default.svg
nova-clavecloha.default.svg
nova-duslelaslu.default.svg
novainternational.default.svg
novahd-duslelaslu.default.svg
```

Are you replacing any of these? If you are, please name the logos  you are are attaching to match the existing names. 
If you are adding extra logos, please name them as per our method.

Links:
Some of the links you mention already exist.  We do not need to add what is already present. When there are snp names that are same, we distinguish them by using service references in the snp index too.  Please supply what we need to add.

To avoid wasting time, you can submit a pull request.

**Comment by mac84mac** [comment]
No, there is no replacement, only the logo was recently slightly graphically updated, it needs to be updated, snps and srps are unchanged, if you compare the files I attached with the channels i posted, they are 3 channels: Nova, Nova HD and Nova International.
For Nova with HD I don't have vectorial file, maybe can be merged from old logo

**Comment by AbuBaniaz** [comment]
It sounds like we are just replacing the logos to me. But you are saying this is not the case.

**Comment by Lexzie** [comment]
These are the logos I guess? And in vector-format.

`nova-duslelaslu`
https://static.wikia.nocookie.net/logopedia/images/0/07/Nova_CZ_2024.svg

`novainternational`
https://static.wikia.nocookie.net/logopedia/images/4/4e/TV_Nova_International_(2024%252C_blue_box).svg


Oops, I reacted to fast. You already supplied the normal logos in vector format, but you said you didn't find the HD logo in vector format.
Looks like we can copy that from the current `novahd-duslelaslu` logo.
And is the Nova +1 HD logo still used? (`novaplus1hd`)

![afbeelding](https://github.com/user-attachments/assets/94f00b70-b7c7-496f-b7ce-99572346a52f)

**Comment by mac84mac** [comment]
Yes we are simply just replacing 3 logos for the channels in 1st post,  I would say we can copy from the current logo, the HD is the same in the same position, substantially only the "o" changed and colours
Nova +1 HD  is not used anymore since 2 years and not expected to come back

**Comment by AbuBaniaz** [comment]
I have replaced the two logos that were supplied

**Comment by mac84mac** [comment]
Perfect, I just ended editing the HD version with Inkscape, I didn't edited maybe 7 years but I'm still able to make simple edits :) 

![novahd2024](https://github.com/user-attachments/assets/28d38a69-9c0d-4056-8c7d-25244eaed7b0)

**Comment by Lexzie** [comment]
Great!

**Comment by mac84mac** [comment]
I don't know which requisites for logos are required, i set width to 600px, if something is wrong please edit before changing the old logo. Thank You.

**Comment by AbuBaniaz** [comment]
I have deleted the links from the post. It is useless information and removes  clarity. 
We only need to be told what to add/delete/replace.

**Comment by Lexzie** [comment]
For SVG size is irrelevant, but I use 800px mostly.
It is imported that the logo is cropped (but in this case because a background is part of the logo not important) and that the logo is saved as an optimized svg, see https://github.com/picons/picons/wiki/Cleaning-up-SVG-metadata

And what @AbuBaniaz said: Make a issue with only the information what is to be changed/added/deleted.
And supply the logos with the right filename.
See https://github.com/picons/picons/blob/master/CONTRIBUTING.md

**Comment by AbuBaniaz** [comment]
Do we delete this link?

novaplus1hd=novaplus1hd

**Comment by Lexzie** [comment]
Yes, and delete the logo (or archive it).

**Comment by mac84mac** [comment]
Ok thank you both for the info. I'm going to close this issue and open a new one, i noticed Jednotka and Dvojka dropped the HD logo, also on website is dropped.
Or should I rather submit a pull request for simply removing the HDs right?

**Comment by AbuBaniaz** [comment]
Submitting a pull request is best.

**Comment by Lexzie** [comment]
> Ok thank you both for the info. I'm going to close this issue and open a new one, i noticed Jednotka and Dvojka dropped the HD logo, also on website is dropped. Or should I rather submit a pull request for simply removing the HDs right?

Also make sure the links in srp.index and snp.index are changed when deleting a logo.
