### ISSUE TITLE
Max picon resolution supported by enigma2 ?

### ISSUE THREAD

**Issue by FlexMcMurphy** [picons/picons#2343]
Hello,

The picon lists on this GitHub repo come in pixel sizes like: 100x60; 220x132; 190x102.

When I look at 100x60 picons on my enigma2 image the resolution of the image is often pretty bad. Is it possible to get really high resolution picons to display in enigma2 or will that always be limited by the pixel dimensions?

Could I create a 1920x1080 picon and enigma2 would display that on my TV on screen display and give me a nice high resolution picon instead of the fuzzy out of focus look I often get?

Cheer,

Flex

**Comment by TheLegoBatman** [comment]
Hello. Why not choose a package that has higher quality picons! Also it's all dependent on the skin used anyway.

It's probably best that you enquire about this on the forum dedicated to whatever enigma2 image you use.

**Comment by Lexzie** [comment]
On our repo almost all logos are of high resolution. SVG-logos can get any resolution you want.
So the downsize of the logos is the work of your Enigma2 image who makes the picons.
I use f.e. 400x240 pixel logos which my image (OpenPLi) provides in their feed.
Our own releases indeed contain not that size...but I'm not the one who maintains that.

**Comment by AbuBaniaz** [comment]
Some images resize and some skins/images allow different sizes but insist that a specific folder is used. Some images allow SVG files but the system can slows down.

220x132 should be fine for you. Otherwise 400x240 which you can download from openpicons.com. Best you check the dimensions of picon space on your skin though.

You can build any resolution you want.

**Comment by FlexMcMurphy** [comment]
Thank you both for your responses.

@AbuBaniaz

I am using the MetrixHD skin. How do I know what picon sizes are supported? What do you mean: _"You can build any resolution you want too."_?

I notice I have a plugin called MyMetrixLite and in there I can set the skin resolution to 1920x1080 or 1280x720. Is that what you mean?

I have a ZGemmaH7S, 1GB of memory. I guess my system could handle higher resolution picons?

Flex

**Comment by FlexMcMurphy** [comment]
I tried the 220x132 pixel size picons on my ZGemma and they work but now I see that many 28.2E picons I need are missing from the latest set 220x132 set.

To update my question above...

1. How do I know what picon sizes are supported on MetrixHD on my OpenATV image running on a ZGemmaH7S?
2. Where can I find a blank `220x132-190x102.dark.on.reflection` image with no channel logo on it so I could make my own picon when one is not available in the set I downloaded? The latest `220x132-190x102.dark.on.reflection` set on GitHub has a lot of "blank" picons but the "Reflection" background is smaller than 220x132.
3. There seems to be an automated way of producing a new set of picons regularly to this GitHub repository but is there any human quality control checking what picons are missing or named incorrectly? If I make a picon that is missing how could I send that to you guys to add to the collection?

Cheers,

Flex

**Comment by Lexzie** [comment]
For any missing picons you can make an issue and please **use the template** and **read it carefully** what we need.

**Comment by FlexMcMurphy** [comment]
Ok I eventually figured out what you meant by a "template" and where the [template](https://github.com/picons/picons/tree/master/.github/ISSUE_TEMPLATE) is and also a blank "Reflection" [background](https://github.com/picons/picons/blob/master/build-source/backgrounds/220x132/reflection.png) image in the size I wanted that I had also asked about.

My only remaining question is:

1. How do I know what picon sizes are supported on MetrixHD on my OpenATV image running on a ZGemmaH7S?

Cheers,

Flex

**Comment by Lexzie** [comment]
Well if you just click on the button _New Issue_ and then on the button _Get started_, that's the template I meant.

**Comment by Lexzie** [comment]
> 
>     1. How do I know what picon sizes are supported on MetrixHD on my OpenATV image running on a ZGemmaH7S?
> 

Maybe ask the makers of the skin and the image?
Or just try what still works.
We are not involved in making skins and/or images.

**Comment by FlexMcMurphy** [comment]
I'm pretty sure @AbuBaniaz has experience with skins but it's OK I found out where to [ask the question](https://github.com/openatv/MetrixHD/issues/612).

Thank you for your help.

Flex

**Comment by AbuBaniaz** [comment]
Which picon types are you using? SNP or SRP? The SRP ones should be complete for 28.2.

The Sky almost weekly renames of Movie channels  are a chore and awkward to keep up with. Sometimes a channel changes name and back again the same day depending on what is on. If you are using SNPs you will have to download the logos and make them yourself. Try Kiddac E-piconizer's plugin which will do the for you. 

I  am not gong to waste my time on those. By the time a build is done, the channel changes name again.  I used to add the Service reference, but they were removed.

**Comment by FlexMcMurphy** [comment]
I don't have a Sky subscription so only use the Free to Air channels on Astra 28.2E.

I prefer to use SNP.

But many of the SRP are also missing.
I downloaded `enigma2-plugin-picons-snp-13e.19e.23e.28e.100x60-86x46.dark.on.reflection_2024-08-31--23-44-14_all` from GitHub.

Specifically:
Lots of the BBC radio stations, several from the "That's TV" channels, several from the "Great! xxx" channels and lots more missing too.

There are only 141 SRP picons in that set.
52 of the SRPs are blank images.
Many of the others are not for channels that are on 28.2E.

**Comment by AbuBaniaz** [comment]
Our picons use links, this is why they are 0kb.

Use the all version, not the one for 4 satellites. 

The one you used is built against a channel list. The channel list is awkward to update. I think build process checks bouquets too, not just lamedb, but I might be wrong.

**Comment by FlexMcMurphy** [comment]
I also downloaded `enigma2-plugin-picons-srp-13e.19e.23e.28e.220x132-190x102.dark.on.reflection_2024-08-31--23-44-14_all` and then `enigma2-plugin-picons-srp-full.220x132-190x102.dark.on.reflection_2024-08-31--23-44-14_all`. In each case they are missing pretty much the same channels.

About the 0kb picons you mentioned... I wasn't talking about picon file size but in about 10-20% of cases the images themselves have got no logos on them.

Ok maybe this is a volunteer service but where is the quality control? Does anyone working on these picon sets actually do a fresh scan, say of Astra 28.2E, and test how many of these SRP picons are attaching to channels and then how many of the logos on them are actually correct and up to date? And how many of them that do attach to channels are just blank picons with no logos?

Maybe I will try Kiddac E-piconizer's plugin but if that only gets picons from what Sky show on their platform then maybe it will be missing many that are FTA or Freesat which is all I am interested in.

Cheers,

Flex

**Comment by AbuBaniaz** [comment]
I regularly remove 28.2 services and start afresh. They are working for me apart from radio services. The radio services is a known issue.

**Comment by Lexzie** [comment]
> I regularly remove 28.2 services and start afresh. They are working for me apart from radio services. The radio services is a known issue.

The issue with radio services is why we build the version for the four satellites against the repo [picons/channellists](https://github.com/picons/channellists). There are the tv and radio services in different bouquets so that the radio services would be build with the prefix `1_0_2_` instead of `1_0_1_`.
At least that was told to me by @mrhotio 
It looks like I am the only one contributing there and my last change for 28.2E is from June 5th.
So maybe there were a lot changes since then? Lately I have less time and energy for maintaining the picon project.
I'll try to update it this evening.

**Comment by AbuBaniaz** [comment]
28.2 has been migrating services to dvb-s2, so there have been lots of changes.

It is a pain in the rear maintaining one bouquet with all channels in them.  I am not going to try. 

I don't understand how you are creating those bouquet or if they are being obtained from elsewhere. I have created 28.2 tv an radio bouquets and submitted a pull request. Please merge if appropriate.

To create the bouquets, I did following
UP (next to OK) > Green (Satellites) > Highlight 28.2 > Menu > Copy to bouquets

If these are no longer  required, please delete
userbouquet.astra_2e_2f_2g_at_28_2_e.radio
userbouquet.astra_2e_2f_2g_at_28_2_e.tv

**Comment by FlexMcMurphy** [comment]
In the channel channel list mentioned by @Lexzie the satellites.xml file is a year old and yes many transponders have changed over the summer. 

Likewise the lamedb is 2 months old and those bouquets haven't been updated in ages.

I don't really know how the automated process works to produce so many picon lists on to GitHub almost daily but it seems pointless to do that when the main problem is so many channels do not have a picon at all.

Having an up to date picon for every channel that I then have to manually attach to channels myself using dreamboxedit or echannelizer would be far more valuable than having hundreds of lists of SNP and SRP picon archives getting auto generated daily that:
1. I doubt hardly anyone is using.
2. Are filled with blank picons, not 0kb picons, I mean images with no logos on them.
3. Missing loads of picons with correct channel logos.
4. Loads of picons not working because the SNP names are wrong.
5. Loads of picons that attach to a channel are wrong because the SRP names are matching picons with incorrect logos to channels that have recently changed.

If no one wants to support the SNP picons then you should stop auto generating SNP picons packs, that's pointless and just confuses people and wastes energy, bandwidth and cloud storage.

I didn't understand the issue described about radio station picons. The issue to me again seems that no one is keeping up with making and updating picons for satellite TV or Radio channels and that's what people are looking for when they come here.

I'm sorry for the harsh feedback but I think this project needs to re-evaluate its reason for being if there is no interest in supporting it adequately.

My suggestion is forget about creating huge archives with 1000s of picons 99% of which are no use. There should be a single archive file for each satellite. Don't even bother naming the picons with SNP or SRP naming schemes. The current name of the channel would be sufficient.

The only concern should be that on the date that archive was generated it has picons for all the channels broadcasting on that satellite constellation on that day. This wouldn't need to be done every day in an automated fashion that no one is checking for up to date completeness. Once a week would be enough, even once a month if it was done properly.

Flex

**Comment by AbuBaniaz** [comment]
Something must have gone wrong during the bot-build, if they are not working for you.  Download them from openpicons.com.

There are only handful of 28.2 TV channels with no logos, I have already committed those links. Please upload your lamedb fiel if you want us to look at your issue further.

There is another topic about making satellite/regional picons. Please continue those discussions in that issue. The best way to make picons relevant to you is to build it against your channel list. Have a read of the readme.

The satellites.xml is not used on this project. Actually, it s a waste of time channel list distributors including it in their distributions.

**Comment by AbuBaniaz** [comment]
@FlexMcMurphy 
I am going to close this issue now. Please submit any further changes going by the template. We work with links in the srp.index and snp.index files and logos.
