### ISSUE TITLE
lots of missing logos srp build and no stream ref change 

### ISSUE THREAD

**Issue by leec32** [picons/picons#235]
hi

could someone check the srp repo please, lots of missing logos and the stream ref haven't changed because i am still getting epg info for the channels. lots missing 

i noticed it on 6/6 build and thought maybe it will be fixed on the latest but just downloaded that and its not

Thanks

**Comment by mrhotio** [comment]
You downloaded what?

**Comment by leec32** [comment]
enigma2-plugin-picons-srp-full.220x132-190x102.light.on.transparent_2020-06-10--23-21-59_all.ipk

**Comment by mrhotio** [comment]
and which service references are supposedly missing?

**Comment by leec32** [comment]
just to name a few without having to get the references and channels for all, to many missing

itv hd 510E_80F_2_11A0000
channel 5 hd 1E46_809_2_11A0000
sky one hd F15_7E9_2_11A0000
sky witness hd
sky atlantic hd
fox hd
paramount hd 

was like this with the 6/6 update and also this most recent 10/6

**Comment by leec32** [comment]
discovery hd
discovery +1 
nat geo hd
sky crime 

like i say lots missing

**Comment by mrhotio** [comment]
Thanks for reporting this, next time don't hesitate

**Comment by mrhotio** [comment]
new build is on its way, just for you :-)

**Comment by leec32** [comment]
@hotio haha thank you very much :)
