### ISSUE TITLE
Thousands (2000+) of "empty" PNGs/missing channel logos

### ISSUE THREAD

**Issue by SaaX-IRL** [picons/picons#2359]
Hi guys,

I'm wondering if I'm just doing something wrong or if there's an issues with some channel logos.

Since a while I'm missing some of the logos and noticed that ca. 2000 channel logos seem to be "empty" files, just 132 bytes small. I am currently using old ones from end of 2023 which don't seem to have this problem.

Hopefully they'll be complete again at some stage.

Cheers

![2024-09-12 12_05_53-D__xxx_1_snp-13e 19e 23e 28e 220x132-190x102 dark on transparent_2024-09-06--21-](https://github.com/user-attachments/assets/78835208-f474-4bcb-8637-8f0642d42ec6)

**Comment by AbuBaniaz** [comment]
The bot building process has a problem.  Please download from openpicons.com for now.

**Comment by TheLegoBatman** [comment]
Is this on specific backgrounds or all of them?

**Comment by SaaX-IRL** [comment]
I noticed with dark.on.transparent but checked some random other ones - showing the same issue...

**Comment by TheLegoBatman** [comment]
It seems to me that some are complete. This is probably going to be fixed by the next build. Report back if it isn't.
