### ISSUE TITLE
Movistar+ summer changes

### ISSUE THREAD

**Issue by Jglez3** [picons/picons#241]
# SRP entries

**srp.index**
```
7508_420_1_C00000=vamos
78BE_3EC_1_C00000=axnwhitehd
7825_428_1_C00000=syfyhd
749D_41C_1_C00000=movistarfest
7539_426_1_C00000=movistarestrenos
750A_420_1_C00000=vamos
74A7_41C_1_C00000=eurosport2
7798_424_1_C00000=realmadridtv
7884_414_1_C00000=viajarhd
74A8_41C_1_C00000=bemad
76C4_40E_1_C00000=canalpanda
76C1_40E_1_C00000=tveclan
18F1_3F4_1_C00000=tvgalicia
7473_3F0_1_C00000=aragontvint
76C5_40E_1_C00000=laligatv
76C2_40E_1_C00000=tvela1
772C_416_1_C00000=antena3
7792_424_1_000000=cuatro
778C_424_1_C00000=telecinco
74A6_41C_1_C00000=lasexta
7733_416_1_C00000=vamos
76CB_40E_1_C00000=tnt
7734_426_1_C00000=vamos
7472_3F0_1_C00000=natgeowild
```

# Logos

I don't know where to find the Movistar Fest (movistarfest) logo besides here, and it's a bad one (100x89 px png)
https://www.movistarplus.es/recorte/m-NEO/canal/MONFIR.png

**Comment by AbuBaniaz** [comment]
If we do not have all the logs for which you want us to add links, please say which of the above links you provided do we not have logos? It is too much work to go through every link and check the repository for logos.

**Comment by Jglez3** [comment]
The only ref that doesn't have a logo is this:
749D_41C_1_C00000=movistarfest

All the other ones have logos, it's just add the refs to the srp.index.

**Comment by AbuBaniaz** [comment]
I have added the links here
https://github.com/picons/picons/commit/6e7cb373505c4fc4e36858fd699be2bb8b1f5e4e

**Comment by Jglez3** [comment]
Thanks for adding those references.

Here's another one to add to the srp.index.

```
7474_3F0_1_C00000=tvela2
```

**Comment by Lexzie** [comment]
Added in fa0a14b
