### ISSUE TITLE
Penthouse rebranding

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#25]
Penthouse HD1 is rebranded in Penthouse Gold,
Penthouse HD2 is rebranded in Penthouse Quickies and
Penthouse HD is rebranded in Penthouse Passion.
Penthouse Black has a new logo.

But the only logos I can find are:
https://www.penthousetv.com/images/logo_phGold.png
https://www.penthousetv.com/images/logo_phQuickies.png
https://www.penthousetv.com/images/logo_phPassion.png
https://www.penthousetv.com/images/logo_phBlack.png

Can anyone find better logos?

**Comment by AbuBaniaz** [comment]
Try this
https://github.com/Jasmeet181/mediaportal-cz-logos/commit/afd77947b6ef2cda79b66fa1af179e2e994e485b

**Comment by Lexzie** [comment]
Those are the same as the ones I already found (435x95) , if they are okay enough I will use those.

I already found a better one (988x215) for Penthouse Gold.

**Comment by Jasmeet181** [comment]
I tried making them and added a lighter Penthouse Passion.
[Penthouse.zip](https://github.com/picons/picons/files/3067058/Penthouse.zip)
