### ISSUE TITLE
Insight UHD

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#26]
Is there anywhere a backup of that logo?
They changed again from `Insight HDR` to `Insight UHD` logo.

**Comment by mcfly822** [comment]
https://github.com/picons/picons/blob/abd783b8bae0ee51d70bcf3991a63b46219f8acc/build-source/logos/insightuhd.default.svg

**Comment by TheLegoBatman** [comment]
Added at the same time :-D

Edit: Actually you will have to add the one mcfly822 added as I changed the letter U and didn't realise the D is different .

**Comment by Lexzie** [comment]
Thanks!
