### ISSUE TITLE
Missing Canal Digitaal logos

### ISSUE THREAD

**Issue by Varkentjes** [picons/picons#267]
# SNP/SRP entries

When snp reference is used, some logos are missing in LCD4Linux displays. So please find attached new snp.index entries to fix the problem.

**snp.index**
```
sbs6hd=sbs6
foxsports1hd=foxsports1 
foxsports2hd=foxsports2
foxsports3hd=foxsports3
foxsports4hd=foxsports4
stingrayclassicahd=stingrayclassica

```

**Comment by AbuBaniaz** [comment]
The picon code in enigma2 trims the hd if a picon is not found. Please ask plugin creators to add that code or just use it from enigma2.

I don't think we should be adding what you request.

**Comment by AbuBaniaz** [comment]
The function was added here:
https://github.com/oe-alliance/oe-alliance-plugins/commit/f8871ffd0af7a982b4fbb8f480853e2243bc5e54#diff-59bcd2858a6d60edc79e153e2b25040b

Which version of the plugin are you using? Which image?

**Comment by Varkentjes** [comment]
If that is the case, why have entries been made for rtl4hd to rtl9hd?

I am using LCD4Linux V5.0-r6 in OpenPLi 7.3 image.

**Comment by mrhotio** [comment]
@Varkentjes I've already added them, enjoy

**Comment by Lexzie** [comment]
@hotio Should we add those links too now?

**Comment by mrhotio** [comment]
What links?

**Comment by Lexzie** [comment]
`<channelname>hd=logoname` when there is already `<channelname>=logoname` (and no specific hd logo).

**Comment by mrhotio** [comment]
That has always been the case, said it numerous times that we should not care if some enigma 2 image has a trick or not.

**Comment by Lexzie** [comment]
Okay, I will do so accordingly.
