### ISSUE TITLE
Downloading Schau TV logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#27]
I can't seem to save this image:
https://schautv.at/assets/schautvat/logos/header.svg

Found it here: https://schautv.at/

Anyone else give it a try?

**Comment by TheLegoBatman** [comment]
[Schau.zip](https://github.com/picons/picons/files/3090410/Schau.zip)

I just used Control+S and it saved.

**Comment by Lexzie** [comment]
Thanks, I already did that but when I open the file in Inkscape I only get `tv`.

**Comment by Jasmeet181** [comment]
There are masks on the Sch, a and u.
I've got cleaned up versions
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Schau%20TV.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Schau%20TV%20-%20Dark.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Schau%20TV%20HD.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Schau%20TV%20HD%20-%20Dark.svg

Freenet Shopping svg too
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Freenet%20Shopping.svg
https://github.com/Jasmeet181/mediaportal-de-logos/blob/master/TV/Freenet%20Shopping%20-%20Dark.svg

**Comment by Lexzie** [comment]
Great. I will look into it and replace the logos asap.

**Comment by Lexzie** [comment]
Also replaced the Freenet Shopping logo. ( 2aa13f3 )
