### ISSUE TITLE
Another set of 3 new SLAM! Logos

### ISSUE THREAD

**Issue by Varkentjes** [picons/picons#273]
# SNP/SRP entries

**snp.index**
```
slamhardstyle=slamhardstyle
slamnonstop=slamnonstop
slamjuize=slamjuize
```
# Logos

[logosslam.zip](https://github.com/picons/picons/files/5129854/logosslam.zip)

@Lexzie I spent several hours to make also logos in light, but I'm not satisfied with the final result. Can you help me to do that for me again? Or can you tell me how to do it myself?

**Comment by Lexzie** [comment]
@Varkentjes I'll have a look later.

**Comment by Lexzie** [comment]
@Varkentjes I hope these were the best quality logos you could find?

Anyhow, how to unvert dark/light:
I use [Paint.net](https://www.getpaint.net/) for this.
Select the arae you don't want to invert.
![afbeelding](https://user-images.githubusercontent.com/14023349/91668096-fcfea000-eb09-11ea-9b51-331cabf14d33.png)

Press Ctrl-I, the selection will be inverted:
![afbeelding](https://user-images.githubusercontent.com/14023349/91668108-17d11480-eb0a-11ea-95df-1f6a91e167e7.png)

Press Ctrl-Shift-I and the colors in the selcted area will be inverted,
![afbeelding](https://user-images.githubusercontent.com/14023349/91668260-b7db6d80-eb0b-11ea-849e-a70eef3dcb7c.png)


Unfortunaltely in that way you'll see that there's still an ugly outline which needs to be removed.
In the source picture must be a white outline too, but that's not so clearly visinle.
To make it visible just add another layer (Ctrl-Shift-N) and drag it below the background layer:
![afbeelding](https://user-images.githubusercontent.com/14023349/91668153-ab0a4a00-eb0a-11ea-9cd5-94e7540093ed.png)

Then fill new layer with black or white depending on which picture you want to clean.
![afbeelding](https://user-images.githubusercontent.com/14023349/91668304-215b7c00-eb0c-11ea-82bb-c6c546d4683e.png)

In the source picture I added a dark layer below the logo:
![afbeelding](https://user-images.githubusercontent.com/14023349/91668331-48b24900-eb0c-11ea-89e0-70e68a2d0543.png)
You also see there's also an outline around the 'SLAM!'  logo.
To get a clear SLAM! logo just export a png from the slamfm.default.svg logo already present and import that here.

Editing away that outline can be a lot of work (better try and find a source picture that is better).
You can f.e. define as secundairy color 0 with Opacity-Alpha 0:
![afbeelding](https://user-images.githubusercontent.com/14023349/91668197-2c61dc80-eb0b-11ea-814e-4af305109c47.png)
Then use the Paint Bucket and click with the right mouse button on the space which is already transparent, make sure Blending Mode is set to Overwrite and Tolerance is 50%:
![afbeelding](https://user-images.githubusercontent.com/14023349/91668236-82368480-eb0b-11ea-81a3-0187c091de9a.png)

And/or fill the painted areas with the same color, pick the color with the dropper.

Sometimes you even have to zoom in and edit pixel by pixel... (I know, a lot of work!).

What might be not that difficult for the SLAM! Non-Stop and SLAM! Mixmarathon is making them in Inkscape, using the slamfm.default.svg logo, as soon as you know which font is used.
But I'll have to do that another time...

I hope I didn;t discourage you to find missing logos, there are still a lot missing.

**Comment by Varkentjes** [comment]
@Lexzie thanks for the detailed explanation. I'll practice a bit and then upload the updated logos here. Maybe your explanation is the start of a manual? Because I actually miss that for new ones who also want to contribute here.

**Comment by Lexzie** [comment]
I think this is done in PR #290 so we can close this.
