### ISSUE TITLE
Update TV Koper entries

### ISSUE THREAD

**Issue by yadranko** [picons/picons#275]
**snp.index**
```
tvkoper=kopercapodistria
```

delete tvkc=kopercapodistria

**srp.index**
```
44_3_40_A00000=kopercapodistria
```

delete C83_2328_13E_820000=kopercapodistria

**Comment by AbuBaniaz** [comment]
Are you sure the deletes are required? They are on a different satellite to what you are adding.

The additions have been committed.

**Comment by yadranko** [comment]
Hi, 
regarding srp.index yes, I'm sure.
The channel left Hotbird in November 2019 and about 10 days ago restarted broadcasting on Eutelsat 16A.
Regarding snp.index that was the old id on Hotbird, but maybe you could keep it if it is still used somewhere else (cable etc.).
Thank you.

**Comment by AbuBaniaz** [comment]
Done
