### ISSUE TITLE
Removing background

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#28]
Could someone remove the white background of this logo? Without destroying the white of the '2'?
And maybe also make one without the '2'?
![afbeelding](https://user-images.githubusercontent.com/14023349/57022718-3e3e2180-6c30-11e9-8fd4-83c34e0a5b80.png)

These are the two channels:
![afbeelding](https://user-images.githubusercontent.com/14023349/57022818-970dba00-6c30-11e9-9192-efd769cbdd77.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/57023027-421e7380-6c31-11e9-8abf-8c0af034caee.png)

**Comment by TheLegoBatman** [comment]
![pinkhits2 default](https://user-images.githubusercontent.com/22258726/57041282-c2f16580-6c59-11e9-9105-7125c4abd2c6.png)

I removed the white background. Can't make it without the 2 though. Maybe someone else will be able to.

Edit: Or maybe add this one https://totaltv.tv/oec/images/tv_channels/56c614a681b6aff5286efaeae360e74c.png

**Comment by Lexzie** [comment]
Thanks again @TheLegoBatman 

> Edit: Or maybe add this one https://totaltv.tv/oec/images/tv_channels/56c614a681b6aff5286efaeae360e74c.png


Isn't that logo to low res?

**Comment by TheLegoBatman** [comment]
It is a bit low resolution but I have searched for a bit and that was the best one I found. Sometimes there is really no better options.
