### ISSUE TITLE
website issues

### ISSUE THREAD

**Issue by leec32** [picons/picons#3]
hi

is there issues with https://www.picons.eu/

on my chrome browser This site can’t be reached picons.eu’s server IP address could not be found.

connects using firefox but when i click downloads it takes me straight to git hub but only offers snp picons https://github.com/picons/picons/releases

thanks

**Comment by mrhotio** [comment]
try an incognito windows, there could be some issues with cache...
new downloads are currently building

**Comment by leec32** [comment]
still the same. 
ill try back tomorrow for the new build
thanks

**Comment by mrhotio** [comment]
what is still the same?

**Comment by mrhotio** [comment]
make sure you are going to www......

**Comment by leec32** [comment]
www. works on chrome, i was just using the picons.eu that came up automatically, thanks for that

**Comment by leec32** [comment]
when i click downloads it still takes me to https://github.com/picons/picons/releases

is that because the new new downloads are currently building ?

**Comment by mrhotio** [comment]
you should see the releases now on https://github.com/picons/picons/releases
builds can be tracked at https://drone.mailboxy.eu/picons/picons/
detail for last build https://drone.mailboxy.eu/picons/picons/3, the ones that take a long time and contain 'build' and 'publish' will produce new downloads

**Comment by leec32** [comment]
Successfully uploaded build-output/binaries-srp-full/enigma2-plugin-picons-srp-full.220x132-220x132.light.on.transparent_2019-03-08--20-21-47_all.ipk artifact

i have downloaded this one and installed onto my enigma box but all picons are not showing, just blank

**Comment by mrhotio** [comment]
god damn it, you're right

**Comment by leec32** [comment]
yes i wasn't sure if it was a problem at my end

**Comment by mrhotio** [comment]
should be fixed, now we have to wait +/- 4hours for all the releases to show up

**Comment by leec32** [comment]
great, thanks

**Comment by leec32** [comment]
@hotio all good now thanks
