### ISSUE TITLE
Removing red background

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#30]
Another one which gets ugly when I try it.
Can anyone neatly remove the red background?
https://live-tv-channels.org/pt-data/uploads/logo/ro-favorit-tv.jpg
or:
https://satsis.info/uploads/posts/2018-08/1535575195_www.satsis.info__favorit-tv.jpg
The text 'TELEVIZIUNEA' don't have to be spared since they don't show on TV:
![afbeelding](https://user-images.githubusercontent.com/14023349/57179183-358d5b80-6e7b-11e9-9697-52c6d84b9a2a.png)

**Comment by TheLegoBatman** [comment]
This is the best I could do.

![favorit_tv_ro](https://user-images.githubusercontent.com/22258726/57184321-f4fd0480-6eb1-11e9-846d-b13b65a8f5f6.png)

**Comment by Lexzie** [comment]
Added in commit 075825c0e4953496b3d38efad5becfb9c4b565b0
