### ISSUE TITLE
channel logos are missing - tv oberfranken / Beate-Uhse.TV

### ISSUE THREAD

**Issue by nicoh88** [picons/picons#31]
Hi,

awesome work, thanks!

But, two channel logos are missing:

- tv oberfranken hd 
- Beate-Uhse.TV HD

Thank you!

**Comment by TheLegoBatman** [comment]
Hi. Those logos are present. You will need to give us the references to link them to.

Please check https://github.com/picons/picons/blob/master/CONTRIBUTING.md for more info.

**Comment by nicoh88** [comment]
**snp.index**

```
tvoberfrankenhd=tvoberfranken
beateuhsetvhd=beateuhsetv
```

**srp.index**

```
170F_419_1_C00000=tvoberfranken
85_3_85_C00000=beateuhsetv
```

**logos**

[beateuhsetv.default.svg](https://github.com/picons/picons/files/3169919/beateuhsetv.default.svg.txt)
[tvoberfranken.default.svg](https://github.com/picons/picons/files/3169922/tvoberfranken.default.svg.txt)

**Comment by nicoh88** [comment]
@AbuBaniaz you still need add the new  logos/svgs?

**Comment by AbuBaniaz** [comment]
`Picon` = `Link on this repository/project` + `logo on this repository/project`

Logo existed on repository already. Links you provided have been added. When next build is run, the picons will be created as the two ingredients are now present.

If above explanation does not answer your query, please rephrase what you want to say as I do not understand you last comment.

**Comment by AbuBaniaz** [comment]
Do the logos need replacing?

**Comment by AbuBaniaz** [comment]
We have the latest logo for beate-uhse. Your one is older.
```
https://en.wikipedia.org/wiki/Beate-Uhse.TV#Logos
```
I have replaced the tvoberfranken png with the svg file you provided. Thanks.
