### ISSUE TITLE
[FEEDBACK] Input wanted on what to decide

### ISSUE THREAD

**Issue by Varkentjes** [picons/picons#321]
I have designed 3 different versions for 100% NL logos, but I cannot decide for myself which one can best be used. Does anyone have any advice for me?

[100procentnlnederpop.demo.zip](https://github.com/picons/picons/files/5287012/100procentnlnederpop.demo.zip)

**Comment by Lexzie** [comment]
What I would do:
1. How is the logo used by the broadcaster? Look for it onscreen (for TV) and their own website.
2. If there's no special logo in use (like in this case) try to use one that is best visible.
3. When in doubt, you can ask everyone's opinion like you did.

In this case I would choose the one on the bottom with the white letters.

**Comment by Varkentjes** [comment]
My first approach was to design a logo in the same style as the broadcaster uses. Otherwise, I'll do the same trick over and over and in the end everything will look the same. So this time designing everything in 1 color with a gradient was my goal. However, the readability depends on what the user has set. Differences in skins, dark, light, padding, nopadding etc. This makes it difficult to predict what is best for everyone.

I agree with your choice for the third one. The white letters are certainly readable for everyone and this also offers the possibility to slightly individualize each logo like I did earlier.

**Comment by mrhotio** [comment]
3rd one

**Comment by Lexzie** [comment]
Logos added in PR #324
