### ISSUE TITLE
Finding/making good logo for Scan TV

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#33]
Can anyone help in finding or making a better looking logo for Scan TV?
Website of the station: http://www.scan-tv.com/

![image](https://user-images.githubusercontent.com/14023349/57921461-ad0cb300-789d-11e9-8eae-47bd2a756e7e.png)
http://www.scan-tv.com/wp-content/uploads/2016/12/logo-default.png

This logo would be good too:
![image](https://user-images.githubusercontent.com/14023349/57921526-d75e7080-789d-11e9-88d1-e129a643cd41.png)

**Comment by mcfly822** [comment]
If @TheLegoBatman will be not as fast as usual 😉 , I'll try to make it in svg tomorrow.

**Comment by TheLegoBatman** [comment]
Added the logos. :)

**Comment by Lexzie** [comment]
Wow, great. I will add the links ASAP.

**Comment by mcfly822** [comment]
Wow, @TheLegoBatman was so quick.
I think I can retire now :-)

**Comment by TheLegoBatman** [comment]
:laughing:
