### ISSUE TITLE
Halk Tv HD New Picon

### ISSUE THREAD

**Issue by suatsuphi** [picons/picons#334]
Halk Tv HD New Picon and frequency
turksat 42e
12685 30000 Vertical auto dvb-s2

1_0_1_C693_7BD6_42E_1A40000_0_0_0.png

![1_0_1_C693_7BD6_42E_1A40000_0_0_0](https://user-images.githubusercontent.com/20780272/95016300-e0024300-065a-11eb-99a9-b5cd197705ce.png)

**Comment by AbuBaniaz** [comment]
Link updated. From what I can see, we have the same logo that you provided on our repo. If this is not correct, please supply a good quality graphic and we will replace it.

https://github.com/picons/picons/blob/master/build-source/logos/halk.default.png
