### ISSUE TITLE
Several errors in Astra 19.2

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#335]
Sorry for not using the template. I read it but I found it very confusing to explain the problems I have came through. Please discard my message if you consider that not following the rules invalidates my contribution. ;-)

- 1_0_1_7734_416_1_C00000_0_0_0 (service name "#VAMOS") picon is missing and should be the same as 1_0_1_7733_416_1_C00000_0_0_0 (service name "#VAMOS")
- 1_0_1_7853_41A_1_C00000_0_0_0 (service name "10729V SID 0x7853") is empty but has an picon assigned
- 1_0_1_7855_41A_1_C00000_0_0_0 (service name "10729V SID 0x7855") is empty but has an picon assigned
- 1_0_1_785A_41A_1_C00000_0_0_0 (service name "10729V SID 0x785a") is empty but has an picon assigned
- 1_0_1_785F_41A_1_C00000_0_0_0 (service name "10729V SID 0x785f") is empty but has an picon assigned
- 1_0_1_7861_41A_1_C00000_0_0_0 (service name "10729V SID 0x7861") is empty but has an picon assigned
- 1_0_1_7864_41A_1_C00000_0_0_0 (service name "10729V SID 0x7864") is empty but has an picon assigned
- 1_0_1_76A6_41E_1_C00000_0_0_0 (service name "10788V SID 0x76a6") is empty but has an picon assigned
- 1_0_1_77D8_40A_1_C00000_0_0_0 (service name "10979V SID 0x77d8") is empty but has an picon assigned
- 1_0_1_1B64_3FC_1_C00000_0_0_0 (service name "Arirang HD") picon is missing and should be the same as 1_0_1_1B63_3FC_1_C00000_0_0_0 (service name "Arirang TV")
- 1_0_1_749D_41C_1_C00000_0_0_0 (service name "M. Fest") picon is missing
- 1_0_19_74CD_3F8_1_C00000_0_0_0 (service name "M. LaLiga 2 HD") picon is missing and should be the same as 1_0_1_7580_412_1_C00000_0_0_0 (service name "M. LaLiga 2")
- 1_0_19_74D3_3F8_1_C00000_0_0_0 (service name "M. LaLiga 3 HD") picon is missing and should be the same as 1_0_1_769C_41E_1_C00000_0_0_0 (service name "M. LaLiga 3")
- 1_0_19_74D5_3F8_1_C00000_0_0_0 (service name "M.LCAMPEON1") picon is missing and should be the same as 1_0_1_757A_412_1_C00000_0_0_0 (service name "M.LCAMPEON1")
- 1_0_19_74DB_3F8_1_C00000_0_0_0 (service name "M.LCAMPEON2") picon is missing and should be the same as 1_0_1_769F_41E_1_C00000_0_0_0 (service name "M.LCAMPEON2")
- 1_0_1_76A4_41E_1_C00000_0_0_0 (service name "TEST 88") is a test channel and should not have picon
- 1_0_1_772A_416_1_C00000_0_0_0 (service name "TEST D") is a test channel and should not have picon
- 1_0_1_76A7_41E_1_C00000_0_0_0 (service name "TEST F1") is a test channel and should not have picon
- 1_0_1_1090_3EE_1_C00000_0_0_0 (service name "TV Trwam") picon is missing

Thank you very much.
Best regards.

**Comment by AbuBaniaz** [comment]
Our links do not use the `1_0_1` or `1_0_19` at beginning of service references or `_0_0_0` at the end

You should have posted something like:

Please add the following links
```
7734_416_1_C00000=vamos
1B64_3FC_1_C00000=arirangtv
74CD_3F8_1_C00000=movistarlaliga2
74D3_3F8_1_C00000=movistarlaliga3
74D5_3F8_1_C00000=movistarligadecampeones1
74DB_3F8_1_C00000=movistarligadecampeones2
1090_3EE_1_C00000=trwam
```

Pease delete the following links
```
76A4_41E_1_C00000=canalorbe21
772A_416_1_C00000=disneyxd
76A7_41E_1_C00000=movistarfutbol
76A7_41E_1_C00000=movistarmultifutbol
76A7_41E_1_C00000=movistarmultideporte
7853_41A_1_C00000=beinsportslaliga
7853_41A_1_C00000=beinsportslaliga
7855_41A_1_C00000=movistarlaliga2
785A_41A_1_C00000=laligatv
785F_41A_1_C00000=movistarlaliga3
7861_41A_1_C00000=movistarligadecampeones1
7861_41A_1_C00000=beinsportsmax1
7864_41A_1_C00000=beinsportsmax2
7864_41A_1_C00000=movistarligadecampeones2
76A6_41E_1_C00000=laligatv
77D8_40A_1_C00000=nationalgeographicwild
``` 
I can't find the Movistar festival logo on our repo, so that needs to be sourced before we can add it.

**Comment by Lexzie** [comment]
Is there still anything to do with this?

**Comment by AbuBaniaz** [comment]
>I can't find the Movistar festival logo on our repo, so that needs to be sourced before we can add it.

Just the movistar festival logo

**Comment by Lexzie** [comment]
That should be this one I guess:

![afbeelding](https://user-images.githubusercontent.com/14023349/95691730-892fd700-0c21-11eb-9bc4-3dcb2247fa2e.png)

Can't find a better one for now.
https://i0.wp.com/jungle-team.com/wp-content/uploads/2020/06/movistarfest.png

**Comment by Varkentjes** [comment]
Movistar Fest was a pop up channel that aired from June 26 til August 16, 2020.

Source:
https://jungle-team.com/picon-nuevo-canal-movistar-fest/

I think this item can be closed.

**Comment by Lexzie** [comment]
The ident is still present and has a bitrate, so there should be something happening there behind the encryption.
@qosobrin can you make a screenshot?

**Comment by qosobrin** [comment]
Black screen, @Lexzie. I think you can delete it. If it comes back in the future I will let you know.

Best regards.

**Comment by Lexzie** [comment]
Nothing to delete, but we can close this issue.
