### ISSUE TITLE
Double gradient for logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#34]
Hi guys, I have another challenge for you.
I created this logo, but I can't get the color gradient right for the stripe.
[rtb.zip](https://github.com/picons/picons/files/3221042/rtb.zip)
This is how it must be:
![afbeelding](https://user-images.githubusercontent.com/14023349/58386325-53735980-7ffe-11e9-8fe8-9d3fbd343cde.png)

**Comment by mcfly822** [comment]
Hi @Lexzie , I made this with mesh gradient tool.
The problem is, that when I open the svg in browser or in GIMP, the gradient part showed as black.
I dont know what will be the solution...
[rtb_mcfly82_20190527.zip](https://github.com/picons/picons/files/3222548/rtb_mcfly82_20190527.zip)

**Comment by mrhotio** [comment]
I can't fix it either...maybe export as high res png instead.....

**Comment by Jasmeet181** [comment]
Gradient meshes won't be a part of the SVG spec until [2.1](http://libregraphicsworld.org/blog/entry/gradient-meshes-and-hatching-to-be-removed-from-svg-2-0), support for up to 1.1 Second Edition is the current norm for most applications.

Try this
[rtb_j.zip](https://github.com/picons/picons/files/3223299/rtb_j.zip)

**Comment by Lexzie** [comment]
All thanks for the help.
@Jasmeet181 How did you do that?

**Comment by mcfly822** [comment]
@Lexzie Just by the simplest solution, by linear gradient... (Why I did not try this? 🤦‍♂ )
@Jasmeet181 thank you for the information!

**Comment by Lexzie** [comment]
@mcfly822 I used the lineair gradient, so I got a gradient from two colours. That's why I named this **double** gradient. (In this case) from green to yellow to red.
As I open the svg from Jasmeet181 I see defined 'Mesh gradient' and below that ''Use Mesh tool to modify the mesh''. How does that Mesh tool work? What is it?

**Comment by mcfly822** [comment]
@Lexzie you can do multiple color gradients by the mesh tool. I also made my version by this tool. But unfortunately, as @Jasmeet181 wrote, this is not supported by many browsers and programs.
Jasmeet made his (or her? 😺 ) version by linear gradient tool, with 2 stops (see image below). This is a very good and tricky solution 😉 
(You can add or remove color stops in inkscape, I marked this option by a red circle)
![gradient](https://user-images.githubusercontent.com/22531870/58689297-eb6a9d80-8386-11e9-8715-5554e43a71cd.png)

**Comment by mcfly822** [comment]
Any other to do with this issue?

**Comment by Lexzie** [comment]
Still haven't tried it myself.
