### ISSUE TITLE
Two crappy logos, can anyone make or find better ones?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#35]
**Holygod TV**
![afbeelding](https://user-images.githubusercontent.com/14023349/58437931-73714e80-80cc-11e9-9f6c-60573562a34c.png)

Similar logo is from Holygod TV India, but the stripe on the bottom needs to be blue gradient into white gradient into red.
![afbeelding](https://user-images.githubusercontent.com/14023349/58437715-7ddf1880-80cb-11e9-92ec-924ef81fe9f5.png)

**NLM TV**
![afbeelding](https://user-images.githubusercontent.com/14023349/58437724-8afc0780-80cb-11e9-8ebb-2427d3552913.png)

**Comment by AbuBaniaz** [comment]
jpg here
`http://www.newlivingministries.org/images/stories/LOGOS/NLM%20TV%20logo.jpg`

**Comment by Lexzie** [comment]
Thanks!

**Comment by Jasmeet181** [comment]
[Holygod TV svg](https://github.com/picons/picons/files/3245990/holygodtv.default.zip)

**Comment by Lexzie** [comment]
Fantastic!
