### ISSUE TITLE
Search for logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#36]
I'm trying to find a better version of this logo.
Or trying to identify the font, but no real good matches.
![afbeelding](https://user-images.githubusercontent.com/14023349/60467657-7e814680-9c57-11e9-8a24-e2ad88e5fa48.png)
Found it here: http://www.first-channel.tv/

Needs to look like this:
![afbeelding](https://user-images.githubusercontent.com/14023349/60467748-b7212000-9c57-11e9-9ecf-0c4ba4eb3b97.png)
Transparent background, the letters ``CHANNEL`` also transparent.
And, of course a dark version where the white letters are purple as well.

**Comment by Lexzie** [comment]
No-one can help me with this? @TheLegoBatman ? @mcfly822 ? No hurry of course.

**Comment by TheLegoBatman** [comment]
I had tried the other day but had no luck, finding a better version of that logo, the font or anything similar. This one might be out of my skills :D

**Comment by Lexzie** [comment]
Too bad, many thanks for trying.

**Comment by mcfly822** [comment]
I'll try to draw the logo, maybe tonight or sometimes on next week.

**Comment by mcfly822** [comment]
I hope that this result is acceptable.

**Comment by Lexzie** [comment]
Wow, that's great.
Added the links.
Have to check later if a light version is necessary.

**Comment by mcfly822** [comment]
Thank you for your kind words 😳
