### ISSUE TITLE
Missing picons ( I can submit them )

### ISSUE THREAD

**Issue by rmohsenn** [picons/picons#38]
Not really an issue. I’m from Egypt and using tvheadend. Most of the picons for local channels are missing , I tried adding them manually from the internet URL and it worked but I want to submit them to picons.eu so other people can benefit from this. How do I do that ?

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons/blob/master/CONTRIBUTING.md

Have a look at the contributions file above

**Comment by Lexzie** [comment]
@rmohsenn What's the status? I'm willing to help as far as time allows me.
Maybe first step is to submit the logos. Make sure they are SVG's or PNG's of good quality.
Make sure the filename represents what is seen in the logo, further more name them like stated under [naming](https://github.com/picons/picons/blob/master/CONTRIBUTING.md#naming) in the above mentioned [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md) 
Also make sure to convert letters like `é`, `à`, `ö` to `e`, `a` and `o` respectively.

Besides that submit a list of channel names **how they appear after scanning the channels** linked to the logo-names, like:
```
channelname=logoname
```
_Please in alphabetic order of the logoname._
Also for the `channelname` use correct naming (lowercase, no spaces, no special characters, etc. etc.).

I beleive tvheadend does not use service references, like in Enigma2, so no need to find out what the service reference is.
How do you receive those channels? Satellite (which ones?), Terrestrial, IPTV or Cable?

**Comment by Lexzie** [comment]
I guess we can close this since there's nothing to work with.
