### ISSUE TITLE
Movistar+ 2019 summer changes

### ISSUE THREAD

**Issue by Jglez3** [picons/picons#39]
Like evey summer, Movistar+ is making some changes in refs and channels.

Here's the full list of changes to add to the srp.index and the new logos attached.

```
750F_420_1_C00000=movistarlaliga
7797_424_1_C00000=movistarlaliga
74FF_420_1_C00000=movistarlaliga1
756b_412_1_C00000=movistarlaliga1
7855_41A_1_C00000=movistarlaliga2
7580_412_1_C00000=movistarlaliga2
785F_41A_1_C00000=movistarlaliga3
769C_41E_1_C00000=movistarlaliga3
769b_41E_1_C00000=movistarlaliga4
7579_412_1_C00000=movistarlaliga5
757E_412_1_C00000=movistarlaliga6
756E_412_1_C00000=movistarlaliga7
7690_41E_1_C00000=movistarlaliga8
7581_412_1_C00000=movistarlaliga9
7578_412_1_C00000=movistarlaliga10

778E_424_1_C00000=vamos
756C_412_1_C00000=vamos
7584_412_1_C00000=vamos

7574_412_1_C00000=laligatv
76A6_41E_1_C00000=laligatv
```

Thank you!

[movistarlaliga.zip](https://github.com/picons/picons/files/3502805/movistarlaliga.zip)
[barcatv.zip](https://github.com/picons/picons/files/3502822/barcatv.zip)

**Comment by AbuBaniaz** [comment]
Can you upload the svg files instead of png ones?

```
https://es.wikipedia.org/wiki/Movistar_LaLiga#/media/Archivo:Movistar_LaLiga.svg
```

**Comment by Jasmeet181** [comment]
I have the Barca TV and Movistar LaLiga 1-10 in my repo
https://github.com/Jasmeet181/mediaportal-es-logos/tree/master/TV/Source

**Comment by AbuBaniaz** [comment]
Thanks. I'll get them later

**Comment by AbuBaniaz** [comment]
Can you add the snp index please?

I have also added the UHD logo

**Comment by norhap** [comment]
hello abu i am spanish who needs the reference?

**Comment by AbuBaniaz** [comment]
I'd like to add them to the SNP index that we build.

**Comment by norhap** [comment]
If I use your picons and these channels do not appear in the symlink snp that I use.
I need to know what you need.

**Comment by AbuBaniaz** [comment]
They won't show because links have not been added yet.

Can you attach your lamedb file please? I'll work them out from there.

**Comment by norhap** [comment]
if of course I will attach it.
give me time please ... it will probably be tomorrow.

**Comment by norhap** [comment]
there are some more that need updating in movistar platform ... I will put them here.

**Comment by norhap** [comment]
here the missing logos .... same logo is for M.Liga HD and for SD version.

<a href="https://ibb.co/frRRzRX"><img src="https://i.ibb.co/vL5565c/1.jpg" alt="1" border="0"></a>

channels SD:
<a href="https://ibb.co/hLPfzG2"><img src="https://i.ibb.co/sb0HYTs/2.jpg" alt="2" border="0"></a>
[lamedb.zip](https://github.com/picons/picons/files/3538304/lamedb.zip)

**Comment by norhap** [comment]
more.....LALIGATVBAR2,4
<a href="https://ibb.co/T0mgFfL"><img src="https://i.ibb.co/5jBRf0F/3.jpg" alt="3" border="0"></a>
more....
LALIGATV BAR ......This has an obsolete log must be updated.
<a href="https://ibb.co/cyZvHhx"><img src="https://i.ibb.co/51S9yh2/4.jpg" alt="4" border="0"></a>

**Comment by mrhotio** [comment]
please read the contributing guidelines

**Comment by Jglez3** [comment]
Sorry for the delay, I didn't have access to an internet connection these days.

Here's Movistar LaLiga SVG logo, the one without numbers.

[movistarlaliga.svg.zip](https://github.com/picons/picons/files/3561376/movistarlaliga.svg.zip)

**Comment by AbuBaniaz** [comment]
We already have that logo. We also have a light edition of it.  They are called `movistarlaligatv`

**Comment by AbuBaniaz** [comment]
These references are in use

SRP
```
7574_412_1_C00000=movistarlaligatv
76A6_41E_1_C00000=movistarlaligatv
```
SNP
```
mlaliga=movistarlaligatv
```

If any more are needed, please say so.

**Comment by Jglez3** [comment]
Two references haven't been changed. This is because I thought the logo was going to be called `movistarlaliga`.

```
750F_420_1_C00000=movistarlaligatv
7797_424_1_C00000=movistarlaligatv
```

The references you posted are from channels called LALIGATVBAR3 and LALIGATVBAR4 and they use the logo `laligatv` as I posted on the first message, not the `movistarlaligatv` one.

```
7574_412_1_C00000=laligatv
76A6_41E_1_C00000=laligatv
```

Could you make those changes?

Thanks.

**Comment by AbuBaniaz** [comment]
Changing something has a "from" and "to". You have not said these explicitly.

Please just say what I need to "add" and separately say what I need to delete.

Please use names of logos on repository.

**Comment by Jglez3** [comment]
Sorry for not being completely explicit. Let's try it again in the good way.

Delete this (wrong logos):
```
750F_420_1_C00000=beinsportslaliga
7797_424_1_C00000=beinsportslaliga
7574_412_1_C00000=movistarlaligatv
76A6_41E_1_C00000=movistarlaligatv
```

Add this:
```
750F_420_1_C00000=movistarlaligatv
7797_424_1_C00000=movistarlaligatv
7574_412_1_C00000=laligatv
76A6_41E_1_C00000=laligatv
```

Thank you.
