### ISSUE TITLE
BT Sport logo change

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#40]
Anyone allready busy making these logos or want to do it? Otherwise I will.
This is the basic `BT Sport` SVG (source: Logopedia):
[btsport.default.svg.zip](https://github.com/picons/picons/files/3517294/btsport.default.svg.zip)

These are the different logos:
![image](https://user-images.githubusercontent.com/14023349/63290833-932aa400-c2c2-11e9-8036-5fd2f5d95b45.png)![image](https://user-images.githubusercontent.com/14023349/63290802-84dc8800-c2c2-11e9-9946-408d325ae881.png)![image](https://user-images.githubusercontent.com/14023349/63290862-a0e02980-c2c2-11e9-923c-5f0278e905e2.png)![image](https://user-images.githubusercontent.com/14023349/63290909-bbb29e00-c2c2-11e9-8c83-81474f621884.png)![image](https://user-images.githubusercontent.com/14023349/63290979-e4d32e80-c2c2-11e9-9a4c-0944ad9e54cb.png)

BT Sport extra on screen:
![image](https://user-images.githubusercontent.com/14023349/63291623-34662a00-c2c4-11e9-8022-508b2f566b39.png)![image](https://user-images.githubusercontent.com/14023349/63291583-1ac4e280-c2c4-11e9-838b-9d921af266d8.png)![image](https://user-images.githubusercontent.com/14023349/63291537-fff26e00-c2c3-11e9-9f9f-0451dfb88d92.png)![image](https://user-images.githubusercontent.com/14023349/63291460-dcc7be80-c2c3-11e9-9a6d-d1e6d5c72605.png)![image](https://user-images.githubusercontent.com/14023349/63291411-c02b8680-c2c3-11e9-8ff6-4dbc25a08df6.png)![image](https://user-images.githubusercontent.com/14023349/63291660-48119080-c2c4-11e9-86d6-d164d3c2fa3c.png)

The `HD` channels still use `HD` in the logo:
![image](https://user-images.githubusercontent.com/14023349/63291203-61fea380-c2c3-11e9-9c7e-786f0bf0a852.png)

I already commited the `btsport` logo: 5d7f85fc2b1add4ecfe4c22f653a199fb3496f9c
Maybe a `light` version is needed too?

**Comment by Jasmeet181** [comment]
I based mine on BT's TV guide so apart from 1-3, they're stacked (easier to read too).
'Box Office' is in bold or heavy on some sites but in regular on theirs, it doesn't broadcast in SD or have 'HD' in the logo, see 'BT Sport Box Office HD - Original.svg'.
https://github.com/Jasmeet181/mediaportal-uk-logos/tree/master/TV/Source

**Comment by Lexzie** [comment]
Stacked is fine by me, we can use your logos here?
Shall I add them?

**Comment by AbuBaniaz** [comment]
@Jasmeet181 is fine with having his logos here. I have used many of his.

His dark version are our default ones
The ones without dark are our light version

**Comment by Jasmeet181** [comment]
Yeah, I don't have a problem with it, I've used logos from here too.

**Comment by Lexzie** [comment]
> His dark version are our default ones
> The ones without dark are our light version

Yes, I know. I was going to rename them dark > `.default`, others > `.light` (when there is also a dark version, otherwise they will be named `.default` too).
But it seems I have downloaded them wrong, I get errors from Inkscape ('failed to load requested file').

**Comment by Lexzie** [comment]
I figured it out, I have to open each file and then save picture as...
So that's going to take a little longer.
Does anyone know a way to bulk download the files `BT Sport*.svg` without having to use Git Desktop?

**Comment by Jasmeet181** [comment]
On the main page there's a green button that says Clone or download, you can choose [Download ZIP](https://github.com/Jasmeet181/mediaportal-uk-logos/archive/master.zip) from there.

You should click Raw and then save as on the page of text for single svg files.

**Comment by Lexzie** [comment]
Okay, I knew that option. Then I download the whole project, not just the `BT Sport*.*` files.
But still an easier way than file by file.
