### ISSUE TITLE
Removing background

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#41]
Could anyone remove the background of this image without destroying the "star" between the two microphones f.e.?
https://totaltv.tv/Picture/34995/png/BRAVO_MUSIC_TTV-VIJEST.png

**Comment by chocholousek** [comment]
https://lh3.googleusercontent.com/o_SeNFuNcWbEV40j0-b-oJ_EFEeaAN5seBUk14uxiX1CmuK-qFPZtDxeaTOpThViCnryUseypflbIc4LOwJrLVHPACgbf_DqseIpsLJxJtAjymQjwcYadp4YNbi5eZJvxCbKGB9QeHn7weOkwUowx7PGY_u1ancQKzwpoOFmeAEtKUx85_RTIxiGuW3bqBzbBHXInqHi4f28B8zpsKvxdNgaPZ8jUGS9eBDl8TE-y-2WntKzTVdWQaajkFY1j0DDoh2t2wW9viLWdPrIzjshwscZtgNMegzZpWFbO6p3x-p8AmtoxDXZ2WlOw-Y_dspsQZl-ZBXTshiIEIzCftkyY0B7l-5xSGLQc7IzeRVR68_XVE9QXswXBRnOlpvgNpPtecSm6WtOFzquhdP7Xvf-wp4e4x3i2rqhZy11wr9oNg9G79gms-h-oX95XMZpvQ6uXNcKYqh6fH8u1E1_jS1vzZR2LbPhisC5US3Eqp5Y2HIsV1v4spTNnueMg0kCDIKbupOMtWRAITOfaFlUdHqFzMAlwQuF2z2oGeCo7O9NEMAOBMuwYsaH1OO-Tdc3gOzYibhT2YCkZJYplnwM78I1SRY3Al9mnUiQ0EH2zhjvgiXz5h7M76CRfMleo7dZbxRfZ7CzwMoDdgi1qs9UmRZk5ymD0xXok3Q=w338-h333-no

**Comment by Lexzie** [comment]
Thank you, I will add it.
