### ISSUE TITLE
Some polish picons 13E missing

### ISSUE THREAD

**Issue by sz00gun** [picons/picons#424]
Just installed enigma2-plugin-picons-snp-13e.19e.23e.28e.220x132-190x102.light.on.transparent_2021-01-02--19-15-02_all.ipk

However some picons are missing from polish TV:
4fun gold hits
BBC lifestyle hd
Kino Polska hd
NAT geo people hd
TVC
CI Polsat HD
Studiomed tv HD
TTV HD
TVN24 bis HD
TVP info HD

**Comment by sz00gun** [comment]
why invalid? some picons are missing... can I help you somehow?

**Comment by AbuBaniaz** [comment]
You did not use the template. So details are not all there. Using the template ensures that the fixes you want are added quickly.

I don't have 13e so can't test. Please upload your lamedb file after zipping it.

**Comment by sz00gun** [comment]
sorry I didn't know this. 
[lamedb.zip](https://github.com/picons/picons/files/5766650/lamedb.zip)

**Comment by AbuBaniaz** [comment]
Just realised, you installed the one that is built against a lamedb file. So we will haev to update teh lamedb file we use. 
Please uninstall it and install the `full` version
