### ISSUE TITLE
picon missing for Sportdigital HD

### ISSUE THREAD

**Issue by rodajc** [picons/picons#433]
This channel is on TP 1030 (11656.00 MHz) of Astra 1N (19.2E)
https://en.kingofsat.net/pos-19.2E.php

**Comment by AbuBaniaz** [comment]
SRP:
1194_406_1_C00000

SNP:
sportdigitalfussballhd

SNP version is working for me.

**Comment by rodajc** [comment]
Where is it? I can't find it in snp-13e.19e.23e.28e.220x132-190x102.light.on.transparent_2021-01-09--23-23-36.symlink.tar.xz

**Comment by AbuBaniaz** [comment]
The one you used is built against a channel list. The channel list was updated a  couple of days ago.

I use the full version.

**Comment by Lexzie** [comment]
> 
> 
> This channel is on TP 1030 (11656.00 MHz) of Astra 1N (19.2E)
> https://en.kingofsat.net/pos-19.2E.php

Channel is there since at least 13-2-2019, so should be in the channel list long ago.
Did a rescan on 11656 V and the channel still uses the same name and service reference.

The channellist is indeed updated just 4 days ago, maybe wait for next update.
Do the other channels on the same transponder have no logo either?

**Comment by rodajc** [comment]
Sport 1 + HD is the only channel on that transponder with a logo.
Anyway, I'll wait for the next update.
No problem.
I'm very happy with all these beautiful logos.

**Comment by Lexzie** [comment]
That's weird. All channels should have picons.
What image are you using?

**Comment by rodajc** [comment]
openbh 4.3.039
Why?

**Comment by Lexzie** [comment]
Why? To help you.

But I think I know what's wrong.
We have this link in snp.index: `sportdigitalfussball=sportdigitalhd`
While the channel is named Sport Digital Fussball **HD**.
Aparently OpenBH doesn't look if a link exist without `HD` on the end.
So `sportdigitalfussballhd=sportdigitalhd` must be added.
I was doing so for a lot of channels right now, so hopefully I am done tomorrow.

**Comment by Lexzie** [comment]
@rodajc 
Just submitted the new link, I hope it is fixed for you in the next update.
