### ISSUE TITLE
FOX Sports is now ESPN

### ISSUE THREAD

**Issue by rodajc** [picons/picons#441]
and this has its consequences for the logos of three channels:

ESPN Netherlands HD and ESPN 4 HD netherlands are on TP 3202 (11739 MHz) of Astra 3B (23.5 E)
ESPN 2 Netherlands HD is on TP 3208 (11856 MHz) of Astra 3B (23.5 E)

**Comment by AbuBaniaz** [comment]
Can you please use the template. Frequencies have no bearing on picons. The service reference is what we need.

**Comment by Lexzie** [comment]
> 
> 
> Can you please use the template. Frequencies have no bearing on picons. The service reference is what we need.

@AbuBaniaz The service references were already added.

I added the logos ASAP after 1-1-2021. Canal Digitaal did not changed their stationnames, appearantly someone overthere woke up and they are changed now?
I think someone overthere should go in the mascot suit, not Hans Kraay jr. 🤣 
[https://www.facebook.com/ESPNNL/videos/1006766506481399/](https://www.facebook.com/ESPNNL/videos/1006766506481399/)

I will add the correct links, but as @AbuBaniaz says please use the template so I only have to copy-paste the new links.

**Comment by Lexzie** [comment]
I see the names are `ESPN HD`, `ESPN 2 HD` and `ESPN 4 HD`.
You should have a (wrong) picon on ESPN HD, but the rest is not automatically changed to the SD-variant in your image.
If you followed the template we should have had this list to add to snp.index:
```
17CC_C82_3_EB0000=espn
espn2hd=espn2
espn4hd=espn4
```
