### ISSUE TITLE
Movistar DAZN and Formula 1 2020 new logos

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#448]
I am aware some of these changes have already been submited on https://github.com/picons/picons/pull/446 but the logos commited there were not the ones the channels are using and here I propose more changes than the ones on that PR.

https://www.movistarplus.es/canal/dazn-1?id=M1SD
https://www.movistarplus.es/canal/dazn-2?id=M2SD
https://www.movistarplus.es/canal/movistar-formula-1?id=MVF1

# SNP/SRP entries

**snp.index**
```
dazn1=dazn1-malaspafro
dazn2=dazn2-malaspafro
dazn1hd=dazn1-malaspafro
dazn2hd=dazn2-malaspafro
mformula12020=movistarformula1-malaspafro
```

**srp.index**
```
76A4_41E_1_C00000=dazn1-malaspafro
772A_416_1_C00000=dazn2-malaspafro
7855_41A_1_C00000=dazn1hd-malaspafro
785F_41A_1_C00000=dazn2hd-malaspafro
74A4_41C_1_C00000=movistarformula1-malaspafro
7531_426_1_C00000=movistarformula1-malaspafro
```

# Logos

```
 movistar_dazn_and_formula1.zip
```
[movistar_dazn_and_formula1.zip](https://github.com/picons/picons/files/5862289/movistar_dazn_and_formula1.zip)

**Comment by qosobrin** [comment]
I forgot to include both versions of the formula 1 picon, default and light; here you have them.
[movistar-formula12020.zip](https://github.com/picons/picons/files/5865348/movistar-formula12020.zip)

Regards.

**Comment by AbuBaniaz** [comment]
If you want to replace the existing logos, there is no need to give them a different name. Also, if you have two `dazn=`  entries in the index, only one will get used. The `default/light` goes at end of name too.

I have added the formula 1 logos and links. Not sure about the dazn 1/2 as the grey shows, black won't show very well. This is why sometimes, on websites the provider uses a logo with slightly different background to the one on TV.

**Comment by Lexzie** [comment]
I checked the DAZN (España and Deutschland) logos and they are like the ones suggested by @qosobrin 
So I will replace the existing one.
Also all logos were not saved as optimized SVG's.
There was no need to name the formula 1 logos like that, it can simply be named 'movistarformula12020' since that is what's on the logo and that's how the channel is named.
Also some links were missing.
