### ISSUE TITLE
[HELP] servicelist-tvheadend-servermode-srp.txt empty

### ISSUE THREAD

**Issue by FunctionalHacker** [picons/picons#45]
Sorry for the noise, but I don't know where else to ask help with building picons. When running 1-build-servicelist.sh, this is the output:
```
19:02:50 - ERROR: Enigma2: /home/gimli/picons/build-input/enigma2 not found
19:02:54 - INFO: TvHeadend (server-mode): Exported to /home/gimli/picons/build-output/servicelist-tvheadend-servermode-srp.txt
19:02:54 - ERROR: VDR: /home/gimli/picons/build-input/channels.conf not found
```

And when I look at `servicelist-tvheadend-servermode-srp.txt` it is empty. Where should I begin to troubleshoot this?

**Comment by mrhotio** [comment]
You didn't post your configuration, did you configure it?

**Comment by wrohdewald** [comment]
I might have the same problem. Using self compiled tvheadend from July 6 2019, commit id 6be300c430ab614aa527ef34e34f007f34a68ee0

Adding debug output to 1-build-servicelist.sh gives:

`got rx_buf: {"entries":[{"uuid":"ec5e7200b729ecfb8ae9bb9935857b40","enabled":true,"autoname":false,"name":"Al Jazeera Documentary","number":59,"icon":"file:///home/vdr/logos/snp/aljazeeradocumentary.png","icon_public_url":"imagecache/3","epgauto":true,"epglimit":0,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":-1,"services":["de9ff71fa18fb6947e596e0ea3292649"],"tags":["45241861ecba3e6b0e32088b60b03fa9","b16f180baa8543fdeb01cc7e1ad7c9da"],"bouquet":""}],"total":237}`

`got serviceref:
`

So it seems this line cannot parse rx_buf:
`            serviceref=$(echo $rx_buf |  jq -r '.entries[].icon'  | grep -o '1_0_.*_.*_.*_.*_.*_0_0_0')
`
applying jq only gives

`file:///home/vdr/logos/snp/aljazeeradocumentary.png
`

**Comment by mrhotio** [comment]
Only srp is supported and the picon option should be enabled.

**Comment by AbuBaniaz** [comment]
Tvheadend supports SNP. Can our project be adapted for tvheadend users who want to use SNP too?

**Comment by mrhotio** [comment]
It can if someone makes a PR for it...

**Comment by FunctionalHacker** [comment]
Sorry I forgot to add my tvheadend config. I'm on mobile right now but I used this guide https://jamiej.co.uk/blog/working-picons-tvheadend-kodi/

I also tried both snp and srp. No idea what they are but neither of them worked. Happy to provide more info if needed

**Comment by mrhotio** [comment]
https://jamiej.co.uk/blog/wp-content/uploads/2017/04/Picons-TVHeadend-Configuration-Channel-EPG-1.png

Does your setup look like this? Look at User Icon.

**Comment by mrhotio** [comment]
Closing this due to lack of user response and the likelyhood of misconfiguration of tvheadend.

**Comment by FunctionalHacker** [comment]
I was just about to respond. I'm not yet at the point of even building the picons. I'm just trying to pull the servicelist from tvheadend, so is the user icon relevant at this stage? I changed most of them manually the other day to get some icons showing up.

**Comment by mrhotio** [comment]
It is VERY relevant, if it doesn't look like in the picture, it won't work. The guide you followed, mentions that, although he should have mentioned it at the start, not at the bottom.

We also mention the picon section at https://github.com/picons/picons#tvheadend-servicelist-creation

Also @wrohdewald his comment basically gives the solution on a silver platter.

**Comment by FunctionalHacker** [comment]
Okay I got the service list to populate now. Thanks a lot, I believe I got it from here.

**Comment by ReMiOS** [comment]
> I might have the same problem. Using self compiled tvheadend from July 6 2019, commit id 6be300c430ab614aa527ef34e34f007f34a68ee0
> 
> Adding debug output to 1-build-servicelist.sh gives:
> 
> `got rx_buf: {"entries":[{"uuid":"ec5e7200b729ecfb8ae9bb9935857b40","enabled":true,"autoname":false,"name":"Al Jazeera Documentary","number":59,"icon":"file:///home/vdr/logos/snp/aljazeeradocumentary.png","icon_public_url":"imagecache/3","epgauto":true,"epglimit":0,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":-1,"services":["de9ff71fa18fb6947e596e0ea3292649"],"tags":["45241861ecba3e6b0e32088b60b03fa9","b16f180baa8543fdeb01cc7e1ad7c9da"],"bouquet":""}],"total":237}`
> 
> `got serviceref: `
> 
> So it seems this line cannot parse rx_buf:
> ` serviceref=$(echo $rx_buf | jq -r '.entries[].icon' | grep -o '1_0_.*_.*_.*_.*_.*_0_0_0')`
> applying jq only gives
> 
>


Choose "Service name picons" in the General TVheadend config
When you use "Channel icon path" = "file:///<folder>/%C.png" in TVheadend config the picons are mapped to for instance  "file:///<folder>/bbcradio3.png"

Leaving this  "Channel icon path" blank maps to "picon://1_0_2_4707_840_600_FFFF0000_0_0_0.png"

Since i use a web server address to make the picons remotely available i want to use the bbcradio3.png name

After running 1-build-servicelist.sh the servicelist-tvheadend-servermode-snp.txt is empty.
So i made some changes to 1-build-servicelist.sh to make it work:

```
            # extracting service reference and skip the rest if nothing usable found
-            serviceref=$(echo $rx_buf |  jq -r '.entries[].icon'  | grep -o '1_0_.*_.*_.*_.*_.*_0_0_0')
+           serviceref=$(echo $rx_buf |  jq -r '.entries[].icon'  |grep -o \/.*.png|sed 's/21\///;s/\.png//')
or
+           serviceref=$(echo $rx_buf |  jq -r '.entries[].icon' |awk -F"/" '{print $NF}'|sed 's/.png//')

-            unique_id=$(echo "$serviceref" | sed -n -e 's/^1_0_[^_]*_//p' | sed -n -e 's/_0_0_0$//p')
-            channelname=$(echo $rx_buf | jq -r '.entries | .[] | .name')
+            serviceref=$serviceref
+            unique_id=$serviceref
```

After making these changes i succesfully made servicelist-tvheadend-servermode-snp.txt

```
# cat build-output/servicelist-tvheadend-servermode-snp.txt
100nl                        |  100% NL                        |  100nl=100procentnlfeest                         |  100nl=100procentnlradio
bbcfirst                     |  BBC First                      |  bbcfirst=bbcfirst                               |  bbcfirst=bbcfirst
bbcone                       |  BBC One                        |  bbcone=bbcone                                   |  bbcone=bbcone
bbcradio1                    |  BBC Radio 1                    |  bbcradio1=bbcradio1                             |  bbcradio1=bbcradio1
bbcradio2                    |  BBC Radio 2                    |  bbcradio2=bbcradio2                             |  bbcradio2=bbcradio2
bbcradio3                    |  BBC Radio 3                    |  bbcradio3=bbcradio3                             |  bbcradio3=bbcradio3
bbcradio4                    |  BBC Radio 4                    |  bbcradio4=bbcradio4                             |  bbcradio4=bbcradio4
bbctwo                       |  BBC Two                        |  bbctwo=bbctwo                                   |  bbctwo=bbctwo
```

Now you can create the picons with 2-build-picons.sh

This is not how the picons script is intended, but it works for me ....

**Comment by mrhotio** [comment]
Now that I think about it...snp has never been a supported thing for tvheadend, because they didn't support it at the time. And I never supported tvheadend, a user provided it and I've told him at the time that if it were to stop working and he didn't update it, I would remove it.

**Comment by ReMiOS** [comment]
I think you can leave it in 

When you choose "Service name picons" in the General TVheadend config
and leave the "Channel icon path" blank maps to "picon://1_0_2_4707_840_600_FFFF0000_0_0_0.png"

Now the 1-build-servicelist.sh creates the servicelist-tvheadend-servermode-snp.txt and servicelist-tvheadend-servermode-srp.txt
and  2-build-picons.sh creates the picons as intended (SNP and SRP)

The only downside is the picons have to be stored locally 

Thanks for the nice work, i am very happy with the picons :)
