### ISSUE TITLE
Movistar reordered some services

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#468]
Movistar has reordered some sports and one "on demand" channels. [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md) does not mention how to clean up old service references so I decided to add them at the beginning of the srp.index with the second part blank. Sorry if that's not the requested format.

**snp.index**
```
bajodemanda=movistarplus
mlaliga1=movistarlaliga1
mlaliga2=movistarlaliga2
mlaliga3=movistarlaliga3
mlcampeon1=movistarligadecampeones1
mlcampeon2=movistarligadecampeones2
mlcampeon3=movistarligadecampeones3
```

**srp.index**
```
769C_41E_1_C00000=
769F_41E_1_C00000=
75F4_422_1_C00000=
756B_412_1_C00000=
757A_412_1_C00000=
757F_412_1_C00000=
7580_412_1_C00000=
759E_422_1_C00000=movistarplus
760E_408_1_C00000=movistarlaliga1
77BD_40A_1_C00000=movistarlaliga2
7601_408_1_C00000=movistarlaliga3
77C3_40A_1_C00000=movistarligadecampeones1
760A_408_1_C00000=movistarligadecampeones2
77D8_40A_1_C00000=movistarligadecampeones3
```

**Comment by mrhotio** [comment]
there's no need to cleanup stuff, entries added at the beginning take preference

**Comment by AbuBaniaz** [comment]
Although no need to delete them, it is wise to do so. This is because in future, when a service reference is re-used for a different service, the wrong picon will show.  Just add a block asking for which references to delete.

**Comment by AbuBaniaz** [comment]
Most of the SNP links were there already. I've added the rest.
