### ISSUE TITLE
Missing channel: Russia Today

### ISSUE THREAD

**Issue by FunctionalHacker** [picons/picons#47]
srp index:
`FF0_6_0_FFFF0000=russiatoday`

Link to svg logo: https://upload.wikimedia.org/wikipedia/commons/a/a0/Russia-today-logo.svg

**Comment by AbuBaniaz** [comment]
We already had the logo. I have renamed them to make it easier in future. Your link has also been added.

**Comment by FunctionalHacker** [comment]
Thanks a lot!
