### ISSUE TITLE
Cuatro & Dreamworks

### ISSUE THREAD

**Issue by Jglez3** [picons/picons#491]
# SRP entries

**srp.index update**
Line 2923, there's a C letter missing on the reference
```
7792_424_1_C00000=cuatro
```

**srp.index addition**
```
750D_420_1_C00000=dreamworks
77C7_40A_1_C00000=dreamworks
```

# Logos
[dreamworks.zip](https://github.com/picons/picons/files/6024704/dreamworks.zip)

I attached the svg logo, but the onscreen logo on both HD and SD channels is without the "dreamworks" letters.

<img width="716" alt="CleanShot 2021-02-22 at 20 36 16@2x" src="https://user-images.githubusercontent.com/9308819/108760236-b1273380-754d-11eb-8dce-8a46eb3d5d7c.png">

**Comment by Lexzie** [comment]
Dreamworks I already did.

**Comment by Lexzie** [comment]
Service reference corrected.

**Comment by Jglez3** [comment]
Thank you!
