### ISSUE TITLE
new logos for channel re names 28.2 

### ISSUE THREAD

**Issue by leec32** [picons/picons#5]
hi 

could someone please make up these new logos for channel renames on 28.2.
sorry i can never do them correctly or i would make them up myself.

`15AF_7D7_2_11A0000=history2` was formally H2  old logo is also named history2
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb1879.png

`D039_83E_2_11A0000=truecrime` was formally Tru Tv 
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb5414.png

`D034_83E_2_11A0000=trucrimeplus1` was formally Tru Tv +1 
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb1015.png

`CB8D_831_2_11A0000=fascinationtv` was formally property show
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/100/00/skychb5297.png

thanks

**Comment by AbuBaniaz** [comment]
Some of the logos are already on repository, so no need to link to other sites

**Comment by leec32** [comment]
ok sorry, they are recent changes and didn't think they would be on, i normally do check first.
thanks anyway.

**Comment by leec32** [comment]
@AbuBaniaz 

can you check this one please, no picon showing on the new build 

`D034_83E_2_11A0000=trucrimeplus1`

thanks

**Comment by mcfly822** [comment]
@leec32 I think there was an error, which was corrected by @TheLegoBatman in commit https://github.com/picons/picons/commit/829c01ffe801da52f6e0d0aed057582ff3bd74b5

**Comment by leec32** [comment]
@mcfly822  ok thanks, i will check on next build
