### ISSUE TITLE
Missing indexes and 2 missing logos

### ISSUE THREAD

**Issue by FunctionalHacker** [picons/picons#50]
Sorry for the noise, this will be my last issue for a while :smile:  
Just wanted to upload my additions to srp.index because I built it by hand and other people might benefit from it. So here it is:

```
441_d_0_ffff0000=alfatv
15F_2_0_FFFF0000=ava
DC1_7_0_FFFF0000=ava
211_3_F_FFFF0000=fox
1AFA_13_0_FFFF0000=france24
1C4_B_0_FFFF0000=frii
260_7_0_FFFF0000=frii
C8_3_F_FFFF0000=aitoiskelmaharjujapontinen
1C2_2_0_FFFF0000=hero
9C_F_0_FFFF0000=hero
CC42_13_0_FFFF0000=inspirationtv
81_2_0_FFFF0000=jimfi
9A_F_0_FFFF0000=jimfi
B2_3_F_FFFF0000=kutonen
25F_7_0_FFFF0000=kutonen
B1_3_F_FFFF0000=liv
9B_F_0_FFFF0000=liv
31_2_0_FFFF0000=mtv3
CDB_14_0_FFFF0000=mtv3
C89_2_0_FFFF0000=mtv
28F_5_0_FFFF0000=mtv
C9_A_0_FFFF0000=nationalgeographic
41_2_0_FFFF0000=nelonen
1BC_F_0_FFFF0000=nelonen
2485_6_0_FFFF0000=rutv
61_2_0_FFFF0000=sub
DB7_7_0_FFFF0000=sub
BB9_F_0_FFFF0000=teliatvextra
3F8_7_0_FFFF0000=tlc
A1_2_0_FFFF0000=tv5fi
25E_13_0_FFFF0000=tv5fi
51_3_F_FFFF0000=yleteemajafem
5DF_14_0_FFFF0000=yleteemajafem
11_3_F_FFFF0000=yletv1
5DD_9_0_FFFF0000=yletv1
21_3_F_FFFF0000=yletv2
5DE_9_0_FFFF0000=yletv2
F03C_3_F_FFFF0000=taivastv7
F03D_B_0_FFFF0000=himlentv7
```

The last two icons are missing. The first one of them is basically the finnish verion of himlentv7, but I couldn't find a region specific logo for them. This logo would suit the both of them, it's without the text (taivas/himlen):
https://upload.wikimedia.org/wikipedia/fi/5/5a/TV7.svg

**Comment by mrhotio** [comment]
Don't know what "missing indexes' actually means....? I'm guessing you mean 'servicerefs'?
First one should be capitalized

**Comment by FunctionalHacker** [comment]
Sorry I'm still very much a newbie when it comes to this project. This list is what I needed to add to `srp.index` to get my servicelist to populate with icons

**Comment by mrhotio** [comment]
Please don't submit duplicate data in your issues.

**Comment by FunctionalHacker** [comment]
This is related to the other issue about the HD channel transition. 

As of now, almost all of the Finnish channels have an SD and HD variant. In addition to that, there are no HD channel icons for a lot of the channels. This is why I thought it was a better idea to just change the couple HD icons to just point to the "normal ones". 

I Is it okay if I upload it here with the hd channels added back?

**Comment by mrhotio** [comment]
please create a new issue

**Comment by mrhotio** [comment]
we try to follow the tv station as best as possible, but if no hd logo can be found, it's allowed to use the regular logo, work that has been done won't be destroyed until the tv station actually switches.

**Comment by FunctionalHacker** [comment]
Okay, that makes sense. I will open an issue in a few when I hunt down the HD channels back
