### ISSUE TITLE
New Movistar Dreamworks channel

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#508]
https://www.movistarplus.es/canal/dreamworks?id=DWSP

**snp.index**
```
dreamworks=movistardreamworks
dreamworkshd=movistardreamworks
```

**srp.index**
```
77C7_40A_1_C00000=movistardreamworks
750D_420_1_C00000=movistardreamworks
```

# Logos

```
movistardreamworks.zip
```

[movistardreamworks.zip](https://github.com/picons/picons/files/6064009/movistardreamworks.zip)

**Comment by TheLegoBatman** [comment]
This was already present. Please double check next time before opening an issue.

**Comment by qosobrin** [comment]
> This was already present. Please double check next time before opening an issue.

No, @TheLegoBatman, I was right and you are wrong. I double and triple checked and could not find any picon that was exactly equal to the one they are using: it does not contain any word, it is just the logo.

![image](https://user-images.githubusercontent.com/6613431/110246897-cf3b5d80-7f69-11eb-995e-1e23cafe4525.png)

Please, consider the one I commited to this issue.

Thank you very much.
Regards.

**Comment by TheLegoBatman** [comment]
This was resolved in issue  #491 .

**Comment by qosobrin** [comment]
Sorry to insist on this issue but the logo that Movistar is airing does not contain any letters, just the image, like the one I sent. This problem was pointed out by @Jglez3 when he opened his issue https://github.com/picons/picons/issues/491

> I attached the svg logo, but the onscreen logo on both HD and SD channels is without the "dreamworks" letters.

but it was ignored later on when the issue was resolved. I think that the logo should be corrected.

**Comment by TheLegoBatman** [comment]
I think the logo added by @Lexzie should be the one used. 

There are plenty of examples of logos not matching the one displayed on the screen.

**Comment by AbuBaniaz** [comment]
One benefit I see of removing the text is that the logo becomes bigger in the generated picon. I'm not fussed either way, the main  logo is iconic with/without the text.

**Comment by Lexzie** [comment]
I just used the logo which I found here: https://www.movistarplus.es/canal/dreamworks?id=DWSP

I agree the logo would be just as good without the text.

How about the colour? Is the blue to dark for a dark background and shall I make the moon with the boy transparent?

**Comment by qosobrin** [comment]
I have already provided a logo that matches the one on-screen.

**Comment by TheLegoBatman** [comment]
@Lexzie the standard logo looks good in dark background too so no need for a light one.
Edit: Looks good if it has a white in the middle. If only blue it needs a lighter version.

**Comment by Lexzie** [comment]
I want to do this tomorrow, do we agree to make the moon transparent, so the blue as default and a light version?

**Comment by Lexzie** [comment]
Because I prefer coloured logos I just left out the letters.
If this is okay please close the issue.
