### ISSUE TITLE
picons for DAZN 3 and 4

### ISSUE THREAD

**Issue by luka838** [picons/picons#523]
# picons for DAZN 3 and 4

**snp.index**
```
dazn3=dazn3hd
dazn4=dazn4hd
dazn3=dazn3sd
dazn4=dazn4sd

```

**srp.index**
```
74D8_3F8_1_C00000=dazn3hd
74D6_3F8_1_C00000=dazn4hd
77BE_40A_1_C00000=dazn3sd
77C0_40A_1_C00000=dazn4sd

```

# Logos

[dazn.zip](https://github.com/picons/picons/files/6095390/dazn.zip)

```
I don't have the actual logo for channels but I have sample for Numbers 3 and 4 with same font-type 
that used by DAZN I'm 100% sure of that. you could replace Numbers 3 and 4 in DAZN 1 or 2 logo 
```

**Comment by Lexzie** [comment]
Why the same name linking to different logos?

Having scanning the stations, the names still include `Test`, so I guess that won't be their names if the tests are over.
Right now it should be, assuming we will have just one logo for both SD and HD, like it is now for DAZN 1 and 2:

**snp.index**
```
testd3=dazn3
testd3hd=dazn3
testd4=dazn4
testd4hd=dazn4
```

**srp.index**
```
4D8_3F8_1_C00000=dazn3
74D6_3F8_1_C00000=dazn4
77BE_40A_1_C00000=dazn3
77C0_40A_1_C00000=dazn4
```

I see there's also a DAZN F1 station, so we need to find or make a logo for that one too.

Building the logos requires time, and we have to know and be able to obtain the font for the 3 and the 4.
This evening my time is limited to this reaction.

**Comment by qosobrin** [comment]
@Lexzie, DAZN F1 logo is already in the respository as per https://github.com/picons/picons/issues/504. @luka838, could you please tell me what's the font you used for the numbers. I looked for it but could not find it.

**Comment by luka838** [comment]
Hi Lexzie yes the channels still under Test period with name TEST D3 and TEST D4
yes logos for same HD and SD like DAZN 1 & 2 and like qosobrin said DAZN F1 is already in the respository

sorry qosobrin I found it in fonts-free-download site yesterday but I forgot which one
 but this how DAZN Canada and DAZN Espana type number 3, 4 in scoreline

EDIT: I believe I found it. but once again it's similar and not 100% the same
https://www.onlinewebfonts.com/download/4223340cd52dddaa529cb07e54bb0397
 
![EvgVtqZWYAQIGw3](https://user-images.githubusercontent.com/70975338/110217555-49fa6f00-7ebd-11eb-91e3-fcdf182029dd.jpg)
![EvUypAoXAAQtCDX](https://user-images.githubusercontent.com/70975338/110217557-4f57b980-7ebd-11eb-9f0b-6a01979f051e.jpg)

**Comment by Lexzie** [comment]
I checked my receiver for the DAZN F1 logo, I guess I have to update my receiver or check if the snp link is correct.

**Comment by Lexzie** [comment]
I made the logos and am about to upload all changes.
Can you please inform us when the names have changed from 'test' to the actual names?

**Comment by luka838** [comment]
Now the channels has been activated and names change to DAZN 3 HD and DAZN 4 HD and SD channels too.
https://www.movistarplus.es/canal/dazn-3?id=DAZN3
https://www.movistarplus.es/canal/dazn-4?id=DAZN4
I was on rush so I wrote DAZN 3 HD Service Reference wrong 4D8_3F8_1_C00000
right Reference is 74D8_3F8_1_C00000

**Comment by Lexzie** [comment]
Done
