### ISSUE TITLE
Channel changes

### ISSUE THREAD

**Issue by dazedcrazy** [picons/picons#53]
The True Movies/Entertainment channels have changed to Sony channels now.
Sony Channel (True Entertainment) https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb4266.png
Sony Movies Classic/Christmas (True Movies) https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3643.png
Sony Movies Action (Movies4Men) https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3708.png
Sony Movies has also changed https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3709.png
Sony Channel https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb4266.png
The do also have their plus 1's
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3751.png
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3771.png
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb5338.png
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3721.png
Sony Crime doesn't look like it changed logo from the Sky TV guide

**Comment by AbuBaniaz** [comment]
If these are for picons using service references, can you please provide them

**Comment by dazedcrazy** [comment]
I think they've all been added with https://github.com/picons/picons/commit/da72b7d1559385b347757c1f8e3b60205d84c8e6

**Comment by mrhotio** [comment]
He knows that, he's the one who did it. He wants you to provide additional details.

**Comment by dazedcrazy** [comment]
I don't use an enigma2 box so I've pulled these from tvheadend i hope they are what you mean
```
D048_83E_2_11A0000=sonymovieschristmas
D04D_83E_2_11A0000=sonyxmasplus1
D03E_83E_2_11A0000=sonymoviesaction
D075_83E_2_11A0000=sonymoviesactionplus1
D043_83E_2_11A0000=sonymovies
D06B_83E_2_11A0000=sonymoviesplus1
D07F_83E_2_11A0000=sonychannel
D084_83E_2_11A0000=sonychannelplus1
```
