### ISSUE TITLE
Editing radiomaria.default.svg

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#54]
Hello,

I try to edit the `radiomaria.default.svg` logo to make variants like
`Radio Marija`
![afbeelding](https://user-images.githubusercontent.com/14023349/65787409-2de78f80-e159-11e9-8408-e93be8cf26e5.png)

`Mária Rádió Erdély`
![afbeelding](https://user-images.githubusercontent.com/14023349/65787490-596a7a00-e159-11e9-8c46-660c00673f79.png)

But when I try to move a letter it disapears. Tried to make the editing area bigger but no results.
What's happening?

Also, the dark blue is poorly visible on a dark background.
Suggestions for a light variant?

**Comment by TheLegoBatman** [comment]
Try with this one. I just removed the clipPath.
[radiomaria.default.zip](https://github.com/picons/picons/files/3666668/radiomaria.default.zip)

**Comment by Lexzie** [comment]
First result:
![afbeelding](https://user-images.githubusercontent.com/14023349/65834922-6796d280-e2e0-11e9-87ca-f67aec83c8d6.png)

**Comment by Lexzie** [comment]
Have to figure out what font is used. Anyone knows?

**Comment by TheLegoBatman** [comment]
Seems close to Utopia std font. Try with that one.

**Comment by Lexzie** [comment]
Seems I don't have that font (yet)....

**Comment by Lexzie** [comment]
Finished
