### ISSUE TITLE
missing svg

### ISSUE THREAD

**Issue by cybero2912** [picons/picons#540]
./build-source/logos/skysportaustria3.default.svg  is missing

that is strange because :
skysportaustria1.default.svg
skysportaustria2.default.svg
skysportaustria4.default.svg
are there.

**Comment by TheLegoBatman** [comment]
The only one missing is the sky sport austria 3. I will add it soon once I figure out which font is used.

**Comment by cybero2912** [comment]
@TheLegoBatman thx a lot
