### ISSUE TITLE
picons in svg format

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons#550]
OpenPLI are testing addition of svg format. Is it possible we can also build picons in svg file extension if the logo is in svg format, png if no svg is present?

**Comment by cybero2912** [comment]
what is the benefit?

**Comment by BrianG61UK** [comment]
Improved scaling to different (especially large) sizes would presumably be the benefit.
But I don't know if it's worth the effort needed.
I mean in the sense that some sizes do sometimes look slightly ragged at the moment but I don't know if changing to svg would help or not.

**Comment by AbuBaniaz** [comment]
As an aside, could someone convert these to svg format for me please?
[PLi-FullNightHD.zip](https://github.com/picons/picons/files/6276152/PLi-FullNightHD.zip)

**Comment by AbuBaniaz** [comment]
There is too much processing using some SVG picons, so I doubt this will be a good idea.
