### ISSUE TITLE
please remove spaces from two entries

### ISSUE THREAD

**Issue by cybero2912** [picons/picons#554]
# SNP/SRP entries
# sorry but that was my fault  :(

please remove spaces in these two srp.index entries:
148_3 _85_FFFF0000=skysport9hd
152_4 _85_FFFF0000=skysport10hd

**srp.index**
```
148_3_85_FFFF0000=skysport9hd
152_4_85_FFFF0000=skysport10hd
```

**Comment by TheLegoBatman** [comment]
I should have double checked. Fixed now.
