### ISSUE TITLE
srp.index update Sky Sport F1 HD [Vodafone Cable Germany]

### ISSUE THREAD

**Issue by cybero2912** [picons/picons#560]
# SNP/SRP entries

**srp.index**
```
11_4_85_FFFF0000=skysportf1hd
```
what or who is 'phibruspel' ?
there is no 'skysportf1hd.default.svg' in ./build-source/logos/
only 'skysportf1hd-phibruspel.default.svg' found

**Comment by AbuBaniaz** [comment]
The suffix is added to distinguish between different versions of a logo

**Comment by AbuBaniaz** [comment]
Both are present.
https://github.com/picons/picons/blob/master/build-source/logos/skysportsf1hd.default.svg

https://github.com/picons/picons/blob/master/build-source/logos/skysportf1hd-phibruspel.default.svg

**Comment by TheLegoBatman** [comment]
Seems that the difference is that some are Sky Sports and others are Sky Sport with no S.

**Comment by AbuBaniaz** [comment]
That is the usual difference between Sky De (no S) and Sky UK (has S)

**Comment by TheLegoBatman** [comment]
Is this case then it seems there is no need for a ```skysportf1-phibruspel.default``` so we could rename those to ```skysportf1.default```.

Edit: Same goes for the hd one.

**Comment by cybero2912** [comment]
> That is the usual difference between Sky De (no S) and Sky UK (has S)

that's true
two options: dublicate skysportsf1hd.default.svg in skysportf1hd.default.svg
or link 11_4_85_FFFF0000  to skysportsf1hd
I don't care. ;)

**Comment by AbuBaniaz** [comment]
> Is this case then it seems there is no need for a `skysportf1-phibruspel.default` so we could rename those to `skysportf1.default`.
> 
> Edit: Same goes for the hd one.

I don't agree with this approach. As a rule of thumb, the `-phibruspel` logos have historically been the Austrian/German variants. I'd prefer they remained.

If a picon is being  made to point to `logo x`, but we want to use `logo y`, just change the link to point to `logo y`. There is no need to rename `logo x` and `logo y`. Otherwise we start anther can of worms of renaming logos just because the channel has changed its name slightly.

**Comment by cybero2912** [comment]
OK then  ;)

`
11_4_85_FFFF0000=skysportsf1hd
`
but we have german logo names without 's' for other Sky Sport cannels in ./build-source/logos/
example:  skysport1.default.svg, skysport2.default.svg  etc...

but as already mentionend:
**you decide, I am only a user  :D**

**Comment by AbuBaniaz** [comment]
We have different logos on the repository. The picons are made up with combining service references with the desired logo.

Your post is not making sense to me with regards to what needs to be done.  Please post what link should be deleted.
E.g Please delete `xxxxxxxx`

Please post what needs to be added
e.g Please add `yyyyyyy`

**Comment by cybero2912** [comment]
I know how to request additions 

it was no post it was a reply to this "discussion" about the naming

**Comment by AbuBaniaz** [comment]
So ok to close this then?

**Comment by cybero2912** [comment]
yes
