### ISSUE TITLE
srp.index update Sky Sport F1 HD [Vodafone Cable Germany]

### ISSUE THREAD

**Issue by cybero2912** [picons/picons#566]
# SNP/SRP entries

**srp.index**
```
11_4_85_FFFF0000=skysportsf1hd
```

**Comment by AbuBaniaz** [comment]
You have just posted a link. What do you want done with it?

**Comment by cybero2912** [comment]
adding to index ?
like in #565 
@TheLegoBatman knows what to do with it  ;)

**Comment by AbuBaniaz** [comment]
You could have said that in the other issue instead of closing it and starting another issue. I have added it.

Please try submitting a pull request for your next set of changes

**Comment by cybero2912** [comment]
I said that in other issue, or thought I did
maybe a misunderstanding
I don't know if I am allowed or have enough rights to create pull requests
and according to the rules here this is the way to request an index update

**Comment by AbuBaniaz** [comment]
You just posted a link without saying anything. So yes, maybe misunderstanding, hopefully I've added what you want/need. Anybody can submit a pull request.
