### ISSUE TITLE
RMC Sport Live 5 to 16

### ISSUE THREAD

**Issue by Altaess** [picons/picons#57]
Hi,

Can you please add RMC Sport live 5 to 16 logo in french pack?
You can found them here : http://tvepg.eu/fr/france/epg/sports or http://tv.sfr.fr/epg/maintenant/RMC%20Sport-51601/

Thank you for your database, it's awesome

**Comment by TheLegoBatman** [comment]
Hi. What are the names to link them to?

For more info visit https://github.com/picons/picons/blob/master/CONTRIBUTING.md.
