### ISSUE TITLE
Changing colour on svg logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#58]
I don't get it how this SVG is coloured
I have this logo:

I want these two logos:
![afbeelding](https://user-images.githubusercontent.com/14023349/66155384-cb423800-e61f-11e9-8164-fd3af6ec0993.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/66155433-e4e37f80-e61f-11e9-8780-45a3a0047ef6.png)

Can anyone help?

**Comment by TheLegoBatman** [comment]
Can you upload the svg?

**Comment by Lexzie** [comment]
Huh?? It was there (in a zip file), let's try again:
[m1film.zip](https://github.com/picons/picons/files/3688174/m1film.zip)

**Comment by mcfly822** [comment]
Maybe something like this:
[m1film_mcfly822.zip](https://github.com/picons/picons/files/3689695/m1film_mcfly822.zip)

**Comment by Lexzie** [comment]
Thank you, that's perfect.
But now I still can't change the colours of the letters '**FILM**' for a `default` logo (meant for a light background).

**Comment by mcfly822** [comment]
In inkscape, open the file, then CTRL+A (select everything) and press CTRL+SHIFT+G one time. It ungroups the drawing. After this you can select only the part "film", and colorize with another color. I tried this just now and works without doubt.

**Comment by Lexzie** [comment]
I'm sorry, after Ctrl-Shift-G I select one of the ends of the gradient and change the color-code, but nothing changes.

**Comment by Lexzie** [comment]
@mcfly822 Can you help me making the letters `FILM` dark?

**Comment by mcfly822** [comment]
> I'm sorry, after Ctrl-Shift-G I select one of the ends of the gradient and change the color-code, but nothing changes.

@Lexzie For me, this worked... I don't why this not working for you.
I made the letters in dark.
[m1filmbluered_darkletters_mcfly822.zip](https://github.com/picons/picons/files/3723281/m1filmbluered_darkletters_mcfly822.zip)

**Comment by Lexzie** [comment]
Thanks!
