### ISSUE TITLE
download latest release 

### ISSUE THREAD

**Issue by leec32** [picons/picons#59]
hi

i am trying to download the latest release but all i see is snp picons no srp and last released on the 13th sept, am i missing something ?

thanks

**Comment by mrhotio** [comment]
no, you are not missing something

**Comment by mrhotio** [comment]
new release is currently building

**Comment by leec32** [comment]
ah ok, thanks

**Comment by leec32** [comment]
Is their no srp anymore or is it still building ?

thanks

**Comment by mrhotio** [comment]
no there's no srp, I think snp is good enough for most....if there's enough demand I can maybe re-enable it, but I need to stay under 1 hour for the builds.
