### ISSUE TITLE
srp-link in snp.index not working

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#60]
On 16E is a radio station with the name `radio 1`, but that one is already used for VRT Radio 1.
So I added 'BB9_5E24_16E_A00000=radio1-slegilimeh` where as `radio1-slegilimeh` is the correct logo for this channel.
Still the logo for VRT Radio 1 is shown.
Is there a way to get the right logo on that channel?

**Comment by mrhotio** [comment]
1) there's no logo `radio1` used for VRT Radio 1, not even for any other channel
2) can't see anything wrong at first look, but `Still the logo for VRT Radio 1 is shown.` isn't a good measure, you should look at the servicelist, to see how it's linked.

**Comment by mrhotio** [comment]
Only problems I can think of....

1) a bug in enigma2
2) `BB9_5E24_16E_A00000` is actually an incorrect serviceref

**Comment by AbuBaniaz** [comment]
Is the reference in the picon pack that is on receiver? If not, no point looking at E2.

**Comment by Lexzie** [comment]
No, there isn't a logo `radio1` but there is a link `radio1=vrtradio1`. (So I can and have renamed `radio1-slegilimeh` to `radio1`).
But that's not the problem: There are two different radio-stations with the name `radio1`, so I added an srp-link in snp-index `BB9_5E24_16E_A00000=radio1`.

The serviceref is `1_0_2_BB9_5E24_16E_A00000_0_0_0`.
Maybe it;s caused by the `1_0_2_` (instead of `1_0_1_`)?

If I check the folder /picon on my Enigma2-receicver I indead see a symlink `1_0_1_BB9_5E24_16E_A00000_0_0_0.png`.
If I manually add the symlink `1_0_2_BB9_5E24_16E_A00000_0_0_0.png` I get the right picon.

Conclusion: srp-link for a radio-station is not possible.
I think we discussed this before? I thought this was somehow solved (although I can't think of how).

**Comment by mrhotio** [comment]
That's indeed the problem 102 vs 101 and can be solved by building against a lamedb.

**Comment by Lexzie** [comment]
> That's indeed the problem 102 vs 101 and can be solved by building against a lamedb.

How? The serviceref is in lamedb.

**Comment by Lexzie** [comment]
I stumble upon this again, examples `Love Radio` on Hotbird and `RTL 2`, a French radiostation. And there are more. Besides that, when I install srp-logos (instead of snp) I have no logo for any radiostation. I would say, it's no use adding srp-links for radio stations in srp.index?

@hotio :
What is exaclty meant by "building against a lamedb"? How is that done?

**Comment by mrhotio** [comment]
1) it has a use
2) when building against a lamedb, only existing channels inside that db are used and a lookup is done to see if 101, 102, 1019, ... has to be used. Withoutt it, just 101 is picked.

**Comment by Lexzie** [comment]
If that's the case, then I don't know why the radiostations show another picon.

Example: RTL 2 gets the logo of the German TV station. Both are in lamedb I guess, since I have scanned them.

**RTL 2**, Astra 1N (19.2°E), 12363 V, DVB-S, SR:27500, FEC:3/4, QPSK, SID 9186
**RTL Zwei** (the one using the name 'RTL2'), Astra 1L (19.2°E) 12188 H, DVB-S, SR:27500, FEC:3/4, QPSK, SID 12020

RTL 2 has service reference 1_0_2_23E2_44A_1_C00000_0_0_0, therefor in snp.index:
```23E2_44A_1_C00000=rtl2```
Also in snp.index, because the German TV station uses (also) the name `RTL 2`:
```rtl2=rtlzwei```

Perhabs I still don't understand what building againts a lamedb means.
I, like I guess a lot of users, just install the picons from the feed or ipk.
I tested on my receiver by first deinstalling the picons and then installing them again.
Still the wrong picons.

**Comment by AbuBaniaz** [comment]
Build against lamedb = place a lamedb file in your build sources

Downside of this is that you will only have links for services that are in lamedb.

**Comment by Lexzie** [comment]
Like I said, I don't build the source. Just install/update the picon-package.
I guess like every normal user does, so they have the wrong picons too.

**Comment by mrhotio** [comment]
Ofcourse they have the wrong ones, you can reinstall untill your fingers bleed....the picons that we build are NOT build against a lamedb, if you want flawless picons, you should build them yourself. The only way for us to do it is if somebody uploads a regularly updated lamedb from a motorized setup. But after all these years and me repeating myself over and over, that hasn't happened.

**Comment by Lexzie** [comment]
I never heard that request.
I need to correctly setup my dish, but after that I can receive Ku-band from 42E-37.5W, with 120cm.
If you still like to have the lamedb I can upload it.

**Comment by mrhotio** [comment]
if you can keep it up2date, sure
