### ISSUE TITLE
Comedy Central srp Update and white picon missed

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#63]
Please Update srp.index because viva ist gone since 2018

5E25_B5_270F_FFFF0000=comedycentral_viva
B02D_1C3_270F_FFFF0000=comedycentralhd_vivahd
33F8_85_DE_FFFF0000=comedycentralhd_vivahd

must be

5E25_B5_270F_FFFF0000=comedycentral
B02D_1C3_270F_FFFF0000=comedycentralhd
33F8_85_DE_FFFF0000=comedycentralhd

I also create a white svg ;)

[comedycentral.white.svg.zip](https://github.com/picons/picons/files/3731121/comedycentral.white.svg.zip)

thx

**Comment by Lexzie** [comment]
Done
