### ISSUE TITLE
picons.eu domain appears to have expired.

### ISSUE THREAD

**Issue by BrianG61UK** [picons/picons#630]
The picons.eu domain appears to have expired yet you are still showing it on your front page https://github.com/picons.

**Comment by AbuBaniaz** [comment]
@mrhotio 
Any update on this please?

**Comment by mrhotio** [comment]
url is removed from the front page now. it was no longer financially feasable to keep the domain, 0 donations and almost 0 ad revenue

**Comment by BrianG61UK** [comment]
Okay. :(
Closing issue now.
