### ISSUE TITLE
ardalphahd picons missed

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#64]
Hey i missed the picon for ardalphahd so i create 3 for default, light and white ;)

[ardalphahd.zip](https://github.com/picons/picons/files/3731145/ardalphahd.zip)

please add them
thx

**Comment by Lexzie** [comment]
Done and added/changed links for Astra 19,2E.
I cannot check the other srp-links.

**Comment by SmoothMC** [comment]
ah i forgot
i only can can deliver it for cable dvb-c (Kabel Vodafone)
C38D_2722_F001_FFFF0000

**Comment by Lexzie** [comment]
Added the link.
