### ISSUE TITLE
light and white picons bbcworldnews and bbcworldservice missed

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#66]
i missed the light and white picons for these services - so i create them

[bbcworldnews.zip](https://github.com/picons/picons/files/3731191/bbcworldnews.zip)

please add them
thx

**Comment by Lexzie** [comment]
I only added the `white` logos.
There's no need for a `light` logo since the `default` logo is perfectly visible on a dark background.

**Comment by Lexzie** [comment]
Please don't upload the wrong logo for BBC World Service.
Now I got blamed for it.

**Comment by SmoothMC** [comment]
ok? but in the srp the bbcworldnews picon is also used for bbcworldservice picon
can you check it please

sry Lexzie this was not my intention
next time i double proof it

**Comment by SmoothMC** [comment]
here is the correct one for bbcworldservice.white

sry again

[bbcworldservice.white.zip](https://github.com/picons/picons/files/3735482/bbcworldservice.white.zip)

**Comment by Lexzie** [comment]
In snp.index is `bbcworldservice=bbcworldservice` defined. So BBC World Service uses bbcworldservice logo. Maybe in srp.index there's a wrong link. No way to quickly check that.
If you have a wrong picon on BBC World Service, give me the Service Reference, so I can check.

Uploaded the new white logo.
