### ISSUE TITLE
mtv white picon missed

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#68]
i missed the white picon for mtv - so i create it

[mtv.white..zip](https://github.com/picons/picons/files/3731685/mtv.white.zip)

please add it
thx

**Comment by Lexzie** [comment]
This logo is the same as the `light` logo.
I'm not sure, but I beleive for building the `white` picons when there is no white variant first the light variant is used?

**Comment by SmoothMC** [comment]
hey i testet it without the .white and it used the .default as standard :/
it would be great if building use the .light one if exists. but for now it doesn't do it

**Comment by mrhotio** [comment]
No, everything will fall back to default. But why add a white one, there are hardly any included.....

**Comment by Lexzie** [comment]
If it was up to me we don't add white logos at all, apparently someone uses them?

**Comment by SmoothMC** [comment]
i only use the white ones it looks much better in kodi

my opinion the best why when create white picons the fallback ist light when the white one is missed...i there a way to update the code?

it would be nice
thx

**Comment by Lexzie** [comment]
If @hotio is okay with it I can add the white logo.

**Comment by mrhotio** [comment]
Sure, all white logos may be added, just wanted to make sure we don't mixup white and light. A white logo can only contain 'white' FFFFFF fyi

**Comment by Lexzie** [comment]
The `light` logo also only contains 'FFFFFF'. So that's why I was in doubt wether to submit the same logo.

**Comment by mrhotio** [comment]
MTV is an odd one since the default is all black.
