### ISSUE TITLE
ITV4 & ITVBe (UK) Picons not showing from Commit in Issue 679

### ISSUE THREAD

**Issue by carpcat** [picons/picons#682]
A number of service refs changed recently for ITV, and the new srp indexes listed in Issue 679. Most of these are now showing in the latest build, however ITV4 and ITVBe are not displaying. ITV4 I believe is my mistake as I left a gap between the service ref and ‘=itv4’. The correct line is now shown below.

**srp.index**
```
27B4_805_2_11A0000=itv4
```

With ITVBe, I can not see the reason why it’s not showing? I’ve checked the correct service ref and the naming of ‘itvbe’ is correct for the channel as below. Anyone else able to offer an explaination?

**srp.index**
```
27F9_806_2_11A0000=itvbe
```

**Comment by AbuBaniaz** [comment]
Must have been my mistake, there was a space at end of the line. Sorry.
