### ISSUE TITLE
sonlife white picon missed

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#69]
i missed the white picon for sonlife - so i create it

[sonlifetv.white.zip](https://github.com/picons/picons/files/3731688/sonlifetv.white.zip)

please add it
thx

**Comment by mrhotio** [comment]
Do you think it's funny to zip every logo seperate and create a bunch of issues? Do I have to write this comment in every issue too?

**Comment by Lexzie** [comment]
For commiting svg-files you have to zip it, but I agree it would be better to combine all the files in one zip-file and one issue.

**Comment by Lexzie** [comment]
Done

**Comment by SmoothMC** [comment]
i will keep it in mind ;) thx
