### ISSUE TITLE
New Movistar pop-up channel

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#696]
Movistar has a new pop-up channel (https://www.movistarplus.es/vhs)

# SNP/SRP entries

**snp.index**
```
mvhs=movistarvhs
```

**srp.index**
```
749D_41C_1_C00000=movistarvhs
```

# Logos

[movistarvhs.zip](https://github.com/picons/picons/files/6633508/movistarvhs.zip)

**Comment by Lexzie** [comment]
Already added, PR #693

What was your source for the svg images?

**Comment by qosobrin** [comment]
> Already added, PR #693
> 
> What was your source for the svg images?

I made it myself using this image https://www.movistarplus.es/recorte/e/original/33645aefb4fc23e5903187ff06cc15ea as a template, this font is https://www.dafont.com/vcr-osd-mono.font and five minutes work.

Regards.

**Comment by Lexzie** [comment]
Nice. How did you find out what the font is?

**Comment by qosobrin** [comment]
I was very lucky. I googled "VHS bitmap font" and, voilà, there it was. :-D It seems that the people at Movistar didn't bother much either to search for a font to use.

**Comment by Lexzie** [comment]
Can you make the Movistar Amenábar logo as SVG too?
https://www.movistarplus.es/recorte/m-NEO/canal/MAMEN.png
https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/09/1_0_1_749D_41C_1_C00000_0_0_0-2.png

**Comment by Lexzie** [comment]
It's already done (PR #864)
