### ISSUE TITLE
Snp

### ISSUE THREAD

**Issue by ladigb** [picons/picons#7]
Hi
any chance for snp 400x240 

Regards

**Comment by TheLegoBatman** [comment]
It seems it didn't build for some reason. Meanwhile extract the ipk for that size or install as is.

@hotio

**Comment by mrhotio** [comment]
They build fine, but the upload to github crapped out...no idea why, as far as I can see there are no github limits for releases....we'll have to see next build.

**Comment by ladigb** [comment]
no problem i will wait for it.

**Comment by mrhotio** [comment]
Builds are on their way, let's hope for the best.
https://drone.mailboxy.eu/picons/picons/19

**Comment by TheLegoBatman** [comment]
It worked. That size is present now.

**Comment by mrhotio** [comment]
lol, only took 03:49:18

**Comment by TheLegoBatman** [comment]
:smile:
