### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by mrhotio** [picons/picons#70]
I'm not sure how I should get your attention, because you keep ignoring my comments in our team discussion... But, you keep adding false entries, don't you check the build warnings??

**Comment by Lexzie** [comment]
Which discussions? Last thing I saw was the worry about charlesduco. Or is there anywhere else a discussion which I'm not aware of?

What false entries are you reffering to? And are you sure I am responsable for all of them?
And I'm very sorry if sometimes a typo occurs, with so many commits I make it can happen sometimes although I check it before uploading.

What are build warnings? I use GitHub Desktop as you all have been so kind to learn me, apparantly I am not doing all the steps right?

**Comment by mrhotio** [comment]
https://cloud.drone.io/picons/picons/75/1/2

See the 'checks' section

**Comment by mrhotio** [comment]
PS: don't get me wrong, your hard work is very much appreciated :-).

**Comment by Lexzie** [comment]
I don't understand.
Most of those errors I had it corrected.
Like the ifilm2 logo should be uploaded in the same commit when I committed the link.

Have to sleep now, hope I can check it soon.

**Comment by mrhotio** [comment]
I can only find this one https://github.com/picons/picons/blob/master/build-source/logos/ifilm.default.png

**Comment by mrhotio** [comment]
Check my commit in which I fixed the build warnings to verify if that's the expected output.....
