### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by myhobby2** [picons/picons#700]
Is there a script available (to be used for an Enigma2 compatible receiver) that downloads the Picons you created based on:
- Picon size/type available here in the github ( set your preferred Picon type in this script) 
- Select TV or Radio or all Picons
- Scan the favourite (TV/Radio/All) lists in /etc/enigma2 to see which channels are in use
- Download the Picons, from the correct set, belonging to these channels in the correct place in the enigma2 file structure
- Create the necessary links between the downloaded Picons and Channels
End of script...

I'm currently running out of space with 400x220 Picons, but most of them I don't need in my life. By using a script like this I save flash memory which I can use for some plugin. 

If it does not exist, can it be created ;-)

**Comment by Lexzie** [comment]
I hope someone can answer this, I couldn't so I pointed out the possibility to commit an issue for this.

When we build the ipk's for 13e.19e.23e.28e I guess a similar script is used?

@mrhotio Can you help?

**Comment by mrhotio** [comment]
No script exists to do all that.

**Comment by Lexzie** [comment]
I'm afraid @myhobby2 you have to think of a solution yourself.
Try building the picons yourself, maybe along the way you'll find a way.

**Comment by mrhotio** [comment]
Yep building yourself is exactly why this is all opensource...

**Comment by myhobby2** [comment]
Thanks for the response. I will give building the picons myself a try. Just didn't want to re-invent the wheel.
