### ISSUE TITLE
new services to DVB-T2 Germany (update)

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#72]
hey...me again. here some updates to the german dvb-t2 network

4240_4061_2114_EEEE0000=disneychannelhd
4242_4061_2114_EEEE0000=dmaxhd
4243_4061_2114_EEEE0000=eurosport1hd
4222_4031_2114_EEEE0000=kabeleinshd
4244_4061_2114_EEEE0000=nickhd
4205_4001_2114_EEEE0000=rtlnitrohd
4204_4001_2114_EEEE0000=ntvhd
4224_4031_2114_EEEE0000=prosiebenmaxxhd
4221_4031_2114_EEEE0000=prosiebenhd
4200_4001_2114_EEEE0000=rtlhd
4203_4001_2114_EEEE0000=rtl2
4225_4031_2114_EEEE0000=sat1goldhd
4220_4031_2114_EEEE0000=sat1hd
4223_4031_2114_EEEE0000=sixxhd
4226_4031_2114_EEEE0000=sport1hd-wispelutri
4202_4001_2114_EEEE0000=superrtlhd
4206_4001_2114_EEEE0000=tele5hd
4201_4001_2114_EEEE0000=voxhd
4249_4061_2114_EEEE0000=freenetshopping

for this service there is no logo for now in the source
424A_4061_2114_EEEE0000=qvc2hd
4241_4061_2114_EEEE0000=welthd

thx for add

**Comment by Lexzie** [comment]
I've changed dmaxhd to dmaxhd-wispelutri, since that is the German one.
For now I used `qvc2` and `welt`.
If you can supply the `hd` logos also re-submit these links.
