### ISSUE TITLE
Puls 24 / Puls24 HD (AT, new channel)

### ISSUE THREAD

**Issue by bernhardberger** [picons/picons#74]
We have a new TV channel in Austria: Puls24 and Puls 24 HD (a sister channel to Puls 4).

Would it be possible to add a logo for that one? I hate starring at a naked/blank field when switching to the channel for NFL ;-)

https://www.puls4.com/Puls24
https://www.tele.at/senderinformationen/412/puls-24.html

https://www.satindex.de/channel/29340/

**Comment by mrhotio** [comment]
We could if you provide us with the needed info as requested in CONTRIBUTING.md

**Comment by Lexzie** [comment]
I tried finding a decent logo for that channel, because I also want a logo for that channel, but I couldn't find it (yet).
Maybe later I will give it a try again.

**Comment by Lexzie** [comment]
I found a 1763x473 pixel image, I can upload it together with the links for Astra 1N.

**Comment by Lexzie** [comment]
Done, if you have more links re-open this issue.
