### ISSUE TITLE
New channels Ukraine 1 and 2

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#76]
New on Astra 1N at 19.2°E: 11568 V, FTA (at the moment).
For Ukraine 1 I made this:
![ukraine1 default](https://user-images.githubusercontent.com/14023349/67625512-699c7480-f83f-11e9-91ca-f245da794762.png)

But no luck for Ukraine 2 yet, it should be like this:
![ukraine2](https://user-images.githubusercontent.com/14023349/67625517-7d47db00-f83f-11e9-93b9-0cd873f8ec1e.png)

These channels are part of the Media Group Ukraine:
https://mgukraine.com/en/assets/tv/

Also offered in Kartina IPTV package: https://www.kartina.tv/en

Can anyone help with the logo for Ukraine 2?

**Comment by mcfly822** [comment]
I found this, not the best qulity, but this is the official 😈 😄 
![ukraine2](https://user-images.githubusercontent.com/22531870/67626233-ccded480-f848-11e9-8f16-4fa818922272.png)
Source: http://trkmedia.ollcdn.net/uploads/mgu-www/15623297821184.pdf

**Comment by Lexzie** [comment]
I polished up the logo, I think this is acceptable.
![ukraine2 default](https://user-images.githubusercontent.com/14023349/67627736-007a2880-f862-11e9-99ba-209c7879072d.png)

If this is okay I will upload this and a few more Russian and Ukrainian logos tomorrow.
