### ISSUE TITLE
Old deleted logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#77]
Where can I find logos that are deleted from the repository?
I want the former 'sonychannel' logo. The Russian version is still using that logo.
https://www.sonychannel.ru/

**Comment by mrhotio** [comment]
Didn't I warn in the past for not deleting logos to fast? You can find the commit that deleted/changed the logo...

**Comment by Lexzie** [comment]
Let's make things clear first: I didn't delete the logo. In the past we had more changes like this (think of Discovery Science, Animal Planet, Nickelodeon), and I always paid a lot of attention if the old logo really isn't somewhere still in use.

Is there a way to search in the commits?

**Comment by mrhotio** [comment]
I'm not saying you did it, but there have been conversations in the past of people wanting to do a good cleanup... If the logo has been replaced, we could look at the git commits done to that file. If it was just deleted it might be harder. Maybe it's possible to search for it with some cli magic...

**Comment by mrhotio** [comment]
https://github.com/picons/picons/blob/85baff117a4538b54a2786c5c92f65521066db69/build-source/logos/sonychannel.default.png

**Comment by mrhotio** [comment]
https://github.com/picons/picons/blob/85baff117a4538b54a2786c5c92f65521066db69/build-source/logos/sonychannel.light.png

**Comment by Lexzie** [comment]
Thanks for recovering the logos, but I see now that the logo for Sony Channel Russia is a little bit different. I found the right one,
