### ISSUE TITLE
Improving Kuwait TV logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#78]
Hi @all,

I was going to make light variants of the `ktv...`-logos, but they are not really very good quality.
I could not find any better quality logos, maybe someone else is more lucky?

As an example, this is the currect ktv1-logo:
![ktv1 default](https://user-images.githubusercontent.com/14023349/68773129-4dfce080-062b-11ea-8a01-516f2a0463b5.png)

First of all, there is too much empty space around the logo, removing that results in this:
![afbeelding](https://user-images.githubusercontent.com/14023349/68773241-7edd1580-062b-11ea-8dd5-949df7dff3bc.png)

And this is the best I could do on making a light variant:
[ktv1.zip](https://github.com/picons/picons/files/3841743/ktv1.zip)

Before I do the same for ktv1plus, ktv2, ktvalaraby, ktvethraa, ktvsport and ktvsportplus I like your opions.

**Comment by mrhotio** [comment]
[68773129-4dfce080-062b-11ea-8a01-516f2a0463b5.zip](https://github.com/picons/picons/files/3842054/68773129-4dfce080-062b-11ea-8a01-516f2a0463b5.zip)
I made an svg from it, not perfect, but better

**Comment by mrhotio** [comment]
PREVIEW
![g4528](https://user-images.githubusercontent.com/26902309/68779592-2b6fc500-0635-11ea-8b1a-0755f4599ddd.png)

**Comment by mrhotio** [comment]
But why are you cropping the whitespace and re-uploading them again? Now they take up twice the space and no benefit at all in the output. The cropping should happen the first time, otherwise it's pointless.

**Comment by Lexzie** [comment]
I don't understand what you mean.
I was told there should be no whitespace around the logo, so that's why.
And why you say they take up more space?

```
 -9.75 KB (62%) build-source/logos/ktv1.default.png
 -474 Bytes (98%) build-source/logos/ktv1hd.default.png
```

In my opinion is that less space.
Or do you mean the logo is bigger? If it was good quality that would sure be my goal.

The SVG is probably made by tracing the bitmap? After that a lot fine-tuning is needed if it that is even possible with the Arab text.

**Comment by mrhotio** [comment]
They will always remain in the github history... The whitespace is cropped on building the picons.

It works different than you think, not 62% and 98%, but +200%....And indeed ideally whitespace should be trimmed, the First time, after that the damage is already done. We don't wanna end up with a repo several GB's, if we can avoid it.

**Comment by Lexzie** [comment]
Okay, so no way to get rid of it.
What's the problem when it remains in the history?
