### ISSUE TITLE
Identifying this font

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#79]
To build these logo's (without the background) I need to know what font is used and preferably where to find it (for free).

![afbeelding](https://user-images.githubusercontent.com/14023349/68998443-bd383600-08b2-11ea-8fe7-7b2dc26d8d75.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/68998447-c0cbbd00-08b2-11ea-8b59-c5696cf3cc15.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/68998449-c3c6ad80-08b2-11ea-865b-bced00dd1c69.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/68998450-c6c19e00-08b2-11ea-9bd1-38ff00a5ff8f.png)

**Comment by mrhotio** [comment]
![bannerx](https://user-images.githubusercontent.com/26902309/68999002-23748700-08ba-11ea-9d82-dfa482a0530e.png)
<img width="600" alt="facebookShareImage 89488910" src="https://user-images.githubusercontent.com/26902309/68999003-240d1d80-08ba-11ea-9f98-3e0c2883075a.png">

I'm unable to identify the fonts and the ones that were pretty close cost $$

**Comment by Lexzie** [comment]
Paying $$ (or €€) is not the intention.
Thanks for searching.

Maybe I will have to build png's.

**Comment by mrhotio** [comment]
just pick something that looks close enough and free, nobody will notice

**Comment by Lexzie** [comment]
Good thinking. I will give it a try later.
