### ISSUE TITLE
Movistar+ (Spain) changes

### ISSUE THREAD

**Issue by Jglez3** [picons/picons#791]
Hi, some frequencies came back to its original channels since the Olympics finished.

To add or modify srp.index:

**srp.index**
```
77C2_40A_1_C00000=movistardeportes2
77BF_40A_1_C00000=movistardeportes3
77C8_40A_1_C00000=movistardeportes4
769B_41E_1_C00000=movistardeportes5
75FF_408_1_C00000=movistardeportes6
7602_408_1_C00000=movistardeportes7
```

Thanks.

**Comment by AbuBaniaz** [comment]
I have added the links you posted. If that is not what you wanted, please re-open issue and rephrase your request.

**Comment by Jglez3** [comment]
That's it. Thanks.
