### ISSUE TITLE
Last commit "Optimize all svg files" broke MANY picons

### ISSUE THREAD

**Issue by pexner** [picons/picons#8]
The last commit "Optimize all svg files" broke MANY picons.
They are disorted, broken, unreadable.
Please revert!

**Comment by AbuBaniaz** [comment]
Can you post a picture showing what you mean please?

**Comment by pexner** [comment]
This should be "ntv HD". And almost 70% of all picons are mangled like this.
![_tmp_1552501894261](https://user-images.githubusercontent.com/7347603/54305066-d6bc0c00-45c6-11e9-8a30-06efb11cc1d1.png)

**Comment by pexner** [comment]
This is "BBC ONE". LOL
![_tmp_1552502114230](https://user-images.githubusercontent.com/7347603/54305275-403c1a80-45c7-11e9-8c88-8947d95717e6.png)

**Comment by TheLegoBatman** [comment]
How are you building them?

**Comment by pexner** [comment]
Like this:
220x132;220x132;light;transparent

**Comment by AbuBaniaz** [comment]
We had this issue before. The SVG files have to be cleaned with specific options. I'll post details later

**Comment by pexner** [comment]
Could you please revert the commit, until it's fixed or a solution is known, please?

**Comment by secuflag** [comment]
Looks strange, I built picons two times before to push the commit and I didn't see any broken images.

**Comment by TheLegoBatman** [comment]
We did but the problem ended up being with the building process and the rsvg-convert version. Which version of rsvg-convert are you using @pexner ?

I also just built that specific size and type and those two logos are not broken.

**Comment by pexner** [comment]
rsvg-convert version 2.40.5
Debian 8, up to date

**Comment by pexner** [comment]
I just followed the readme:
`sudo apt-get install git binutils pngquant imagemagick librsvg2-bin jq`

**Comment by AbuBaniaz** [comment]
It was the logos themselves. Issue didn't show when viewing with inkscape, but did with another program.

I had used jasmeets logos. I'll check my emails when I get home.

**Comment by pexner** [comment]
`# convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-11-11 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib`

**Comment by mrhotio** [comment]
beware of these auto optimize programs, in most cases they do more harm then good

**Comment by pexner** [comment]
Tanks for the revert.

**Comment by TheLegoBatman** [comment]
@AbuBaniaz sorry, I thought you meant issue 3 on gitlab.

**Comment by AbuBaniaz** [comment]
Sorry, I cant find the e-mail. It was roughly in September 2017 when we had the issue. If I remember correctly, we have to clean using the scour protocol.
