### ISSUE TITLE
Add new logo Sky Crime - Sky UK and Virgin UK

### ISSUE THREAD

**Issue by chenks** [picons/picons#80]
new channel called Sky Crime & Sky Crime HD on both Sky UK and Virgin UK
although it appears to just be a rebrand of Sky Real Lives channels.

can this be added please?

on virgin
Sky Crime HD - 1_0_19_CE6_21_F020_FFFF0000_0_0_0
Sky Crime - 1_0_1_D8_2_F020_FFFF0000_0_0_0

SVG logo here https://en.wikipedia.org/wiki/File:Sky_Crime_logo_2019.svg
![1600px-Sky_Crime_logo_2019 svg](https://user-images.githubusercontent.com/11945919/69257652-51f0ab80-0bb3-11ea-8bf8-1536d46da77e.png)

**Comment by AbuBaniaz** [comment]
I have added them.

Please follow the contributing guide. If you don't understand it, please ask. You are making the effort to get things addressed, best to do it in full.

**Comment by chenks** [comment]
ok, when's the next updated build being pushed out?
current one is showing from 31/10

**Comment by mrhotio** [comment]
update is currently running
