### ISSUE TITLE
Movistar Liga de Campeones 10 picon missing

### ISSUE THREAD

**Issue by qosobrin** [picons/picons#813]
Movistar Liga de Campeones 10 picon is missing

# SNP/SRP entries

**snp.index**
```
mlcampeon10=movistarligadecampeones10
```

**srp.index**
```
760D_408_1_C00000=movistarligadecampeones10
```

# Logos

[movistarligadecampeones.zip](https://github.com/picons/picons/files/7117411/movistarligadecampeones.zip)

**Comment by Lexzie** [comment]
I made the 9, 11 and 12 logos by using the digits from the other logos, so there was no zero.
Thanks for providing the logos.

**Comment by Lexzie** [comment]
Done
