### ISSUE TITLE
New channel VOXup

### ISSUE THREAD

**Issue by di-schi** [picons/picons#82]
There is a new channel in germany called VOXup. I cant download a picon but perhabs someboedy else know a solution for that.
https://www.vox.de/cms/voxup-mediengruppe-rtl-gruendet-neuen-tv-sender-4409856.html

**Comment by mrhotio** [comment]
A new channel without any service ref? That's odd...

**Comment by di-schi** [comment]
i dont know what you meen, but here are some more informations
https://www.vox.de/cms/voxup/empfang.html

**Comment by AbuBaniaz** [comment]
On what satellite is it? Do you know how to get the service reference?

**Comment by di-schi** [comment]
it is on Astra 1L. Please see my second link.

**Comment by AbuBaniaz** [comment]
>Do you know how to get the service reference?

Please obtain the service reference. Select the service, open up  openwebif
Select the service/channel on receiver. Open OpenWebIf, click current, copy and paste the name and reference here

**Comment by Lexzie** [comment]
And if you look to the left of that, you can select the part of the Service Reference we need.
Add an '=' and the name of the logo 'voxup'...
![afbeelding](https://user-images.githubusercontent.com/14023349/70003012-1f0ac800-1562-11ea-8014-e51afc973971.png)
Please read the [contribution guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md).

**Comment by di-schi** [comment]
oh, sorry, but i only use the picons from here in my tvheadend server with dvb-c. I dont have a enigma receiver and cant do this to help find a logo. If i have doing something wrong with opening this issue, please close it

**Comment by mrhotio** [comment]
We can't help if you can't provide the required info, so closing until more info pops up.

**Comment by Lexzie** [comment]
I want the logo too, so I will add it.
