### ISSUE TITLE
[ADD] Rai 5 HD

### ISSUE THREAD

**Issue by JackSlaterIV** [picons/picons#83]
Hi, can you please add this channel?
Here is the logo.
https://it.wikipedia.org/wiki/Rai_5#/media/File:Rai_5_HD_-_Logo_2017.svg
Thanks in advance.

**Comment by mrhotio** [comment]
Why did you not use the template?

**Comment by JackSlaterIV** [comment]
> 
> 
> Why did you not use the template?

Because the second part of that template is not clear to me.
I just know the channel name, nothing more.

```
422B_3DB8_13E_820000=samplelogoname
425A_3DB8_13E_820000=samplelogoname1
4257_3DB8_13E_820000=samplelogoname2
````

**Comment by mrhotio** [comment]
Then there's nothing we can do...

**Comment by JackSlaterIV** [comment]
Dear hotio, you can explain what information is needed, and I can see what I can do. I do not see any explaination about that anywhere in your site. Makes more sense than just closing this without further explainations. What do you need?

**Comment by AbuBaniaz** [comment]
We need the service reference. Are you using Enigma2?

**Comment by mrhotio** [comment]
Are you kidding me? The entire repo consists of nothing BUT examples. The contributing.md explains just about everything and the template says exactly what you need to provide.

**Comment by AbuBaniaz** [comment]
BTW, the logo is already on our repository.
`https://github.com/picons/picons/blob/master/build-source/logos/rai5hd.default.svg`

**Comment by AbuBaniaz** [comment]
There is this entry in the srp.index file
`D4F_1450_13E_820000=rai5hd`

I have just added the following to snp index
`rai5hd=rai5hd`

**Comment by JackSlaterIV** [comment]
> Are you kidding me? The entire repo consists of nothing BUT examples. The contributing.md explains just about everything and the template says exactly what you need to provide.

Since you are now personally insulting me I have to reply: the only one "kidding" here must be you for sure. From the first message you posted. And here is why.

First, you had closed the report without even explaining. Who do you think you are?
You rage-closed the report just because the user (me) was not providing you the full data and not following a template (which is not self-explainatory at all). And you did not even explain anything. 
Probably you took it like an insult, so you had to overreact... This was your logic.
The point is that the user has always the right to report just the channel name, without having to be "punished" like you wanted to do... (maybe in your dreams). 

Second, the user may not even know what a "service reference" is, the only thing he can do help the project is telling you if a logo is missing or not.

Third, inside the template there is NO reference to any CONTRIBUTING.md, which is not even the first file in the repo, and you are also supposing that every user should have read it or has the willingness/time to do it, which is not always the case.

You have a lot to learn from your colleague who instead of posting unhelpful frustration messages, was kind and smart enough to listen and understand, instead of overracting.

@AbuBaniaz of course thank you.

**Comment by mrhotio** [comment]
Dude, I did not overreact. The logo was already in the repo and you did not even bother to tell us on what network you were receiving this channel. Stop being a little child about it, if you didn't know what to provide DYOR. We are not your bitches.

**Comment by mrhotio** [comment]
And do please explain where the insult is? Or just trolling?

Who do I think I am? The guy that's gonna block your ass lol.

**Comment by mrhotio** [comment]
@JackSlaterIV happy? https://github.com/picons/picons/commit/61bbff12bb2008a5ef1656091e09873b4201f6fc
