### ISSUE TITLE
[ADD] Request to add RTV Slovenija picons

### ISSUE THREAD

**Issue by yadranko** [picons/picons#85]
Please add the enclosed 3 default picons regarding RTV Slovenija national channels.

The references are for sat (16E) and DVB-T broadcasting.
Regarding SRP entries I skipped the references for SD sat channels as they will be dismissed in January.

Thank you 

# SNP/SRP entries

**snp.index**
```
slo1hd=slo1hd
slo1=slo1hd
slo2hd=slo2hd
slo2=slo2hd
slo3hd=slo3hd
slo3=slo3hd
```

**srp.index**
```
D67_C738_16E_A00000=slo1hd
1_3_22C1_EEEE0000=slo1hd
6_6_22C1_EEEE0000=slo1hd
D68_C738_16E_A00000=slo2hd
2_3_22C1_EEEE0000=slo2hd
7_6_22C1_EEEE0000=slo2hd
D69_C738_16E_A00000=slo3hd
3_3_22C1_EEEE0000=slo3hd
8_6_22C1_EEEE0000=slo3hd
```
[rtvslovenija.zip](https://github.com/picons/picons/files/4003353/rtvslovenija.zip)

**Comment by Lexzie** [comment]
You have already done a great job by creating this issue, now please check how the logos are named in the repository. You'll see that there are already logos present for RTV SLO 1 and 2. These logos are svg's, could you try to find a SVG for RTV SLO 3 too?

**Comment by yadranko** [comment]
Hi, 
thank you. 

I checked now the repository and I found out:
rtvslo1.default.svg
rtvslo2.default.svg

But also:
tvslovenija1.default.svg
tvslovenija2.default.svg
tvslovenija3.default.svg

Probably should be keeped the last ones.

snp.index

```
slo1hd=tvslovenija1.default.svg
slo1=tvslovenija1.default.svg
slo2hd=tvslovenija2.default.svg
slo2=tvslovenija2.default.svg
slo3hd=tvslovenija3.default.svg
slo3=tvslovenija3.default.svg
```

srp.index

```
D67_C738_16E_A00000=tvslovenija1.default.svg
1_3_22C1_EEEE0000=tvslovenija1.default.svg
6_6_22C1_EEEE0000=tvslovenija1.default.svg
D68_C738_16E_A00000=tvslovenija2.default.svg
2_3_22C1_EEEE0000=tvslovenija2.default.svg
7_6_22C1_EEEE0000=tvslovenija2.default.svg
D69_C738_16E_A00000=tvslovenija3.default.svg
3_3_22C1_EEEE0000=tvslovenija3.default.svg
8_6_22C1_EEEE0000=tvslovenija3.default.svg
```

**Comment by yadranko** [comment]
Please could you add also the picons regarding RTV Slovenija regional channels.

Both channels are available via DVB-T broadcasting. 

Tv Koper-Capodistria was already present in the repository (with a previous version of the logo) as kopercapodistria.default.png.
Probably could be changed with the enclosed kopercapodistria.default.svg.

Thank you.

snp.index

```
koper=kopercapodistria.default.png
telem=maribor.default.svg
```

srp.index
```
5_3_22C1_EEEE0000=kopercapodistria.default.png
4_3_22C1_EEEE0000=maribor.default.svg
```

[regional rtvslovenija.zip](https://github.com/picons/picons/files/4003471/regional.rtvslovenija.zip)

**Comment by Lexzie** [comment]
Seems we have to delete some double logos.
Next time please leave out `.default.png` (or `.default.svg`) in the snp/srp.index links.
I renamed the logo for RTV Slovenija Maribor channel, so that it will have a less common name (and there is `RTV SLO` in the logo.
