### ISSUE TITLE
Missed Logo Links in snp.index

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#87]
# SNP/SRP entries

**snp.index**
```
hauptstadttv=-------- logo also missed
qvc2hd=-------- logo also missed
welthd=-------- logo also missed

```
thx

Edit by Abu Baniaz: 
I have renamed the br logos

See comment by Lexie below. The following are already present but with the replacements for aumlat etc
```
brfernsehensüd=bayerischesfernsehen
brfernsehensüdhd=bayerischesfernsehenhd
wdrhdköln=wdrhd
wdrköln=wdr
```

Added the following already
```
alexberlinsd=alexberlin
handystar=handystar
homeandgardentv=hgtv
rtlzwei=rtlzwei
```

**Comment by mrhotio** [comment]
What's the meaning of 'logo also missed'?

**Comment by AbuBaniaz** [comment]
Those names are not in our index file, so nothing is missed. If you want to have them added, please answer the following questions:

To which logo on our repository do you want to use for the servicename `hauptstadttv`
To which logo on our repository do you want to use for the servicename `qvc2hd`
To which logo on our repository do you want to use for the servicename `welthd`

**Comment by SmoothMC** [comment]
logo also missed = there is no logo for this in "build-source/logos"

but this task is on my side...i will deliver this logos in a few days

**Comment by mrhotio** [comment]
Then there's no point in adding that comment, now this issue is invalid and the problem has to be corrected first....

**Comment by SmoothMC** [comment]
didn't want to break anything ...just wanted to note that there is no logo in the source for this services

just want to support your work :/

**Comment by AbuBaniaz** [comment]
Do you have these logos?

**Comment by SmoothMC** [comment]
not now ...but i will get them soon

**Comment by AbuBaniaz** [comment]
Don't forget to add entries in SRP.index too if you have the details.

**Comment by Lexzie** [comment]
`ü` and `ö` are also invalid characters, please change them to `u` resp. `o`.
And that saying, these links are already present, so no need to include them in your commit:
```
brfernsehensud=br
brfernsehensudhd=brhd
wdrkoln=wdr
wdrhdkoln=wdrhd
```

Right now **QVC 2 HD** will have the logo of **QVC 2**, because this line:
```
qvc2=qvc2
```
(If there is no seperate line for qvc2hd, a channel named like that will get the logo of the same name without `hd`)*.
_*Not sure if that applies to all images and other TV-software, so if not we could add the line_
```
qvc2hd=qvc2
```
_if that logo is sufficiant for you, otherwise:_

This is the **QVC 2 HD** logo:
![afbeelding](https://user-images.githubusercontent.com/14023349/71935900-462f6780-31a8-11ea-8414-b246661cb13d.png)

If you can find or make a better quality logo, please submit that one.
Maybe you can find or make a logo for **QVC UHD** as well?

The same applies to **Welt HD**.

**Comment by Lexzie** [comment]
Here's some help:
https://www.hauptstadt.tv/img/logo_hstdtv_mobile.png

**Comment by AbuBaniaz** [comment]
Some of those links are already there. I have added some of the ones mentioned in the issue

**Comment by SmoothMC** [comment]
hm that's bad. because ä,ö,ü are part of the german language. When i rename this services, they are also show wrong spelled in my tv client. sry. Thats not the goal

Why should this umlauts be a problem. when i enter the service names in the "servicelist-tvheadend-servermode-snp.txt" manually, it works without any issues. can you explain please?

> `ü` and `ö` are also invalid characters, please change them to `u` resp. `o`.
> And that saying, these links are already present, so no need to include them in your commit:
> 
> ```
> brfernsehensud=br
> brfernsehensudhd=brhd
> wdrkoln=wdr
> wdrhdkoln=wdrhd
> ```
> 
> Right now **QVC 2 HD** will have the logo of **QVC 2**, because this line:
> 
> ```
> qvc2=qvc2
> ```
> 
> (If there is no seperate line for qvc2hd, a channel named like that will get the logo of the same name without `hd`)*.
> _*Not sure if that applies to all images and other TV-software, so if not we could add the line_
> 
> ```
> qvc2hd=qvc2
> ```
> 
> _if that logo is sufficiant for you, otherwise:_
> 
> This is the **QVC 2 HD** logo:
> ![afbeelding](https://user-images.githubusercontent.com/14023349/71935900-462f6780-31a8-11ea-8414-b246661cb13d.png)
> 
> If you can find or make a better quality logo, please submit that one.
> Maybe you can find or make a logo for **QVC UHD** as well?
> 
> The same applies to **Welt HD**.

**Comment by AbuBaniaz** [comment]
The comments made were in relation to Enigma2. That is how they are dealt with by almost all images.

If tvheadend is different, then I don't see any problem adding them, but decision is with Hotio.

**Comment by SmoothMC** [comment]
mh. ok i use tvheadend and there is no problem with umlauts.
hopefully we can find a solution for it

**Comment by AbuBaniaz** [comment]
Maybe you can ask Tvheadend people to apply same logic to their picon engine. No need to rename channels.

**Comment by SmoothMC** [comment]
i will have a try on it

**Comment by mrhotio** [comment]
doesn't really matter that tvheadend supports it, we do not.

**Comment by Lexzie** [comment]
What AbuBaniaz said is what I meant.
I have also all kinds of special characters in the name on my receiver, even Greek and Cyrillic characters which aren't supported at all.
I just use the name how they are assigned to that service after scanning the frequency. If that name contains special characters like ä, é, ö, ï etc. they are replaced by a, e, o, i etc.
Unsupported characters are totally left out, so in some cases (f.e. with the Greek or Cyrillic characters) we have to use a srp-link in the snp.index for that particular service.

Read more about it in the contribution guidelines.

**Comment by Jasmeet181** [comment]
> 
> This is the **QVC 2 HD** logo:
> ![afbeelding](https://user-images.githubusercontent.com/14023349/71935900-462f6780-31a8-11ea-8414-b246661cb13d.png)
> 
> If you can find or make a better quality logo, please submit that one.
> Maybe you can find or make a logo for **QVC UHD** as well?
> 
> The same applies to **Welt HD**.

The German QVC HD and Style logos are different from the British versions, the Welt HD colours will need changing to match the SD files you have.

- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC%20HD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC%20UHD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC2%20HD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC2%20UHD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC%20Style.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/QVC%20Style%20HD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/Welt%20HD.svg
- https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/Welt%20HD%20-%20Dark.svg

**Comment by SmoothMC** [comment]
ok i will proof it thx

**Comment by SmoothMC** [comment]
Here we go... the proofed Service Logos for QVC (default & white)

# Logos

[qvc.zip](https://github.com/picons/picons/files/4044686/qvc.zip)

this is what I can deliver as srp links

**srp.index**
```
D170_2717_F001_FFFF0000=qvc
C61A_2726_F001_FFFF0000=qvc2
424A_4061_2114_EEEE0000=qvc2hd
4246_4061_2114_EEEE0000=qvchd
C36B_2716_F001_FFFF0000=qvchd
```

**Comment by SmoothMC** [comment]
Here the proofed (New) Logos for Welt and srp link

# Logos
[welt.zip](https://github.com/picons/picons/files/4046138/welt.zip)

**srp.index**
```
D17B_2718_F001_FFFF0000=welt
4241_4061_2114_EEEE0000=welthd
```

**Comment by SmoothMC** [comment]
A high Quality Logo for the Service "haupstadt.tv" is 
requested per mail on http://www.hauptstadtsport.tv. i just wait for response.

**Comment by mrhotio** [comment]
:-) that's probably the first time anyone asked the tv station directly for a good quality logo...

**Comment by SmoothMC** [comment]
if they don't have ...who else
asking costs nothing

a good organized company like "welt" provide the files online ;)
http://n24wirdwelt.de/b2b/

**Comment by AbuBaniaz** [comment]
Can you confirm if you want the existing logos on this repository replaced? If not, we will need to use a different name for them.

I have not replaced these ones
```
qvchd.default
qvchd.white
qvcstyle.default
qvcstylehd.default
qvcuhd.default
welt.default
welt.white
```

**Comment by AbuBaniaz** [comment]
Ditto the existing QVC logos

**Comment by SmoothMC** [comment]
yes i can confirm it

http://n24wirdwelt.de/b2b/

https://unternehmen.qvc.de/newsroom/pressrelease/qvc-neupositionierung-tv-kanaele-und-mehr-live-programm/

**Comment by SmoothMC** [comment]
hey sry AbuBaniaz i  just notice that sd version of the "qvc style" svg is buggy
in this zip it is fixed

# Logos
[qvc style.zip](https://github.com/picons/picons/files/4050039/qvc.style.zip)

sry and thx

**Comment by Lexzie** [comment]
And now that we have the QVC2 (HD/UHD) logo updated they changed the logo:

![afbeelding](https://user-images.githubusercontent.com/14023349/72690198-4de0fb80-3b1a-11ea-968c-5304bf7692c5.png)
_QVC Zwei HD_

![afbeelding](https://user-images.githubusercontent.com/14023349/72690214-81238a80-3b1a-11ea-9b53-37e31728e3ed.png)
_QVC Zwei_
