### ISSUE TITLE
Missing snp picons in release assets

### ISSUE THREAD

**Issue by Programie** [picons/picons#870]
Since the release of 2021-09-30, the snp Picons are no longer included as assets in the releases. The previous release (2021-09-25) provided the snp Picons in the release assets.

Is there a reason for that? If so, what would be the alternative to use Picons in Kodi using the Tvheadend PVR backend?

Edit: Just saw that the [GitHub Action is failing](https://github.com/picons/picons/runs/3848924193?check_suite_focus=true#step:6:228).

**Comment by mrhotio** [comment]
they are not being ommited on purpose....github actions is being a real dick lately, stuff failing and getting stuck until it times out after 6 hours....not much to do besides praying they'll get their stuff in order
