### ISSUE TITLE
Old entry

### ISSUE THREAD

**Issue by MegaV0lt** [picons/picons#874]
https://github.com/picons/picons/blob/0b442a67bda0c289a25a9a4f411fb63e1acb81cc/build-source/srp.index#L7017

Can be removed. It is replaced by warnertvhd

**Comment by TheLegoBatman** [comment]
Do you mean change `8C_E_85_C00000=tntfilmhd` to `8C_E_85_C00000=warnertv`?

**Comment by Lexzie** [comment]
No, 8C_E_85_C00000 is not in use anymore, in fact the whole transponder is not in use anymore.
Warner TV is on 2018_430_1_C00000, which is already present in srp.index.
So it would just be a clean up.
But checking this I see a lot more links in srp.index are not in use anymore. Apperently Sky Deutschland doesn't use the same service reference quickly again.
Would it be a good idea to clean it?

**Comment by TheLegoBatman** [comment]
Wouldn't that be too time consuming?

**Comment by MegaV0lt** [comment]
As @Lexzie  said already 8C_4_85_C00000=warnertvfilmhd is replacing the old entry

**Comment by AbuBaniaz** [comment]
If there are two or more references, only the top one is used. When I add SRP links, I usually delete duplicated/replaced ones. However, there is no need.

In my opinion, if people can't submit people requests yet,  is so much easier if people say:
Please delete this `link`
Please add this `link`
Or change this `link` to this `link`

**Comment by Lexzie** [comment]
> Wouldn't that be too time consuming?

Yes

**Comment by AbuBaniaz** [comment]
I have deleted the old link. Please re-open issue if that is not what you meant/wanted
