### ISSUE TITLE
A description of what you are updating by this request

### ISSUE THREAD

**Issue by Huevos** [picons/picons#879]
Could you please explain how to build packages for individual satellites. e.g. if I want all snp picons for 28.2E in one package and all snp picons for 13.0E in another package.

And will the package be named to reflect this?

**Comment by TheLegoBatman** [comment]
You will need to build against a list. You add the list in a dir named ```enigma2``` to ```build-input``` dir, then build the list with ```1-build-servicelist.sh snp```. Then just build the picons with ```2-build-picons.sh snp```.

You will need to use this for every package you require.

Take a look at https://github.com/picons/picons/blob/master/.github/workflows/build-picons-snp.yml for the workflow.

**Comment by mrhotio** [comment]
how the packages are named depends on how you do it

```
        bash 1-build-servicelist.sh snp
        bash 2-build-picons.sh snp -13e.19e.23e.28e
```
