### ISSUE TITLE
Enhanced Service Logos for vox and voxhd

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#88]
# Logos

enhanced logos for vox and voxhd as .svg
currently there only .png for this services

[vox.zip](https://github.com/picons/picons/files/4032505/vox.zip)

thx for add

**Comment by mrhotio** [comment]
Try to give a meaningful title to an issue

**Comment by SmoothMC** [comment]
sry i pressed to early on save

**Comment by AbuBaniaz** [comment]
Added here
https://github.com/picons/picons/commit/7bc1ce3811514aa79966c0c0a67f8d6fb8837342
There are a few more Vox png files if you have them
