### ISSUE TITLE
Sony Movies Classic & Sony Movies Classic +1 picons are missing

### ISSUE THREAD

**Issue by nicolasnantua** [picons/picons#90]
Hi,

Sony Movies Christmas & Sony Movies Christmas +1 have changed to Sony Movies Classic & Sony Movies Classic +1 now.

Can you add the picons for these channels

Sony Movies Classic : 1_0_1_D048_83E_2_11A0000_0_0_0
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3643.png

Sony Movies Classic +1 : 1_0_1_D04D_83E_2_11A0000_0_0_0
https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/0/0/skychb3751.png

Thanks

Nicolas

**Comment by AbuBaniaz** [comment]
We are using different logos. I have added the links.

https://github.com/picons/picons/blob/master/build-source/logos/sonymoviesclassicplus1.default.png

https://github.com/picons/picons/blob/master/build-source/logos/sonymoviesclassic.default.png

**Comment by mrhotio** [comment]
@nicolasnantua use the template next time
