### ISSUE TITLE
Why no enigma2-plugin-picons-snp-full.220x132-190x102.light.on.transparent_2021-11-05--23-56-42_all.ipk ?

### ISSUE THREAD

**Issue by BrianG61UK** [picons/picons#906]
Has enigma2-plugin-picons-snp-full.220x132-190x102.light.on.transparent been discontinued?

**Comment by Lexzie** [comment]
I'm not the one who makes the ipk's, but I am curious why there are different sizes.
I just choose the biggest.
What's the use for the other sizes?

**Comment by BrianG61UK** [comment]
> What's the use for the other sizes?

Maybe some boxes don't have room for the bigger sizes?
Maybe some people would just feel it was wasteful to use a bigger size than they need?

I always use 220x132-190x102 because the next size down doesn't look good on my box.

**Comment by BrianG61UK** [comment]
Actually, after looking at recent releases, it seems like quite a few of the files are often missing.
Up until 2021-09-17--23-09-32 there were always, or nearly always, 110 "assets" in each release.
Since then there are frequently far fewer.
It's like the build is running out of CPU time, being uploaded before it's finished, or something.

**Comment by Lexzie** [comment]
> > What's the use for the other sizes?
> 
> Maybe some boxes don't have room for the bigger sizes? Maybe some people would just feel it was wasteful to use a bigger size than they need?
> 

Fair enough, that could be the reason.

Another thing I'm wondering:
Why are there two sizes in the same ipk?


The ipk's are build by a bot, I thing @mrhotio  is responsible for it?

**Comment by BrianG61UK** [comment]
Yes, I don't understand exactly why each ipk (or compressed tar) is labelled with two different sizes.
I'm pretty certain there is actually only one size present in each ipk.
I remember seeing something somewhere that suggested it's to do with padding pixels around the logos.

**Comment by mrhotio** [comment]
It's indeed labeled with two sizes to indicate the padding.

**Comment by mrhotio** [comment]
Looking at the Action logs, seems stuff failed, gha is not very reliable lately
