### ISSUE TITLE
[ADD] updated sat.1 logos

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#95]
# Logos
[sat.1 services.zip](https://github.com/picons/picons/files/4049958/sat.1.services.zip)
 
by the way the service "sat1 comedy" is off since 2016. so the png can be deleted in source ;)

thx

**Comment by AbuBaniaz** [comment]
It's not allowed for svg files to contain base64 encoded images.

**Comment by SmoothMC** [comment]
OK? but it work without any problem. what is the reason?

**Comment by AbuBaniaz** [comment]
Not sure why, but I think something to do with the build process.

**Comment by SmoothMC** [comment]
hm ok? i build it more than 10 times with this svg files on my server and there is noch problem. Maybe it is times to cancel the restriction ;)
give it a try...please

**Comment by SmoothMC** [comment]
any updates to this issue?

**Comment by AbuBaniaz** [comment]
There has been no change in the rules. I'm sure @Hotio will explain why that rule is there.

**Comment by mrhotio** [comment]
A base64 encode image in an svg will NEVER be allowed, why you may ask? Because it's stupid, just upload the png in that case. You can put lipstick on a pig, but it's still a pig.

**Comment by SmoothMC** [comment]
ok ok..
no real explanation, but i will deliver png instead. In this case it will be much better for file size.
But when it "NEVER be allowed" i wonder that there is an option to save it that way in Illustrator. ;)

no matter...You're the boss ;)

**Comment by mrhotio** [comment]
'no real explanation' are you joking?

A base64 encoded png inside an svg == a png, so why on earth would you wanna disguise that as an svg? I don't think you grasp the concept of what we are talking about here....

**Comment by mrhotio** [comment]
Just to make this real clear, a base64 encoded png inside an svg document IS NOT a svg, known as Scalable Vector Graphics. A png is not scalable.

**Comment by SmoothMC** [comment]
thats a true fact...no worries...I got it...sry! that was operational blindness...no matter
back to topic ...I deliver the logos in a format that is useful.
