### ISSUE TITLE
[ADD] zdfneohd to srp.index

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#96]
# SNP/SRP entries

**srp.index**
```
2B7A_2719_F001_FFFF0000=zdfneohd
7D3_203_2114_EEEE0000=zdfneohd
```

thx

**Comment by AbuBaniaz** [comment]
Do you know how to submit pull requests?

**Comment by SmoothMC** [comment]
no i don't...what do I have to do differently?

**Comment by AbuBaniaz** [comment]
Fork the project. Make a new branch. Commit changes in new branch. There will be option to compare/pull request.

Do not make changes to the master branch of your fork.

I'll upload a guide that is not professional, but simple to follow tomorrow. It is on world of satellite forum if you want to look at it now.

**Comment by SmoothMC** [comment]
i got it and make a own fork
i make a pull request asap

thx

**Comment by AbuBaniaz** [comment]
Hope these help

[Github mini guide.pdf](https://github.com/picons/picons/files/4050627/Github.mini.guide.pdf)
[Using Sourcetree to keep your fork updated.pdf](https://github.com/picons/picons/files/4050628/Using.Sourcetree.to.keep.your.fork.updated.pdf)

I also added the pull bot to keep my project in sync without my intervention

```https://github.com/wei/pull#readme```

**Comment by AbuBaniaz** [comment]
I have added the links
